'use strict';
const DICT = {
'important':['ɪmˈpɔːtnt','adj.',"having great value or influence"],
'improve':['ɪmˈpruːv','v.',"to make something better"],
'problem':['ˈprɒbləm','n.',"a difficulty that needs to be solved"],
'increase':['ˈɪnkriːs','n.',"a rise in amount or number"],
'decrease':['ˈdiːkriːs','n.',"a reduction in amount or number"],
'expensive':['ɪkˈspensɪv','adj.',"costing a lot of money"],
'cheap':['tʃiːp','adj.',"costing little money"],
'big':['bɪɡ','adj.',"large in size or amount"],
'small':['smɔːl','adj.',"little in size or amount"],
'need':['niːd','v.',"to require something"],
'show':['ʃəʊ','v.',"to make something clear or visible"],
'get':['ɡet','v.',"to obtain or receive something"],
'buy':['baɪ','v.',"to get something by paying money"],
'help':['help','v.',"to make it easier for someone to do something"],
'start':['stɑːt','v.',"to begin"],
'finish':['ˈfɪnɪʃ','v.',"to complete something"],
'choose':['tʃuːz','v.',"to pick one thing from a group"],
'change':['tʃeɪndʒ','v.',"to make or become different"],
'enough':['ɪˈnʌf','adj.',"as much as is needed"],
'many':['ˈmeni','adj.',"a large number of"],
'most':['məʊst','adj.',"the majority of"],
'also':['ˈɔːlsəʊ','adv.',"in addition"],
'because':['bɪˈkɒz','conj.',"for the reason that"],
'so':['səʊ','conj.',"therefore"],
'but':['bʌt','conj.',"however"],
'maybe':['ˈmeɪbi','adv.',"perhaps"],
'about':['əˈbaʊt','adv.',"approximately"],
'very':['ˈveri','adv.',"to a high degree"],
'often':['ˈɒfn','adv.',"frequently"],
'rarely':['ˈreəli','adv.',"not often"],
'course':['kɔːs','n.',"a series of lessons"],
'subject':['ˈsʌbdʒɪkt','n.',"an area of study"],
'teacher':['ˈtiːtʃə','n.',"a person who teaches"],
'student':['ˈstjuːdnt','n.',"a person who studies"],
'homework':['ˈhəʊmwɜːk','n.',"school work done at home"],
'exam':['ɪɡˈzæm','n.',"a formal test"],
'score':['skɔː','n.',"the number of points in a test"],
'degree':['dɪˈɡriː','n.',"a qualification from a university"],
'university':['ˌjuːnɪˈvɜːsəti','n.',"a place of higher education"],
'lesson':['ˈlesn','n.',"a period of teaching"],
'learn':['lɜːn','v.',"to gain knowledge or skill"],
'revise':['rɪˈvaɪz','v.',"to review work for an exam"],
'difficult':['ˈdɪfɪkəlt','adj.',"hard to do"],
'easy':['ˈiːzi','adj.',"not difficult"],
'compulsory':['kəmˈpʌlsəri','adj.',"required by rule"],
'knowledge':['ˈnɒlɪdʒ','n.',"information and understanding"],
'job':['dʒɒb','n.',"paid work"],
'salary':['ˈsæləri','n.',"regular pay for work"],
'company':['ˈkʌmpəni','n.',"a business organization"],
'employee':['ɪmˈplɔɪiː','n.',"a person who works for a company"],
'manager':['ˈmænɪdʒə','n.',"a person in charge of a team"],
'meeting':['ˈmiːtɪŋ','n.',"a planned discussion"],
'retire':['rɪˈtaɪə','v.',"to stop working, usually at an older age"],
'hire':['haɪə','v.',"to give someone a job"],
'fire':['faɪə','v.',"to dismiss someone from a job"],
'promotion':['prəˈməʊʃn','n.',"movement to a higher position"],
'experience':['ɪkˈspɪəriəns','n.',"knowledge gained from doing something"],
'skill':['skɪl','n.',"an ability to do something well"],
'colleague':['ˈkɒliːɡ','n.',"a person you work with"],
'office':['ˈɒfɪs','n.',"a place where people work"],
'travel':['ˈtrævl','v.',"to go from one place to another"],
'arrive':['əˈraɪv','v.',"to reach a place"],
'leave':['liːv','v.',"to go away from a place"],
'return':['rɪˈtɜːn','v.',"to come or go back"],
'book':['bʊk','v.',"to reserve in advance"],
'ticket':['ˈtɪkɪt','n.',"a document that allows travel or entry"],
'near':['nɪə','adj.',"close in distance"],
'far':['fɑː','adj.',"a long distance away"],
'fast':['fɑːst','adj.',"quick"],
'slow':['sləʊ','adj.',"not quick"],
'busy':['ˈbɪzi','adj.',"full of people or activity"],
'free':['friː','adj.',"available or costing nothing"],
'luggage':['ˈlʌɡɪdʒ','n.',"bags carried when travelling"],
'vehicle':['ˈviːəkl','n.',"a machine used for transport"],
'route':['ruːt','n.',"the way from one place to another"],
'postpone':['pəˈspəʊn','v.',"to delay to a later time"],
'ill':['ɪl','adj.',"not well"],
'tired':['ˈtaɪəd','adj.',"needing rest"],
'healthy':['ˈhelθi','adj.',"in good condition of body and mind"],
'exercise':['ˈeksəsaɪz','n.',"physical activity for fitness"],
'diet':['ˈdaɪət','n.',"the food a person eats"],
'medicine':['ˈmedsn','n.',"a substance used to treat illness"],
'injury':['ˈɪndʒəri','n.',"physical damage to the body"],
'recover':['rɪˈkʌvə','v.',"to get better after illness"],
'pain':['peɪn','n.',"a feeling of hurt"],
'stress':['stres','n.',"pressure that causes worry"],
'relax':['rɪˈlæks','v.',"to rest and become calm"],
'sleep':['sliːp','n.',"rest with eyes closed"],
'strong':['strɒŋ','adj.',"having great physical power"],
'weak':['wiːk','adj.',"lacking strength"],
'cure':['kjʊə','v.',"to make an illness go away"],
'prevent':['prɪˈvent','v.',"to stop something from happening"],
'environment':['ɪnˈvaɪrənmənt','n.',"the natural world around us"],
'pollution':['pəˈluːʃn','n.',"dirt or waste that harms the environment"],
'waste':['weɪst','n.',"unwanted materials or rubbish"],
'recycle':['ˌriːˈsaɪkl','v.',"to treat used materials so they can be used again"],
'energy':['ˈenədʒi','n.',"power from sources such as electricity or fuel"],
'climate':['ˈklaɪmət','n.',"the usual weather of a place"],
'damage':['ˈdæmɪdʒ','n.',"harm caused to something"],
'protect':['prəˈtekt','v.',"to keep something safe"],
'reduce':['rɪˈdjuːs','v.',"to make smaller or less"],
'plant':['plɑːnt','n.',"a living thing that grows in the ground"],
'animal':['ˈænɪml','n.',"a living creature that is not a plant"],
'resource':['rɪˈsɔːs','n.',"a supply of something useful"],
'growth':['ɡrəʊθ','n.',"an increase in size or amount"],
'shortage':['ˈʃɔːtɪdʒ','n.',"a lack of something needed"],
'solve':['sɒlv','v.',"to find an answer to a problem"],
'eco-friendly':['ˈiːkəʊ ˌfrendli','adj.',"not harmful to the environment"],
'house':['haʊs','n.',"a building for people to live in"],
'room':['ruːm','n.',"a space inside a building"],
'rent':['rent','v.',"to pay to use a property"],
'landlord':['ˈlændlɔːd','n.',"a person who rents out property"],
'bill':['bɪl','n.',"an amount of money owed"],
'pay':['peɪ','v.',"to give money for something"],
'save':['seɪv','v.',"to keep money or use less"],
'quiet':['ˈkwaɪət','adj.',"making little noise"],
'noisy':['ˈnɔɪzi','adj.',"making a lot of noise"],
'spacious':['ˈspeɪʃəs','adj.',"large with plenty of space"],
'cramped':['kræmpt','adj.',"too small and crowded"],
'comfortable':['ˈkʌmftəbl','adj.',"pleasant and relaxing"],
'convenient':['kənˈviːniənt','adj.',"easy and suitable"],
'remote':['rɪˈməʊt','adj.',"far away from towns"],
'facilities':['fəˈsɪlətiz','n.',"buildings and equipment for a purpose"],
'repair':['rɪˈpeə','v.',"to fix something broken"],
'research':['rɪˈsɜːtʃ','n.',"careful study to find new information"],
'data':['ˈdeɪtə','n.',"facts and figures"],
'method':['ˈmeθəd','n.',"a way of doing something"],
'experiment':['ɪkˈsperɪmənt','n.',"a scientific test"],
'result':['rɪˈzʌlt','n.',"what happens at the end"],
'cause':['kɔːz','v.',"to make something happen"],
'effect':['ɪˈfekt','n.',"a change caused by something"],
'example':['ɪɡˈzɑːmpl','n.',"one item that shows a type"],
'reason':['ˈriːzn','n.',"why something happens"],
'suggest':['səˈdʒest','v.',"to show or imply"],
'prove':['pruːv','v.',"to show that something is true"],
'examine':['ɪɡˈzæmɪn','v.',"to look at something carefully"],
'measure':['ˈmeʒə','v.',"to find the size or amount"],
'compare':['kəmˈpeə','v.',"to look at how things are alike or different"],
'similar':['ˈsɪmələ','adj.',"alike in some way"],
'conclusion':['kənˈkluːʒn','n.',"a final decision or opinion"],
'price':['praɪs','n.',"the amount of money needed to buy something"],
'discount':['ˈdɪskaʊnt','n.',"a reduction in price"],
'refund':['ˈriːfʌnd','n.',"money given back"],
'receipt':['rɪˈsiːt','n.',"a document showing payment"],
'available':['əˈveɪləbl','adj.',"able to be obtained"],
'unavailable':['ˌʌnəˈveɪləbl','adj.',"not able to be obtained"],
'offer':['ˈɒfə','v.',"to provide something"],
'customer':['ˈkʌstəmə','n.',"a person who buys something"],
'queue':['kjuː','n.',"a line of people waiting"],
'popular':['ˈpɒpjələ','adj.',"liked by many people"],
'trendy':['ˈtrendi','adj.',"fashionable and modern"],
'bargain':['ˈbɑːɡɪn','n.',"something bought at a good price"],
'delivery':['dɪˈlɪvəri','n.',"the bringing of goods"],
'quality':['ˈkwɒləti','n.',"how good something is"],
'guarantee':['ˌɡærənˈtiː','n.',"a promise to repair or replace"],
'afford':['əˈfɔːd','v.',"to have enough money for"],
'happy':['ˈhæpi','adj.',"feeling pleasure"],
'sad':['sæd','adj.',"feeling unhappiness"],
'angry':['ˈæŋɡri','adj.',"feeling strong displeasure"],
'worried':['ˈwʌrid','adj.',"feeling anxious"],
'surprised':['səˈpraɪzd','adj.',"feeling sudden wonder"],
'confused':['kənˈfjuːzd','adj.',"unable to understand clearly"],
'interested':['ˈɪntrəstɪd','adj.',"wanting to know or learn"],
'bored':['bɔːd','adj.',"feeling uninterested"],
'excited':['ɪkˈsaɪtɪd','adj.',"feeling very keen and happy"],
'afraid':['əˈfreɪd','adj.',"feeling fear"],
'grateful':['ˈɡreɪtfl','adj.',"feeling thanks"],
'confident':['ˈkɒnfɪdənt','adj.',"feeling sure of oneself"],
'doubtful':['ˈdaʊtfl','adj.',"not sure"],
'prefer':['prɪˈfɜː','v.',"to like one thing more than another"],
'agree':['əˈɡriː','v.',"to have the same opinion"],
'disagree':['ˌdɪsəˈɡriː','v.',"to have a different opinion"],
'refuse':['rɪˈfjuːz','v.',"to say no to something"],
};
const NEW = [
{t:"core",w:"benefit",s:["gain","profit","advantage"],c:"好处，益处",e:"Students gain a real benefit from early revision.",k:"gain",p:"ˈbenɪfɪt",pos:"n.",d:"an advantage or helpful result"},
{t:"core",w:"disadvantage",s:["drawback","downside","shortcoming"],c:"缺点，不利之处",e:"One drawback is the lack of parking space.",k:"drawback",p:"ˌdɪsədˈvɑːntɪdʒ",pos:"n.",d:"a bad or unwanted feature"},
{t:"core",w:"limit",s:["restrict","cap","control"],c:"限制",e:"The number of tickets is restricted to two per person.",k:"restrict",p:"ˈlɪmɪt",pos:"v.",d:"to stop something from going beyond a certain point"},
{t:"core",w:"allow",s:["permit","enable","let"],c:"允许",e:"The library does not permit food inside.",k:"permit",p:"əˈlaʊ",pos:"v.",d:"to give permission for something"},
{t:"core",w:"contain",s:["include","comprise","involve"],c:"包含",e:"The fee includes all materials.",k:"include",p:"kənˈteɪn",pos:"v.",d:"to have something inside or as a part"},
{t:"core",w:"lack",s:["be short of","be without","miss"],c:"缺乏",e:"The region is short of clean water.",k:"short of",p:"læk",pos:"v.",d:"to not have enough of something"},
{t:"core",w:"consider",s:["take into account","think about","weigh up"],c:"考虑",e:"We need to take into account the extra cost.",k:"take into account",p:"kənˈsɪdə",pos:"v.",d:"to think about something carefully"},
{t:"core",w:"decide",s:["make up one's mind","determine","settle on"],c:"决定",e:"She could not settle on a topic for her essay.",k:"settle on",p:"dɪˈsaɪd",pos:"v.",d:"to make a choice"},
{t:"core",w:"explain",s:["clarify","account for","spell out"],c:"解释",e:"The tutor asked him to clarify his point.",k:"clarify",p:"ɪkˈspleɪn",pos:"v.",d:"to make something clear and easy to understand"},
{t:"core",w:"mention",s:["refer to","bring up","touch on"],c:"提及",e:"The speaker will refer to the survey results.",k:"refer to",p:"ˈmenʃn",pos:"v.",d:"to speak about something briefly"},
{t:"core",w:"main",s:["principal","primary","chief"],c:"主要的",e:"The principal reason for the delay was the weather.",k:"principal",p:"meɪn",pos:"adj.",d:"most important"},
{t:"core",w:"possible",s:["feasible","viable","workable"],c:"可能的",e:"The plan is not feasible within the budget.",k:"feasible",p:"ˈpɒsəbl",pos:"adj.",d:"able to happen or be done"},
{t:"edu",w:"lecture",s:["talk","presentation","seminar"],c:"讲座",e:"The talk will be held in Lecture Hall B.",k:"talk",p:"ˈlektʃə",pos:"n.",d:"a formal talk given to students"},
{t:"edu",w:"deadline",s:["closing date","cut-off date","due date"],c:"截止日期",e:"The closing date for applications is 30 June.",k:"closing date",p:"ˈdedlaɪn",pos:"n.",d:"the latest time by which something must be done"},
{t:"edu",w:"syllabus",s:["curriculum","course outline","programme of study"],c:"教学大纲",e:"The curriculum includes two field trips.",k:"curriculum",p:"ˈsɪləbəs",pos:"n.",d:"the list of topics covered in a course"},
{t:"edu",w:"library",s:["resource centre","learning centre"],c:"图书馆",e:"The resource centre opens until ten.",k:"resource centre",p:"ˈlaɪbrəri",pos:"n.",d:"a place where books and materials are kept for reading"},
{t:"edu",w:"attendance",s:["presence","turnout"],c:"出勤",e:"Regular presence at tutorials is expected.",k:"presence",p:"əˈtendəns",pos:"n.",d:"the act of being present at a class or event"},
{t:"edu",w:"fail",s:["not pass","flunk"],c:"不及格",e:"He may not pass the oral test.",k:"not pass",p:"feɪl",pos:"v.",d:"to not succeed in a test or exam"},
{t:"edu",w:"pass",s:["get through","succeed in"],c:"通过",e:"She is sure to get through the interview.",k:"get through",p:"pɑːs",pos:"v.",d:"to succeed in a test or exam"},
{t:"edu",w:"essay",s:["paper","composition","assignment"],c:"文章，论文",e:"The paper should be about 1,500 words.",k:"paper",p:"ˈeseɪ",pos:"n.",d:"a piece of writing on a particular topic"},
{t:"edu",w:"scholarship",s:["grant","bursary","funding"],c:"奖学金",e:"She applied for a grant to cover her fees.",k:"grant",p:"ˈskɒləʃɪp",pos:"n.",d:"money given to help pay for study"},
{t:"edu",w:"tutorial",s:["seminar group","small class"],c:"辅导课",e:"The seminar group meets every Friday.",k:"seminar group",p:"tjuːˈtɔːriəl",pos:"n.",d:"a small teaching group with discussion"},
{t:"edu",w:"canteen",s:["cafeteria","dining hall","refectory"],c:"食堂",e:"The cafeteria serves hot meals until two.",k:"cafeteria",p:"kænˈtiːn",pos:"n.",d:"a place where food is served at a school or workplace"},
{t:"edu",w:"dormitory",s:["hall of residence","student accommodation"],c:"宿舍",e:"First-year students get a place in a hall of residence.",k:"hall of residence",p:"ˈdɔːmətri",pos:"n.",d:"a building where students live"},
{t:"work",w:"apply",s:["put in an application","submit an application"],c:"申请",e:"You should submit an application before Friday.",k:"submit an application",p:"əˈplaɪ",pos:"v.",d:"to make a formal request, usually for a job"},
{t:"work",w:"interview",s:["selection meeting","job talk"],c:"面试",e:"The selection meeting will take about an hour.",k:"selection meeting",p:"ˈɪntəvjuː",pos:"n.",d:"a formal meeting to assess a candidate"},
{t:"work",w:"resume",s:["CV","curriculum vitae"],c:"简历",e:"Please email your CV to the HR department.",k:"CV",p:"ˈrezjumeɪ",pos:"n.",d:"a summary of a person's work experience"},
{t:"work",w:"part-time",s:["casual","temporary","on a flexible basis"],c:"兼职的",e:"She works on a flexible basis during term time.",k:"flexible basis",p:"ˌpɑːt ˈtaɪm",pos:"adj.",d:"working fewer hours than a full-time job"},
{t:"work",w:"full-time",s:["permanent","regular"],c:"全职的",e:"The role is permanent with good benefits.",k:"permanent",p:"ˌfʊl ˈtaɪm",pos:"adj.",d:"working the normal number of hours"},
{t:"work",w:"workload",s:["amount of work","tasks","duties"],c:"工作量",e:"The amount of work increases during busy seasons.",k:"amount of work",p:"ˈwɜːkləʊd",pos:"n.",d:"the amount of work a person has to do"},
{t:"work",w:"training",s:["development","coaching","induction"],c:"培训",e:"New staff receive a week of induction.",k:"induction",p:"ˈtreɪnɪŋ",pos:"n.",d:"teaching that develops job skills"},
{t:"work",w:"qualification",s:["credential","certificate","licence"],c:"资质，资格证书",e:"The job requires a recognised certificate.",k:"certificate",p:"ˌkwɒlɪfɪˈkeɪʃn",pos:"n.",d:"an official proof of a person's skill or education"},
{t:"work",w:"shift",s:["period of work","rota"],c:"轮班",e:"She prefers the early period of work.",k:"period of work",p:"ʃɪft",pos:"n.",d:"a fixed period of time working in a day"},
{t:"work",w:"vacancy",s:["opening","position","post"],c:"职位空缺",e:"There is an opening in the marketing team.",k:"opening",p:"ˈveɪkənsi",pos:"n.",d:"an available job position"},
{t:"work",w:"negotiate",s:["bargain","discuss terms"],c:"协商",e:"Staff can discuss terms for flexible hours.",k:"discuss terms",p:"nɪˈɡəʊʃieɪt",pos:"v.",d:"to discuss with someone to reach an agreement"},
{t:"work",w:"overtime",s:["extra hours","additional time"],c:"加班",e:"She often works extra hours before a deadline.",k:"extra hours",p:"ˈəʊvətaɪm",pos:"n.",d:"extra time worked beyond normal hours"},
{t:"travel",w:"destination",s:["target","endpoint","place you are going to"],c:"目的地",e:"What is your target on the walking tour?",k:"target",p:"ˌdestɪˈneɪʃn",pos:"n.",d:"the place that someone is going to"},
{t:"travel",w:"accommodation",s:["lodging","housing","place to stay"],c:"住宿",e:"Lodging is included in the package price.",k:"lodging",p:"əˌkɒməˈdeɪʃn",pos:"n.",d:"a place where someone can stay"},
{t:"travel",w:"flight",s:["journey by air","plane trip"],c:"航班",e:"The journey by air takes two hours.",k:"journey by air",p:"flaɪt",pos:"n.",d:"a journey made by plane"},
{t:"travel",w:"station",s:["terminus","stop","depot"],c:"车站",e:"The bus stop is outside the museum.",k:"stop",p:"ˈsteɪʃn",pos:"n.",d:"a place where trains or buses stop"},
{t:"travel",w:"departure",s:["leaving","take-off","set-off"],c:"出发",e:"The take-off is delayed by an hour.",k:"take-off",p:"dɪˈpɑːtʃə",pos:"n.",d:"the act of leaving a place"},
{t:"travel",w:"delay",s:["hold-up","setback"],c:"延误",e:"There was a hold-up on the motorway.",k:"hold-up",p:"dɪˈleɪ",pos:"n.",d:"a situation in which something happens later than planned"},
{t:"travel",w:"sightseeing",s:["touring","visiting sights","exploring"],c:"观光",e:"The afternoon is free for visiting sights.",k:"visiting sights",p:"ˈsaɪtsiːɪŋ",pos:"n.",d:"the activity of visiting interesting places as a tourist"},
{t:"travel",w:"guide",s:["tour guide","escort","leader"],c:"导游",e:"The tour guide will meet you at the entrance.",k:"tour guide",p:"ɡaɪd",pos:"n.",d:"a person who shows tourists around a place"},
{t:"travel",w:"passport",s:["travel document","ID"],c:"护照",e:"Please carry your travel document at all times.",k:"travel document",p:"ˈpɑːspɔːt",pos:"n.",d:"an official document that allows travel between countries"},
{t:"travel",w:"visa",s:["entry permit"],c:"签证",e:"You need an entry permit for the country.",k:"entry permit",p:"ˈviːzə",pos:"n.",d:"an official permission to enter a country"},
{t:"travel",w:"journey",s:["trip","commute","excursion"],c:"旅程",e:"The trip to the coast takes an hour.",k:"trip",p:"ˈdʒɜːni",pos:"n.",d:"an act of travelling from one place to another"},
{t:"travel",w:"transfer",s:["change","connection"],c:"转乘",e:"You will need a change at the central station.",k:"change",p:"ˈtrænsfɜː",pos:"n.",d:"a change of transport during a journey"},
{t:"health",w:"symptom",s:["sign","indication"],c:"症状",e:"A persistent cough is a common sign of the infection.",k:"sign",p:"ˈsɪmptəm",pos:"n.",d:"a sign that shows an illness is present"},
{t:"health",w:"treatment",s:["therapy","care","remedy"],c:"治疗",e:"She is receiving therapy for her knee.",k:"therapy",p:"ˈtriːtmənt",pos:"n.",d:"medical care given to make someone well"},
{t:"health",w:"appointment",s:["booking","consultation","session"],c:"预约",e:"Your consultation is at half past three.",k:"consultation",p:"əˈpɔɪntmənt",pos:"n.",d:"a time arranged to see a doctor or specialist"},
{t:"health",w:"patient",s:["person being treated","case"],c:"病人",e:"Each case is reviewed by a specialist.",k:"case",p:"ˈpeɪʃnt",pos:"n.",d:"a person receiving medical care"},
{t:"health",w:"doctor",s:["GP","physician","practitioner"],c:"医生",e:"Your GP can refer you to a specialist.",k:"GP",p:"ˈdɒktə",pos:"n.",d:"a person trained to treat illness"},
{t:"health",w:"hospital",s:["clinic","medical centre","infirmary"],c:"医院",e:"The clinic is open every day.",k:"clinic",p:"ˈhɒspɪtl",pos:"n.",d:"a place where sick or injured people are treated"},
{t:"health",w:"pharmacy",s:["chemist","drugstore","dispensary"],c:"药房",e:"The chemist's is next to the bank.",k:"chemist",p:"ˈfɑːməsi",pos:"n.",d:"a shop that sells medicines"},
{t:"health",w:"vaccine",s:["immunization","injection","jab"],c:"疫苗",e:"The immunization is free for students.",k:"immunization",p:"ˈvæksiːn",pos:"n.",d:"a substance that protects the body against disease"},
{t:"health",w:"infection",s:["disease","illness","virus"],c:"感染",e:"The virus spreads quickly in winter.",k:"virus",p:"ɪnˈfekʃn",pos:"n.",d:"an illness caused by germs entering the body"},
{t:"health",w:"overweight",s:["obese","too heavy"],c:"超重的",e:"Regular exercise helps people who are too heavy.",k:"too heavy",p:"ˌəʊvəˈweɪt",pos:"adj.",d:"heavier than is healthy"},
{t:"health",w:"blood pressure",s:["BP","hypertension"],c:"血压",e:"Your BP reading is normal.",k:"BP",p:"ˈblʌd ˌpreʃə",pos:"n.",d:"the force with which blood pushes against artery walls"},
{t:"health",w:"check-up",s:["examination","health screening"],c:"体检",e:"The health screening is recommended yearly.",k:"health screening",p:"ˈtʃek ʌp",pos:"n.",d:"a medical examination to check health"},
{t:"env",w:"renewable",s:["sustainable","clean","green"],c:"可再生的",e:"The town runs on sustainable energy sources.",k:"sustainable",p:"rɪˈnjuːəbl",pos:"adj.",d:"able to be replaced by natural processes"},
{t:"env",w:"emission",s:["discharge","release","output"],c:"排放",e:"The plant will cut its carbon release by half.",k:"release",p:"ɪˈmɪʃn",pos:"n.",d:"gas or waste sent out into the air"},
{t:"env",w:"conservation",s:["preservation","protection","safeguarding"],c:"资源保护",e:"The park focuses on preservation of rare birds.",k:"preservation",p:"ˌkɒnsəˈveɪʃn",pos:"n.",d:"the careful protection of nature and resources"},
{t:"env",w:"biodiversity",s:["variety of life","ecosystems"],c:"生物多样性",e:"The region is rich in variety of life.",k:"variety of life",p:"ˌbaɪəʊdaɪˈvɜːsəti",pos:"n.",d:"the variety of living things in an area"},
{t:"env",w:"drought",s:["dry spell","water shortage"],c:"干旱",e:"The dry spell lasted three months.",k:"dry spell",p:"draʊt",pos:"n.",d:"a long period without rain"},
{t:"env",w:"flood",s:["inundation","deluge"],c:"洪水",e:"The inundation damaged many homes.",k:"inundation",p:"flʌd",pos:"n.",d:"an overflow of water onto dry land"},
{t:"env",w:"temperature",s:["heat level","degrees"],c:"温度",e:"The heat level rises during summer.",k:"heat level",p:"ˈtemprətʃə",pos:"n.",d:"how hot or cold something is"},
{t:"env",w:"rainfall",s:["precipitation","rain levels"],c:"降雨量",e:"Precipitation is highest in March.",k:"precipitation",p:"ˈreɪnfɔːl",pos:"n.",d:"the amount of rain that falls"},
{t:"env",w:"habitat",s:["natural home","environment"],c:"栖息地",e:"Wetlands are the natural home of many birds.",k:"natural home",p:"ˈhæbɪtæt",pos:"n.",d:"the natural home of an animal or plant"},
{t:"env",w:"deforestation",s:["clearing forests","tree loss"],c:"森林砍伐",e:"Clearing forests speeds up soil erosion.",k:"clearing forests",p:"ˌdiːfɒrɪˈsteɪʃn",pos:"n.",d:"the cutting down of forests"},
{t:"env",w:"landfill",s:["rubbish dump","tip","disposal site"],c:"垃圾填埋场",e:"The rubbish dump will close next year.",k:"rubbish dump",p:"ˈlændfɪl",pos:"n.",d:"a place where rubbish is buried in the ground"},
{t:"env",w:"organic",s:["natural","chemical-free"],c:"有机的",e:"The market sells chemical-free vegetables.",k:"chemical-free",p:"ɔːˈɡænɪk",pos:"adj.",d:"grown or produced without artificial chemicals"},
{t:"living",w:"suburb",s:["outskirts","residential area","commuter belt"],c:"郊区",e:"She lives in a quiet residential area.",k:"residential area",p:"ˈsʌbɜːb",pos:"n.",d:"an area outside the centre of a city"},
{t:"living",w:"neighbourhood",s:["area","district","community"],c:"街区，社区",e:"The district has excellent schools.",k:"district",p:"ˈneɪbəhʊd",pos:"n.",d:"the area around where a person lives"},
{t:"living",w:"furniture",s:["furnishings","fittings"],c:"家具",e:"The flat comes with basic furnishings.",k:"furnishings",p:"ˈfɜːnɪtʃə",pos:"n.",d:"items such as tables, chairs and beds"},
{t:"living",w:"deposit",s:["down payment","advance payment"],c:"押金",e:"A down payment covers the first month.",k:"down payment",p:"dɪˈpɒzɪt",pos:"n.",d:"money paid in advance as a guarantee"},
{t:"living",w:"utilities",s:["services","bills","supplies"],c:"公用事业费",e:"Bills for water and power are separate.",k:"bills",p:"juːˈtɪlətiz",pos:"n.",d:"services such as water, gas and electricity"},
{t:"living",w:"laundry",s:["washing","ironing"],c:"洗衣",e:"There is a washing machine in the basement.",k:"washing",p:"ˈlɔːndri",pos:"n.",d:"clothes that need to be washed"},
{t:"living",w:"garden",s:["yard","backyard","grounds"],c:"花园",e:"The yard is shared by all residents.",k:"yard",p:"ˈɡɑːdn",pos:"n.",d:"an area of ground with plants next to a house"},
{t:"living",w:"neighbour",s:["resident","nearby household"],c:"邻居",e:"A nearby household reported the noise.",k:"nearby household",p:"ˈneɪbə",pos:"n.",d:"a person who lives near you"},
{t:"living",w:"move",s:["relocate","transfer","shift"],c:"搬家",e:"The family will relocate to the north.",k:"relocate",p:"muːv",pos:"v.",d:"to change the place where you live"},
{t:"living",w:"decorate",s:["redecorate","renovate","spruce up"],c:"装修",e:"They plan to renovate the kitchen.",k:"renovate",p:"ˈdekəreɪt",pos:"v.",d:"to make a room look more attractive"},
{t:"living",w:"furnish",s:["equip","fit out"],c:"配备家具",e:"The studio is equipped with a sofa bed.",k:"equip",p:"ˈfɜːnɪʃ",pos:"v.",d:"to put furniture in a room"},
{t:"living",w:"air conditioning",s:["cooling system","AC"],c:"空调",e:"The cooling system breaks down in summer.",k:"cooling system",p:"ˈeə kənˌdɪʃənɪŋ",pos:"n.",d:"a system that cools the air in a building"},
{t:"academic",w:"hypothesis",s:["theory","assumption","proposition"],c:"假设",e:"The theory was tested in a new study.",k:"theory",p:"haɪˈpɒθəsɪs",pos:"n.",d:"an idea that can be tested by research"},
{t:"academic",w:"evidence",s:["proof","grounds","support"],c:"证据",e:"The findings provide clear proof of the link.",k:"proof",p:"ˈevɪdəns",pos:"n.",d:"facts that show something is true"},
{t:"academic",w:"analyse",s:["break down","study in detail"],c:"分析",e:"The team will break down the results by age.",k:"break down",p:"ˈænəlaɪz",pos:"v.",d:"to examine something in detail"},
{t:"academic",w:"publication",s:["paper","article","journal article"],c:"出版物",e:"Her article appears in a leading journal.",k:"article",p:"ˌpʌblɪˈkeɪʃn",pos:"n.",d:"a published piece of writing"},
{t:"academic",w:"citation",s:["reference","quote","source"],c:"引用",e:"Include a full reference for each source.",k:"reference",p:"saɪˈteɪʃn",pos:"n.",d:"a reference to a book or article"},
{t:"academic",w:"peer review",s:["refereeing","evaluation by experts"],c:"同行评审",e:"The paper is under evaluation by experts.",k:"evaluation by experts",p:"ˌpɪə rɪˈvjuː",pos:"n.",d:"assessment of research by other experts"},
{t:"academic",w:"abstract",s:["summary","overview","synopsis"],c:"摘要",e:"The synopsis should be under 200 words.",k:"synopsis",p:"ˈæbstrækt",pos:"n.",d:"a short summary of a paper or talk"},
{t:"academic",w:"bibliography",s:["reference list","sources"],c:"参考书目",e:"The reference list must follow the style guide.",k:"reference list",p:"ˌbɪbliˈɒɡrəfi",pos:"n.",d:"a list of the sources used in a piece of writing"},
{t:"academic",w:"thesis",s:["dissertation","research project"],c:"学位论文",e:"Her dissertation examines urban transport.",k:"dissertation",p:"ˈθiːsɪs",pos:"n.",d:"a long piece of research writing for a degree"},
{t:"academic",w:"sample",s:["specimen","subset"],c:"样本",e:"The subset includes 200 households.",k:"subset",p:"ˈsɑːmpl",pos:"n.",d:"a small group chosen to represent a larger group"},
{t:"academic",w:"survey",s:["questionnaire","poll","study"],c:"调查",e:"The questionnaire was sent to all students.",k:"questionnaire",p:"ˈsɜːveɪ",pos:"n.",d:"a study that collects information from people"},
{t:"academic",w:"trend",s:["tendency","pattern","direction"],c:"趋势",e:"The data shows a clear tendency upward.",k:"tendency",p:"trend",pos:"n.",d:"a general direction in which something is changing"},
{t:"shopping",w:"purchase",s:["buy","acquire","get"],c:"购买",e:"You may buy tickets at the door.",k:"buy",p:"ˈpɜːtʃəs",pos:"v.",d:"to buy something"},
{t:"shopping",w:"checkout",s:["till","register","cash desk"],c:"收银台",e:"Please pay at the cash desk.",k:"cash desk",p:"ˈtʃekaʊt",pos:"n.",d:"the place in a shop where you pay"},
{t:"shopping",w:"cashier",s:["checkout operator","till worker"],c:"收银员",e:"The checkout operator scanned my card.",k:"checkout operator",p:"kæˈʃɪə",pos:"n.",d:"a person who takes payment in a shop"},
{t:"shopping",w:"aisle",s:["passage","walkway"],c:"过道",e:"The walkway leads to the bakery section.",k:"walkway",p:"aɪl",pos:"n.",d:"a passage between rows of shelves"},
{t:"shopping",w:"shelf",s:["shelving","rack"],c:"货架",e:"The item is on the top rack.",k:"rack",p:"ʃelf",pos:"n.",d:"a flat board used for storing goods"},
{t:"shopping",w:"trolley",s:["cart","shopping cart"],c:"购物车",e:"Take a cart from the entrance.",k:"cart",p:"ˈtrɒli",pos:"n.",d:"a wheeled container used when shopping"},
{t:"shopping",w:"label",s:["tag","sticker","price tag"],c:"标签",e:"The price tag shows the old price.",k:"price tag",p:"ˈleɪbl",pos:"n.",d:"a small piece of paper giving information about a product"},
{t:"shopping",w:"exchange",s:["swap","switch","replace"],c:"换货",e:"You can swap it within 30 days.",k:"swap",p:"ɪksˈtʃeɪndʒ",pos:"v.",d:"to give one thing back and receive another"},
{t:"shopping",w:"free sample",s:["tester","trial product"],c:"免费试用装",e:"There is a tester of the new perfume.",k:"tester",p:"ˌfriː ˈsɑːmpl",pos:"n.",d:"a small free product given so customers can try it"},
{t:"shopping",w:"loyalty card",s:["reward card","membership card","points card"],c:"会员卡",e:"Use your reward card to collect points.",k:"reward card",p:"ˈlɔɪəlti kɑːd",pos:"n.",d:"a card that gives rewards for regular shopping"},
{t:"shopping",w:"advertise",s:["promote","market","publicize"],c:"打广告",e:"The store will promote the sale online.",k:"promote",p:"ˈædvətaɪz",pos:"v.",d:"to tell people about a product to encourage buying"},
{t:"shopping",w:"fitting room",s:["changing room","dressing room"],c:"试衣间",e:"The changing room is at the back.",k:"changing room",p:"ˈfɪtɪŋ ruːm",pos:"n.",d:"a room where customers try on clothes"},
{t:"feelings",w:"disappointed",s:["let down","disheartened","dissatisfied"],c:"失望的",e:"She felt let down by the result.",k:"let down",p:"ˌdɪsəˈpɔɪntɪd",pos:"adj.",d:"unhappy because hopes were not met"},
{t:"feelings",w:"relieved",s:["reassured","comforted"],c:"如释重负的",e:"He was reassured by the good news.",k:"reassured",p:"rɪˈliːvd",pos:"adj.",d:"glad that something unpleasant is over"},
{t:"feelings",w:"proud",s:["pleased with oneself","honoured"],c:"自豪的",e:"She felt honoured to receive the award.",k:"honoured",p:"praʊd",pos:"adj.",d:"feeling pleased about an achievement"},
{t:"feelings",w:"embarrassed",s:["ashamed","self-conscious","awkward"],c:"尴尬的",e:"He felt awkward about the mistake.",k:"awkward",p:"ɪmˈbærəst",pos:"adj.",d:"feeling uncomfortable or ashamed in front of others"},
{t:"feelings",w:"lonely",s:["isolated","alone","lonesome"],c:"孤独的",e:"New students can feel isolated at first.",k:"isolated",p:"ˈləʊnli",pos:"adj.",d:"sad because you are alone"},
{t:"feelings",w:"jealous",s:["envious","resentful"],c:"嫉妒的",e:"She was envious of his success.",k:"envious",p:"ˈdʒeləs",pos:"adj.",d:"wanting what another person has"},
{t:"feelings",w:"optimistic",s:["hopeful","positive","upbeat"],c:"乐观的",e:"The manager is hopeful about sales.",k:"hopeful",p:"ˌɒptɪˈmɪstɪk",pos:"adj.",d:"expecting good things to happen"},
{t:"feelings",w:"pessimistic",s:["negative","gloomy","doubtful"],c:"悲观的",e:"He gave a gloomy forecast for the season.",k:"gloomy",p:"ˌpesɪˈmɪstɪk",pos:"adj.",d:"expecting bad things to happen"},
{t:"feelings",w:"calm",s:["composed","relaxed","unruffled"],c:"冷静的",e:"She stayed composed during the test.",k:"composed",p:"kɑːm",pos:"adj.",d:"peaceful and not worried"},
{t:"feelings",w:"nervous",s:["tense","anxious","on edge"],c:"紧张的",e:"Candidates often feel tense before interviews.",k:"tense",p:"ˈnɜːvəs",pos:"adj.",d:"worried and unable to relax"},
{t:"feelings",w:"enthusiastic",s:["keen","passionate","eager"],c:"热情的",e:"The students are eager to join the club.",k:"eager",p:"ɪnˌθjuːziˈæstɪk",pos:"adj.",d:"showing strong interest and excitement"},
{t:"feelings",w:"regret",s:["feel sorry about","rue","wish you hadn't"],c:"后悔",e:"She felt sorry about missing the lecture.",k:"sorry about",p:"rɪˈɡret",pos:"v.",d:"to feel sorry about something you did or did not do"}
];

module.exports = { DICT, NEW };