'use strict';
/* P3 词根词缀批次 3（chunk3，291 学术词） */
const BATCH = {
  'bucket': {rt:'bucket', af:'bucket(桶)', mn:'bucket 联想 pail：装水的桶'},
  'parcel': {rt:'parc', af:'parc(部分)+el', mn:'一部分一部分打包 → 包裹'},
  'epidemic': {rt:'dem', af:'epi(上)+dem(人民)+ic', mn:'在上蔓延到人民 → 流行病'},
  'workshop': {rt:'work·shop', af:'work(工作)+shop(坊)', mn:'工作坊 → 研讨会/车间'},
  'poster': {rt:'post', af:'post(贴)+er', mn:'贴出来的 → 海报'},
  'accumulate': {rt:'cumul', af:'ac(加强)+cumul(堆积)+ate', mn:'堆积起来 → 积累'},
  'adapt': {rt:'apt', af:'ad(向)+apt(适应)', mn:'适应 → 调整'},
  'alienate': {rt:'alien', af:'alien(外来的)+ate', mn:'变成外人 → 疏远'},
  'assimilate': {rt:'simil', af:'as(向)+simil(相似)+ate', mn:'变成相似 → 同化'},
  'attribute': {rt:'tribut', af:'at(向)+tribut(给)+e', mn:'归给 → 归因于/属性'},
  'avert': {rt:'vert', af:'a(离开)+vert(转)', mn:'转开 → 避免'},
  'bolster': {rt:'bolster', af:'bolster(垫子)', mn:'垫起来支撑 → 支撑/增强'},
  'calibrate': {rt:'calibr', af:'calibr(标准)+ate', mn:'校准标准 → 标定'},
  'circulate': {rt:'circ', af:'circ(环)+ulate', mn:'绕环走 → 循环'},
  'clarify': {rt:'clar', af:'clar(清楚)+ify', mn:'使清楚 → 澄清'},
  'classify': {rt:'class', af:'class(等级)+ify', mn:'分等级 → 分类'},
  'collapse': {rt:'laps', af:'col(共同)+lapse(滑落)', mn:'一起滑落 → 倒塌'},
  'complement': {rt:'ple', af:'com(共同)+ple(满)+ment', mn:'互相填满 → 互补'},
  'comply': {rt:'ply', af:'com(共同)+ply(填)', mn:'填合要求 → 遵从'},
  'conceal': {rt:'ceal', af:'con(完全)+ceal(隐藏)', mn:'完全藏起来 → 隐藏'},
  'condense': {rt:'dens', af:'con(加强)+dens(浓)+e', mn:'变浓 → 浓缩/压缩'},
  'confine': {rt:'fin', af:'con(加强)+fin(边界)+e', mn:'限制在边界内 → 限制'},
  'contemplate': {rt:'templ', af:'con(加强)+templ(庙)+ate', mn:'在庙里沉思 → 深思'},
  'converge': {rt:'verg', af:'con(共同)+verg(转向)', mn:'转向一起 → 汇聚'},
  'convey': {rt:'vey', af:'con(共同)+vey(路)', mn:'一同上路 → 传达'},
  'cooperate': {rt:'oper', af:'co(共同)+oper(工作)+ate', mn:'一起工作 → 合作'},
  'coordinate': {rt:'ordin', af:'co(共同)+ordin(顺序)+ate', mn:'排成共同顺序 → 协调'},
  'correspond': {rt:'respond', af:'cor(共同)+respond(回应)', mn:'相互回应 → 相符/通信'},
  'culminate': {rt:'culmin', af:'culmin(顶)+ate', mn:'到顶点 → 达到高潮'},
  'dedicate': {rt:'dic', af:'de(加强)+dic(说)+ate', mn:'郑重说出 → 献身/题献'},
  'deduct': {rt:'duct', af:'de(向下)+duct(引导)', mn:'引下来 → 扣除'},
  'degrade': {rt:'grad', af:'de(向下)+grad(步)+e', mn:'往下走 → 降级/降解'},
  'deprive': {rt:'priv', af:'de(去除)+priv(私有)+e', mn:'夺走私有 → 剥夺'},
  'descend': {rt:'scend', af:'de(向下)+scend(爬)', mn:'向下爬 → 下降'},
  'displace': {rt:'place', af:'dis(移)+place(位置)', mn:'移走位置 → 取代/流离'},
  'dissolve': {rt:'solv', af:'dis(分开)+solve(解开)', mn:'解开分散 → 溶解/解散'},
  'distract': {rt:'tract', af:'dis(分开)+tract(拉)', mn:'拉开注意力 → 分心'},
  'distribute': {rt:'tribut', af:'dis(分开)+tribut(给)+e', mn:'分开给 → 分发'},
  'elevate': {rt:'lev', af:'e(向上)+lev(举)+ate', mn:'举高 → 提升'},
  'embed': {rt:'bed', af:'em(使)+bed(床)', mn:'安进床里 → 嵌入'},
  'emit': {rt:'mit', af:'e(出)+mit(送)', mn:'送出去 → 发出/排放'},
  'emphasize': {rt:'phas', af:'em(使)+phas(显示)+ize', mn:'使显示 → 强调'},
  'encompass': {rt:'compass', af:'en(使)+compass(罗盘/范围)', mn:'圈进范围 → 包含'},
  'enrich': {rt:'rich', af:'en(使)+rich(富)', mn:'使富 → 丰富'},
  'envisage': {rt:'vis', af:'en(使)+vis(看)+age', mn:'在脑中看到 → 设想'},
  'evade': {rt:'vad', af:'e(出)+vade(走)', mn:'走出去躲 → 逃避'},
  'exaggerate': {rt:'agger', af:'ex(出)+agger(堆积)+ate', mn:'堆过头 → 夸大'},
  'fabricate': {rt:'fabric', af:'fabric(制造)+ate', mn:'制造/编造 → 捏造'},
  'fade': {rt:'fade', af:'fade(褪色)', mn:'fade 联想 away：慢慢消失 → 消退'},
  'foresee': {rt:'see', af:'fore(前)+see(看)', mn:'预先看到 → 预见'},
  'grasp': {rt:'grasp', af:'grasp(抓)', mn:'grasp 联想 grab：抓住 → 掌握'},
  'hasten': {rt:'hast', af:'hast(快)+en', mn:'hasty(匆忙的)：使快 → 加快'},
  'imitate': {rt:'imit', af:'imit(模仿)+ate', mn:'模仿 → 效仿'},
  'imply': {rt:'ply', af:'im(内)+ply(折叠)', mn:'叠在里面 → 暗示'},
  'infect': {rt:'fect', af:'in(进)+fect(做)', mn:'做进去 → 感染'},
  'inflate': {rt:'flate', af:'in(进)+flate(吹)', mn:'吹进去 → 膨胀'},
  'innovate': {rt:'nov', af:'in(使)+nov(新)+ate', mn:'使新 → 创新'},
  'interfere': {rt:'fer', af:'inter(之间)+fere(打)', mn:'打到中间 → 干扰'},
  'investigate': {rt:'vestig', af:'in(进)+vestig(脚印)+ate', mn:'跟着脚印查 → 调查'},
  'invoke': {rt:'voc', af:'in(使)+voke(喊)', mn:'喊出来 → 调用/祈求'},
  'lessen': {rt:'less', af:'less(少)+en', mn:'变少 → 减少'},
  'maximize': {rt:'max', af:'max(最大)+imize', mn:'最大化'},
  'mediate': {rt:'medi', af:'medi(中间)+ate', mn:'在中间调解 → 调解'},
  'merge': {rt:'merg', af:'merg(沉)', mn:'沉到一起 → 合并'},
  'migrate': {rt:'migr', af:'migr(迁移)+ate', mn:'迁移 → 迁徙'},
  'mimic': {rt:'mimic', af:'mimic(模仿)', mn:'mimic 联想 imitate：模仿'},
  'occupy': {rt:'cup', af:'oc(加强)+cup(拿)+y', mn:'拿住 → 占据'},
  'originate': {rt:'origin', af:'origin(起源)+ate', mn:'起源 → 发源'},
  'penetrate': {rt:'penetr', af:'penetr(穿刺)+ate', mn:'刺穿 → 渗透'},
  'persevere': {rt:'sever', af:'per(一直)+severe(严格)', mn:'一直严格 → 坚持'},
  'plunge': {rt:'plung', af:'plung(扎)', mn:'猛扎下去 → 暴跌'},
  'portray': {rt:'tray', af:'por(向前)+tray(画)', mn:'画出 → 描绘'},
  'pose': {rt:'pos', af:'pos(放)+e', mn:'摆出 → 提出/姿势'},
  'predict': {rt:'dict', af:'pre(预先)+dict(说)', mn:'预先说 → 预测'},
  'presume': {rt:'sum', af:'pre(预先)+sume(拿)', mn:'预先拿定 → 假定'},
  'proclaim': {rt:'claim', af:'pro(向前)+claim(喊)', mn:'向前喊 → 宣告'},
  'prohibit': {rt:'hibit', af:'pro(前)+hibit(拿)', mn:'挡在前面 → 禁止'},
  'proliferate': {rt:'lifer', af:'pro+life(生命)+erate', mn:'生命繁殖 → 激增'},
  'propel': {rt:'pel', af:'pro(向前)+pel(推)', mn:'向前推 → 推动'},
  'prosper': {rt:'sper', af:'pro(向前)+sper(希望)', mn:'向前有希望 → 繁荣'},
  'pursue': {rt:'sue', af:'pur(向前)+sue(跟随)', mn:'一直跟 → 追求'},
  'recall': {rt:'call', af:'re(再)+call(叫)', mn:'再叫回来 → 回想/召回'},
  'recur': {rt:'cur', af:'re(再)+cur(跑)', mn:'再跑回来 → 重现'},
  'redeem': {rt:'deem', af:'re(再)+deem(买回)', mn:'买回来 → 赎回/补救'},
  'refine': {rt:'fine', af:'re(再)+fine(精细)', mn:'更精细 → 精炼'},
  'refrain': {rt:'frain', af:'re(回)+frain(勒)', mn:'勒住 → 克制'},
  'regulate': {rt:'regul', af:'regul(规则)+ate', mn:'定规则 → 管制'},
  'reiterate': {rt:'iter', af:'re(再)+iter(重复)+ate', mn:'再重复 → 重申'},
  'replicate': {rt:'plic', af:'re(再)+plic(折叠)+ate', mn:'再折出一样 → 复制'},
  'reside': {rt:'sid', af:'re(加强)+side(坐)', mn:'坐定 → 居住'},
  'restore': {rt:'stor', af:'re(再)+store(建立)', mn:'再建起来 → 恢复'},
  'restrict': {rt:'strict', af:'re(加强)+strict(紧)', mn:'拉紧 → 限制'},
  'retrieve': {rt:'trieve', af:'re(再)+trieve(找到)', mn:'找回 → 取回'},
  'reveal': {rt:'veal', af:'re(去除)+veal(幕)', mn:'揭幕 → 揭示'},
  'reverse': {rt:'vers', af:'re(反)+verse(转)', mn:'转反 → 反转'},
  'scatter': {rt:'scatter', af:'scatter(散)', mn:'scatter 联想 spread：散开'},
  'signify': {rt:'sign', af:'sign(标记)+ify', mn:'作标记 → 表示'},
  'soar': {rt:'soar', af:'soar(高飞)', mn:'soar 联想 up：高飞 → 飙升'},
  'spark': {rt:'spark', af:'spark(火花)', mn:'火花 → 引发'},
  'speculate': {rt:'spec', af:'spec(看)+ulate', mn:'看空看多 → 投机/推测'},
  'subsidize': {rt:'sid', af:'sub(下)+sid(坐)+ize', mn:'坐在下面支持 → 补贴'},
  'terminate': {rt:'termin', af:'termin(边界)+ate', mn:'到边界 → 终止'},
  'thrive': {rt:'thrive', af:'thrive(兴旺)', mn:'thrive 联想 rise：兴旺起来'},
  'undergo': {rt:'go', af:'under(下)+go(走)', mn:'在下面走 → 经历'},
  'undertake': {rt:'take', af:'under(下)+take(拿)', mn:'拿下来做 → 承担'},
  'violate': {rt:'viol', af:'viol(暴力)+ate', mn:'用暴力 → 违反/侵犯'},
  'yield': {rt:'yield', af:'yield(产出/让步)', mn:'yield 联想 field(田)：田里产出 → 产量'},
  'affluent': {rt:'flu', af:'af(向)+flu(流)+ent', mn:'财源滚滚 → 富裕的'},
  'ample': {rt:'ample', af:'ample(宽大)', mn:'ample 联想 plenty：充足的'},
  'anonymous': {rt:'onym', af:'an(无)+onym(名字)+ous', mn:'没有名字 → 匿名的'},
  'applicable': {rt:'plic', af:'ap+plic(折叠)+able', mn:'可折合的 → 适用的'},
  'autonomous': {rt:'nom', af:'auto(自己)+nom(法)+ous', mn:'自己定法 → 自主的'},
  'barrier': {rt:'barr', af:'barr(栏)+ier', mn:'拦住的东西 → 障碍'},
  'capability': {rt:'cap', af:'cap(容纳)+ability', mn:'能容纳 → 能力'},
  'chaos': {rt:'chaos', af:'chaos(混乱)', mn:'chaos 联想 noise：一片混乱'},
  'circumstance': {rt:'st', af:'circum(周围)+st(站)+ance', mn:'站在周围 → 环境/情况'},
  'cognitive': {rt:'cogn', af:'cogn(知道)+itive', mn:'认知的'},
  'comprehensive': {rt:'prehend', af:'com(完全)+prehens(抓)+ive', mn:'全部抓住 → 全面的'},
  'concise': {rt:'cis', af:'con(加强)+cis(切)+e', mn:'切得干脆 → 简洁的'},
  'consent': {rt:'sent', af:'con(共同)+sent(感觉)', mn:'共同感觉 → 同意'},
  'consequent': {rt:'sequ', af:'con(共同)+sequ(跟随)+ent', mn:'跟随着 → 随之发生的'},
  'conservative': {rt:'serv', af:'con(完全)+serv(保持)+ative', mn:'完全保持 → 保守的'},
  'consistency': {rt:'sist', af:'con(共同)+sist(站)+ency', mn:'站得一致 → 一致性'},
  'context': {rt:'text', af:'con(共同)+text(编织)', mn:'编在一起的文字 → 语境'},
  'conventional': {rt:'vent', af:'con(共同)+vent(来)+ional', mn:'一起来的风俗 → 传统的'},
  'conviction': {rt:'vict', af:'con(加强)+vict(征服)+ion', mn:'被征服的信念 → 坚信/定罪'},
  'credible': {rt:'cred', af:'cred(相信)+ible', mn:'可信的'},
  'cumulative': {rt:'cumul', af:'cumul(堆积)+ative', mn:'堆积的 → 累积的'},
  'daunting': {rt:'daunt', af:'daunt(威吓)+ing', mn:'吓人的 → 令人生畏的'},
  'decade': {rt:'dec', af:'dec(十)+ade', mn:'十年'},
  'deliberate': {rt:'liber', af:'de+liber(称量)+ate', mn:'仔细称量 → 深思熟虑的'},
  'democracy': {rt:'dem·cracy', af:'demo(人民)+cracy(统治)', mn:'人民统治 → 民主'},
  'dilemma': {rt:'lemma', af:'di(二)+lemma(命题)', mn:'两个命题两难 → 困境'},
  'disability': {rt:'ability', af:'dis(否定)+ability(能力)', mn:'无能力 → 残疾'},
  'domestic': {rt:'dom', af:'dom(家)+estic', mn:'家里的 → 国内的'},
  'dubious': {rt:'dub', af:'dub(二/犹豫)+ious', mn:'犹豫不定 → 可疑的'},
  'dynamic': {rt:'dynam', af:'dynam(力量)+ic', mn:'有力量的 → 动态的'},
  'economical': {rt:'eco', af:'eco(家)+nom(法)+ical', mn:'理家之法 → 经济的/节约的'},
  'elegant': {rt:'leg', af:'e(出)+leg(选择)+ant', mn:'精挑细选的 → 优雅的'},
  'enormous': {rt:'norm', af:'e(超出)+norm(标准)+ous', mn:'超出标准 → 巨大的'},
  'entity': {rt:'ent', af:'ent(存在)+ity', mn:'独立存在 → 实体'},
  'equivalent': {rt:'val', af:'equi(相等)+val(价值)+ent', mn:'价值相等 → 等价的'},
  'essence': {rt:'ess', af:'ess(存在)+ence', mn:'核心存在 → 本质'},
  'ethical': {rt:'eth', af:'eth(风俗)+ical', mn:'符合风俗 → 道德的'},
  'evident': {rt:'vid', af:'e(出)+vid(看)+ent', mn:'看得见 → 明显的'},
  'expertise': {rt:'pert', af:'ex(出)+pert(试)+ise', mn:'试出的本领 → 专长'},
  'extensive': {rt:'tens', af:'ex(出)+tens(伸展)+ive', mn:'伸展出去 → 广泛的'},
  'extravagant': {rt:'vag', af:'extra(超)+vag(游荡)+ant', mn:'游荡过头 → 奢侈的'},
  'fierce': {rt:'fierce', af:'fierce(凶猛)', mn:'fierce 联想 fire：像火一样 → 激烈的'},
  'finite': {rt:'fin', af:'fin(边界)+ite', mn:'有边界的 → 有限的'},
  'fiscal': {rt:'fisc', af:'fisc(国库)+al', mn:'国库的 → 财政的'},
  'foremost': {rt:'most', af:'fore(前)+most(最)', mn:'最前面的 → 首要的'},
  'fragile': {rt:'frag', af:'frag(碎)+ile', mn:'易碎的 → 脆弱的'},
  'framework': {rt:'work', af:'frame(框架)+work(工作)', mn:'框架结构 → 框架'},
  'fraud': {rt:'fraud', af:'fraud(欺骗)', mn:'fraud 联想 false：假的 → 欺诈'},
  'friction': {rt:'frict', af:'frict(摩擦)+ion', mn:'摩擦 → 冲突'},
  'futile': {rt:'futil', af:'futil(徒劳)+e', mn:'白费力气 → 徒劳的'},
  'genuine': {rt:'gen', af:'gen(出生)+uine', mn:'天生的 → 真正的'},
  'grim': {rt:'grim', af:'grim(冷酷)', mn:'grim 联想 grey：灰暗 → 严峻的'},
  'hardship': {rt:'hard·ship', af:'hard(艰难)+ship(状态)', mn:'艰难状态 → 困苦'},
  'humane': {rt:'human', af:'human(人)+e', mn:'有人性的 → 人道的'},
  'hurdle': {rt:'hurdle', af:'hurdle(栏)', mn:'跨栏 → 障碍'},
  'identical': {rt:'ident', af:'ident(相同)+ical', mn:'完全相同的'},
  'ignorance': {rt:'gnor', af:'i(不)+gnor(知道)+ance', mn:'不知道 → 无知'},
  'immense': {rt:'mens', af:'im(不)+mense(量)', mn:'量不完 → 巨大的'},
  'imperative': {rt:'imper', af:'imper(命令)+ative', mn:'命令式的 → 必须的'},
  'implicit': {rt:'plic', af:'im(内)+plic(折叠)+it', mn:'叠在里面的 → 含蓄的'},
  'incentive': {rt:'cent', af:'in(使)+cent(唱)+ive', mn:'让人想唱 → 激励'},
  'incredible': {rt:'cred', af:'in(不)+cred(相信)+ible', mn:'不可信 → 难以置信的'},
  'indigenous': {rt:'gen', af:'indi(内)+gen(出生)+ous', mn:'本地出生的 → 土著的'},
  'inferior': {rt:'infer', af:'infer(低)+ior', mn:'更低的 → 低劣的'},
  'infinite': {rt:'fin', af:'in(不)+fin(边界)+ite', mn:'无边 → 无限的'},
  'influx': {rt:'flu', af:'in(进)+flux(流)', mn:'流入 → 涌入'},
  'ingenious': {rt:'gen', af:'in(内)+gen(天才)+ious', mn:'内在天才 → 巧妙的'},
  'innate': {rt:'nat', af:'in(内)+nat(出生)+e', mn:'生来就有的 → 天生的'},
  'instinct': {rt:'stinct', af:'in(内)+stinct(刺)', mn:'内在的冲动 → 本能'},
  'insufficient': {rt:'fic', af:'in(不)+sufficient(足够)', mn:'不足够的'},
  'intellect': {rt:'lect', af:'intel(之间)+lect(选择)', mn:'会辨别 → 智力'},
  'intermittent': {rt:'mit', af:'inter(之间)+mitt(送)+ent', mn:'送来送去断断续续 → 间歇的'},
  'intricate': {rt:'tric', af:'in(内)+tric(复杂)+ate', mn:'内部复杂 → 错综复杂的'},
  'intuitive': {rt:'tuit', af:'in(内)+tuit(看护)+ive', mn:'内心守护 → 直觉的'},
  'invaluable': {rt:'val', af:'in(不)+valuable(可估)', mn:'无法估价的 → 无价的'},
  'ironic': {rt:'iron', af:'iron(反讽)+ic', mn:'反讽的 → 讽刺的'},
  'jargon': {rt:'jargon', af:'jargon(行话)', mn:'jargon 联想 argot：行话'},
  'leisure': {rt:'leisure', af:'leisure(闲暇)', mn:'leisure 联想 rest：空闲时间'},
  'liberal': {rt:'liber', af:'liber(自由)+al', mn:'自由的 → 开明的'},
  'likelihood': {rt:'like', af:'like(相似)+lihood', mn:'相似程度 → 可能性'},
  'literal': {rt:'liter', af:'liter(文字)+al', mn:'照字面的 → 字面的'},
  'mainstream': {rt:'stream', af:'main(主)+stream(流)', mn:'主流 → 主流的'},
  'mature': {rt:'matur', af:'matur(成熟)+e', mn:'成熟'},
  'measurable': {rt:'mens', af:'measur(测量)+able', mn:'可测量的'},
  'mentor': {rt:'ment', af:'ment(心智)+or', mn:'指导心智的人 → 导师'},
  'momentum': {rt:'moment', af:'moment(动量)+um', mn:'动量 → 势头'},
  'monopoly': {rt:'mono·poly', af:'mono(单)+poly(卖)', mn:'独家卖 → 垄断'},
  'monotonous': {rt:'ton', af:'mono(单)+ton(音)+ous', mn:'单音 → 单调的'},
  'moral': {rt:'mor', af:'mor(风俗)+al', mn:'风俗的 → 道德的'},
  'motive': {rt:'mot', af:'mot(动)+ive', mn:'推动的东西 → 动机'},
  'mutual': {rt:'mut', af:'mut(交换)+ual', mn:'互相交换 → 相互的'},
  'naive': {rt:'naiv', af:'naiv(天生)+e', mn:'天生单纯 → 天真的'},
  'norm': {rt:'norm', af:'norm(标准)', mn:'norm 联想 normal：标准/常态'},
  'notable': {rt:'not', af:'not(标记)+able', mn:'值得标记 → 显著的'},
  'obscure': {rt:'scur', af:'ob(遮)+scure(盖)', mn:'被遮住 → 模糊的/冷门的'},
  'obvious': {rt:'vi', af:'ob(在)+vious(路)', mn:'在路上 → 明显的'},
  'ongoing': {rt:'going', af:'on(上)+going(进行)', mn:'在进行 → 持续的'},
  'onset': {rt:'set', af:'on(上)+set(放置)', mn:'放上来 → 开始/发作'},
  'outcome': {rt:'come', af:'out(出)+come(来)', mn:'出来的东西 → 结果'},
  'outdated': {rt:'date', af:'out(出)+date(日期)', mn:'过了日期 → 过时的'},
  'outlay': {rt:'lay', af:'out(出)+lay(放)', mn:'放出去的钱 → 支出'},
  'overlap': {rt:'lap', af:'over(上)+lap(叠)', mn:'叠在上面 → 重叠'},
  'overt': {rt:'overt', af:'overt(公开)', mn:'overt 联想 cover(盖)：揭开的 → 公开的'},
  'paradox': {rt:'dox', af:'para(反)+dox(意见)', mn:'反着的意见 → 悖论'},
  'peculiar': {rt:'pecul', af:'pecul(特有)+iar', mn:'特有的 → 古怪的'},
  'perspective': {rt:'spect', af:'per(通过)+spect(看)+ive', mn:'透过看的角度 → 视角'},
  'phase': {rt:'phase', af:'phase(阶段)', mn:'phase 联想 stage：阶段'},
  'physician': {rt:'phys', af:'phys(自然/身体)+ician', mn:'研究身体的人 → 内科医生'},
  'plight': {rt:'plight', af:'plight(困境)', mn:'plight 联想 light(亮)：不亮的处境 → 困境'},
  'precise': {rt:'cis', af:'pre(前)+cis(切)+e', mn:'切得准 → 精确的'},
  'predominant': {rt:'domin', af:'pre(前)+domin(支配)+ant', mn:'支配前面的 → 占主导的'},
  'preferable': {rt:'fer', af:'pre(前)+fer(带)+able', mn:'更愿带的 → 更可取的'},
  'prejudice': {rt:'jud', af:'pre(前)+jud(判断)+ice', mn:'先入的判断 → 偏见'},
  'preliminary': {rt:'limin', af:'pre(前)+limin(门槛)+ary', mn:'门槛前的 → 初步的'},
  'principal': {rt:'cip', af:'prin(第一)+cip(取)+al', mn:'第一取 → 主要的/校长'},
  'principle': {rt:'cip', af:'prin(第一)+cip(取)+le', mn:'第一条要取 → 原则'},
  'prominent': {rt:'min', af:'pro(向前)+min(突出)+ent', mn:'向前突出 → 突出的'},
  'prospect': {rt:'spect', af:'pro(向前)+spect(看)', mn:'向前看 → 前景'},
  'prudent': {rt:'prud', af:'prud(谨慎)+ent', mn:'谨慎的 → 明智的'},
  'random': {rt:'random', af:'random(随机)', mn:'random 联想 run(跑)：乱跑的 → 随机的'},
  'rational': {rt:'ratio', af:'ration(理性)+al', mn:'理性的'},
  'realistic': {rt:'real', af:'real(真实)+istic', mn:'现实主义的 → 现实的'},
  'resilient': {rt:'sil', af:'re(再)+sil(跳)+ient', mn:'能跳回来 → 有韧性的'},
  'rigorous': {rt:'rig', af:'rig(硬)+orous', mn:'硬性的 → 严格的'},
  'robust': {rt:'robur', af:'robur(橡木/力量)+st', mn:'像橡木结实 → 强健的'},
  'scenario': {rt:'scen', af:'scen(场景)+ario', mn:'场景 → 情景'},
  'sceptical': {rt:'scept', af:'scept(怀疑)+ical', mn:'怀疑的 → 质疑的'},
  'scheme': {rt:'scheme', af:'scheme(计划)', mn:'scheme 联想 plan：计划/阴谋'},
  'scope': {rt:'scope', af:'scope(范围)', mn:'scope 联想望远镜：看得见的范围'},
  'segment': {rt:'seg', af:'seg(切)+ment', mn:'切开的一段 → 部分'},
  'sensible': {rt:'sens', af:'sens(感觉)+ible', mn:'有感觉的 → 明智的'},
  'sequence': {rt:'sequ', af:'sequ(跟随)+ence', mn:'一个跟一个 → 顺序'},
  'sheer': {rt:'sheer', af:'sheer(纯粹的)', mn:'sheer 联想 pure：纯的 → 完全的'},
  'spontaneous': {rt:'spont', af:'spont(自愿)+aneous', mn:'自愿的 → 自发的'},
  'stark': {rt:'stark', af:'stark(光秃)', mn:'光秃秃的 → 鲜明的/严峻的'},
  'strategic': {rt:'strateg', af:'strateg(将)+ic', mn:'将军的 → 战略的'},
  'sturdy': {rt:'sturdy', af:'sturdy(结实)', mn:'sturdy 联想 strong：结实的'},
  'substantial': {rt:'st', af:'sub(下)+stant(站)+ial', mn:'站得实 → 大量的/实质的'},
  'temporary': {rt:'tempor', af:'tempor(时间)+ary', mn:'只在一段时间 → 临时的'},
  'toxic': {rt:'tox', af:'tox(毒)+ic', mn:'有毒的'},
  'transit': {rt:'it', af:'trans(跨越)+it(走)', mn:'跨走 → 运输/过境'},
  'trauma': {rt:'trauma', af:'trauma(创伤)', mn:'trauma 联想 hurt：创伤'},
  'tremendous': {rt:'trem', af:'trem(颤抖)+endous', mn:'让人发抖的 → 巨大的'},
  'ultimate': {rt:'ultim', af:'ultim(最后)+ate', mn:'最后的 → 最终的'},
  'universal': {rt:'uni', af:'uni(一)+vers(转)+al', mn:'转成一体 → 普遍的'},
  'unprecedented': {rt:'ced', af:'un(无)+pre(前)+ced(走)+ented', mn:'前面没人走过 → 史无前例的'},
  'vague': {rt:'vag', af:'vag(游荡)+ue', mn:'飘忽不定 → 模糊的'},
  'virtue': {rt:'virt', af:'virt(德)+ue', mn:'德性 → 美德'},
  'visible': {rt:'vis', af:'vis(看)+ible', mn:'看得见的'},
  'volatile': {rt:'vol', af:'vol(飞)+atile', mn:'会飞走 → 易变的'},
  'welfare': {rt:'fare', af:'wel(好)+fare(行)', mn:'过得好 → 福利'},
  'wisdom': {rt:'wis', af:'wis(智)+dom', mn:'智慧'},
  'semester': {rt:'seme', af:'seme(半)+ster', mn:'半个学年 → 学期'},
  'handout': {rt:'hand·out', af:'hand(手)+out(出)', mn:'发到手里的 → 讲义'},
  'worksheet': {rt:'work·sheet', af:'work(工作)+sheet(纸)', mn:'工作纸 → 练习单'},
  'overview': {rt:'view', af:'over(上)+view(看)', mn:'从上看 → 概述'},
  'fieldwork': {rt:'field·work', af:'field(野外)+work(工作)', mn:'野外工作 → 实地考察'},
  'questionnaire': {rt:'quest', af:'quest(问)+ionnaire', mn:'问卷'},
  'participant': {rt:'cip', af:'part(部分)+cip(取)+ant', mn:'取一份参与 → 参与者'},
  'respondent': {rt:'spond', af:'re(回)+spond(承诺)+ent', mn:'回应的人 → 受访者'},
  'trial': {rt:'tri', af:'tri(三/试)+al', mn:'试验 → 试用'},
  'equipment': {rt:'quip', af:'equip(装备)+ment', mn:'装备'},
  'quantitative': {rt:'quant', af:'quant(量)+itative', mn:'定量的'},
  'qualitative': {rt:'qual', af:'qual(性质)+itative', mn:'定性的'},
  'statistics': {rt:'stat', af:'stat(站/状态)+istics', mn:'统计'},
  'median': {rt:'medi', af:'medi(中间)+an', mn:'中位数'},
  'fraction': {rt:'fract', af:'fract(断)+ion', mn:'断开的一部分 → 分数/部分'},
  'calculation': {rt:'calcul', af:'calcul(小石子)+ation', mn:'用小石子计数 → 计算'},
  'accuracy': {rt:'cur', af:'ac(使)+cur(细心)+acy', mn:'细心 → 准确'},
  'presentation': {rt:'sent', af:'pre(前)+sent(存在)+ation', mn:'摆到前面 → 演示/陈述'},
  'publish': {rt:'publ', af:'publ(公开)+ish', mn:'公开 → 出版'},
  'article': {rt:'articul', af:'articul(关节)+e', mn:'文章的一个关节 → 文章'},
  'somewhat': {rt:'some·what', af:'some(某)+what(什么)', mn:'某种程度 → 有点'},
  'induction': {rt:'duct', af:'in(进)+duct(引导)+ion', mn:'引导进入 → 入职培训/归纳'},
  'feedback': {rt:'feed·back', af:'feed(喂)+back(回)', mn:'喂回去 → 反馈'},
  'conserve': {rt:'serv', af:'con(完全)+serve(保持)', mn:'完全保持 → 节约/保护'},
  'consumption': {rt:'sum', af:'con(完全)+sum(拿)+ption', mn:'全拿走 → 消费'},
  'glossary': {rt:'gloss', af:'gloss(注释)+ary', mn:'注释集 → 词汇表'},
  'fatigue': {rt:'fatig', af:'fatig(疲惫)+ue', mn:'疲惫 → 疲劳'},
  'pulse': {rt:'puls', af:'puls(推)+e', mn:'推一下一下 → 脉搏'},
  'clinic': {rt:'clin', af:'clin(床)+ic', mn:'躺床看病的 → 诊所'},
  'damp': {rt:'damp', af:'damp(潮湿)', mn:'damp 联想 wet：潮湿的'},
  'replacement': {rt:'place', af:'re(再)+place(放)+ment', mn:'再放一个 → 替代'},
  'brief': {rt:'brief', af:'brief(短)', mn:'brief 联想 short：简短的/简报'},
};
module.exports = { BATCH };
