'use strict';
/* P3 词根词缀批次 6（chunk6，291 学术词） */
const BATCH = {
  'specify': {rt:'spec', af:'spec(看)+ify', mn:'看清楚 → 具体指明'},
  'task': {rt:'task', af:'task(任务)', mn:'任务'},
  'apparent': {rt:'par', af:'ap(向)+par(出现)+ent', mn:'显露出来 → 明显的'},
  'approximate': {rt:'proxim', af:'ap+proxim(接近)+ate', mn:'接近的 → 大约的'},
  'civil': {rt:'civ', af:'civ(公民)+il', mn:'公民的/文明的'},
  'confer': {rt:'fer', af:'con(共同)+fer(带)', mn:'带到一起商谈 → 授予/商议'},
  'ethnic': {rt:'ethn', af:'ethn(民族)+ic', mn:'民族的'},
  'implicate': {rt:'plic', af:'im(内)+plic(折叠)+ate', mn:'折叠进去 → 牵连'},
  'regime': {rt:'reg', af:'reg(统治)+ime', mn:'政权'},
  'statistic': {rt:'st', af:'stat(状态)+istic', mn:'统计'},
  'amend': {rt:'mend', af:'a(向)+mend(改正)', mn:'改正 → 修订'},
  'discrete': {rt:'cret', af:'dis(分开)+cret(区分)+e', mn:'分开的 → 离散的'},
  'orient': {rt:'orient', af:'orient(东方/定向)', mn:'定方向 → 使适应'},
  'prime': {rt:'prim', af:'prim(第一)+e', mn:'首要的/素数'},
  'estate': {rt:'est', af:'est(存在)+ate', mn:'存在的财产 → 房地产'},
  'federal': {rt:'feder', af:'feder(盟约)+al', mn:'联邦的'},
  'input': {rt:'put', af:'in(进)+put(放)', mn:'输入'},
  'instruct': {rt:'struct', af:'in(使)+struct(建造)', mn:'指导 → 指示'},
  'interval': {rt:'vall', af:'inter(之间)+val(墙)', mn:'中间的墙 → 间隔'},
  'ministry': {rt:'ministr', af:'ministr(服务)+y', mn:'部门'},
  'neutral': {rt:'neutr', af:'neutr(中)+al', mn:'中立的'},
  'underlie': {rt:'lie', af:'under(下)+lie(躺)', mn:'躺在下面 → 作为基础'},
  'contrary': {rt:'contra', af:'contr(对立)+ary', mn:'相反的'},
  'definite': {rt:'fin', af:'de(加强)+fin(边界)+ite', mn:'划清边界的 → 明确的'},
  'dispose': {rt:'pos', af:'dis(分开)+pose(放)', mn:'放掉 → 处理/处置'},
  'insert': {rt:'sert', af:'in(进)+sert(连接)', mn:'插进去 → 插入'},
  'sole': {rt:'sol', af:'sol(单独)+e', mn:'唯一的'},
  'successor': {rt:'cess', af:'suc(下)+cess(走)+or', mn:'走在后面接替 → 继任者'},
  'voluntary': {rt:'vol', af:'vol(意愿)+untary', mn:'自愿的'},
  'so-called': {rt:'call', af:'so(如此)+called(称)', mn:'所谓的'},
  'append': {rt:'pend', af:'ap(向)+pend(悬挂)', mn:'挂上去 → 附加'},
  'automate': {rt:'automat', af:'auto(自己)+mate(动)', mn:'自动化'},
  'eventual': {rt:'vent', af:'e(出)+vent(来)+ual', mn:'最终发生的 → 最终的'},
  'guideline': {rt:'line', af:'guide(指导)+line(线)', mn:'指导线 → 准则'},
  'manipulate': {rt:'manu', af:'manu(手)+pul(满)+ate', mn:'用手摆弄 → 操纵'},
  'nuclear': {rt:'nucle', af:'nucle(核)+ar', mn:'核的'},
  'practitioner': {rt:'pract', af:'pract(做)+itioner', mn:'从业者'},
  'via': {rt:'via', af:'via(路)', mn:'经由'},
  'accommodate': {rt:'mod', af:'ac+commod(方便)+ate', mn:'提供方便 → 容纳'},
  'assure': {rt:'sure', af:'as(使)+sure(确定)', mn:'使确定 → 保证'},
  'behalf': {rt:'half', af:'be+half(半)', mn:'代表一方 → 代表'},
  'bulk': {rt:'bulk', af:'bulk(大块)', mn:'大量'},
  'cease': {rt:'ceas', af:'ceas(停止)+e', mn:'停止'},
  'coincide': {rt:'cid', af:'co(共同)+in+cid(落)+e', mn:'同时落下 → 同时发生'},
  'compatible': {rt:'pat', af:'com(共同)+pat(容忍)+ible', mn:'能共处 → 兼容的'},
  'concurrent': {rt:'curr', af:'con(共同)+curr(跑)+ent', mn:'一起跑 → 同时的'},
  'converse': {rt:'vers', af:'con(共同)+verse(转)', mn:'转过来对话 → 交谈/相反的'},
  'ethic': {rt:'eth', af:'eth(风俗)+ic', mn:'伦理'},
  'format': {rt:'form', af:'form(形)+at', mn:'格式'},
  'integral': {rt:'tegr', af:'in(不)+tegr(触碰)+al', mn:'不可分割的 → 完整的'},
  'protocol': {rt:'proto·col', af:'proto(第一)+col(胶)', mn:'开头规则 → 协议'},
  'restrain': {rt:'strain', af:'re(回)+strain(拉紧)', mn:'拉回来 → 抑制'},
  'subordinate': {rt:'ordin', af:'sub(下)+ordin(顺序)+ate', mn:'在下位 → 下属'},
  'suspend': {rt:'pend', af:'sus(下)+pend(悬挂)', mn:'挂起来 → 暂停'},
  'unify': {rt:'uni', af:'uni(一)+fy', mn:'合一 → 统一'},
  'conceive': {rt:'ceiv', af:'con(共同)+ceive(拿)', mn:'拿到脑中 → 构想'},
  'depress': {rt:'press', af:'de(下)+press(压)', mn:'压下 → 抑郁/压抑'},
  'forthcoming': {rt:'coming', af:'forth(向前)+coming(来)', mn:'即将到来的'},
  'incline': {rt:'clin', af:'in(向)+clin(倾)+e', mn:'倾向'},
  'straightforward': {rt:'forward', af:'straight(直)+forward(向前)', mn:'一直向前 → 直截了当的'},
  'whereby': {rt:'where·by', af:'where(哪里)+by(经)', mn:'凭此 → 借以'},
  'cybersecurity': {rt:'cyber·security', af:'cyber(网络)+security(安全)', mn:'网络安全'},
  'disruptive technology': {rt:'disrupt·tech', af:'disruptive(颠覆)+technology(技术)', mn:'颠覆性技术'},
  'big data': {rt:'big·data', af:'big(大)+data(数据)', mn:'大数据'},
  'surveillance': {rt:'veil', af:'sur(上)+veill(看)+ance', mn:'在上面盯着 → 监视'},
  'obsolescence': {rt:'sol', af:'ob(反)+sol(习惯)+escence', mn:'变得过时 → 淘汰'},
  'corruption': {rt:'rupt', af:'cor(共同)+rupt(断)+ion', mn:'一起断 → 腐败'},
  'rehabilitation': {rt:'habilit', af:'re(再)+habilit(能力)+ation', mn:'恢复能力 → 康复'},
  'advanced': {rt:'van', af:'ad(向)+van(前)+ced', mn:'向前的 → 先进的'},
  'apple': {rt:'apple', af:'apple(苹果)', mn:'苹果'},
  'architect': {rt:'arch·tect', af:'arch(主)+tect(建造)', mn:'建筑师'},
  'arise': {rt:'rise', af:'a(加强)+rise(升起)', mn:'升起 → 出现'},
  'artistic': {rt:'art', af:'art(艺术)+istic', mn:'艺术的'},
  'associated': {rt:'soci', af:'as(向)+soci(同伴)+ated', mn:'同伴相连 → 关联的'},
  'basis': {rt:'bas', af:'bas(底)+is', mn:'基础'},
  'blank': {rt:'blank', af:'blank(空白)', mn:'空白的'},
  'bubble': {rt:'bubble', af:'bubble(气泡)', mn:'气泡/泡沫'},
  'bullet': {rt:'bull', af:'bull(球)+et', mn:'小球 → 子弹/项目符号'},
  'century': {rt:'cent', af:'cent(百)+ury', mn:'世纪'},
  'cheat': {rt:'cheat', af:'cheat(欺骗)', mn:'欺骗/作弊'},
  'commonly': {rt:'mon', af:'com(共同)+mon(公共)+ly', mn:'共同地 → 通常'},
  'consideration': {rt:'sider', af:'con(加强)+sider(星)+ation', mn:'像星般细想 → 考虑'},
  'continuous': {rt:'tin', af:'con(共同)+tin(保持)+uous', mn:'一直保持 → 连续的'},
  'contribution': {rt:'tribut', af:'con(共同)+tribut(给)+ion', mn:'贡献'},
  'correctly': {rt:'rect', af:'cor(加强)+rect(直)+ly', mn:'正确地'},
  'criticism': {rt:'crit', af:'crit(判断)+icism', mn:'批评'},
  'criticize': {rt:'crit', af:'crit(判断)+icize', mn:'批评'},
  'definition': {rt:'fin', af:'de(加强)+fin(边界)+ition', mn:'定义'},
  'deliberately': {rt:'liber', af:'de+liber(称量)+ately', mn:'仔细称量地 → 故意地'},
  'discovery': {rt:'cover', af:'dis(去除)+cover(盖)+y', mn:'揭开盖子 → 发现'},
  'discuss': {rt:'cuss', af:'dis(分开)+cuss(击)', mn:'反复敲打议题 → 讨论'},
  'distribution': {rt:'tribut', af:'dis(分开)+tribut(给)+ion', mn:'分发'},
  'existence': {rt:'sist', af:'ex(出)+ist(站)+ence', mn:'站出来 → 存在'},
  'finding': {rt:'find', af:'find(找到)+ing', mn:'发现'},
  'genre': {rt:'gen', af:'gen(种类)+re', mn:'体裁'},
  'ghost': {rt:'ghost', af:'ghost(鬼)', mn:'鬼/幽灵'},
  'goods': {rt:'good', af:'good(好)+s', mn:'货物'},
  'illustration': {rt:'lustr', af:'il(使)+lustr(照亮)+ation', mn:'图解'},
  'incredibly': {rt:'cred', af:'in(不)+cred(相信)+ibly', mn:'难以置信地'},
  'indirect': {rt:'rect', af:'in(不)+direct(直接)', mn:'间接的'},
  'informal': {rt:'form', af:'in(不)+formal(正式)', mn:'非正式的'},
  'initially': {rt:'it', af:'init(开始)+ially', mn:'最初'},
  'lab': {rt:'lab', af:'lab(实验室缩写)', mn:'实验室'},
  'logical': {rt:'log', af:'log(理)+ical', mn:'逻辑的'},
  'lung': {rt:'lung', af:'lung(肺)', mn:'肺'},
  'monkey': {rt:'monkey', af:'monkey(猴)', mn:'猴子'},
  'neat': {rt:'neat', af:'neat(整洁)', mn:'整洁的/巧妙的'},
  'necessarily': {rt:'necess', af:'necess(必要)+arily', mn:'必然地'},
  'organ': {rt:'organ', af:'organ(器官/风琴)', mn:'器官'},
  'outer': {rt:'out', af:'out(外)+er', mn:'外部的'},
  'painful': {rt:'pain', af:'pain(痛)+ful', mn:'痛苦的'},
  'passage': {rt:'pass', af:'pass(通过)+age', mn:'通道/段落'},
  'poem': {rt:'poem', af:'poem(诗)', mn:'诗'},
  'poet': {rt:'poet', af:'poet(诗人)', mn:'诗人'},
  'powder': {rt:'powder', af:'powder(粉末)', mn:'粉末'},
  'previously': {rt:'vi', af:'pre(前)+vi(路)+ously', mn:'先前地'},
  'psychologist': {rt:'psycho·log', af:'psycho(心灵)+log(学)+ist', mn:'心理学家'},
  'punish': {rt:'pun', af:'pun(惩罚)+ish', mn:'惩罚'},
  'punishment': {rt:'pun', af:'pun(惩罚)+ishment', mn:'惩罚'},
  'rapidly': {rt:'rap', af:'rap(快)+idly', mn:'快速地'},
  'reduction': {rt:'duct', af:'re(回)+duct(引导)+ion', mn:'引回 → 减少'},
  'refer': {rt:'fer', af:'re(回)+fer(带)', mn:'带回去查 → 提及'},
  'regard': {rt:'gard', af:'re(加强)+gard(看)', mn:'看待'},
  'relate': {rt:'lat', af:'re(回)+late(搬运)', mn:'带回来 → 关联'},
  'related': {rt:'lat', af:'relate(关联)+d', mn:'相关的'},
  'relation': {rt:'lat', af:'re(回)+lat(搬)+ion', mn:'关系'},
  'robot': {rt:'robot', af:'robot(苦工/机器人)', mn:'机器人'},
  'rope': {rt:'rope', af:'rope(绳)', mn:'绳子'},
  'scientific': {rt:'sci', af:'sci(知道)+entific', mn:'科学的'},
  'secondly': {rt:'secund', af:'second(第二)+ly', mn:'其次'},
  'significantly': {rt:'sign', af:'sign(标记)+ificantly', mn:'显著地'},
  'snake': {rt:'snake', af:'snake(蛇)', mn:'蛇'},
  'specifically': {rt:'spec', af:'speci(种类)+fically', mn:'具体地'},
  'sublist': {rt:'list', af:'sub(下)+list(表)', mn:'子表'},
  'summarize': {rt:'sum', af:'sum(总)+marize', mn:'总结'},
  'thus': {rt:'thus', af:'thus(因此)', mn:'因此'},
  'abdominal': {rt:'abdomen', af:'abdomin(腹)+al', mn:'腹部的'},
  'absorption': {rt:'sorb', af:'ab(加强)+sorp(吸)+tion', mn:'吸收'},
  'acceleration': {rt:'celer', af:'ac(使)+celer(快)+ation', mn:'加速'},
  'accumulation': {rt:'cumul', af:'ac(加强)+cumul(堆积)+ation', mn:'积累'},
  'accurately': {rt:'cur', af:'ac(使)+cur(细心)+ately', mn:'准确地'},
  'acidic': {rt:'ac', af:'ac(尖)+id+ic', mn:'酸性的'},
  'activate': {rt:'act', af:'act(做)+ivate', mn:'激活'},
  'actively': {rt:'act', af:'act(做)+ively', mn:'积极地'},
  'adaptive': {rt:'apt', af:'ad(向)+apt(适应)+ive', mn:'适应的'},
  'admission': {rt:'miss', af:'ad(向)+miss(送)+ion', mn:'准入'},
  'adolescent': {rt:'alesc', af:'ad(向)+olesc(成长)+ent', mn:'成长中 → 青少年'},
  'adverse': {rt:'vers', af:'ad(向)+verse(转)', mn:'转向不利 → 有害的'},
  'aerosol': {rt:'aero', af:'aero(空气)+sol(溶胶)', mn:'气溶胶'},
  'affirm': {rt:'firm', af:'af(加强)+firm(坚固)', mn:'使坚固 → 肯定'},
  'afterward': {rt:'ward', af:'after(后)+ward(向)', mn:'向后 → 之后'},
  'airplane': {rt:'plane', af:'air(空气)+plane(平面/飞机)', mn:'飞机'},
  'alliance': {rt:'all', af:'all(联合)+iance', mn:'联盟'},
  'aluminum': {rt:'alum', af:'alum(明矾)+inum', mn:'铝'},
  'amino': {rt:'amino', af:'amino(氨基)', mn:'氨基的'},
  'amongst': {rt:'among', af:'among(之间)+st', mn:'在……之中'},
  'amplitude': {rt:'ampl', af:'ampl(大)+itude', mn:'幅度'},
  'anthropology': {rt:'anthropo·logy', af:'anthropo(人)+logy(学)', mn:'人类学'},
  'antibiotic': {rt:'bio', af:'anti(抗)+bio(生命)+tic', mn:'抗生素'},
  'antibody': {rt:'body', af:'anti(抗)+body(体)', mn:'抗体'},
  'antiquity': {rt:'antiq', af:'antiq(古老)+uity', mn:'古代'},
  'appendix': {rt:'pend', af:'ap(向)+pend(挂)+ix', mn:'挂上去的 → 附录'},
  'applause': {rt:'plaud', af:'ap(向)+plaud(拍手)+e', mn:'掌声'},
  'approximation': {rt:'proxim', af:'ap+proxim(接近)+ation', mn:'近似'},
  'array': {rt:'array', af:'array(排列)', mn:'阵列'},
  'arrow': {rt:'arrow', af:'arrow(箭)', mn:'箭头'},
  'artwork': {rt:'work', af:'art(艺术)+work(作品)', mn:'艺术品'},
  'assembly': {rt:'sembl', af:'as(向)+sembl(一起)+y', mn:'组装/集会'},
  'athletic': {rt:'athl', af:'athl(竞技)+etic', mn:'运动的'},
  'atomic': {rt:'atom', af:'atom(原子)+ic', mn:'原子的'},
  'auction': {rt:'aug', af:'aug(增加)+tion', mn:'加价拍卖 → 拍卖'},
  'axiom': {rt:'axiom', af:'axiom(公理)', mn:'公理'},
  'backward': {rt:'ward', af:'back(后)+ward(向)', mn:'向后的'},
  'bacterial': {rt:'bacter', af:'bacter(杆)+ial', mn:'细菌的'},
  'bang': {rt:'bang', af:'bang(巨响)', mn:'砰的一声'},
  'basin': {rt:'basin', af:'basin(盆/盆地)', mn:'盆地/流域'},
  'beam': {rt:'beam', af:'beam(光束/梁)', mn:'光束/横梁'},
  'behavioral': {rt:'hav', af:'be+hav(拥有)+ioral', mn:'行为的'},
  'bizarre': {rt:'bizarre', af:'bizarre(怪诞)', mn:'奇异的'},
  'bleed': {rt:'bleed', af:'bleed(流血)', mn:'流血'},
  'bodily': {rt:'body', af:'body(身体)+ly', mn:'身体的'},
  'bracket': {rt:'bracket', af:'bracket(支架/括号)', mn:'括号/档次'},
  'breakdown': {rt:'break·down', af:'break(破)+down(下)', mn:'崩溃/细分'},
  'broadly': {rt:'broad', af:'broad(宽)+ly', mn:'广泛地'},
  'calcium': {rt:'calc', af:'calc(石灰)+ium', mn:'钙'},
  'calculator': {rt:'calcul', af:'calcul(小石子)+ator', mn:'计算器'},
  'capillary': {rt:'capill', af:'capill(毛发)+ary', mn:'毛细血管'},
  'capitalist': {rt:'capit', af:'capit(头/资本)+alist', mn:'资本家'},
  'carrier': {rt:'carr', af:'carr(车)+ier', mn:'载体/携带者'},
  'censor': {rt:'cens', af:'cens(审查)+or', mn:'审查'},
  'characterization': {rt:'char', af:'character(特征)+ization', mn:'刻画'},
  'cheer': {rt:'cheer', af:'cheer(欢呼)', mn:'欢呼/鼓舞'},
  'chemotherapy': {rt:'chemo·therapy', af:'chemo(化学)+therapy(治疗)', mn:'化疗'},
  'chloride': {rt:'chlor', af:'chlor(氯)+ide', mn:'氯化物'},
  'chromosome': {rt:'chrom·some', af:'chrom(颜色)+some(体)', mn:'染色体'},
  'circa': {rt:'circ', af:'circ(环/约)+a', mn:'大约'},
  'clip': {rt:'clip', af:'clip(夹子/剪)', mn:'夹/剪'},
  'clone': {rt:'clone', af:'clone(克隆)', mn:'克隆'},
  'closure': {rt:'clos', af:'clos(关)+ure', mn:'关闭'},
  'coefficient': {rt:'fic', af:'co(共同)+effic(效力)+ient', mn:'系数'},
  'collective': {rt:'lect', af:'col(共同)+lect(选)+ive', mn:'集体的'},
  'colonial': {rt:'col', af:'col(耕种)+onial', mn:'殖民的'},
  'comma': {rt:'comma', af:'comma(逗号)', mn:'逗号'},
  'communicative': {rt:'mun', af:'com(共同)+mun(服务)+icative', mn:'善于交流的'},
  'communist': {rt:'mun', af:'com(共同)+mun(公共)+ist', mn:'共产主义者'},
  'compact': {rt:'pact', af:'com(共同)+pact(敲紧)', mn:'压紧 → 紧凑的'},
  'comparative': {rt:'par', af:'com(共同)+par(相等)+ative', mn:'比较的'},
  'competent': {rt:'pet', af:'com(共同)+pet(追求)+ent', mn:'能追求的 → 有能力的'},
  'complication': {rt:'plic', af:'com(共同)+plic(折叠)+ation', mn:'叠在一起 → 并发症'},
  'composer': {rt:'pos', af:'com(共同)+pos(放)+er', mn:'作曲者'},
  'composite': {rt:'pos', af:'com(共同)+posit(放)+e', mn:'复合的'},
  'computation': {rt:'put', af:'com(共同)+put(算)+ation', mn:'计算'},
  'conception': {rt:'cept', af:'con(共同)+cept(拿)+ion', mn:'构想/受孕'},
  'conceptual': {rt:'cept', af:'con(共同)+cept(拿)+ual', mn:'概念的'},
  'conditional': {rt:'dit', af:'con(共同)+dit(说)+ional', mn:'有条件的'},
  'conduction': {rt:'duct', af:'con(共同)+duct(引导)+ion', mn:'传导'},
  'configuration': {rt:'figur', af:'con(共同)+figur(形)+ation', mn:'配置'},
  'confound': {rt:'fund', af:'con(共同)+found(底)', mn:'把底搅乱 → 使困惑'},
  'congruent': {rt:'gru', af:'con(共同)+gru(一致)+ent', mn:'全等的'},
  'connector': {rt:'nect', af:'con(共同)+nect(连接)+or', mn:'连接器'},
  'connotation': {rt:'not', af:'con(共同)+not(标记)+ation', mn:'内涵'},
  'consciousness': {rt:'sci', af:'con(共同)+sci(知道)+ousness', mn:'意识'},
  'constitution': {rt:'st', af:'con(共同)+stitut(站)+ion', mn:'宪法/构成'},
  'continuity': {rt:'tin', af:'con(共同)+tin(保持)+uity', mn:'连续性'},
  'contour': {rt:'tour', af:'con(共同)+tour(转)', mn:'轮廓/等高线'},
  'contradictory': {rt:'dict', af:'contra(反)+dict(说)+ory', mn:'矛盾的'},
  'convergence': {rt:'verg', af:'con(共同)+verg(转)+ence', mn:'汇聚'},
  'coordination': {rt:'ordin', af:'co(共同)+ordin(顺序)+ation', mn:'协调'},
  'coronary': {rt:'coron', af:'coron(冠)+ary', mn:'冠状动脉的'},
  'corpus': {rt:'corpus', af:'corpus(身体/语料)', mn:'语料库'},
  'correspondence': {rt:'spond', af:'cor(共同)+respond(回应)+ence', mn:'通信/对应'},
  'cortex': {rt:'cortex', af:'cortex(树皮/皮层)', mn:'皮层'},
  'critically': {rt:'crit', af:'crit(判断)+ically', mn:'批判地'},
  'critique': {rt:'crit', af:'crit(判断)+ique', mn:'评论'},
  'cue': {rt:'cue', af:'cue(提示)', mn:'提示'},
  'cyclic': {rt:'cycl', af:'cycl(环)+ic', mn:'循环的'},
  'cylinder': {rt:'cylind', af:'cylind(圆柱)+er', mn:'圆柱体'},
  'deceive': {rt:'ceiv', af:'de(加强)+ceive(拿)', mn:'骗走 → 欺骗'},
  'defect': {rt:'fect', af:'de(缺)+fect(做)', mn:'缺陷'},
  'deflection': {rt:'flect', af:'de(离开)+flect(弯)+ion', mn:'偏转'},
  'demonstrator': {rt:'monstr', af:'de(加强)+monstr(展示)+ator', mn:'演示者/抗议者'},
  'denominator': {rt:'nomin', af:'de(加强)+nomin(名字)+ator', mn:'分母'},
  'dependence': {rt:'pend', af:'de(下)+pend(挂)+ence', mn:'依赖'},
  'derivative': {rt:'riv', af:'de(从)+riv(河流)+ative', mn:'派生词'},
  'descendent': {rt:'scend', af:'de(下)+scend(爬)+ent', mn:'后代'},
  'descriptor': {rt:'scrib', af:'de+script(写)+or', mn:'描述符'},
  'detection': {rt:'tect', af:'de(去除)+tect(盖)+ion', mn:'检测'},
  'developmental': {rt:'velop', af:'de+velop(包)+mental', mn:'发展的'},
  'diagnostic': {rt:'gnos', af:'dia(通过)+gnos(知道)+tic', mn:'诊断的'},
  'differential': {rt:'fer', af:'dif(分开)+fer(带)+ential', mn:'差别的'},
  'differentiation': {rt:'fer', af:'dif(分开)+fer(带)+entiation', mn:'区分'},
  'diffusion': {rt:'fus', af:'dif(分开)+fus(倒)+ion', mn:'扩散'},
  'dimensional': {rt:'mens', af:'di(分开)+mens(量)+ional', mn:'维度的'},
  'directive': {rt:'rect', af:'di+rect(直)+ive', mn:'指令'},
  'discourse': {rt:'cur', af:'dis(分开)+course(跑)', mn:'话语/论述'},
  'displacement': {rt:'place', af:'dis(移)+place(位置)+ment', mn:'取代/流离'},
  'dissection': {rt:'sect', af:'dis(分开)+sect(切)+ion', mn:'解剖'},
  'disturbance': {rt:'turb', af:'dis(加强)+turb(扰)+ance', mn:'干扰'},
  'dominant': {rt:'domin', af:'domin(主人)+ant', mn:'主导的'},
  'domination': {rt:'domin', af:'domin(主人)+ation', mn:'支配'},
  'ecological': {rt:'eco·log', af:'eco(家园)+log(学)+ical', mn:'生态的'},
  'economically': {rt:'eco', af:'eco(家)+nom(法)+ically', mn:'经济上地'},
  'economist': {rt:'eco', af:'eco(家)+nom(法)+ist', mn:'经济学家'},
  'effectiveness': {rt:'fect', af:'ef(出)+fect(做)+iveness', mn:'有效性'},
  'elastic': {rt:'elas', af:'elas(弹)+tic', mn:'有弹性的'},
  'elasticity': {rt:'elas', af:'elas(弹)+ticity', mn:'弹性'},
  'elevation': {rt:'lev', af:'e(向上)+lev(举)+ation', mn:'海拔/提升'},
  'elimination': {rt:'limin', af:'e(出)+limin(门槛)+ation', mn:'消除'},
  'encode': {rt:'code', af:'en(使)+code(码)', mn:'编码'},
  'enormously': {rt:'norm', af:'e(超)+norm(标准)+ously', mn:'巨大地'},
  'entrant': {rt:'entr', af:'entr(进入)+ant', mn:'参赛者'},
  'epidemiology': {rt:'epidemio·logy', af:'epi(上)+demo(人民)+logy(学)', mn:'流行病学'},
  'equality': {rt:'equ', af:'equ(相等)+ality', mn:'平等'},
  'equivalence': {rt:'val', af:'equi(相等)+val(价值)+ence', mn:'等价'},
  'erase': {rt:'ras', af:'e(出)+rase(刮)', mn:'刮掉 → 擦除'},
  'estimation': {rt:'estim', af:'estim(估价)+ation', mn:'估计'},
  'ethics': {rt:'eth', af:'eth(风俗)+ics', mn:'伦理'},
  'evolutionary': {rt:'volv', af:'e(出)+volut(转)+ionary', mn:'进化的'},
  'execute': {rt:'secut', af:'ex(出)+ecute(跟随)', mn:'执行'},
  'execution': {rt:'secut', af:'ex(出)+ecut(跟随)+ion', mn:'执行'},
  'explicitly': {rt:'plic', af:'ex(出)+plic(折叠)+itly', mn:'明确地'},
  'facet': {rt:'fac', af:'fac(面)+et', mn:'小平面 → 方面'},
  'factorial': {rt:'fact', af:'fact(做)+orial', mn:'阶乘'},
  'fertility': {rt:'fertil', af:'fert(产)+ility', mn:'生育力'},
  'fetal': {rt:'fet', af:'fet(胎儿)+al', mn:'胎儿的'},
  'flesh': {rt:'flesh', af:'flesh(肉)', mn:'肉'},
  'flexibility': {rt:'flect', af:'flex(弯)+ibility', mn:'灵活性'},
  'flux': {rt:'flux', af:'flux(流动)', mn:'流动'},
  'footnote': {rt:'note', af:'foot(脚/底)+note(注)', mn:'脚注'},
  'formally': {rt:'form', af:'form(形式)+ally', mn:'正式地'},
  'freely': {rt:'free', af:'free(自由)+ly', mn:'自由地'},
};
module.exports = { BATCH };
