'use strict';
/* P3 词根词缀批次 5（chunk5，291 学术词） */
const BATCH = {
  'gravity': {rt:'grav', af:'grav(重)+ity', mn:'重力'},
  'rely': {rt:'ly', af:'re(再)+ly(绑)', mn:'靠着绑 → 依赖'},
  'assemble': {rt:'sembl', af:'as(向)+sembl(一起)+e', mn:'聚到一起 → 组装/集合'},
  'consist': {rt:'sist', af:'con(共同)+sist(站)', mn:'站在一起 → 组成/在于'},
  'administration': {rt:'ministr', af:'ad(向)+ministr(服务)+ation', mn:'提供服务管理 → 行政'},
  'couple': {rt:'copul', af:'couple(连接)', mn:'couple 联想 pair：一对/连接'},
  'emphasis': {rt:'phas', af:'em(使)+phas(显示)+is', mn:'使其显示 → 强调'},
  'trace': {rt:'tract', af:'trace(跟随脚印)', mn:'跟着脚印 → 追踪/微量'},
  'deny': {rt:'deny', af:'deny(否认)', mn:'deny 联想 no：说不 → 否认'},
  'valid': {rt:'val', af:'val(强壮)+id', mn:'站得强 → 有效的'},
  'intermediate': {rt:'medi', af:'inter(之间)+medi(中间)+ate', mn:'中间的 → 中级的'},
  'microscope': {rt:'micro·scope', af:'micro(小)+scope(看)', mn:'看小东西 → 显微镜'},
  'occur': {rt:'cur', af:'oc(向)+cur(跑)', mn:'跑出来 → 发生'},
  'trigger': {rt:'trigger', af:'trigger(扳机)', mn:'扣扳机 → 引发'},
  'altitude': {rt:'alt', af:'alt(高)+itude', mn:'高度/海拔'},
  'angle': {rt:'angle', af:'angle(角)', mn:'角'},
  'extent': {rt:'tent', af:'ex(出)+tent(伸展)', mn:'伸展出去 → 程度/范围'},
  'hydrogen': {rt:'hydro·gen', af:'hydro(水)+gen(产生)', mn:'生成水的 → 氢'},
  'horizon': {rt:'horiz', af:'horiz(边界)+on', mn:'天际线 → 地平线'},
  'mineral': {rt:'min', af:'mine(矿)+ral', mn:'矿里的 → 矿物'},
  'marble': {rt:'marble', af:'marble(大理石)', mn:'大理石'},
  'delta': {rt:'delta', af:'delta(三角/Δ)', mn:'河口像Δ → 三角洲'},
  'globe': {rt:'glob', af:'glob(球)+e', mn:'地球仪 → 球体'},
  'pole': {rt:'pole', af:'pole(杆/极)', mn:'地轴两端 → 极点/杆'},
  'polar': {rt:'pol', af:'pol(极)+ar', mn:'极地的'},
  'axis': {rt:'axis', af:'axis(轴)', mn:'轴'},
  'erode': {rt:'rod', af:'e(出)+rode(咬)', mn:'咬蚀掉 → 侵蚀'},
  'meteorology': {rt:'meteor·logy', af:'meteor(气象)+logy(学)', mn:'气象学'},
  'thermal': {rt:'therm', af:'therm(热)+al', mn:'热的'},
  'sediment': {rt:'sed', af:'sed(坐)+iment', mn:'坐下来的 → 沉积物'},
  'fringe': {rt:'fringe', af:'fringe(边缘)', mn:'fringe 联想 edge：边缘'},
  'super': {rt:'super', af:'super(上)', mn:'超级'},
  'precipitate': {rt:'cip', af:'pre(前)+cipit(落)+ate', mn:'提前落下 → 沉淀/促成'},
  'reservoir': {rt:'serv', af:'re(再)+serv(保存)+oir', mn:'存水的地方 → 水库'},
  'dense': {rt:'dens', af:'dens(浓)+e', mn:'浓密'},
  'synthetic': {rt:'thes', af:'syn(共同)+thet(放)+ic', mn:'放在一起造的 → 合成的'},
  'dioxide': {rt:'ox', af:'di(二)+oxide(氧化物)', mn:'二氧化碳'},
  'vegetation': {rt:'veget', af:'veget(生长)+ation', mn:'生长的植物 → 植被'},
  'organism': {rt:'organ', af:'organ(器官)+ism', mn:'有器官的 → 生物体'},
  'genetics': {rt:'gen', af:'gen(出生)+etics', mn:'遗传学'},
  'mutation': {rt:'mut', af:'mut(变化)+ation', mn:'变异'},
  'stack': {rt:'stack', af:'stack(堆)', mn:'堆叠'},
  'bundle': {rt:'bind', af:'bund(绑)+le', mn:'绑在一起 → 捆'},
  'fungus': {rt:'fung', af:'fung(蘑菇)+us', mn:'真菌'},
  'decay': {rt:'decay', af:'de(下)+cay(落)', mn:'往下落 → 腐烂/衰变'},
  'plantation': {rt:'plant', af:'plant(种植)+ation', mn:'种植园'},
  'enzyme': {rt:'en·zyme', af:'en(使)+zyme(发酵)', mn:'发酵用的 → 酶'},
  'circulation': {rt:'circ', af:'circ(环)+ulation', mn:'循环'},
  'nutrient': {rt:'nutri', af:'nutri(滋养)+ent', mn:'营养物质'},
  'productive': {rt:'duct', af:'pro(向前)+duct(引导)+ive', mn:'高产的'},
  'minimal': {rt:'min', af:'min(小)+imal', mn:'最小的'},
  'optimal': {rt:'opt', af:'opt(最好)+imal', mn:'最优的'},
  'biologist': {rt:'bio·log', af:'bio(生命)+log(学)+ist', mn:'研究生命的人 → 生物学家'},
  'offspring': {rt:'spring', af:'off(出)+spring(跳)', mn:'跳出来的 → 后代'},
  'pest': {rt:'pest', af:'pest(害虫)', mn:'害虫'},
  'hawk': {rt:'hawk', af:'hawk(鹰)', mn:'鹰'},
  'rub': {rt:'rub', af:'rub(摩擦)', mn:'摩擦'},
  'anatomy': {rt:'ana·tomy', af:'ana(分开)+tomy(切)', mn:'切开看 → 解剖学'},
  'secrete': {rt:'cret', af:'se(分开)+crete(分泌)', mn:'分开排出 → 分泌'},
  'optical': {rt:'optic', af:'optic(光)+al', mn:'光学的/视觉的'},
  'prey': {rt:'prey', af:'prey(猎物)', mn:'猎物'},
  'predator': {rt:'pred', af:'pred(掠夺)+ator', mn:'掠夺者 → 捕食者'},
  'galaxy': {rt:'galax', af:'galax(乳)+y', mn:'银河 → 星系'},
  'cosmos': {rt:'cosm', af:'cosm(宇宙)+os', mn:'宇宙'},
  'interstellar': {rt:'stellar', af:'inter(之间)+stellar(星)', mn:'星际的'},
  'terrestrial': {rt:'terr', af:'terr(地)+estrial', mn:'地球的/陆地的'},
  'celestial': {rt:'celest', af:'celest(天)+ial', mn:'天上的'},
  'astronomy': {rt:'astro·nom', af:'astro(星)+nom(法则)+y', mn:'星空法则 → 天文学'},
  'astrology': {rt:'astro·logy', af:'astro(星)+logy(学)', mn:'占星术'},
  'astronaut': {rt:'astro·naut', af:'astro(星)+naut(航行者)', mn:'星际航行者 → 宇航员'},
  'comet': {rt:'comet', af:'comet(彗星)', mn:'彗星'},
  'meteorite': {rt:'meteor', af:'meteor(流星)+ite', mn:'落地的流星 → 陨石'},
  'crater': {rt:'crater', af:'crater(碗状坑)', mn:'撞击坑 → 火山口'},
  'ash': {rt:'ash', af:'ash(灰)', mn:'灰烬'},
  'chunk': {rt:'chunk', af:'chunk(大块)', mn:'大块'},
  'spacecraft': {rt:'craft', af:'space(太空)+craft(船)', mn:'太空船'},
  'spaceship': {rt:'ship', af:'space(太空)+ship(船)', mn:'太空船'},
  'probe': {rt:'prob', af:'probe(探测)', mn:'探测'},
  'propulsion': {rt:'puls', af:'pro(向前)+puls(推)+ion', mn:'向前推 → 推进'},
  'dynamics': {rt:'dynam', af:'dynam(力量)+ics', mn:'力学/动态'},
  'motion': {rt:'mot', af:'mot(动)+ion', mn:'运动'},
  'vent': {rt:'vent', af:'vent(风/出口)', mn:'通气口 → 发泄'},
  'curve': {rt:'curv', af:'curv(弯)+e', mn:'曲线'},
  'exploration': {rt:'plor', af:'ex(出)+plor(喊)+ation', mn:'出去探索 → 勘探'},
  'expedition': {rt:'ped', af:'ex(出)+ped(脚)+ition', mn:'出脚远行 → 远征'},
  'flyby': {rt:'fly·by', af:'fly(飞)+by(过)', mn:'飞过 → 飞掠'},
  'observatory': {rt:'serv', af:'ob(向)+serv(看)+atory', mn:'看星星的地方 → 天文台'},
  'telescope': {rt:'tele·scope', af:'tele(远)+scope(看)', mn:'看远 → 望远镜'},
  'spectacle': {rt:'spect', af:'spect(看)+acle', mn:'好看的东西 → 壮观景象'},
  'orbit': {rt:'orbit', af:'orbit(轨道)', mn:'轨道'},
  'ecliptic': {rt:'eclipt', af:'eclipt(蚀)+ic', mn:'日月蚀的 → 黄道'},
  'radius': {rt:'radi', af:'radi(光线/辐)+us', mn:'从中心辐射的 → 半径'},
  'composition': {rt:'pos', af:'com(共同)+posit(放)+ion', mn:'放在一起 → 组成/作文'},
  'compound': {rt:'pound', af:'com(共同)+pound(放)', mn:'放在一起 → 化合物/复合的'},
  'particle': {rt:'part', af:'part(部分)+icle(小)', mn:'小部分 → 粒子'},
  'atom': {rt:'atom', af:'a(不)+tom(切)', mn:'不可切分 → 原子'},
  'ion': {rt:'ion', af:'ion(离子)', mn:'离子'},
  'electron': {rt:'electr·on', af:'electr(电)+on', mn:'电子'},
  'quantum': {rt:'quant', af:'quant(量)+um', mn:'量子'},
  'fluid': {rt:'flu', af:'flu(流)+id', mn:'流体'},
  'formation': {rt:'form', af:'form(形)+ation', mn:'形成'},
  'spectrum': {rt:'spect', af:'spect(看)+rum', mn:'光谱'},
  'antenna': {rt:'antenna', af:'antenna(天线)', mn:'天线'},
  'circuit': {rt:'circ', af:'circ(环)+uit', mn:'电路'},
  'refraction': {rt:'fract', af:'re(再)+fract(折)+ion', mn:'折射'},
  'ultraviolet': {rt:'violet', af:'ultra(超)+violet(紫)', mn:'紫外'},
  'radioactive': {rt:'radi·act', af:'radio(射线)+active(活跃)', mn:'放射性的'},
  'discernible': {rt:'cern', af:'dis(分开)+cern(筛)+ible', mn:'能筛出来的 → 可辨的'},
  'invisible': {rt:'vis', af:'in(不)+vis(看)+ible', mn:'看不见的'},
  'collision': {rt:'lid', af:'col(共同)+lid(打)+ion', mn:'互相打 → 碰撞'},
  'squash': {rt:'squash', af:'squash(压扁)', mn:'压扁'},
  'fragment': {rt:'frag', af:'frag(碎)+ment', mn:'碎片'},
  'cataclysmic': {rt:'clys', af:'cata(下)+clysm(冲刷)+ic', mn:'大冲刷 → 灾难性的'},
  'overwhelming': {rt:'whelm', af:'over(压倒)+whelm(淹没)+ing', mn:'压倒性的'},
  'desperate': {rt:'sper', af:'de(无)+sper(希望)+ate', mn:'没希望的 → 绝望的'},
  'hopeless': {rt:'hope', af:'hope(希望)+less(无)', mn:'绝望的'},
  'academy': {rt:'academ', af:'academ(学院)+y', mn:'学院'},
  'novice': {rt:'nov', af:'nov(新)+ice', mn:'新手'},
  'enable': {rt:'able', af:'en(使)+able(能)', mn:'使能 → 使能够'},
  'elite': {rt:'elig', af:'e(出)+lit(选)+e', mn:'精选出来的 → 精英'},
  'junior': {rt:'jun', af:'jun(年轻)+ior', mn:'更年轻的 → 初级的'},
  'series': {rt:'ser', af:'ser(连接)+ies', mn:'一连串 → 系列'},
  'sketch': {rt:'sketch', af:'sketch(速写)', mn:'草图'},
  'index': {rt:'dex', af:'in(向)+dex(指)', mn:'索引/指数'},
  'chapter': {rt:'chapter', af:'chapter(章)', mn:'章节'},
  'audit': {rt:'aud', af:'aud(听)+it', mn:'听账 → 审计'},
  'chemistry': {rt:'chem', af:'chem(化学)+istry', mn:'化学'},
  'algebra': {rt:'al·gebr', af:'algebra(代数)', mn:'代数'},
  'calculus': {rt:'calcul', af:'calcul(小石子)+us', mn:'微积分'},
  'plus': {rt:'plus', af:'plus(加)', mn:'加'},
  'sum': {rt:'sum', af:'sum(总和)', mn:'总和'},
  'minus': {rt:'min', af:'minus(减)', mn:'减'},
  'subtract': {rt:'tract', af:'sub(下)+tract(拉)', mn:'拉下去 → 减去'},
  'multiply': {rt:'mult', af:'mult(多)+iply', mn:'变多 → 乘'},
  'diagram': {rt:'dia·gram', af:'dia(穿过)+gram(画)', mn:'画线示意 → 图表'},
  'matrix': {rt:'matrix', af:'matrix(母体/矩阵)', mn:'矩阵'},
  'triangle': {rt:'tri·angle', af:'tri(三)+angle(角)', mn:'三角形'},
  'sphere': {rt:'sphere', af:'sphere(球)', mn:'球体'},
  'cone': {rt:'cone', af:'cone(圆锥)', mn:'圆锥'},
  'percent': {rt:'cent', af:'per(每)+cent(百)', mn:'百分比'},
  'ratio': {rt:'ratio', af:'ratio(比率)', mn:'比率'},
  'mercury': {rt:'merc', af:'merc(水银)+ury', mn:'水银/水星'},
  'dilute': {rt:'lut', af:'di(分开)+lute(洗)', mn:'冲淡 → 稀释'},
  'static': {rt:'st', af:'stat(站)+ic', mn:'静止的'},
  'inherent': {rt:'her', af:'in(内)+her(粘)+ent', mn:'粘在内部 → 固有的'},
  'formula': {rt:'form', af:'form(形)+ula(小)', mn:'定型 → 公式'},
  'empirical': {rt:'empir', af:'empir(经验)+ical', mn:'经验的'},
  'doctrine': {rt:'doc', af:'doc(教)+trine', mn:'教义'},
  'forum': {rt:'forum', af:'forum(广场)', mn:'论坛'},
  'rudimentary': {rt:'rud', af:'rud(粗)+imentary', mn:'粗糙的 → 基本的'},
  'elementary': {rt:'element', af:'element(元素)+ary', mn:'基本的/初级的'},
  'selective': {rt:'lect', af:'se(分开)+lect(选)+ive', mn:'选择性的'},
  'dictate': {rt:'dict', af:'dict(说)+ate', mn:'口述/命令'},
  'plagiarise': {rt:'plagiar', af:'plagiar(斜/偷)+ise', mn:'偷抄 → 抄袭'},
  'outset': {rt:'set', af:'out(出)+set(出发)', mn:'出发 → 开始'},
  'gist': {rt:'gist', af:'gist(要点)', mn:'gist 联想 essence：要点'},
  'cite': {rt:'cit', af:'cit(引用)+e', mn:'引用'},
  'quote': {rt:'quote', af:'quote(引述)', mn:'引用'},
  'summary': {rt:'sum', af:'sum(总)+mary', mn:'总结'},
  'postulate': {rt:'postul', af:'postul(要求)+ate', mn:'要求成立的 → 假定'},
  'diagnose': {rt:'gnos', af:'dia(通过)+gnos(知道)+e', mn:'通过检查知道 → 诊断'},
  'infer': {rt:'fer', af:'in(内)+fer(带)', mn:'从内带出 → 推断'},
  'analogy': {rt:'log', af:'ana(按)+log(言)+y', mn:'按同理说 → 类比'},
  'inductive': {rt:'duct', af:'in(进)+duct(引导)+ive', mn:'归纳的'},
  'instance': {rt:'st', af:'in(在)+stance(站)', mn:'站在眼前 → 例子'},
  'manifest': {rt:'man', af:'mani(手)+fest(打)', mn:'用手指出 → 表明'},
  'underestimate': {rt:'estim', af:'under(下)+estimate(估计)', mn:'低估'},
  'overestimate': {rt:'estim', af:'over(上)+estimate(估计)', mn:'高估'},
  'mechanic': {rt:'mechan', af:'mechan(机器)+ic', mn:'机械师'},
  'uncover': {rt:'cover', af:'un(开)+cover(盖)', mn:'揭开 → 揭露'},
  'domain': {rt:'dom', af:'dom(主人)+ain', mn:'主人的领地 → 领域'},
  'realm': {rt:'realm', af:'realm(王国)', mn:'王国 → 领域'},
  'utilise': {rt:'util', af:'util(用)+ise', mn:'利用'},
  'usage': {rt:'us', af:'us(用)+age', mn:'用法/用量'},
  'compute': {rt:'put', af:'com(共同)+pute(算)', mn:'计算'},
  'optics': {rt:'optic', af:'optic(光)+s', mn:'光学'},
  'lens': {rt:'lens', af:'lens(透镜)', mn:'透镜'},
  'radar': {rt:'radar', af:'radar(雷达)', mn:'雷达'},
  'multimedia': {rt:'multi·media', af:'multi(多)+media(媒体)', mn:'多媒体'},
  'microcomputer': {rt:'micro·compute', af:'micro(小)+computer(计算机)', mn:'微型计算机'},
  'binary': {rt:'bin', af:'bin(二)+ary', mn:'二进制的'},
  'digital': {rt:'digit', af:'digit(手指/数字)+al', mn:'数字的'},
  'audio': {rt:'aud', af:'aud(听)+io', mn:'音频'},
  'pivot': {rt:'pivot', af:'pivot(枢轴)', mn:'枢轴/旋转'},
  'hydraulic': {rt:'hydro', af:'hydro(水)+aulic', mn:'水力的'},
  'drainage': {rt:'drain', af:'drain(排干)+age', mn:'排水'},
  'ventilation': {rt:'vent', af:'vent(风)+ilation', mn:'通风'},
  'compress': {rt:'press', af:'com(共同)+press(压)', mn:'压在一起 → 压缩'},
  'simplify': {rt:'simpl', af:'simpl(简单)+ify', mn:'简化'},
  'distil': {rt:'still', af:'di(下)+stil(滴)', mn:'滴下提取 → 蒸馏'},
  'mode': {rt:'mod', af:'mod(尺度)+e', mn:'模式'},
  'correct': {rt:'rect', af:'cor(加强)+rect(直)', mn:'弄直 → 正确/纠正'},
  'flaw': {rt:'flaw', af:'flaw(裂缝)', mn:'裂缝 → 缺陷'},
  'fault': {rt:'fault', af:'fault(过错)', mn:'错误/断层'},
  'stumble': {rt:'stumbl', af:'stumble(绊倒)', mn:'绊倒 → 结巴/失误'},
  'contingency': {rt:'ting', af:'con(共同)+ting(触)+ency', mn:'碰上的意外 → 应急'},
  'civilization': {rt:'civ', af:'civ(公民)+ilization', mn:'文明'},
  'tribe': {rt:'tribe', af:'tribe(部落)', mn:'部落'},
  'alien': {rt:'alien', af:'alien(外来的)', mn:'外星人/外来的'},
  'anthropologist': {rt:'anthropo·log', af:'anthropo(人)+log(学)+ist', mn:'研究人的 → 人类学家'},
  'excavate': {rt:'cav', af:'ex(出)+cav(洞)+ate', mn:'挖出洞 → 发掘'},
  'ritual': {rt:'rit', af:'rit(仪式)+ual', mn:'仪式'},
  'chronology': {rt:'chrono·logy', af:'chrono(时间)+logy(学)', mn:'编年学'},
  'emperor': {rt:'imper', af:'imper(命令)+or', mn:'发令者 → 皇帝'},
  'gesture': {rt:'gest', af:'gest(带/做)+ure', mn:'手势'},
  'handwriting': {rt:'hand·write', af:'hand(手)+writing(写)', mn:'笔迹'},
  'pictograph': {rt:'pict·graph', af:'pict(画)+graph(写)', mn:'画写的 → 象形文字'},
  'wedge': {rt:'wedge', af:'wedge(楔子)', mn:'楔形文字'},
  'knot': {rt:'knot', af:'knot(结)', mn:'绳结/结'},
  'linguistics': {rt:'lingu', af:'lingu(舌/语言)+istics', mn:'语言学'},
  'semantic': {rt:'sema', af:'sema(符号)+ntic', mn:'语义的'},
  'syntax': {rt:'syn·tax', af:'syn(共同)+tax(排列)', mn:'排列规则 → 句法'},
  'phonetics': {rt:'phon', af:'phon(声音)+etics', mn:'语音学'},
  'pronounce': {rt:'nunc', af:'pro(向前)+nounce(宣布)', mn:'发音'},
  'intonation': {rt:'ton', af:'in(加强)+ton(音)+ation', mn:'语调'},
  'inflection': {rt:'flect', af:'in(内)+flect(弯)+ion', mn:'词形变化/语调变化'},
  'dialect': {rt:'lect', af:'dia(之间)+lect(说)', mn:'方言'},
  'accent': {rt:'cent', af:'ac+cent(唱)', mn:'口音'},
  'utterance': {rt:'utter', af:'utter(说出)+ance', mn:'话语'},
  'oral': {rt:'or', af:'or(口)+al', mn:'口头的'},
  'verbal': {rt:'verb', af:'verb(词/言)+al', mn:'言语的/动词的'},
  'syllable': {rt:'syllab', af:'syl(一起)+lab(拿)+le', mn:'音节'},
  'phoneme': {rt:'phon', af:'phon(音)+eme', mn:'音素'},
  'vowel': {rt:'vowel', af:'vowel(元音)', mn:'元音'},
  'consonant': {rt:'son', af:'con(共同)+son(音)+ant', mn:'辅音'},
  'alphabet': {rt:'alpha·beta', af:'alpha(α)+beta(β)', mn:'字母表'},
  'logogram': {rt:'logo·gram', af:'logo(词)+gram(写)', mn:'表意文字'},
  'idiom': {rt:'idiom', af:'idiom(习语)', mn:'习语'},
  'phrase': {rt:'phrase', af:'phrase(短语)', mn:'短语'},
  'clause': {rt:'claus', af:'clause(分句)', mn:'从句/条款'},
  'tense': {rt:'tens', af:'tens(伸)+e', mn:'时态'},
  'prefix': {rt:'fix', af:'pre(前)+fix(固定)', mn:'前缀'},
  'suffix': {rt:'fix', af:'suf(后)+fix(固定)', mn:'后缀'},
  'abbreviation': {rt:'brev', af:'ab(缩短)+brev(短)+iation', mn:'缩写'},
  'synonym': {rt:'syn·onym', af:'syn(同)+onym(名)', mn:'同义词'},
  'antonym': {rt:'ant·onym', af:'ant(反)+onym(名)', mn:'反义词'},
  'noun': {rt:'noun', af:'noun(名词)', mn:'名词'},
  'singular': {rt:'singul', af:'singul(单)+ar', mn:'单数'},
  'plural': {rt:'plur', af:'plur(多)+al', mn:'复数'},
  'pronoun': {rt:'pro·noun', af:'pro(代)+noun(名)', mn:'代词'},
  'verb': {rt:'verb', af:'verb(词/言)', mn:'动词'},
  'adjective': {rt:'ject', af:'ad(向)+ject(扔)+ive', mn:'形容词'},
  'adverb': {rt:'verb', af:'ad(向)+verb(词)', mn:'副词'},
  'preposition': {rt:'pos', af:'pre(前)+posit(放)+ion', mn:'介词'},
  'conjunction': {rt:'junct', af:'con(共同)+junct(连接)+ion', mn:'连词'},
  'paraphrase': {rt:'para·phrase', af:'para(旁)+phrase(说)', mn:'换句话 → 释义'},
  'narrate': {rt:'nar', af:'nar(知道)+rate', mn:'讲述'},
  'decipher': {rt:'cipher', af:'de(解开)+cipher(密码)', mn:'解密码 → 破译'},
  'eloquence': {rt:'loqu', af:'e(出)+loqu(说)+ence', mn:'说得好 → 口才'},
  'commentary': {rt:'ment', af:'comment(评论)+ary', mn:'评述'},
  'contention': {rt:'tend', af:'con(共同)+tent(伸)+ion', mn:'争着伸 → 争论'},
  'messenger': {rt:'miss', af:'mess(送)+enger', mn:'送信人'},
  'simulate': {rt:'simul', af:'simul(相似)+ate', mn:'模拟'},
  'role': {rt:'role', af:'role(角色)', mn:'角色'},
  'aesthetic': {rt:'aesthet', af:'aesthet(感觉)+ic', mn:'审美的'},
  'rhythm': {rt:'rhythm', af:'rhythm(节奏)', mn:'节奏'},
  'chess': {rt:'chess', af:'chess(国际象棋)', mn:'象棋'},
  'bat': {rt:'bat', af:'bat(蝙蝠/球拍)', mn:'蝙蝠/球拍'},
  'flip': {rt:'flip', af:'flip(翻转)', mn:'翻转'},
  'drift': {rt:'drift', af:'drift(漂流)', mn:'漂流'},
  'artifact': {rt:'art·fact', af:'art(技艺)+fact(做)', mn:'人工制品 → 文物'},
  'crude': {rt:'crud', af:'crud(粗糙)+e', mn:'粗糙的/原油的'},
  'necessity': {rt:'necess', af:'necess(必要)+ity', mn:'必要性'},
  'cord': {rt:'cord', af:'cord(心/绳)', mn:'绳/索'},
  'strand': {rt:'strand', af:'strand(股/线)', mn:'一股线'},
  'portfolio': {rt:'folio', af:'port(携带)+folio(纸张)', mn:'作品集'},
  'opacity': {rt:'opac', af:'opac(不透明)+ity', mn:'不透明度'},
  'barrel': {rt:'barrel', af:'barrel(桶)', mn:'桶'},
  'alloy': {rt:'alloy', af:'al(向)+loy(绑)', mn:'绑合 → 合金'},
  'fiber': {rt:'fibr', af:'fibr(纤维)+er', mn:'纤维'},
  'fabric': {rt:'fabric', af:'fabric(织物)', mn:'织物/结构'},
  'weave': {rt:'weave', af:'weave(编织)', mn:'编织'},
  'lubricate': {rt:'lubric', af:'lubric(滑)+ate', mn:'润滑'},
  'dye': {rt:'dye', af:'dye(染料)', mn:'染料'},
  'legislate': {rt:'leg·lat', af:'leg(法律)+islate(提出)', mn:'立法'},
  'period': {rt:'period', af:'peri(周围)+od(路)', mn:'走一圈 → 周期/时期'},
  'proceed': {rt:'ceed', af:'pro(向前)+ceed(走)', mn:'向前走 → 进行'},
  'sector': {rt:'sect', af:'sect(切)+or', mn:'切出的一块 → 部门/扇形'},
  'equate': {rt:'equ', af:'equ(相等)+ate', mn:'相等'},
  'final': {rt:'fin', af:'fin(结束)+al', mn:'最终的'},
  'injure': {rt:'jur', af:'in(不)+jure(法律)', mn:'不合法伤害 → 伤害'},
  'seek': {rt:'seek', af:'seek(寻找)', mn:'寻找'},
  'text': {rt:'text', af:'text(编织)', mn:'编织的文字 → 文本'},
  'alternative': {rt:'alter', af:'altern(其他)+ative', mn:'另一个选择 → 备选的'},
  'convene': {rt:'ven', af:'con(共同)+vene(来)', mn:'聚来开会 → 召集'},
  'corporate': {rt:'corpor', af:'corpor(身体/团体)+ate', mn:'团体的 → 公司的'},
  'criteria': {rt:'crit', af:'crit(判断)+eria', mn:'标准'},
  'exclude': {rt:'clud', af:'ex(出)+clude(关闭)', mn:'关在外面 → 排除'},
  'immigrate': {rt:'migr', af:'im(进)+migr(迁移)+ate', mn:'迁入 → 移民'},
  'maximise': {rt:'max', af:'max(最大)+imise', mn:'最大化'},
  'negate': {rt:'neg', af:'neg(否定)+ate', mn:'否定'},
};
module.exports = { BATCH };
