'use strict';
/* P3 词根词缀批次 1（chunk1，291 学术词）：{word: {rt 词根, af 词缀拆分+含义, mn 记忆提示}} */
const BATCH = {
  'homework': {rt:'work', af:'home(家)+work(作业)', mn:'在家做的工作 → 家庭作业'},
  'revise': {rt:'vis', af:'re(再)+vis(看)+e', mn:'再看一遍 → 复习'},
  'job': {rt:'job', af:'job(工作)', mn:'J=Just,O=One,B=Boss：只管一个老板 → 工作'},
  'colleague': {rt:'leg', af:'col(共同)+league(league联盟/leg选)', mn:'colleague 联想 league(联盟)：一起共事的人 → 同事'},
  'vehicle': {rt:'veh', af:'veh(运载)+icle(小词缀)', mn:'veh 联想 carry：运载人的工具 → 车辆'},
  'route': {rt:'route', af:'route(路)', mn:'route = r+oute，联想 road(路)：走的路 → 路线'},
  'recover': {rt:'cover', af:'re(重新)+cover(覆盖/获得)', mn:'重新获得健康 → 恢复'},
  'stress': {rt:'stress', af:'stress(压)', mn:'st+ress，联想 press(压)：被压住 → 压力'},
  'relax': {rt:'lax', af:'re(加强)+lax(放松)', mn:'lax=松：放松下来 → 休息'},
  'cure': {rt:'cure', af:'cure(医治)', mn:'cure = cur(关心)+e：关心病人 → 治愈'},
  'environment': {rt:'viron', af:'en(使)+viron(环绕)+ment', mn:'环绕你的周围 → 环境'},
  'energy': {rt:'erg', af:'en(使)+erg(工作)+y', mn:'erg=工作：能干活的东西 → 能量'},
  'resource': {rt:'source', af:'re(再)+source(源泉)', mn:'再生的源泉 → 资源'},
  'noisy': {rt:'noise', af:'noise(噪音)+y(形容词)', mn:'noise 噪音 → 吵闹的'},
  'research': {rt:'search', af:'re(再)+search(寻找)', mn:'反复寻找 → 研究'},
  'data': {rt:'data', af:'data(数据)', mn:'data=给(的东西)：给出的资料 → 数据'},
  'method': {rt:'hod', af:'meta(沿)+hod(路)', mn:'沿着一条路走 → 方法'},
  'experiment': {rt:'peri', af:'ex(向外)+peri(尝试)+ment', mn:'向外试 → 实验'},
  'result': {rt:'sult', af:'re(回)+sult(跳)', mn:'跳回来 → 结果'},
  'cause': {rt:'cause', af:'cause(原因)', mn:'cause 与 because 同源：因为 → 原因'},
  'effect': {rt:'fect', af:'ef(出)+fect(做)', mn:'做出来的东西 → 效果'},
  'example': {rt:'empl', af:'ex(出)+ample(取)', mn:'取出来给人看 → 例子'},
  'reason': {rt:'ratio', af:'reason(理性/理由)', mn:'reason 联想 ratio(比率/理性)：讲道理 → 原因'},
  'suggest': {rt:'gest', af:'sug(下)+gest(带来)', mn:'从下面带上来 → 建议'},
  'prove': {rt:'prob', af:'pro(向前)+ve(验证)', mn:'prove 联想 prove(证明)：证实'},
  'examine': {rt:'exam', af:'ex(出)+amin(检查)', mn:'examine = ex+amine：仔细查看 → 检查'},
  'measure': {rt:'mens', af:'measure(量)', mn:'measure = mea+sure：量出大小 → 测量'},
  'compare': {rt:'par', af:'com(共同)+par(相等)+e', mn:'把两者放在一起看相等 → 比较'},
  'similar': {rt:'simil', af:'simil(相似)+ar', mn:'simil 同 same：相似的'},
  'conclusion': {rt:'clud', af:'con(完全)+clud(关闭)+sion', mn:'把讨论关起来 → 结论'},
  'available': {rt:'val', af:'avail(有用)+able', mn:'avail=有用：能用的 → 可获得的'},
  'bargain': {rt:'bargain', af:'bargain(交易)', mn:'bargain 联想 bar(酒吧)+gain(得到)：砍价买到 → 便宜货'},
  'guarantee': {rt:'guar', af:'guar(保护)+antee', mn:'guar 联想 guard(守卫)：保证安全 → 保证'},
  'benefit': {rt:'bene', af:'bene(好)+fit(做)', mn:'bene=好：做好事得到好处 → 利益'},
  'disadvantage': {rt:'vant', af:'dis(否定)+advantage(优势)', mn:'没有优势 → 劣势'},
  'lecture': {rt:'leg', af:'lect(读)+ure', mn:'lect=读：朗读讲义 → 讲座'},
  'deadline': {rt:'line', af:'dead(死)+line(线)', mn:'过了这条线就死 → 截止日期'},
  'syllabus': {rt:'syllab', af:'syllabus(课程大纲)', mn:'syllabus 联想 syllable(音节)：列出的课程表 → 教学大纲'},
  'scholarship': {rt:'schol', af:'schol(学)+ar+ship', mn:'schol 同 school：给学者的钱 → 奖学金'},
  'shift': {rt:'shift', af:'shift(转换/轮班)', mn:'shift 联想 shift键：切换 → 轮班'},
  'destination': {rt:'stin', af:'de(加强)+stin(站)+ation', mn:'要站定的地方 → 目的地'},
  'transfer': {rt:'fer', af:'trans(跨越)+fer(搬运)', mn:'fer=搬：搬过去 → 转移'},
  'emission': {rt:'miss', af:'e(出)+miss(送)+ion', mn:'miss=送：送出去 → 排放'},
  'conservation': {rt:'serv', af:'con(完全)+serv(保持)+ation', mn:'完全保持 → 保护(资源)'},
  'biodiversity': {rt:'bio·diverse', af:'bio(生命)+diversity(多样)', mn:'生命的多样性 → 生物多样性'},
  'rainfall': {rt:'fall', af:'rain(雨)+fall(落)', mn:'雨落下来 → 降雨量'},
  'habitat': {rt:'habit', af:'habit(居住)+at', mn:'habit=居住：生物居住的地方 → 栖息地'},
  'hypothesis': {rt:'thes', af:'hypo(下面)+thes(放)+is', mn:'放在下面做基础的假设 → 假说'},
  'evidence': {rt:'vid', af:'e(出)+vid(看)+ence', mn:'看得见的东西 → 证据'},
  'analyse': {rt:'lys', af:'ana(分开)+lys(解开)+e', mn:'把整体拆开 → 分析'},
  'publication': {rt:'publ', af:'public(公开)+ation', mn:'公开出版 → 出版物'},
  'citation': {rt:'cit', af:'cit(呼唤/引用)+ation', mn:'cit 联想 quote：引用的文字 → 引用'},
  'peer review': {rt:'peer·view', af:'peer(同辈)+review(评审)', mn:'同行评审 → 同行审稿'},
  'abstract': {rt:'tract', af:'abs(离开)+tract(拉)', mn:'从正文拉出来的摘要 → 摘要/抽象的'},
  'bibliography': {rt:'biblio·graphy', af:'biblio(书)+graphy(写)', mn:'写书目录 → 参考书目'},
  'thesis': {rt:'thes', af:'thes(放)+is', mn:'放出来立论 → 论文/论点'},
  'sample': {rt:'sample', af:'sample(样本)', mn:'sample 联想 example：取出的代表 → 样本'},
  'survey': {rt:'vey', af:'sur(上)+vey(看)', mn:'从上往下看 → 调查'},
  'trend': {rt:'trend', af:'trend(趋势)', mn:'trend 联想 turn：转向的方向 → 趋势'},
  'purchase': {rt:'chas', af:'pur(向前)+chase(追)', mn:'追着买 → 购买'},
  'label': {rt:'label', af:'label(标签)', mn:'label 联想 label(标签)：贴上的名称'},
  'argument': {rt:'arg', af:'arg(论证)+ument', mn:'argue(争论)的名词 → 论点'},
  'claim': {rt:'claim', af:'claim(喊/宣称)', mn:'claim 联想 call(喊)：大声说出 → 声称'},
  'opinion': {rt:'opin', af:'op(选择)+in+ion', mn:'opin 联想 open(开放)：开放的想法 → 观点'},
  'support': {rt:'port', af:'sup(下)+port(搬运)', mn:'在下面托着 → 支持'},
  'illustrate': {rt:'lustr', af:'il(使)+lustr(照亮)+ate', mn:'照亮让人看清 → 说明/图解'},
  'emphasise': {rt:'phas', af:'em(使)+phas(显示)+ise', mn:'使显示出来 → 强调'},
  'consequence': {rt:'sequ', af:'con(跟随)+sequ(跟随)+ence', mn:'跟着来的结果 → 后果'},
  'contribute': {rt:'tribut', af:'con(共同)+tribut(给)+e', mn:'一起给 → 贡献'},
  'factor': {rt:'fact', af:'fact(做)+or', mn:'做事情的因素 → 因素'},
  'significant': {rt:'sign', af:'sign(标记)+ific+ant', mn:'有标记的 → 重要的'},
  'marginal': {rt:'margin', af:'margin(边缘)+al', mn:'在边缘的 → 边缘的/微小的'},
  'gradual': {rt:'grad', af:'grad(步)+ual', mn:'一步步的 → 逐渐的'},
  'sharp': {rt:'sharp', af:'sharp(尖锐)', mn:'sharp 联想刀尖：锐利的 → 急剧的'},
  'fluctuate': {rt:'fluct', af:'fluct(流动)+uate', mn:'fluct=flow：来回流动 → 波动'},
  'peak': {rt:'peak', af:'peak(峰顶)', mn:'peak 联想山尖：最高点 → 顶峰'},
  'plateau': {rt:'plat', af:'plat(平)+eau', mn:'plat=flat(平)：平原 → 高原/平台期'},
  'proportion': {rt:'port', af:'pro(按照)+portion(部分)', mn:'按部分分配 → 比例'},
  'figure': {rt:'fig', af:'fig(做/形)+ure', mn:'fig 联想 make：做出来的形 → 数字/图表'},
  'estimate': {rt:'est', af:'estim(估价)+ate', mn:'估个价 → 估计'},
  'double': {rt:'du', af:'du(二)+ble', mn:'du 同 two：变成两倍 → 翻倍'},
  'whereas': {rt:'where·as', af:'where(哪里)+as(如同)', mn:'在哪里与何处不同 → 然而/反之'},
  'similarly': {rt:'simil', af:'simil(相似)+ar+ly', mn:'相似的 → 同样地'},
  'differ': {rt:'fer', af:'dif(分开)+fer(带)', mn:'带着不同的方向 → 不同'},
  'distinct': {rt:'stinct', af:'di(分开)+stinct(刺)', mn:'刺开分开 → 截然不同的'},
  'justify': {rt:'just', af:'just(公正)+ify(使)', mn:'使公正 → 证明有理'},
  'summarise': {rt:'sum', af:'sum(总和)+marise', mn:'取总和 → 总结'},
  'overall': {rt:'over·all', af:'over(全部)+all(全部)', mn:'全部之上 → 总体上'},
  'notably': {rt:'not', af:'not(标记)+ably', mn:'not 联想 note：值得注意地 → 显著地'},
  'graph': {rt:'graph', af:'graph(写/画)', mn:'graph 联想 photo：画出来的图 → 图表'},
  'comparison': {rt:'par', af:'com(共同)+par(相等)+ison', mn:'放在一起比 → 比较'},
  'percentage': {rt:'cent', af:'per(每)+cent(百)+age', mn:'每一百 → 百分比'},
  'achieve': {rt:'chief', af:'a(向)+chieve(头)', mn:'向着头(目标) → 达成'},
  'policy': {rt:'pol', af:'pol(城邦/治理)+icy', mn:'治理城市的办法 → 政策'},
  'individual': {rt:'divid', af:'in(不)+divid(分开)+ual', mn:'不能再分的 → 个人的'},
  'inequality': {rt:'equ', af:'in(不)+equal(相等)+ity', mn:'不相等 → 不平等'},
  'income': {rt:'come', af:'in(进)+come(来)', mn:'进来的钱 → 收入'},
  'surplus': {rt:'plus', af:'sur(超过)+plus(加)', mn:'加过头 → 过剩'},
  'sustainable': {rt:'tain', af:'sus(向上)+tain(保持)+able', mn:'能一直保持 → 可持续的'},
  'mental': {rt:'ment', af:'ment(心智)+al', mn:'心智的 → 精神的'},
  'technology': {rt:'tech·logy', af:'tech(技艺)+logy(学)', mn:'技艺之学 → 技术'},
  'device': {rt:'vis', af:'de(分开)+vic(看)+e', mn:'设计出来的东西 → 设备'},
  'artificial': {rt:'fic', af:'art(技艺)+i+fic(做)+ial', mn:'人工做的 → 人造的'},
  'curriculum': {rt:'curr', af:'curr(跑)+iculum', mn:'课程要跑过的路线 → 课程'},
  'productivity': {rt:'duct', af:'pro(向前)+duct(引导)+ivity', mn:'产出能力 → 生产力'},
  'flexible': {rt:'flect', af:'flex(弯曲)+ible', mn:'能弯曲的 → 灵活的'},
  'infrastructure': {rt:'struct', af:'infra(下)+struct(建造)+ure', mn:'底下建造的基础 → 基础设施'},
  'positive': {rt:'pos', af:'pos(放)+itive', mn:'正面放着的 → 积极的'},
  'contrast': {rt:'st', af:'contra(对立)+st(站)', mn:'对立而站 → 对比'},
  'similarity': {rt:'simil', af:'simil(相似)+arity', mn:'相似性'},
  'transform': {rt:'form', af:'trans(改变)+form(形)', mn:'改变形状 → 转变'},
  'implement': {rt:'ple', af:'im(使)+ple(满)+ment', mn:'填满使它运作 → 实施'},
  'evaluate': {rt:'valu', af:'e(出)+valu(价值)+ate', mn:'算出价值 → 评估'},
  'debate': {rt:'bat', af:'de(下)+bat(打)+e', mn:'打嘴仗 → 辩论'},
  'fundamental': {rt:'fund', af:'fund(基础)+a+mental', mn:'作为地基的 → 根本的'},
  'major': {rt:'major', af:'major(大)', mn:'major 联想 mayor(市长)：大的 → 主要的'},
  'minor': {rt:'minor', af:'minor(小)', mn:'minor 联想 minus(减)：小的 → 次要的'},
  'widespread': {rt:'wide·spread', af:'wide(宽)+spread(展开)', mn:'铺开得很宽 → 广泛分布的'},
  'previous': {rt:'vi', af:'pre(前)+vi(路)+ous', mn:'前面走过的路 → 先前的'},
  'despite': {rt:'spite', af:'de(下)+spite(看)', mn:'往下看不管 → 尽管'},
  'attitude': {rt:'tude', af:'attitud(态度)+e', mn:'attitude 联想 apt(倾向)：倾向的态度'},
  'terminal': {rt:'termin', af:'termin(边界)+al', mn:'到边界的 → 终端的'},
  'draft': {rt:'draft', af:'draft(草稿)', mn:'draft 联想 draw(画)：画出的初稿 → 草稿'},
  'outlet': {rt:'let', af:'out(出)+let(让)', mn:'让东西出去的口 → 出口'},
  'adjacent': {rt:'jac', af:'ad(向)+jac(躺)+ent', mn:'躺在旁边的 → 相邻的'},
  'exit': {rt:'it', af:'ex(出)+it(走)', mn:'走出去 → 出口'},
  'surge': {rt:'surge', af:'surge(涌起)', mn:'surge 联想 up：往上涌 → 激增'},
  'plummet': {rt:'plummet', af:'plummet(铅垂)', mn:'像铅一样坠下 → 暴跌'},
  'dip': {rt:'dip', af:'dip(蘸/下倾)', mn:'蘸下去又上来 → 小幅下降'},
  'rebound': {rt:'bound', af:'re(再)+bound(弹)', mn:'反弹回来 → 回升'},
  'escalate': {rt:'scal', af:'e(出)+scal(梯)+ate', mn:'爬上梯子 → 升级/加剧'},
  'diminish': {rt:'min', af:'di(向下)+min(小)+ish', mn:'变小 → 减少'},
  'halve': {rt:'half', af:'halv(半)+e', mn:'变成一半 → 减半'},
  'triple': {rt:'tri', af:'tri(三)+ple', mn:'tri 同 three：三倍 → 增至三倍'},
  'outstrip': {rt:'strip', af:'out(超)+strip(跑)', mn:'跑在前面 → 超过'},
  'account for': {rt:'count', af:'account(计算)+for', mn:'算清楚原因 → 占/解释'},
  'comprise': {rt:'prise', af:'com(共同)+prise(抓住)', mn:'抓在一起 → 包含'},
  'approximately': {rt:'proxim', af:'ap+proxim(接近)+ately', mn:'接近 → 大约'},
  'fluctuation': {rt:'fluct', af:'fluct(流动)+uation', mn:'流动变化 → 波动'},
  'considerable': {rt:'sider', af:'con(加强)+sider(星)+able', mn:'像星星一样多 → 相当大的'},
  'modest': {rt:'mod', af:'mod(适度)+est', mn:'适度的 → 不大的'},
  'slight': {rt:'slight', af:'slight(轻微)', mn:'slight 联想 light(轻)：很轻的 → 轻微的'},
  'marked': {rt:'mark', af:'mark(标记)+ed', mn:'有标记的 → 明显的'},
  'conversely': {rt:'vers', af:'con(反转)+verse(转)+ly', mn:'转过来 → 相反地'},
  'give rise to': {rt:'rise', af:'give(给)+rise(升起)+to', mn:'使升起 → 引起'},
  'stem from': {rt:'stem', af:'stem(茎)+from(从)', mn:'从茎长出 → 源于'},
  'bring about': {rt:'bring·about', af:'bring(带来)+about(四周)', mn:'带来 → 导致'},
  'hinder': {rt:'hinder', af:'hinder(阻碍)', mn:'hinder 联想 behind(后面)：把人拖在后面 → 阻碍'},
  'facilitate': {rt:'facil', af:'facil(容易)+itate', mn:'使容易 → 促进'},
  'accelerate': {rt:'celer', af:'ac(使)+celer(快)+ate', mn:'celer=fast：加速'},
  'crucial': {rt:'cruc', af:'cruc(十字)+ial', mn:'在十字路口的关键 → 关键的'},
  'paramount': {rt:'mount', af:'para(超过)+mount(山)', mn:'比山还高 → 至上的'},
  'indispensable': {rt:'pens', af:'in(不)+dispensable(可免除)', mn:'不可免除的 → 不可或缺的'},
  'merit': {rt:'merit', af:'merit(价值)', mn:'merit 联想 worth：值得 → 优点'},
  'downside': {rt:'side', af:'down(下)+side(边)', mn:'下面那一边 → 缺点'},
  'shortcoming': {rt:'short·coming', af:'short(短)+coming(来)', mn:'不足之处 → 缺点'},
  'pitfall': {rt:'fall', af:'pit(坑)+fall(落)', mn:'掉进坑里 → 陷阱/隐患'},
  'trade-off': {rt:'trade·off', af:'trade(交易)+off(掉)', mn:'用这个换那个 → 权衡'},
  'majority': {rt:'major', af:'major(大)+ity', mn:'大的部分 → 大多数'},
  'minority': {rt:'minor', af:'minor(小)+ity', mn:'小的部分 → 少数'},
  'contend': {rt:'tend', af:'con(共同)+tend(伸)', mn:'伸出手争 → 主张/竞争'},
  'assert': {rt:'sert', af:'as(向)+sert(连接)', mn:'把自己的话接上 → 断言'},
  'advocate': {rt:'voc', af:'ad(向)+voc(喊)+ate', mn:'为某人喊 → 提倡'},
  'oppose': {rt:'pos', af:'op(相反)+pos(放)+e', mn:'放在对面 → 反对'},
  'reject': {rt:'ject', af:'re(回)+ject(扔)', mn:'扔回去 → 拒绝'},
  'refute': {rt:'fut', af:'re(回)+fute(打)', mn:'打回去 → 驳斥'},
  'concede': {rt:'cede', af:'con(完全)+cede(让)', mn:'完全让出 → 让步/承认'},
  'acknowledge': {rt:'know', af:'ac+know(知道)+ledge', mn:'使知道 → 承认'},
  'highlight': {rt:'light', af:'high(高)+light(光)', mn:'高高亮起 → 强调'},
  'underscore': {rt:'score', af:'under(下)+score(线)', mn:'在下面划线 → 强调'},
  'spotlight': {rt:'light', af:'spot(点)+light(光)', mn:'聚光灯照着 → 凸显'},
  'furthermore': {rt:'further·more', af:'further(更远)+more(更多)', mn:'更进一步 → 此外'},
  'nevertheless': {rt:'never·the·less', af:'never(绝不)+the+less(少)', mn:'绝不少 → 然而/仍然'},
  'hence': {rt:'hence', af:'hence(因此)', mn:'hence 联想 here(这里)：从这里 → 因此'},
  'accordingly': {rt:'cord', af:'ac+cord(心)+ingly', mn:'随其心 → 相应地'},
  'subsequently': {rt:'sequ', af:'sub(下)+sequ(跟随)+ently', mn:'跟在后面 → 随后'},
  'simultaneously': {rt:'simul', af:'simul(同时)+taneously', mn:'同时发生 → 同时地'},
  'alleviate': {rt:'lev', af:'al(使)+lev(轻)+iate', mn:'使变轻 → 减轻'},
  'mitigate': {rt:'mitig', af:'mitig(温和)+ate', mn:'使温和 → 缓解'},
  'remedy': {rt:'med', af:'re(回)+med(医治)+y', mn:'医回去 → 补救'},
  'eradicate': {rt:'radic', af:'e(出)+radic(根)+ate', mn:'连根拔出 → 根除'},
  'curb': {rt:'curb', af:'curb(勒住)', mn:'curb 联想 curb(马嚼子)：勒住 → 抑制'},
  'resolve': {rt:'solv', af:'re(再)+solve(解开)', mn:'解开问题 → 解决'},
  'accessibility': {rt:'cess', af:'ac(向)+cess(走)+ibility', mn:'能走过去 → 可及性'},
  'affordability': {rt:'ford', af:'af+ford(承担)+ability', mn:'承担得起 → 可负担性'},
  'efficacy': {rt:'fic', af:'ef(出)+fic(做)+acy', mn:'做出来的效力 → 功效'},
  'feasibility': {rt:'fac', af:'feas(做)+ibility', mn:'能做成 → 可行性'},
  'longevity': {rt:'long', af:'long(长)+evity(年龄)', mn:'活得长 → 长寿'},
  'prosperity': {rt:'sper', af:'pro(向前)+sper(希望)+ity', mn:'向前有希望 → 繁荣'},
  'disparity': {rt:'par', af:'dis(不)+par(相等)+ity', mn:'不相等 → 差距'},
  'discrepancy': {rt:'crep', af:'dis(分开)+crep(发出)+ancy', mn:'发出的声音不一致 → 差异'},
  'prevalence': {rt:'val', af:'pre(前)+val(强壮)+ence', mn:'强占前面 → 盛行'},
  'propensity': {rt:'pend', af:'pro(向前)+pens(悬挂)+ity', mn:'向前倾向 → 倾向'},
  'reluctance': {rt:'luct', af:'re(反)+luct(挣扎)+ance', mn:'挣扎不愿 → 不情愿'},
  'depict': {rt:'pict', af:'de(加强)+pict(画)', mn:'pict 联想 picture：画出来 → 描绘'},
  'demonstrate': {rt:'monstr', af:'de(加强)+monstr(展示)+ate', mn:'展示出来 → 证明/演示'},
  'exhibit': {rt:'hibit', af:'ex(出)+hibit(拿)', mn:'拿出来展示 → 展出'},
  'indicate': {rt:'dic', af:'in(向)+dic(说)+ate', mn:'指着说 → 表明'},
  'outline': {rt:'line', af:'out(外)+line(线)', mn:'画出外线 → 概述'},
  'prevalent': {rt:'val', af:'pre(前)+val(强壮)+ent', mn:'强占前面的 → 流行的'},
  'ubiquitous': {rt:'ubique', af:'ubi(到处)+quitous', mn:'到处都是 → 无处不在的'},
  'pervasive': {rt:'vas', af:'per(通过)+vas(走)+ive', mn:'走遍各处 → 弥漫的'},
  'acute': {rt:'ac', af:'ac(尖)+ute', mn:'尖锐的 → 急性的'},
  'chronic': {rt:'chron', af:'chron(时间)+ic', mn:'时间长久的 → 慢性的'},
  'profound': {rt:'fund', af:'pro(向前)+found(底)', mn:'到最底部 → 深刻的'},
  'subtle': {rt:'sub', af:'sub(下)+tle', mn:'藏在下层的 → 微妙的'},
  'trivial': {rt:'tri', af:'tri(三)+vial(路)', mn:'三条小路的分岔 → 琐碎的'},
  'negligible': {rt:'neg', af:'neg(不)+lig(选)+ible', mn:'可以不选的 → 微不足道的'},
  'drastic': {rt:'drast', af:'drast(行动)+ic', mn:'立即行动的 → 猛烈的'},
  'dramatic': {rt:'drama', af:'drama(戏剧)+tic', mn:'像戏剧一样 → 戏剧性的/剧烈的'},
  'exponential': {rt:'pon', af:'ex(出)+pon(放)+ential', mn:'翻倍放大的 → 指数的'},
  'drastically': {rt:'drast', af:'drastic(猛烈)+ally', mn:'猛烈地 → 大幅地'},
  'substantially': {rt:'st', af:'sub(下)+stant(站)+ially', mn:'站得实 → 实质性地'},
  'marginally': {rt:'margin', af:'margin(边缘)+ally', mn:'在边缘地 → 略微地'},
  'moderately': {rt:'mod', af:'mod(适度)+erately', mn:'适度地'},
  'steeply': {rt:'steep', af:'steep(陡)+ly', mn:'陡峭地 → 急剧地'},
  'gradually': {rt:'grad', af:'grad(步)+ually', mn:'一步步地 → 逐渐地'},
  'markedly': {rt:'mark', af:'mark(标记)+edly', mn:'有明显标记地 → 显著地'},
  'overwhelmingly': {rt:'whelm', af:'over(压倒)+whelm(淹没)+ingly', mn:'压倒性地 → 绝大多数地'},
  'predominantly': {rt:'domin', af:'pre(前)+domin(支配)+antly', mn:'支配前面的 → 主要地'},
  'exceptionally': {rt:'cept', af:'ex(出)+cept(拿)+ionally', mn:'被拿出例外的 → 异常地'},
  'likewise': {rt:'like', af:'like(相似)+wise(方式)', mn:'相似的方式 → 同样地'},
  'notwithstanding': {rt:'stand', af:'not(不)+withstand(抵抗)+ing', mn:'顶住不管 → 尽管'},
  'notion': {rt:'not', af:'not(标记)+ion', mn:'标记在心的想法 → 概念'},
  'coherent': {rt:'her', af:'co(共同)+her(粘)+ent', mn:'粘在一起 → 连贯的'},
  'plausible': {rt:'plaud', af:'plaus(鼓掌)+ible', mn:'值得鼓掌 → 貌似可信的'},
  'ambiguous': {rt:'ambig', af:'ambi(两)+guous', mn:'两边都行 → 模糊的'},
  'explicit': {rt:'plic', af:'ex(出)+plic(折叠)+it', mn:'展开的 → 明确的'},
  'intrinsic': {rt:'intrin', af:'intri(内)+nsic', mn:'内在的 → 本质的'},
  'viable': {rt:'vi', af:'vi(路)+able', mn:'有路可走 → 可行的'},
  'attain': {rt:'tain', af:'at(向)+tain(触碰)', mn:'触到目标 → 达到'},
  'undermine': {rt:'mine', af:'under(下)+mine(挖)', mn:'在下面挖 → 削弱'},
  'retain': {rt:'tain', af:'re(保持)+tain(拿)', mn:'拿住不放 → 保留'},
  'obtain': {rt:'tain', af:'ob(加强)+tain(拿)', mn:'拿到 → 获得'},
  'shuttle': {rt:'shuttle', af:'shuttle(梭子)', mn:'像梭子来回 → 穿梭/班车'},
  'recipe': {rt:'cip', af:'re(回)+cipe(取)', mn:'取回的药方 → 配方'},
  'portion': {rt:'port', af:'port(分)+ion', mn:'分出的一份 → 部分'},
  'dose': {rt:'dose', af:'dose(剂量)', mn:'dose 联想 do(做)+se：做一次的量 → 剂量'},
  'injection': {rt:'ject', af:'in(进)+ject(扔)+ion', mn:'扔进去 → 注射'},
  'diagnosis': {rt:'gnos', af:'dia(通过)+gnos(知道)+is', mn:'通过检查知道 → 诊断'},
  'deficiency': {rt:'fic', af:'de(缺)+fic(做)+iency', mn:'做不够 → 缺乏'},
  'bacteria': {rt:'bacter', af:'bacter(杆)+ia', mn:'杆菌状 → 细菌'},
  'fracture': {rt:'fract', af:'fract(断)+ure', mn:'fract 联想 break：断裂 → 骨折'},
  'supplement': {rt:'ple', af:'sup(下)+ple(满)+ment', mn:'补充填满 → 补充'},
  'fever': {rt:'fever', af:'fever(热)', mn:'fever 联想 fire(火)：身体发热 → 发烧'},
  'consultation': {rt:'sult', af:'con(共同)+sult(商量)+ation', mn:'一起商量 → 咨询'},
  'discharge': {rt:'charge', af:'dis(去除)+charge(负荷)', mn:'卸下负荷 → 出院/排出'},
  'transplant': {rt:'plant', af:'trans(转移)+plant(种植)', mn:'移种过去 → 移植'},
  'donor': {rt:'don', af:'don(给)+or', mn:'don=give：给东西的人 → 捐赠者'},
  'breakthrough': {rt:'break·through', af:'break(破)+through(通过)', mn:'破墙而出 → 突破'},
  'invention': {rt:'vent', af:'in(使)+vent(来)+ion', mn:'使出现 → 发明'},
  'researcher': {rt:'search', af:'re(再)+search(寻找)+er', mn:'反复寻找的人 → 研究者'},
  'specimen': {rt:'spec', af:'spec(看)+imen', mn:'看的东西 → 标本'},
  'observation': {rt:'serv', af:'ob(向)+serv(看)+ation', mn:'看着 → 观察'},
  'methodology': {rt:'hod·logy', af:'method(方法)+logy(学)', mn:'方法之学 → 方法论'},
  'findings': {rt:'find', af:'find(找到)+ings', mn:'找到的结果 → 发现'},
  'patent': {rt:'pat', af:'pat(公开)+ent', mn:'公开的 → 专利'},
  'prototype': {rt:'type', af:'proto(第一)+type(型)', mn:'第一型 → 原型'},
  'gadget': {rt:'gadget', af:'gadget(小机件)', mn:'gadget 联想 gizmo：小玩意儿 → 小装置'},
  'software': {rt:'ware', af:'soft(软)+ware(器)', mn:'软的器件 → 软件'},
  'hardware': {rt:'ware', af:'hard(硬)+ware(器)', mn:'硬的器件 → 硬件'},
  'wireless': {rt:'wire', af:'wire(线)+less(无)', mn:'无线 → 无线的'},
  'network': {rt:'work', af:'net(网)+work(工作)', mn:'织成的网 → 网络'},
  'password': {rt:'word', af:'pass(过)+word(词)', mn:'通过用的词 → 密码'},
  'username': {rt:'name', af:'user(用户)+name(名)', mn:'用户的名字 → 用户名'},
  'browser': {rt:'brows', af:'browse(浏览)+er', mn:'浏览的人/工具 → 浏览器'},
  'virtual': {rt:'virt', af:'virt(德/能)+ual', mn:'实际存在的效力 → 虚拟的'},
  'robotic': {rt:'robot', af:'robot(机器人)+ic', mn:'robot 来自 robota(苦工)：机器人的 → 机器人的'},
  'algorithm': {rt:'arith', af:'algo(算术)+rithm', mn:'算术步骤 → 算法'},
  'database': {rt:'base', af:'data(数据)+base(库)', mn:'数据的仓库 → 数据库'},
  'backup': {rt:'up', af:'back(后)+up(上)', mn:'在后面兜底 → 备份'},
  'sensor': {rt:'sens', af:'sens(感觉)+or', mn:'能感觉的器件 → 传感器'},
  'drone': {rt:'drone', af:'drone(雄蜂)', mn:'雄蜂嗡嗡飞 → 无人机'},
  'artificial intelligence': {rt:'art·fic·lig', af:'artificial(人造)+intelligence(智能)', mn:'人造智能 → 人工智能'},
  'download': {rt:'load', af:'down(下)+load(装载)', mn:'往下装 → 下载'},
  'upload': {rt:'load', af:'up(上)+load(装载)', mn:'往上装 → 上传'},
  'update': {rt:'date', af:'up(上)+date(日期)', mn:'更新到新日期 → 更新'},
  'screen': {rt:'screen', af:'screen(屏)', mn:'screen 联想遮屏：显示的地方 → 屏幕'},
  'battery': {rt:'bat', af:'bat(打)+tery', mn:'能反复放电 → 电池'},
  'charger': {rt:'char', af:'charge(充电)+er', mn:'充电的东西 → 充电器'},
  'cable': {rt:'cable', af:'cable(缆)', mn:'cable 联想 cable TV：缆线'},
  'display': {rt:'play', af:'dis(展开)+play(放)', mn:'展开摆放 → 显示'},
  'assignment': {rt:'sign', af:'as(向)+sign(标记)+ment', mn:'指派的活 → 作业/任务'},
  'undergraduate': {rt:'grad', af:'under(下)+grad(步)+uate', mn:'还没毕业的人 → 本科生'},
  'postgraduate': {rt:'grad', af:'post(后)+grad(步)+uate', mn:'毕业后继续学 → 研究生'},
  'campus': {rt:'camp', af:'camp(营地)+us', mn:'学习营地 → 校园'},
  'faculty': {rt:'fac', af:'fac(做)+ulty', mn:'会做(教)的人 → 院系/教职'},
  'tutor': {rt:'tut', af:'tut(看护)+or', mn:'看着你学的人 → 导师'},
  'seminar': {rt:'semin', af:'semin(种子)+ar', mn:'播种讨论 → 研讨课'},
  'lecturer': {rt:'leg', af:'lect(读)+urer', mn:'朗读讲课的人 → 讲师'},
  'dissertation': {rt:'sert', af:'dis(分开)+sert(连接)+ation', mn:'展开论述 → 学位论文'},
};
module.exports = { BATCH };
