'use strict';
/* P3 词根词缀批次 2（chunk2，291 学术词） */
const BATCH = {
  'bonus': {rt:'bon', af:'bon(好)+us', mn:'bon 联想 good：给的好东西 → 奖金'},
  'pesticide': {rt:'pest', af:'pest(害虫)+i+cide(杀)', mn:'cide=杀：杀害虫的 → 杀虫剂'},
  'contemporary': {rt:'tempor', af:'con(共同)+tempor(时代)+ary', mn:'同一时代的 → 当代的'},
  'archaeology': {rt:'archaeo·logy', af:'archaeo(古代)+logy(学)', mn:'研究古代的学问 → 考古学'},
  'transaction': {rt:'act', af:'trans(跨越)+act(做)+ion', mn:'跨着做交易 → 交易'},
  'fee': {rt:'fee', af:'fee(费)', mn:'fee 联想 free：要交的 → 费用'},
  'currency': {rt:'curr', af:'curr(跑)+ency', mn:'流通的钱 → 货币'},
  'grant': {rt:'grant', af:'grant(给予)', mn:'grant 联想 give：给的钱 → 拨款'},
  'orientation': {rt:'orient', af:'orient(东方/定向)+ation', mn:'找方向 → 迎新/定位'},
  'imminent': {rt:'min', af:'im(上)+min(突出)+ent', mn:'冒出来的 → 即将发生的'},
  'inevitable': {rt:'vit', af:'in(不)+evit(避开)+able', mn:'避不开的 → 不可避免的'},
  'phenomenon': {rt:'phen', af:'phen(显示)+omenon', mn:'显示出来的 → 现象'},
  'paradigm': {rt:'deigm', af:'para(旁)+digm(显示)', mn:'旁边的示范 → 范式'},
  'enhance': {rt:'hanc', af:'en(使)+hance(高)', mn:'使变高 → 增强'},
  'hamper': {rt:'hamper', af:'hamper(阻碍)', mn:'hamper 联想 basket(篮子)：装了东西走不动 → 阻碍'},
  'impede': {rt:'ped', af:'im(向)+ped(脚)+e', mn:'脚被绊住 → 妨碍'},
  'exacerbate': {rt:'acer', af:'ex(加强)+acerb(尖酸)+ate', mn:'使更尖 → 加剧'},
  'reinforce': {rt:'force', af:'re(再)+in(进)+force(力量)', mn:'再注入力量 → 加强'},
  'substantiate': {rt:'stant', af:'sub(下)+stant(站)+iate', mn:'站稳脚跟 → 证实'},
  'corroborate': {rt:'robor', af:'cor(共同)+robor(力量)+ate', mn:'一起给力量 → 证实'},
  'juxtapose': {rt:'pose', af:'juxta(旁)+pose(放)', mn:'放在旁边对比 → 并列'},
  'nuanced': {rt:'nu', af:'nuanc(细微)+ed', mn:'细微的差别 → 微妙的'},
  'overarching': {rt:'arch', af:'over(上)+arch(弓)+ing', mn:'弓在上方覆盖 → 总领的'},
  'dichotomy': {rt:'tomy', af:'di(二)+cho(分)+tomy(切)', mn:'切成两半 → 二分法'},
  'arbitrary': {rt:'arbit', af:'arbit(裁判)+rary', mn:'裁判随意判 → 任意的'},
  'pragmatic': {rt:'prag', af:'prag(做)+matic', mn:'重实用 → 务实的'},
  'tangible': {rt:'tang', af:'tang(触碰)+ible', mn:'摸得到的 → 有形的'},
  'myriad': {rt:'myriad', af:'myriad(一万)', mn:'上万 → 无数的'},
  'burgeoning': {rt:'burg', af:'burge(芽)+oning', mn:'冒芽生长 → 迅速发展的'},
  'scarcity': {rt:'scar', af:'scar(短缺)+city', mn:'scarce(稀少的)名词 → 稀缺'},
  'abundance': {rt:'und', af:'ab(加强)+und(波浪)+ance', mn:'像波浪涌来 → 丰富'},
  'deficit': {rt:'fic', af:'de(缺)+fic(做)+it', mn:'做不够 → 赤字/短缺'},
  'incentivise': {rt:'cent', af:'in(使)+cent(唱)+ivise', mn:'唱着鼓劲 → 激励'},
  'penalise': {rt:'pen', af:'pen(惩罚)+alise', mn:'pen 联想 punish：处罚 → 惩罚'},
  'outweigh': {rt:'weigh', af:'out(超)+weigh(称)', mn:'称起来更重 → 超过'},
  'underpin': {rt:'pin', af:'under(下)+pin(钉)', mn:'在下面钉住 → 支撑'},
  'relinquish': {rt:'linqu', af:'re(回)+linqu(留下)+ish', mn:'留下放弃 → 放弃'},
  'ascertain': {rt:'cert', af:'as(使)+cert(确定)+ain', mn:'使确定 → 查明'},
  'deem': {rt:'deem', af:'deem(认为)', mn:'deem 联想 judge：判断为 → 认为'},
  'availability': {rt:'val', af:'avail(有用)+ability', mn:'可用性'},
  'identification': {rt:'ident', af:'ident(相同)+ification', mn:'认出相同 → 识别'},
  'confirm': {rt:'firm', af:'con(加强)+firm(坚固)', mn:'使坚固 → 确认'},
  'prior': {rt:'prior', af:'prior(在前)', mn:'prior 联想 before：之前的'},
  'twofold': {rt:'fold', af:'two(二)+fold(倍)', mn:'两倍 → 双重的'},
  'annual': {rt:'ann', af:'ann(年)+ual', mn:'ann 联想 year：每年的'},
  'quarterly': {rt:'quart', af:'quart(四)+erly', mn:'四分之一年 → 每季度的'},
  'aggregate': {rt:'greg', af:'ag(向)+greg(群)+ate', mn:'聚成群 → 总计'},
  'interim': {rt:'interim', af:'inter(之间)+im', mn:'在中间的 → 临时的'},
  'subsequent': {rt:'sequ', af:'sub(下)+sequ(跟随)+ent', mn:'跟在后面的 → 随后的'},
  'magnitude': {rt:'magn', af:'magn(大)+itude', mn:'magn 联想 big：大小 → 量级'},
  'capacity': {rt:'cap', af:'cap(容纳)+acity', mn:'能容纳 → 容量/能力'},
  'resilience': {rt:'sil', af:'re(再)+sil(跳)+ience', mn:'跳回来 → 韧性'},
  'volatility': {rt:'vol', af:'vol(飞)+atility', mn:'飞上飞下 → 波动性'},
  'credibility': {rt:'cred', af:'cred(相信)+ibility', mn:'可信度'},
  'accountability': {rt:'count', af:'account(算账)+ability', mn:'能算清 → 问责制'},
  'transparency': {rt:'par', af:'trans(穿过)+par(看见)+ency', mn:'看得穿 → 透明度'},
  'equilibrium': {rt:'libra', af:'equi(等)+libri(秤)+um', mn:'秤平衡 → 均衡'},
  'trajectory': {rt:'ject', af:'tra(穿过)+ject(扔)+ory', mn:'扔出的路线 → 轨迹'},
  'parameter': {rt:'meter', af:'para(旁)+meter(测量)', mn:'在旁边衡量的 → 参数'},
  'criterion': {rt:'crit', af:'crit(判断)+erion', mn:'判断的标准 → 标准'},
  'anomaly': {rt:'nom', af:'a(不)+nom(规则)+aly', mn:'不合规则 → 异常'},
  'nuance': {rt:'nu', af:'nuanc(细微)+e', mn:'细微差别 → 微妙之处'},
  'succinct': {rt:'cinct', af:'suc(下)+cinct(束)', mn:'束紧的 → 简明的'},
  'verbose': {rt:'verb', af:'verb(词)+ose', mn:'词太多 → 冗长的'},
  'deviate': {rt:'vi', af:'de(离开)+vi(路)+ate', mn:'离开道路 → 偏离'},
  'conform': {rt:'form', af:'con(共同)+form(形)', mn:'做成共同形状 → 遵从'},
  'augment': {rt:'aug', af:'aug(增加)+ment', mn:'aug 联想 increase：增大'},
  'delineate': {rt:'line', af:'de(加强)+line(线)+ate', mn:'画线 → 描绘'},
  'assist': {rt:'sist', af:'as(向)+sist(站)', mn:'站在旁边 → 协助'},
  'interrupt': {rt:'rupt', af:'inter(中间)+rupt(断)', mn:'从中打断 → 中断'},
  'require': {rt:'quir', af:'re(再)+quire(求)', mn:'反复要求 → 需要'},
  'appreciate': {rt:'preci', af:'ap+preci(价值)+ate', mn:'看出价值 → 欣赏/感激'},
  'assess': {rt:'sess', af:'as(向)+sess(坐)', mn:'坐下来评 → 评估'},
  'convert': {rt:'vert', af:'con(完全)+vert(转)', mn:'完全转过来 → 转换'},
  'convince': {rt:'vinc', af:'con(加强)+vinc(征服)+e', mn:'征服对方 → 说服'},
  'decline': {rt:'clin', af:'de(向下)+clin(倾斜)+e', mn:'向下倾斜 → 下降/拒绝'},
  'define': {rt:'fin', af:'de(加强)+fin(边界)+e', mn:'画出边界 → 定义'},
  'design': {rt:'sign', af:'de(加强)+sign(标记)', mn:'做出标记 → 设计'},
  'devote': {rt:'vot', af:'de(加强)+vot(誓)+e', mn:'发誓投入 → 奉献'},
  'edit': {rt:'edit', af:'e(出)+dit(给)', mn:'给出成稿 → 编辑'},
  'equip': {rt:'ship', af:'equip(装备)', mn:'equip 联想 ship(船)：给船配东西 → 装备'},
  'establish': {rt:'st', af:'e+stabl(站立)+ish', mn:'使站立 → 建立'},
  'expand': {rt:'pand', af:'ex(出)+pand(展开)', mn:'展开出去 → 扩大'},
  'feature': {rt:'fact', af:'feat(做)+ure', mn:'做出来的特点 → 特征'},
  'focus': {rt:'focus', af:'focus(焦点)', mn:'focus 联想火炉中心 → 焦点'},
  'found': {rt:'found', af:'found(基础)', mn:'found 联想 ground：打地基 → 建立'},
  'function': {rt:'funct', af:'funct(做)+ion', mn:'做的事 → 功能'},
  'generate': {rt:'gener', af:'gener(产生)+ate', mn:'产生 → 生成'},
  'harvest': {rt:'harvest', af:'harvest(收获)', mn:'harvest 联想 autumn(秋)：秋收 → 收获'},
  'inspect': {rt:'spect', af:'in(向内)+spect(看)', mn:'往里看 → 检查'},
  'interact': {rt:'act', af:'inter(互相)+act(做)', mn:'互相做 → 互动'},
  'interpret': {rt:'pret', af:'inter(之间)+pret(解释)', mn:'在两种语言间解释 → 口译/解读'},
  'invent': {rt:'vent', af:'in(使)+vent(来)', mn:'使新东西出现 → 发明'},
  'invest': {rt:'vest', af:'in(进)+vest(衣)', mn:'投进衣袋 → 投资'},
  'locate': {rt:'loc', af:'loc(地方)+ate', mn:'找地方 → 定位'},
  'maintain': {rt:'tain', af:'main(手)+tain(拿)', mn:'用手拿住 → 维持'},
  'monitor': {rt:'mon', af:'mon(提醒)+itor', mn:'提醒查看 → 监测'},
  'candidate': {rt:'cand', af:'cand(白/亮)+idate', mn:'穿白衣参选 → 候选人'},
  'contact': {rt:'tact', af:'con(共同)+tact(触摸)', mn:'互相碰到 → 联系'},
  'contract': {rt:'tract', af:'con(共同)+tract(拉)', mn:'拉到一起 → 合同/收缩'},
  'duration': {rt:'dur', af:'dur(持续)+ation', mn:'dur 联想 during：持续期间 → 持续时间'},
  'fuel': {rt:'fuel', af:'fuel(燃料)', mn:'fuel 联想 fire：烧的东西 → 燃料'},
  'licence': {rt:'lic', af:'lic(允许)+ence', mn:'被允许 → 许可证'},
  'manual': {rt:'manu', af:'manu(手)+al', mn:'用手做的 → 手册/手工的'},
  'option': {rt:'opt', af:'opt(选择)+ion', mn:'opt 联想 choose：可选 → 选项'},
  'priority': {rt:'prior', af:'prior(在前)+ity', mn:'在前面 → 优先'},
  'process': {rt:'cess', af:'pro(向前)+cess(走)', mn:'往前走 → 过程'},
  'quiz': {rt:'quiz', af:'quiz(小测)', mn:'quiz 联想 question：小测验'},
  'schedule': {rt:'sched', af:'schedule(日程)', mn:'schedule 联想 time：安排时间 → 日程'},
  'source': {rt:'surge', af:'source(源泉)', mn:'source 联想 rise(升起)：水冒出的地方 → 来源'},
  'strategy': {rt:'strateg', af:'strateg(将)+y', mn:'将军的计谋 → 策略'},
  'target': {rt:'target', af:'target(靶)', mn:'target 联想 goal：靶子 → 目标'},
  'technique': {rt:'techn', af:'techn(技艺)+ique', mn:'技艺 → 技巧'},
  'albeit': {rt:'al·be·it', af:'al(虽然)+be+it', mn:'虽然它是 → 尽管'},
  'nonetheless': {rt:'less', af:'none(没有)+the+less(少)', mn:'一点也不少 → 尽管如此'},
  'dramatically': {rt:'drama', af:'drama(戏剧)+tically', mn:'戏剧性地 → 急剧地'},
  'exclusively': {rt:'clud', af:'ex(出)+clus(关)+ively', mn:'关在外的 → 独占地'},
  'virtually': {rt:'virt', af:'virt(实质)+ually', mn:'实质上是 → 几乎/虚拟地'},
  'essentially': {rt:'ess', af:'ess(存在)+entially', mn:'本质存在 → 本质上'},
  'inherently': {rt:'her', af:'in(内)+her(粘)+ently', mn:'粘在内部的 → 固有地'},
  'increasingly': {rt:'cre', af:'in(使)+cre(生长)+asingly', mn:'不断生长 → 越来越'},
  'ultimately': {rt:'ultim', af:'ultim(最后)+ately', mn:'到最后 → 最终'},
  'thereby': {rt:'there·by', af:'there(那里)+by(经)', mn:'经由那里 → 因此'},
  'acquisition': {rt:'quir', af:'ac(向)+quis(求)+ition', mn:'求得 → 收购/习得'},
  'allocation': {rt:'loc', af:'al(向)+loc(地方)+ation', mn:'分到各处 → 分配'},
  'alteration': {rt:'alter', af:'alter(其他)+ation', mn:'变成其他 → 改变'},
  'bias': {rt:'bias', af:'bias(偏)', mn:'bias 联想 side：偏向一边 → 偏见'},
  'cohesion': {rt:'her', af:'co(共同)+hes(粘)+ion', mn:'粘在一起 → 凝聚力'},
  'commodity': {rt:'mod', af:'com+mod(尺度)+ity', mn:'可按尺度交易 → 商品'},
  'compensation': {rt:'pens', af:'com(完全)+pens(称/付)+ation', mn:'称重赔付 → 补偿'},
  'competence': {rt:'pet', af:'com(共同)+pet(追求)+ence', mn:'能追求到 → 能力'},
  'consensus': {rt:'sens', af:'con(共同)+sens(感觉)+us', mn:'共同感觉 → 共识'},
  'contradiction': {rt:'dict', af:'contra(反)+dict(说)+ion', mn:'反着说 → 矛盾'},
  'controversy': {rt:'vers', af:'contro(反)+vers(转)+y', mn:'转着争 → 争议'},
  'correlation': {rt:'relat', af:'co(共同)+relation(关系)', mn:'共同关系 → 相关'},
  'deterioration': {rt:'ter', af:'de(向下)+terior(地)+ation', mn:'往下走 → 恶化'},
  'deviation': {rt:'vi', af:'de(离开)+vi(路)+ation', mn:'离开道路 → 偏离'},
  'disruption': {rt:'rupt', af:'dis(分开)+rupt(断)+ion', mn:'断开 → 扰乱'},
  'dominance': {rt:'domin', af:'domin(主人)+ance', mn:'当主人 → 支配'},
  'efficiency': {rt:'fic', af:'ef(出)+fic(做)+iency', mn:'做得快 → 效率'},
  'emergence': {rt:'merg', af:'e(出)+merg(沉)+ence', mn:'浮出来 → 出现'},
  'endorsement': {rt:'dors', af:'en(使)+dors(背)+ement', mn:'背书上签名 → 背书/支持'},
  'enforcement': {rt:'force', af:'en(使)+force(力)+ment', mn:'用力实施 → 执行'},
  'enhancement': {rt:'hanc', af:'en(使)+hanc(高)+ement', mn:'提高 → 增强'},
  'expenditure': {rt:'pend', af:'ex(出)+pend(称/付)+iture', mn:'付出的钱 → 支出'},
  'formulation': {rt:'form', af:'form(形)+ulation', mn:'形成 → 制定'},
  'hierarchy': {rt:'arch', af:'hier(神圣)+archy(统治)', mn:'分层统治 → 等级制度'},
  'ideology': {rt:'ideo·logy', af:'ideo(观念)+logy(学)', mn:'观念之学 → 意识形态'},
  'illusion': {rt:'lus', af:'il(使)+lus(玩)+ion', mn:'耍弄眼睛 → 错觉'},
  'implementation': {rt:'ple', af:'im(使)+ple(满)+mentation', mn:'填满实行 → 实施'},
  'incidence': {rt:'cid', af:'in(上)+cid(落)+ence', mn:'落下来的次数 → 发生率'},
  'inconsistency': {rt:'sist', af:'in(不)+consist(一致)+ency', mn:'不一致 → 矛盾'},
  'indicator': {rt:'dic', af:'in(向)+dic(说)+ator', mn:'指着说的东西 → 指标'},
  'inference': {rt:'fer', af:'in(向内)+fer(带)+ence', mn:'从内推出 → 推断'},
  'insight': {rt:'sight', af:'in(内)+sight(看)', mn:'看进内部 → 洞察'},
  'integration': {rt:'tegr', af:'in(使)+tegr(完整)+ation', mn:'使完整 → 整合'},
  'integrity': {rt:'tegr', af:'in(不)+tegr(触碰)+ity', mn:'不被触碰 → 正直/完整'},
  'intensity': {rt:'tens', af:'in(加强)+tens(伸展)+ity', mn:'伸展到极限 → 强度'},
  'intervention': {rt:'vent', af:'inter(之间)+vent(来)+ion', mn:'插进来 → 干预'},
  'justification': {rt:'just', af:'just(公正)+ification', mn:'证明公正 → 理由'},
  'legitimacy': {rt:'leg', af:'leg(法律)+itimacy', mn:'合法的 → 合法性'},
  'manifestation': {rt:'man', af:'mani(手)+fest(打)+ation', mn:'用手指出 → 表现'},
  'manipulation': {rt:'manu', af:'manu(手)+pul(满)+ation', mn:'用手摆弄 → 操纵'},
  'mechanism': {rt:'mechan', af:'mechan(机器)+ism', mn:'机器的运作 → 机制'},
  'misconception': {rt:'cept', af:'mis(错)+conception(概念)', mn:'错误概念 → 误解'},
  'modification': {rt:'mod', af:'mod(尺度)+ification', mn:'改尺度 → 修改'},
  'obligation': {rt:'lig', af:'ob(加强)+lig(绑)+ation', mn:'被绑住 → 义务'},
  'obstacle': {rt:'sta', af:'ob(对)+stacle(站)', mn:'挡在前面站着 → 障碍'},
  'optimisation': {rt:'opt', af:'opt(最好)+imisation', mn:'做到最好 → 优化'},
  'participation': {rt:'cip', af:'part(部分)+cip(取)+ation', mn:'取一部分 → 参与'},
  'perception': {rt:'cept', af:'per(通过)+cept(拿)+ion', mn:'通过感官拿到 → 感知'},
  'persistence': {rt:'sist', af:'per(一直)+sist(站)+ence', mn:'一直站着 → 坚持'},
  'probability': {rt:'prob', af:'prob(证明)+ability', mn:'能被证明的 → 概率'},
  'proficiency': {rt:'fic', af:'pro(向前)+fic(做)+iency', mn:'做得上前 → 熟练'},
  'progression': {rt:'gress', af:'pro(向前)+gress(走)+ion', mn:'向前走 → 进展'},
  'proliferation': {rt:'lifer', af:'pro+life(生命)+ration', mn:'繁殖扩散 → 激增'},
  'prominence': {rt:'min', af:'pro(向前)+min(突出)+ence', mn:'突出来 → 突出/显赫'},
  'rationale': {rt:'ratio', af:'ration(理性)+ale', mn:'理性依据 → 理由'},
  'recession': {rt:'cess', af:'re(回)+cess(走)+ion', mn:'往回走 → 衰退'},
  'recognition': {rt:'cogn', af:'re(再)+cogn(知道)+ition', mn:'再知道 → 认出/承认'},
  'reconciliation': {rt:'cili', af:'re(再)+concil(和解)+iation', mn:'再次和解 → 调和'},
  'relevance': {rt:'lev', af:'re(再)+lev(举起)+ance', mn:'再举起来 → 相关性'},
  'reliability': {rt:'li', af:'re(再)+li(绑)+ability', mn:'绑得牢 → 可靠性'},
  'reputation': {rt:'put', af:'re(再)+put(想)+ation', mn:'别人怎么想 → 声誉'},
  'resistance': {rt:'sist', af:'re(反)+sist(站)+ance', mn:'站着反抗 → 抵抗'},
  'resolution': {rt:'solv', af:'re(再)+solut(解开)+ion', mn:'解开 → 解决/决心'},
  'retention': {rt:'ten', af:'re(保持)+tent(拿)+ion', mn:'拿住 → 保留'},
  'revenue': {rt:'ven', af:'re(回)+ven(来)+ue', mn:'收回来的钱 → 收入'},
  'scrutiny': {rt:'scrut', af:'scrut(检查)+iny', mn:'scrutin 联想 search：细查 → 审视'},
  'sensitivity': {rt:'sens', af:'sens(感觉)+itivity', mn:'感觉灵敏 → 敏感性'},
  'significance': {rt:'sign', af:'sign(标记)+ificance', mn:'有标记 → 重要性'},
  'simulation': {rt:'simul', af:'simul(相似)+ation', mn:'模拟相似 → 仿真'},
  'stability': {rt:'st', af:'st(站)+ability', mn:'站得住 → 稳定'},
  'stagnation': {rt:'stagn', af:'stagn(停滞)+ation', mn:'水不流动 → 停滞'},
  'stimulus': {rt:'stimul', af:'stimul(刺激)+us', mn:'刺激物 → 刺激'},
  'sustainability': {rt:'tain', af:'sus(向上)+tain(保持)+ability', mn:'能持续保持 → 可持续性'},
  'synthesis': {rt:'thes', af:'syn(共同)+thes(放)+is', mn:'放在一起 → 综合'},
  'tendency': {rt:'tend', af:'tend(伸向)+ency', mn:'伸向某方 → 倾向'},
  'threshold': {rt:'thresh', af:'thresh(门槛)+old', mn:'门槛 → 阈值'},
  'tolerance': {rt:'toler', af:'toler(容忍)+ance', mn:'容忍 → 耐受'},
  'transition': {rt:'it', af:'trans(跨越)+it(走)+ion', mn:'跨过去 → 过渡'},
  'validity': {rt:'val', af:'val(强壮)+idity', mn:'站得强 → 有效性'},
  'viability': {rt:'vi', af:'vi(路)+ability', mn:'有路可走 → 可行性'},
  'vulnerability': {rt:'vulner', af:'vulner(伤)+ability', mn:'易受伤 → 脆弱性'},
  'allocate': {rt:'loc', af:'al(向)+loc(地方)+ate', mn:'分到地方 → 分配'},
  'anticipate': {rt:'cip', af:'anti(前)+cip(取)+ate', mn:'提前取 → 预期'},
  'articulate': {rt:'articul', af:'articul(关节)+ate', mn:'关节般清晰 → 清晰表达'},
  'categorise': {rt:'categ', af:'categor(种类)+ise', mn:'分种类 → 归类'},
  'collaborate': {rt:'labor', af:'col(共同)+labor(劳动)+ate', mn:'一起劳动 → 合作'},
  'commence': {rt:'menc', af:'com(开始)+menc(开始)', mn:'开始 → 着手'},
  'compensate': {rt:'pens', af:'com(完全)+pens(称/付)+ate', mn:'称重付清 → 补偿'},
  'compile': {rt:'pil', af:'com(共同)+pile(堆)', mn:'堆在一起 → 汇编'},
  'comprehend': {rt:'prehend', af:'com(完全)+prehend(抓)', mn:'全部抓住 → 理解'},
  'compromise': {rt:'promis', af:'com(共同)+promise(承诺)', mn:'双方承诺 → 妥协'},
  'confront': {rt:'front', af:'con(共同)+front(面)', mn:'面对面 → 面对'},
  'consolidate': {rt:'solid', af:'con(加强)+solid(固)+ate', mn:'使坚固 → 巩固'},
  'constrain': {rt:'strain', af:'con(加强)+strain(拉紧)', mn:'拉紧 → 限制'},
  'contradict': {rt:'dict', af:'contra(反)+dict(说)', mn:'反着说 → 反驳'},
  'correlate': {rt:'relat', af:'co(共同)+relate(联系)', mn:'相互联系 → 相关'},
  'cultivate': {rt:'cult', af:'cult(耕种)+ivate', mn:'耕种 → 培养'},
  'curtail': {rt:'tail', af:'cur(短)+tail(剪)', mn:'剪短 → 削减'},
  'deduce': {rt:'duc', af:'de(向下)+duce(引导)', mn:'往下引 → 推断'},
  'denote': {rt:'not', af:'de(加强)+note(标记)', mn:'作标记 → 表示'},
  'derive': {rt:'riv', af:'de(从)+rive(河流)', mn:'从河流来 → 源于'},
  'designate': {rt:'sign', af:'de(加强)+sign(标记)+ate', mn:'作标记 → 指定'},
  'detect': {rt:'tect', af:'de(去除)+tect(盖)', mn:'揭开盖子 → 发现'},
  'deter': {rt:'ter', af:'de(加强)+ter(吓)', mn:'吓住 → 阻止'},
  'devise': {rt:'vis', af:'de(加强)+vise(看)', mn:'看清楚设计 → 设计/想出'},
  'differentiate': {rt:'fer', af:'dif(分开)+fer(带)+entiate', mn:'带着分开 → 区分'},
  'discern': {rt:'cern', af:'dis(分开)+cern(筛)', mn:'筛出来 → 辨别'},
  'disclose': {rt:'close', af:'dis(打开)+close(关)', mn:'打开关着的 → 披露'},
  'discriminate': {rt:'crimin', af:'dis(分开)+crimin(判定)+ate', mn:'分开判定 → 歧视/区分'},
  'dismantle': {rt:'mantle', af:'dis(去掉)+mantle(斗篷)', mn:'拆掉外罩 → 拆除'},
  'distort': {rt:'tort', af:'dis(加强)+tort(扭)', mn:'扭歪 → 扭曲'},
  'diverge': {rt:'verg', af:'di(分开)+verg(转向)', mn:'转向分开 → 分歧'},
  'diversify': {rt:'vers', af:'di(分开)+vers(转)+ify', mn:'转向多种 → 多样化'},
  'dominate': {rt:'domin', af:'domin(主人)+ate', mn:'当主人 → 支配'},
  'elaborate': {rt:'labor', af:'e(出)+labor(劳动)+ate', mn:'多劳动 → 精心制作'},
  'elicit': {rt:'lic', af:'e(出)+lic(引诱)+it', mn:'引出来 → 引出'},
  'eliminate': {rt:'limin', af:'e(出)+limin(门槛)+ate', mn:'赶出门槛 → 消除'},
  'embody': {rt:'body', af:'em(使)+body(身体)', mn:'使其有形体 → 体现'},
  'emerge': {rt:'merg', af:'e(出)+merge(沉)', mn:'浮出水面 → 出现'},
  'enact': {rt:'act', af:'en(使)+act(做)', mn:'使其生效 → 颁布'},
  'encounter': {rt:'counter', af:'en(使)+counter(相对)', mn:'相对遇上 → 遭遇'},
  'enforce': {rt:'force', af:'en(使)+force(力量)', mn:'用力实施 → 执行'},
  'engender': {rt:'gen', af:'en(使)+gender(产生)', mn:'使产生 → 引起'},
  'entail': {rt:'tail', af:'en+tail(切割)', mn:'牵涉到 → 需要/包含'},
  'evoke': {rt:'voc', af:'e(出)+voke(喊)', mn:'喊出来 → 唤起'},
  'evolve': {rt:'vol', af:'e(出)+volve(滚动)', mn:'滚动展开 → 进化'},
  'exert': {rt:'sert', af:'ex(出)+sert(放)', mn:'放出力量 → 施加'},
  'expedite': {rt:'ped', af:'ex(出)+ped(脚)+ite', mn:'放出脚 → 加快'},
  'exploit': {rt:'plic', af:'ex(出)+ploit(折叠)', mn:'把资源展开 → 利用'},
  'expose': {rt:'pos', af:'ex(出)+pose(放)', mn:'放在外面 → 暴露'},
  'extract': {rt:'tract', af:'ex(出)+tract(拉)', mn:'拉出来 → 提取'},
  'fulfil': {rt:'fil', af:'ful(满)+fil(填)', mn:'填满 → 履行'},
  'generalise': {rt:'gener', af:'gener(种类)+alise', mn:'归为一类 → 概括'},
  'gauge': {rt:'gauge', af:'gauge(量)', mn:'gauge 联想 measure：测量 → 衡量'},
  'hypothesise': {rt:'thes', af:'hypo(下)+thes(放)+ise', mn:'放下假说 → 假设'},
  'illuminate': {rt:'lumin', af:'il(使)+lumin(光)+ate', mn:'光照亮 → 阐明'},
  'impose': {rt:'pos', af:'im(上)+pose(放)', mn:'放在上面强加 → 强加/征收'},
  'incorporate': {rt:'corpor', af:'in(进)+corpor(身体)+ate', mn:'并入身体 → 纳入'},
  'induce': {rt:'duc', af:'in(进)+duce(引导)', mn:'引入 → 诱导'},
  'inhibit': {rt:'hibit', af:'in(内)+hibit(拿)', mn:'拿住不放 → 抑制'},
  'initiate': {rt:'it', af:'init(开始)+iate', mn:'开始 → 发起'},
  'integrate': {rt:'tegr', af:'in(使)+tegr(完整)+ate', mn:'使完整 → 整合'},
  'intervene': {rt:'ven', af:'inter(之间)+ven(来)+e', mn:'插进来 → 干预'},
  'isolate': {rt:'isol', af:'island(岛)+ate', mn:'变成孤岛 → 隔离'},
  'minimise': {rt:'min', af:'min(小)+imise', mn:'变小 → 最小化'},
  'modify': {rt:'mod', af:'mod(尺度)+ify', mn:'改尺度 → 修改'},
  'motivate': {rt:'mot', af:'mot(动)+ivate', mn:'推动 → 激励'},
  'nurture': {rt:'nurt', af:'nurt(滋养)+ure', mn:'滋养 → 培育'},
  'offset': {rt:'set', af:'off(离)+set(放)', mn:'放在旁边抵消 → 抵消'},
  'omit': {rt:'mit', af:'o(出)+mit(送)', mn:'送走 → 省略'},
  'perceive': {rt:'ceiv', af:'per(通过)+ceive(拿)', mn:'通过感官拿到 → 感知'},
  'persist': {rt:'sist', af:'per(一直)+sist(站)', mn:'一直站着 → 坚持'},
  'pinpoint': {rt:'point', af:'pin(针)+point(点)', mn:'针尖定位 → 精确定位'},
  'precede': {rt:'cede', af:'pre(前)+cede(走)', mn:'走在前 → 先于'},
  'cinema': {rt:'kin', af:'cine(动)+ma', mn:'放映动影 → 电影院'},
  'community': {rt:'mun', af:'com(共同)+mun(服务)+ity', mn:'共同服务 → 社区'},
  'conference': {rt:'fer', af:'con(共同)+fer(带)+ence', mn:'带到一起开会 → 会议'},
  'diary': {rt:'di', af:'di(日)+ary', mn:'每天记 → 日记'},
  'drain': {rt:'drain', af:'drain(排干)', mn:'drain 联想 dry(干)：排干水 → 排水'},
  'engine': {rt:'gen', af:'en(使)+gine(产生)', mn:'产生动力的机器 → 发动机'},
  'expert': {rt:'pert', af:'ex(出)+pert(尝试)', mn:'试出来的人 → 专家'},
  'grade': {rt:'grad', af:'grad(步)+e', mn:'一步步的等级 → 年级/评分'},
  'hedge': {rt:'hedge', af:'hedge(树篱)', mn:'树篱挡风险 → 对冲'},
  'institute': {rt:'st', af:'in(使)+stitut(站)+e', mn:'使站立 → 建立/研究所'},
  'journal': {rt:'journ', af:'journ(日)+al', mn:'每天记 → 期刊/日记'},
  'mall': {rt:'mall', af:'mall(商场)', mn:'mall 联想 walk：走路购物的地方 → 商场'},
  'molecule': {rt:'mole', af:'mole(团)+cule', mn:'小微团 → 分子'},
  'plug': {rt:'plug', af:'plug(插头)', mn:'plug 联想 hole：堵孔的东西 → 插头'},
};
module.exports = { BATCH };
