'use strict';
/* P3 词根词缀批次 4（chunk4，291 学术词） */
const BATCH = {
  'panel': {rt:'panel', af:'panel(板/讨论组)', mn:'panel 联想 board：专家座谈 → 小组'},
  'submit': {rt:'mit', af:'sub(下)+mit(送)', mn:'送上去 → 提交'},
  'comment': {rt:'ment', af:'com(加强)+ment(心智)', mn:'说出想法 → 评论'},
  'slot': {rt:'slot', af:'slot(槽)', mn:'slot 联想 gap：时间空档 → 时段'},
  'quotation': {rt:'quot', af:'quot(引述)+ation', mn:'引用的话 → 引文/报价'},
  'provoke': {rt:'vok', af:'pro(向前)+voke(喊)', mn:'喊出来 → 激起'},
  'owing to': {rt:'ow', af:'owe(欠)+ing+to', mn:'欠着因为 → 由于'},
  'repercussion': {rt:'cuss', af:'re(回)+percuss(打)+ion', mn:'打回来的波 → 反响/后果'},
  'by-product': {rt:'product', af:'by(旁)+product(产品)', mn:'副产品'},
  'ensue': {rt:'sue', af:'en(使)+sue(跟随)', mn:'随之而来 → 接着发生'},
  'invariably': {rt:'vari', af:'in(不)+vari(变)+ably', mn:'总不变地 → 总是'},
  'classic': {rt:'class', af:'class(等级)+ic', mn:'一等经典的 → 经典的'},
  'representative': {rt:'sent', af:'re(再)+present(呈现)+ative', mn:'代表呈现 → 代表'},
  'case in point': {rt:'case·point', af:'case(例子)+in+point(点)', mn:'正点例子 → 典型例子'},
  'comparable': {rt:'par', af:'com(共同)+par(相等)+able', mn:'可比的 → 类似的'},
  'resemble': {rt:'sembl', af:'re(再)+sembl(相似)+e', mn:'很像 → 相似'},
  'divergent': {rt:'verg', af:'di(分开)+verg(转)+ent', mn:'转开分歧 → 分叉的'},
  'proportional': {rt:'port', af:'pro(按)+portion(部分)+al', mn:'按部分 → 成比例的'},
  'inverse': {rt:'vers', af:'in(反)+verse(转)', mn:'反过来 → 相反的'},
  'superior': {rt:'super', af:'super(上)+ior', mn:'更上面的 → 优越的'},
  'exceed': {rt:'ceed', af:'ex(出)+ceed(走)', mn:'走出来 → 超过'},
  'conclusive': {rt:'clud', af:'con(完全)+clus(关闭)+ive', mn:'完全定论 → 决定性的'},
  'definitive': {rt:'fin', af:'de(加强)+fin(边界)+itive', mn:'划死边界的 → 权威的/最终的'},
  'upshot': {rt:'up·shot', af:'up(上)+shot(射)', mn:'射出的结果 → 最终结果'},
  'in the final analysis': {rt:'final·analysis', af:'in+the+final(最终)+analysis(分析)', mn:'最终分析 → 归根结底'},
  'namely': {rt:'name', af:'name(名)+ly', mn:'点名 → 即/也就是'},
  'autonomy': {rt:'nom', af:'auto(自己)+nom(法)+y', mn:'自己立法 → 自治'},
  'comprehension': {rt:'prehend', af:'com(完全)+prehens(抓)+ion', mn:'全部抓住 → 理解'},
  'output': {rt:'put', af:'out(出)+put(放)', mn:'放出来的 → 产出'},
  'levy': {rt:'lev', af:'lev(举/征)+y', mn:'举起来收 → 征税'},
  'treaty': {rt:'treat', af:'treat(处理)+y', mn:'处理国事的协议 → 条约'},
  'subsidy': {rt:'sid', af:'sub(下)+sid(坐)+y', mn:'坐在下面支持 → 补贴'},
  'irrigation': {rt:'rig', af:'ir(进)+rig(浇灌)+ation', mn:'浇灌 → 灌溉'},
  'precipitation': {rt:'cip', af:'pre(前)+cipit(落)+ation', mn:'落下来 → 降水'},
  'constitute': {rt:'st', af:'con(共同)+stitut(站)+e', mn:'站在一起组成 → 构成'},
  'overtake': {rt:'take', af:'over(超过)+take(拿)', mn:'拿过去 → 超越'},
  'seasonal variation': {rt:'season·vari', af:'seasonal(季节)+variation(变化)', mn:'随季节变化 → 季节变化'},
  'stance': {rt:'st', af:'st(站)+ance', mn:'站的姿势 → 立场'},
  'objection': {rt:'ject', af:'ob(反)+ject(扔)+ion', mn:'扔回去 → 反对'},
  'subjective': {rt:'ject', af:'sub(下)+ject(扔)+ive', mn:'主观投射 → 主观的'},
  'objective': {rt:'ject', af:'ob(向)+ject(扔)+ive', mn:'客观对象 → 客观的'},
  'indifference': {rt:'fer', af:'in(不)+difference(区别)', mn:'没区别 → 冷漠/无所谓'},
  'lifestyle': {rt:'life·style', af:'life(生活)+style(方式)', mn:'生活方式'},
  'mortality': {rt:'mort', af:'mort(死)+ality', mn:'死亡 → 死亡率'},
  'transmission': {rt:'miss', af:'trans(跨越)+miss(送)+ion', mn:'跨送 → 传播/传输'},
  'metabolism': {rt:'bol', af:'meta(变)+bol(抛)+ism', mn:'体内物质变换 → 新陈代谢'},
  'vitamin': {rt:'vit', af:'vit(生命)+amin', mn:'维持生命的 → 维生素'},
  'consume': {rt:'sum', af:'con(完全)+sume(拿)', mn:'全拿走 → 消耗'},
  'occupation': {rt:'cup', af:'oc(加强)+cup(拿)+ation', mn:'拿住的事 → 职业/占领'},
  'discrimination': {rt:'crimin', af:'dis(分开)+crimin(判定)+ation', mn:'分开判定 → 歧视'},
  'labour': {rt:'labor', af:'labor(劳动)', mn:'labor 联想 work：劳动/劳动力'},
  'academic': {rt:'academ', af:'academ(学院)+ic', mn:'学院的 → 学术的'},
  'accurate': {rt:'cur', af:'ac(使)+cur(细心)+ate', mn:'细心的 → 准确的'},
  'acid': {rt:'ac', af:'ac(尖)+id', mn:'尖锐刺口 → 酸'},
  'adaptation': {rt:'apt', af:'ad(向)+apt(适应)+ation', mn:'适应 → 改编'},
  'adult': {rt:'adult', af:'adult(成年)', mn:'adult 联想 grow：长大的 → 成人'},
  'agriculture': {rt:'agri·cult', af:'agri(田地)+cult(耕种)+ure', mn:'田地耕种 → 农业'},
  'analysis': {rt:'lys', af:'ana(分开)+lys(解开)+is', mn:'解开分析 → 分析'},
  'approach': {rt:'proach', af:'ap(向)+proach(接近)', mn:'走近 → 方法/接近'},
  'average': {rt:'aver', af:'average(平均)', mn:'average 联想 equal：平均的'},
  'behavior': {rt:'hav', af:'be+hav(拥有)+ior', mn:'拥有的举止 → 行为'},
  'bilingual': {rt:'lingu', af:'bi(双)+lingu(舌/语言)+al', mn:'双语言的'},
  'capitalism': {rt:'capit', af:'capit(头/资本)+alism', mn:'以资本为头 → 资本主义'},
  'cattle': {rt:'cattle', af:'cattle(牛)', mn:'cattle 联想 cow：牛群'},
  'classification': {rt:'class', af:'class(等级)+ification', mn:'分等级 → 分类'},
  'classroom': {rt:'room', af:'class(班级)+room(房间)', mn:'教室'},
  'clay': {rt:'clay', af:'clay(黏土)', mn:'clay 联想 mud：黏土'},
  'code': {rt:'code', af:'code(编码)', mn:'code 联想 secret：密文 → 编码/代码'},
  'colony': {rt:'col', af:'col(耕种)+ony', mn:'开垦定居 → 殖民地'},
  'comets': {rt:'comet', af:'comet(彗星)+s', mn:'comet 联想星尾：彗星'},
  'complex': {rt:'plex', af:'com(共同)+plex(编织)', mn:'编在一起 → 复杂的'},
  'complicated': {rt:'plic', af:'com(共同)+plic(折叠)+ated', mn:'叠在一起 → 复杂的'},
  'considerably': {rt:'sider', af:'con(加强)+sider(星)+ably', mn:'像星星多 → 相当地'},
  'constant': {rt:'st', af:'con(完全)+stant(站)', mn:'一直站着 → 恒定的'},
  'container': {rt:'ten', af:'con(共同)+tain(拿)+er', mn:'拿着东西 → 容器'},
  'correction': {rt:'rect', af:'cor(加强)+rect(直)+ion', mn:'弄直 → 纠正'},
  'credit': {rt:'cred', af:'cred(相信)+it', mn:'相信你 → 信用/学分'},
  'crystal': {rt:'cryst', af:'cryst(冰/结晶)+al', mn:'结晶 → 水晶'},
  'culture': {rt:'cult', af:'cult(耕种)+ure', mn:'耕种培育 → 文化'},
  'detail': {rt:'tail', af:'de(分开)+tail(切)', mn:'切开细看 → 细节'},
  'diameter': {rt:'meter', af:'dia(穿过)+meter(量)', mn:'穿过去量 → 直径'},
  'dictionary': {rt:'dict', af:'dict(说)+ionary', mn:'记录说的话 → 词典'},
  'distortion': {rt:'tort', af:'dis(加强)+tort(扭)+ion', mn:'扭歪 → 扭曲'},
  'economic': {rt:'eco', af:'eco(家)+nom(法)+ic', mn:'理家之法的 → 经济的'},
  'expansion': {rt:'pand', af:'ex(出)+pans(展开)+ion', mn:'展开 → 扩张'},
  'female': {rt:'fem', af:'fem(女人)+ale', mn:'女性的'},
  'finance': {rt:'fin', af:'fin(结束/支付)+ance', mn:'结账的钱 → 金融/财政'},
  'frequency': {rt:'freq', af:'frequ(频繁)+ency', mn:'频率'},
  'gender': {rt:'gen', af:'gen(出生)+der', mn:'出生的性别 → 性别'},
  'gene': {rt:'gen', af:'gen(出生)+e', mn:'决定出生的 → 基因'},
  'graphic': {rt:'graph', af:'graph(画)+ic', mn:'画图的 → 图形的'},
  'history': {rt:'story', af:'hist(知道)+ory', mn:'过去的事 → 历史'},
  'image': {rt:'imag', af:'imag(模仿)+e', mn:'模仿的像 → 图像'},
  'impact': {rt:'pact', af:'im(进)+pact(敲)', mn:'敲进去 → 冲击/影响'},
  'intensive': {rt:'tens', af:'in(加强)+tens(伸展)+ive', mn:'用力伸展 → 密集的'},
  'item': {rt:'item', af:'item(条目)', mn:'item 联想 list：清单中的一项'},
  'jazz': {rt:'jazz', af:'jazz(爵士乐)', mn:'jazz 联想音乐：爵士乐'},
  'leaf': {rt:'leaf', af:'leaf(叶)', mn:'叶子'},
  'liter': {rt:'liter', af:'liter(升)', mn:'liter 联想 liquid：液体计量 → 升'},
  'logic': {rt:'log', af:'log(言/理)+ic', mn:'讲道理 → 逻辑'},
  'mass': {rt:'mass', af:'mass(大块)', mn:'mass 联想 many：大块/质量'},
  'material': {rt:'mater', af:'mater(母/物质)+ial', mn:'物质材料 → 材料'},
  'measurement': {rt:'mens', af:'measure(测量)+ment', mn:'测量'},
  'media': {rt:'medi', af:'medi(中间)+a', mn:'中间的传播 → 媒体'},
  'medical': {rt:'med', af:'med(医治)+ical', mn:'医学的'},
  'microphone': {rt:'micro·phone', af:'micro(小)+phone(声音)', mn:'收小声的 → 麦克风'},
  'migration': {rt:'migr', af:'migr(迁移)+ation', mn:'迁移'},
  'military': {rt:'milit', af:'milit(士兵)+ary', mn:'士兵的 → 军事的'},
  'model': {rt:'mod', af:'mod(尺度)+el', mn:'按尺度做 → 模型'},
  'nest': {rt:'nest', af:'nest(巢)', mn:'鸟巢 → 巢'},
  'note-taking': {rt:'note·take', af:'note(笔记)+taking(记)', mn:'做笔记'},
  'oxygen': {rt:'oxy·gen', af:'oxy(酸)+gen(产生)', mn:'产生酸的气体 → 氧气'},
  'page': {rt:'page', af:'page(页)', mn:'页面'},
  'paper': {rt:'paper', af:'paper(纸)', mn:'纸'},
  'paragraph': {rt:'graph', af:'para(旁)+graph(写)', mn:'旁边写的一段 → 段落'},
  'partner': {rt:'part', af:'part(部分)+ner', mn:'一起的部分 → 伙伴'},
  'physics': {rt:'phys', af:'phys(自然)+ics', mn:'自然之学 → 物理学'},
  'poetry': {rt:'poet', af:'poet(诗人)+ry', mn:'诗'},
  'political': {rt:'pol', af:'pol(城邦)+itical', mn:'城邦事务的 → 政治的'},
  'politics': {rt:'pol', af:'pol(城邦)+itics', mn:'城邦之学 → 政治'},
  'prediction': {rt:'dict', af:'pre(前)+dict(说)+ion', mn:'预先说 → 预测'},
  'primary': {rt:'prim', af:'prim(第一)+ary', mn:'第一的 → 主要的'},
  'project': {rt:'ject', af:'pro(向前)+ject(扔)', mn:'扔出去的计划 → 项目'},
  'puzzle': {rt:'puzzle', af:'puzzle(谜)', mn:'puzzle 联想 ask：难解之问 → 谜题'},
  'recording': {rt:'cord', af:'re(再)+cord(心/记)+ing', mn:'记下来 → 录音'},
  'reproduction': {rt:'duct', af:'re(再)+pro(向前)+duct(引导)+ion', mn:'再生产 → 繁殖/复制'},
  'science': {rt:'sci', af:'sci(知道)+ence', mn:'知道之学 → 科学'},
  'select': {rt:'lect', af:'se(分开)+lect(选)', mn:'挑出来 → 选择'},
  'sex': {rt:'sex', af:'sex(性)', mn:'性别/性'},
  'slavery': {rt:'slav', af:'slav(斯拉夫/奴)+ery', mn:'奴隶制度'},
  'slaves': {rt:'slav', af:'slave(奴隶)+s', mn:'奴隶'},
  'slides': {rt:'slide', af:'slide(滑)+s', mn:'滑片 → 幻灯片'},
  'socialize': {rt:'soci', af:'soci(同伴)+alize', mn:'与同伴交往 → 社交'},
  'solar': {rt:'sol', af:'sol(太阳)+ar', mn:'太阳的'},
  'speech': {rt:'speech', af:'speech(说话)', mn:'speech 联想 speak：说话 → 演讲'},
  'stadium': {rt:'stad', af:'stad(站)+ium', mn:'站着看比赛的地方 → 体育场'},
  'structure': {rt:'struct', af:'struct(建造)+ure', mn:'建造 → 结构'},
  'style': {rt:'styl', af:'styl(风格)+e', mn:'风格'},
  'superiority': {rt:'super', af:'super(上)+ior+ity', mn:'优越性'},
  'tape': {rt:'tape', af:'tape(带子)', mn:'磁带'},
  'team': {rt:'team', af:'team(队)', mn:'队伍'},
  'technical': {rt:'techn', af:'techn(技艺)+ical', mn:'技术的'},
  'telegraph': {rt:'tele·graph', af:'tele(远)+graph(写)', mn:'远处传写的 → 电报'},
  'textbook': {rt:'text·book', af:'text(文)+book(书)', mn:'教科书'},
  'theme': {rt:'them', af:'them(放置)+e', mn:'放进去的主题 → 主题'},
  'topic': {rt:'top', af:'top(地方)+ic', mn:'话题'},
  'transport': {rt:'port', af:'trans(跨越)+port(搬运)', mn:'搬运跨越 → 运输'},
  'uniform': {rt:'uni·form', af:'uni(一)+form(形)', mn:'统一形状 → 制服/统一的'},
  'unit': {rt:'uni', af:'uni(一)+t', mn:'一个 → 单元'},
  'vision': {rt:'vis', af:'vis(看)+ion', mn:'看见 → 愿景/视力'},
  'vocabulary': {rt:'voc', af:'voc(说)+abulary', mn:'说的话汇总 → 词汇'},
  'radical': {rt:'radic', af:'radic(根)+al', mn:'从根上 → 激进的'},
  'access': {rt:'cess', af:'ac(向)+cess(走)', mn:'走过去 → 访问/通道'},
  'challenge': {rt:'challeng', af:'challenge(挑战)', mn:'challenge 联想 change：考验变化 → 挑战'},
  'potential': {rt:'pot', af:'pot(能力)+ential', mn:'有能力的 → 潜在的'},
  'promote': {rt:'mot', af:'pro(向前)+mot(动)+e', mn:'向前推动 → 促进/晋升'},
  'identify': {rt:'ident', af:'ident(相同)+ify', mn:'认出相同 → 识别'},
  'medium': {rt:'medi', af:'medi(中间)+um', mn:'中间的媒介 → 媒介/中等的'},
  'release': {rt:'lease', af:'re(再)+lease(放松)', mn:'放松放走 → 发布/释放'},
  'unique': {rt:'uni', af:'uni(一)+que', mn:'独一无二的'},
  'range': {rt:'range', af:'range(范围)', mn:'range 联想 区间：范围'},
  'concentrate': {rt:'centr', af:'con(共同)+centr(中心)+ate', mn:'聚到中心 → 集中'},
  'survive': {rt:'viv', af:'sur(上)+viv(活)+e', mn:'活下来 → 幸存'},
  'literature': {rt:'liter', af:'liter(文字)+ature', mn:'文字作品 → 文学'},
  'appropriate': {rt:'propri', af:'ap+propri(自己的)+ate', mn:'归自己的 → 合适的'},
  'assume': {rt:'sum', af:'as(向)+sume(拿)', mn:'拿过来当 → 假定'},
  'external': {rt:'extern', af:'extern(外)+al', mn:'外部的'},
  'issue': {rt:'iss', af:'iss(出)+ue', mn:'发出来的 → 问题/发行'},
  'involve': {rt:'volv', af:'in(进)+volve(转)', mn:'卷进去 → 涉及'},
  'conflict': {rt:'flict', af:'con(共同)+flict(打)', mn:'互相打 → 冲突'},
  'affect': {rt:'fect', af:'af(向)+fect(做)', mn:'作用于 → 影响'},
  'relevant': {rt:'lev', af:'re(再)+lev(举)+ant', mn:'再举起来 → 相关的'},
  'initial': {rt:'it', af:'init(开始)+ial', mn:'开始的 → 最初的'},
  'create': {rt:'cre', af:'cre(生长)+ate', mn:'生长出来 → 创造'},
  'register': {rt:'gest', af:'re(再)+gist(带来)', mn:'带来记录 → 注册'},
  'status': {rt:'st', af:'st(站)+atus', mn:'站的位置 → 地位/状态'},
  'authority': {rt:'author', af:'author(作者/权威)+ity', mn:'权威'},
  'conduct': {rt:'duct', af:'con(共同)+duct(引导)', mn:'引导 → 进行/行为'},
  'professional': {rt:'fess', af:'pro(公开)+fess(说)+ional', mn:'公开宣称专业 → 职业的'},
  'insect': {rt:'sect', af:'in(进)+sect(切)', mn:'切成段的身体 → 昆虫'},
  'volume': {rt:'volv', af:'vol(卷)+ume', mn:'卷起来 → 体积/音量/卷'},
  'acquire': {rt:'quir', af:'ac(向)+quire(求)', mn:'求得 → 获得'},
  'adjust': {rt:'just', af:'ad(向)+just(正)', mn:'弄正 → 调整'},
  'absorb': {rt:'sorb', af:'ab(加强)+sorb(吸)', mn:'吸进去 → 吸收'},
  'element': {rt:'lement', af:'element(元素)', mn:'element 联想 basic：基本元素'},
  'observe': {rt:'serv', af:'ob(向)+serve(看)', mn:'看着 → 观察'},
  'vary': {rt:'vari', af:'vari(变化)+y', mn:'变化'},
  'communicate': {rt:'mun', af:'com(共同)+mun(服务)+icate', mn:'共同服务 → 交流'},
  'respond': {rt:'spond', af:'re(回)+spond(承诺)', mn:'回应 → 回答'},
  'aspect': {rt:'spect', af:'a(向)+spect(看)', mn:'看的方向 → 方面'},
  'characteristic': {rt:'char', af:'character(特征)+istic', mn:'特征 → 典型的'},
  'component': {rt:'pon', af:'com(共同)+pon(放)+ent', mn:'放在一起的部分 → 组件'},
  'sufficient': {rt:'fic', af:'suf(下)+fic(做)+ient', mn:'做得够 → 充足的'},
  'aware': {rt:'war', af:'a(向)+ware(注意)', mn:'注意到 → 意识到的'},
  'region': {rt:'reg', af:'reg(统治/区域)+ion', mn:'区域'},
  'stimulate': {rt:'stimul', af:'stimul(刺激)+ate', mn:'刺激'},
  'category': {rt:'categ', af:'categor(种类)+y', mn:'种类'},
  'diverse': {rt:'vers', af:'di(分开)+vers(转)+e', mn:'转向不同 → 多样的'},
  'fin': {rt:'fin', af:'fin(鳍)', mn:'鱼鳍'},
  'legal': {rt:'leg', af:'leg(法律)+al', mn:'法律的'},
  'stable': {rt:'st', af:'st(站)+able', mn:'站得住 → 稳定的'},
  'physical': {rt:'phys', af:'phys(身体/自然)+ical', mn:'身体的/物理的'},
  'symbol': {rt:'sym·bol', af:'sym(共同)+bol(抛)', mn:'共同含义的记号 → 符号'},
  'biology': {rt:'bio·logy', af:'bio(生命)+logy(学)', mn:'生命之学 → 生物学'},
  'goal': {rt:'goal', af:'goal(目标)', mn:'goal 联想 球门：目标'},
  'specific': {rt:'spec', af:'speci(种类)+fic(做)', mn:'做成特定种类 → 具体的'},
  'intelligence': {rt:'lig', af:'intel(之间)+lig(选择)+ence', mn:'会选择判断 → 智力'},
  'section': {rt:'sect', af:'sect(切)+ion', mn:'切开的部分 → 章节'},
  'alter': {rt:'alter', af:'alter(其他)', mn:'变成其他 → 改变'},
  'document': {rt:'doc', af:'doc(教/示)+ument', mn:'证明的文件 → 文档'},
  'concept': {rt:'cept', af:'con(共同)+cept(拿)', mn:'拿住的概念 → 概念'},
  'adequate': {rt:'equ', af:'ad(向)+equ(相等)+ate', mn:'足够的'},
  'consult': {rt:'sult', af:'con(共同)+sult(商量)', mn:'一起商量 → 咨询'},
  'philosophy': {rt:'phil·soph', af:'phil(爱)+soph(智)+y', mn:'爱智慧 → 哲学'},
  'economy': {rt:'eco', af:'eco(家)+nom(法)+y', mn:'理家之法 → 经济'},
  'fund': {rt:'fund', af:'fund(基础/资金)', mn:'基金 → 资金/基础'},
  'primitive': {rt:'prim', af:'prim(第一)+itive', mn:'最早的 → 原始的'},
  'shallow': {rt:'shallow', af:'shallow(浅)', mn:'shallow 联想 浅：浅的'},
  'substitute': {rt:'st', af:'sub(下)+stitute(站)', mn:'站在下面替代 → 代替'},
  'attach': {rt:'tach', af:'at(向)+tach(钉)', mn:'钉上去 → 附加'},
  'commit': {rt:'mit', af:'com(共同)+mit(送)', mn:'送出承诺 → 投入/犯罪'},
  'tradition': {rt:'dit', af:'tra(传)+dit(给)+ion', mn:'传给后代 → 传统'},
  'abandon': {rt:'band', af:'a(离开)+bandon(掌控)', mn:'放手离开 → 放弃'},
  'channel': {rt:'channel', af:'channel(渠道)', mn:'channel 联想 canal：渠道/频道'},
  'commission': {rt:'miss', af:'com(共同)+miss(送)+ion', mn:'委派 → 委员会/佣金'},
  'cycle': {rt:'cycl', af:'cycl(环)+e', mn:'循环'},
  'version': {rt:'vers', af:'vers(转)+ion', mn:'转出的版本 → 版本'},
  'odd': {rt:'odd', af:'odd(奇数/奇怪)', mn:'odd 联想 奇数：奇怪的'},
  'ensure': {rt:'sure', af:'en(使)+sure(确定)', mn:'使确定 → 确保'},
  'secure': {rt:'cur', af:'se(分开)+cur(关心)+e', mn:'无忧 → 安全的'},
  'universe': {rt:'vers', af:'uni(一)+verse(转)', mn:'转成一体的万物 → 宇宙'},
  'conscious': {rt:'sci', af:'con(共同)+sci(知道)+ous', mn:'有意识的'},
  'participate': {rt:'cip', af:'part(部分)+cip(取)+ate', mn:'取一份 → 参与'},
  'accompany': {rt:'pan', af:'ac(向)+company(同伴)', mn:'做同伴 → 陪伴'},
  'aid': {rt:'aid', af:'aid(帮助)', mn:'aid 联想 help：帮助'},
  'calculate': {rt:'calcul', af:'calcul(小石子)+ate', mn:'用小石子算 → 计算'},
  'intense': {rt:'tens', af:'in(加强)+tens(伸展)+e', mn:'用力伸展 → 强烈的'},
  'visual': {rt:'vis', af:'vis(看)+ual', mn:'视觉的'},
  'continent': {rt:'tin', af:'con(共同)+tin(保持)+ent', mn:'保持一片的陆地 → 大陆'},
  'error': {rt:'err', af:'err(走偏)+or', mn:'走偏 → 错误'},
  'evolution': {rt:'volv', af:'e(出)+volut(转)+ion', mn:'转出来 → 进化'},
  'generation': {rt:'gener', af:'gener(产生)+ation', mn:'一代人/产生'},
  'vertical': {rt:'vert', af:'vert(转)+ical', mn:'垂直转向 → 垂直的'},
  'ancestor': {rt:'cess', af:'an(前)+cest(走)+or', mn:'走在前面的人 → 祖先'},
  'minimum': {rt:'min', af:'min(小)+imum', mn:'最小的 → 最小值'},
  'area': {rt:'area', af:'area(区域)', mn:'区域/面积'},
  'chemical': {rt:'chem', af:'chem(化学)+ical', mn:'化学的'},
  'clever': {rt:'clever', af:'clever(聪明)', mn:'聪明的'},
  'institution': {rt:'st', af:'in(使)+stitut(站)+ion', mn:'建立的机构 → 制度/机构'},
  'parallel': {rt:'allel', af:'para(旁)+allel(彼此)', mn:'彼此在旁边 → 平行的'},
  'export': {rt:'port', af:'ex(出)+port(搬运)', mn:'搬出去 → 出口'},
  'internal': {rt:'intern', af:'intern(内)+al', mn:'内部的'},
  'psychology': {rt:'psycho·logy', af:'psycho(心灵)+logy(学)', mn:'心灵之学 → 心理学'},
  'revolution': {rt:'volv', af:'re(再)+volut(转)+ion', mn:'翻过来转 → 革命'},
  'compose': {rt:'pos', af:'com(共同)+pose(放)', mn:'放在一起 → 组成/作曲'},
  'construct': {rt:'struct', af:'con(共同)+struct(建造)', mn:'建造 → 构建'},
  'core': {rt:'core', af:'core(心)', mn:'core 联想 heart：核心'},
  'drama': {rt:'drama', af:'drama(戏剧)', mn:'戏剧'},
  'layer': {rt:'lay', af:'lay(放)+er', mn:'放的一层 → 层'},
  'react': {rt:'act', af:'re(反)+act(做)', mn:'反做 → 反应'},
  'remove': {rt:'mov', af:'re(再)+move(移动)', mn:'移走 → 移除'},
  'author': {rt:'author', af:'author(作者)', mn:'author 联想 authority：作者'},
  'site': {rt:'site', af:'sit(坐)+e', mn:'坐落在 → 地点/网站'},
  'chart': {rt:'chart', af:'chart(图表)', mn:'chart 联想 map：图表'},
  'conclude': {rt:'clud', af:'con(完全)+clude(关闭)', mn:'关起来总结 → 得出结论'},
  'architecture': {rt:'arch·tect', af:'arch(主)+tect(建造)+ure', mn:'建造之学 → 建筑学'},
  'click': {rt:'click', af:'click(咔哒)', mn:'点击'},
  'margin': {rt:'margin', af:'margin(边缘)', mn:'边缘/利润'},
  'bond': {rt:'bond', af:'bond(绑)', mn:'bond 联想 bind：债券/纽带'},
  'ecology': {rt:'eco·logy', af:'eco(家园)+logy(学)', mn:'家园之学 → 生态学'},
  'fossil': {rt:'foss', af:'foss(挖)+il', mn:'挖出来的 → 化石'},
  'link': {rt:'link', af:'link(连接)', mn:'链接'},
  'theory': {rt:'theor', af:'theor(看)+y', mn:'观察出的 → 理论'},
  'bound': {rt:'bound', af:'bound(边界)', mn:'bound 联想 boundary：界限'},
  'client': {rt:'clin', af:'clin(依靠)+ent', mn:'依靠你的人 → 客户'},
  'overseas': {rt:'sea', af:'over(越)+seas(海)', mn:'越海 → 海外的'},
  'passive': {rt:'pass', af:'pass(忍受)+ive', mn:'忍受的 → 被动的'},
  'report': {rt:'port', af:'re(回)+port(带)', mn:'带回来 → 报告'},
  'rigid': {rt:'rig', af:'rig(硬)+id', mn:'硬的 → 僵硬的'},
  'dimension': {rt:'mens', af:'di(分开)+mens(量)+ion', mn:'分开量的 → 维度'},
  'file': {rt:'file', af:'file(文件)', mn:'文件'},
  'foundation': {rt:'found', af:'found(基础)+ation', mn:'地基 → 基础/基金会'},
  'immune': {rt:'mun', af:'im(不)+mune(服务)', mn:'不受役使 → 免疫的'},
  'sustain': {rt:'tain', af:'sus(向上)+tain(保持)', mn:'一直保持 → 维持'},
  'assign': {rt:'sign', af:'as(向)+sign(标记)', mn:'指定 → 分配'},
  'intellectual': {rt:'lect', af:'intel(之间)+lect(选)+ual', mn:'会辨别的 → 智力的'},
  'clue': {rt:'clue', af:'clue(线索)', mn:'clue 联想 key：线索'},
  'normal': {rt:'norm', af:'norm(标准)+al', mn:'标准的 → 正常的'},
  'reproduce': {rt:'duct', af:'re(再)+pro(前)+duce(引导)', mn:'再生产 → 复制/繁殖'},
  'transmit': {rt:'mit', af:'trans(跨越)+mit(送)', mn:'跨送 → 传送'},
  'capable': {rt:'cap', af:'cap(容纳)+able', mn:'能容纳 → 有能力的'},
};
module.exports = { BATCH };
