'use strict';
/* P4 近义词辨析 note（~150 簇）：{ word: { note: 辨析说明, with: 近义词 } }
   单词详情弹窗展示「🔀 近义词辨析」区；build 期注入 w.note */
const SYNNOTE = {
  'important': {note:'辨析：important 泛指重要；crucial 至关重要（决定成败）；vital 生死攸关；essential 必不可少', with:'crucial, vital, essential, significant'},
  'big': {note:'辨析：big 泛指大；large 侧重面积/数量；huge 巨大；enormous 庞大；massive 大规模', with:'large, huge, enormous, massive'},
  'good': {note:'辨析：good 泛指好；excellent 极好；outstanding 杰出；superior 优越', with:'excellent, outstanding, superior'},
  'bad': {note:'辨析：bad 泛指差；poor 质量差；harmful 有害；detrimental 有损', with:'poor, harmful, detrimental'},
  'happy': {note:'辨析：happy 高兴；pleased 满意；delighted 欣喜；content 满足', with:'pleased, delighted, content'},
  'sad': {note:'辨析：sad 悲伤；upset 难过；depressed 沮丧；gloomy 阴郁', with:'upset, depressed, gloomy'},
  'angry': {note:'辨析：angry 生气；annoyed 恼火；furious 暴怒；irritated 烦躁', with:'annoyed, furious, irritated'},
  'afraid': {note:'辨析：afraid 害怕；scared 惊恐；frightened 受惊；terrified 极度恐惧', with:'scared, frightened, terrified'},
  'surprised': {note:'辨析：surprised 惊讶；astonished 震惊；amazed 惊叹；shocked 惊骇', with:'astonished, amazed, shocked'},
  'tired': {note:'辨析：tired 疲劳；exhausted 精疲力竭；worn out 累垮；drained 筋疲力尽', with:'exhausted, worn out, drained'},
  'beautiful': {note:'辨析：beautiful 美；pretty 漂亮（小巧）；gorgeous 华丽；stunning 惊艳', with:'pretty, gorgeous, stunning'},
  'difficult': {note:'辨析：difficult 难；hard 费力；challenging 有挑战性；tough 艰难', with:'hard, challenging, tough'},
  'easy': {note:'辨析：easy 容易；simple 简单；effortless 不费力；straightforward 直截了当', with:'simple, effortless, straightforward'},
  'fast': {note:'辨析：fast 快；quick 迅速；rapid 快速（变化）；swift 敏捷', with:'quick, rapid, swift'},
  'slow': {note:'辨析：slow 慢；gradual 逐渐；leisurely 悠闲；sluggish 迟缓', with:'gradual, leisurely, sluggish'},
  'smart': {note:'辨析：smart 聪明；intelligent 智力高；clever 机灵；brilliant 出色', with:'intelligent, clever, brilliant'},
  'rich': {note:'辨析：rich 富有；wealthy 富裕；affluent 殷实；prosperous 繁荣', with:'wealthy, affluent, prosperous'},
  'poor': {note:'辨析：poor 贫穷；impoverished 贫困；deprived 匮乏；destitute 赤贫', with:'impoverished, deprived, destitute'},
  'cheap': {note:'辨析：cheap 便宜（含贬义）；inexpensive 便宜（中性）；affordable 负担得起', with:'inexpensive, affordable'},
  'expensive': {note:'辨析：expensive 贵；costly 高昂；pricey 偏贵；luxurious 奢华', with:'costly, pricey, luxurious'},
  'new': {note:'辨析：new 新；recent 最近；modern 现代；novel 新颖', with:'recent, modern, novel'},
  'old': {note:'辨析：old 老；ancient 古老；aged 年迈；outdated 过时', with:'ancient, aged, outdated'},
  'young': {note:'辨析：young 年轻；youthful 有朝气；adolescent 青春期；juvenile 未成年', with:'youthful, adolescent, juvenile'},
  'small': {note:'辨析：small 小；little 微小；tiny 极小；petite 娇小', with:'little, tiny, petite'},
  'clean': {note:'辨析：clean 干净；tidy 整洁；neat 利落；spotless 一尘不染', with:'tidy, neat, spotless'},
  'dirty': {note:'辨析：dirty 脏；messy 凌乱；filthy 污秽；polluted 污染', with:'messy, filthy, polluted'},
  'quiet': {note:'辨析：quiet 安静；silent 沉默；peaceful 宁静；calm 平静', with:'silent, peaceful, calm'},
  'loud': {note:'辨析：loud 大声；noisy 吵闹；deafening 震耳欲聋；boisterous 喧闹', with:'noisy, deafening, boisterous'},
  'safe': {note:'辨析：safe 安全；secure 稳妥；protected 受保护；harmless 无害', with:'secure, protected, harmless'},
  'dangerous': {note:'辨析：dangerous 危险；risky 有风险；hazardous 有害风险；perilous 危急', with:'risky, hazardous, perilous'},
  'healthy': {note:'辨析：healthy 健康；fit 健壮；well 身体好；nutritious 有营养', with:'fit, well, nutritious'},
  'ill': {note:'辨析：ill 生病；sick 不适；unwell 不舒服；diseased 患病的', with:'sick, unwell, diseased'},
  'increase': {note:'辨析：increase 增加；rise 上升；grow 增长；expand 扩大', with:'rise, grow, expand'},
  'decrease': {note:'辨析：decrease 减少；decline 下降；reduce 降低；diminish 缩减', with:'decline, reduce, diminish'},
  'buy': {note:'辨析：buy 买；purchase 购买（正式）；acquire 获得；procure 采购', with:'purchase, acquire, procure'},
  'sell': {note:'辨析：sell 卖；market 推销；retail 零售；auction 拍卖', with:'market, retail, auction'},
  'get': {note:'辨析：get 得到；obtain 获得；acquire 习得；secure 拿到', with:'obtain, acquire, secure'},
  'give': {note:'辨析：give 给；provide 提供；supply 供应；offer 主动给予', with:'provide, supply, offer'},
  'show': {note:'辨析：show 展示；demonstrate 证明展示；display 陈列；exhibit 展出', with:'demonstrate, display, exhibit'},
  'help': {note:'辨析：help 帮助；assist 协助；support 支持；aid 援助', with:'assist, support, aid'},
  'make': {note:'辨析：make 做；create 创造；produce 生产；construct 建造', with:'create, produce, construct'},
  'use': {note:'辨析：use 使用；utilise 利用；employ 运用；apply 应用', with:'utilise, employ, apply'},
  'look': {note:'辨析：look 看；watch 注视；observe 观察；gaze 凝视', with:'watch, observe, gaze'},
  'see': {note:'辨析：see 看见；notice 注意到；spot 发现；perceive 感知', with:'notice, spot, perceive'},
  'say': {note:'辨析：say 说；tell 告诉；state 陈述；claim 声称', with:'tell, state, claim'},
  'speak': {note:'辨析：speak 说话；talk 交谈；chat 闲聊；address 讲话', with:'talk, chat, address'},
  'walk': {note:'辨析：walk 走；stroll 散步；wander 闲逛；march 行军', with:'stroll, wander, march'},
  'run': {note:'辨析：run 跑；jog 慢跑；sprint 冲刺；dash 飞奔', with:'jog, sprint, dash'},
  'think': {note:'辨析：think 想；consider 考虑；ponder 沉思；reflect 反思', with:'consider, ponder, reflect'},
  'know': {note:'辨析：know 知道；understand 理解；realise 意识到；recognise 认出', with:'understand, realise, recognise'},
  'learn': {note:'辨析：learn 学；study 研习；master 掌握；acquire 习得', with:'study, master, acquire'},
  'teach': {note:'辨析：teach 教；instruct 指导；educate 教育；train 培训', with:'instruct, educate, train'},
  'remember': {note:'辨析：remember 记得；recall 回想；recollect 追忆；retain 记住', with:'recall, recollect, retain'},
  'forget': {note:'辨析：forget 忘记；overlook 忽略；neglect 疏忽；omit 遗漏', with:'overlook, neglect, omit'},
  'start': {note:'辨析：start 开始；begin 着手；commence 开始（正式）；initiate 发起', with:'begin, commence, initiate'},
  'finish': {note:'辨析：finish 完成；complete 完成（彻底）；conclude 结束；end 终止', with:'complete, conclude, end'},
  'stop': {note:'辨析：stop 停止；cease 终止；halt 停顿；quit 放弃', with:'cease, halt, quit'},
  'continue': {note:'辨析：continue 继续；proceed 进行；persist 坚持；resume 恢复', with:'proceed, persist, resume'},
  'try': {note:'辨析：try 尝试；attempt 企图；strive 努力；endeavour 尽力', with:'attempt, strive, endeavour'},
  'want': {note:'辨析：want 想要；desire 渴望；wish 希望；need 需要', with:'desire, wish, need'},
  'like': {note:'辨析：like 喜欢；enjoy 享受；appreciate 欣赏；fancy 喜爱', with:'enjoy, appreciate, fancy'},
  'love': {note:'辨析：love 爱；adore 热爱；cherish 珍爱；be fond of 喜欢', with:'adore, cherish, be fond of'},
  'hate': {note:'辨析：hate 讨厌；dislike 不喜欢；detest 厌恶；abhor 憎恶', with:'dislike, detest, abhor'},
  'ask': {note:'辨析：ask 问；inquire 询问；request 请求；demand 要求', with:'inquire, request, demand'},
  'answer': {note:'辨析：answer 回答；reply 回复；respond 回应；react 反应', with:'reply, respond, react'},
  'talk about': {note:'辨析：talk about 谈论；discuss 讨论；debate 辩论；mention 提及', with:'discuss, debate, mention'},
  'agree': {note:'辨析：agree 同意；consent 同意（许可）；approve 赞成；concur 一致', with:'consent, approve, concur'},
  'disagree': {note:'辨析：disagree 不同意；object 反对；oppose 反对（行为）；differ 有分歧', with:'object, oppose, differ'},
  'explain': {note:'辨析：explain 解释；clarify 澄清；illustrate 图解说明；elaborate 详细阐述', with:'clarify, illustrate, elaborate'},
  'describe': {note:'辨析：describe 描述；depict 描绘；portray 刻画；outline 概述', with:'depict, portray, outline'},
  'choose': {note:'辨析：choose 选择；select 挑选；opt for 选定；pick 挑出', with:'select, opt for, pick'},
  'decide': {note:'辨析：decide 决定；determine 决心；resolve 下决心；settle 敲定', with:'determine, resolve, settle'},
  'plan': {note:'辨析：plan 计划；arrange 安排；prepare 准备；organise 组织', with:'arrange, prepare, organise'},
  'build': {note:'辨析：build 建造；construct 构建；establish 建立；set up 设立', with:'construct, establish, set up'},
  'fix': {note:'辨析：fix 修理；repair 维修；restore 恢复；mend 修补', with:'repair, restore, mend'},
  'change': {note:'辨析：change 改变；alter 变更；modify 修改；transform 转变', with:'alter, modify, transform'},
  'improve': {note:'辨析：improve 改进；enhance 增强；boost 提升；upgrade 升级', with:'enhance, boost, upgrade'},
  'solve': {note:'辨析：solve 解决；resolve 化解；settle 处理；handle 应对', with:'resolve, settle, handle'},
  'reduce': {note:'辨析：reduce 减少；lower 降低；cut 削减；minimise 最小化', with:'lower, cut, minimise'},
  'raise': {note:'辨析：raise 提高；lift 举起；boost 提升；elevate 抬高', with:'lift, boost, elevate'},
  'move': {note:'辨析：move 移动；shift 转移；transfer 迁移；relocate 搬迁', with:'shift, transfer, relocate'},
  'put': {note:'辨析：put 放；place 放置；position 定位；arrange 摆放', with:'place, position, arrange'},
  'take': {note:'辨析：take 拿；grab 抓取；seize 抓住；grasp 握住', with:'grab, seize, grasp'},
  'carry': {note:'辨析：carry 携带；transport 运输；convey 传达；haul 搬运', with:'transport, convey, haul'},
  'hold': {note:'辨析：hold 握住；grip 紧握；grasp 抓住；clutch 攥紧', with:'grip, grasp, clutch'},
  'keep': {note:'辨析：keep 保持；maintain 维持；preserve 保存；retain 保留', with:'maintain, preserve, retain'},
  'protect': {note:'辨析：protect 保护；defend 防卫；guard 守护；shield 遮挡', with:'defend, guard, shield'},
  'save': {note:'辨析：save 节省；conserve 节约；preserve 保藏；reserve 预留', with:'conserve, preserve, reserve'},
  'waste': {note:'辨析：waste 浪费；squander 挥霍；misuse 误用；dissipate 挥散', with:'squander, misuse, dissipate'},
  'need': {note:'辨析：need 需要；require 需要（正式）；demand 需求；necessitate 使必需', with:'require, demand, necessitate'},
  'wish': {note:'辨析：wish 希望；hope 期盼；desire 渴望；long for 向往', with:'hope, desire, long for'},
  'expect': {note:'辨析：expect 预期；anticipate 预见；predict 预测；foresee 预见', with:'anticipate, predict, foresee'},
  'believe': {note:'辨析：believe 相信；trust 信任；assume 假定；presume 推断', with:'trust, assume, presume'},
  'seem': {note:'辨析：seem 似乎；appear 显得；look 看起来；resemble 相似', with:'appear, look, resemble'},
  'feel': {note:'辨析：feel 感觉；sense 感知；experience 经历；undergo 承受', with:'sense, experience, undergo'},
  'hear': {note:'辨析：hear 听见；listen 聆听；overhear 无意听到', with:'listen, overhear'},
  'smell': {note:'辨析：smell 闻；scent 嗅；whiff 闻到', with:'scent, whiff'},
  'taste': {note:'辨析：taste 尝；sample 品尝；savour 品味', with:'sample, savour'},
  'touch': {note:'辨析：touch 触碰；feel 触摸；contact 接触；reach 触及', with:'feel, contact, reach'},
  'eat': {note:'辨析：eat 吃；dine 用餐；consume 摄入；devour 狼吞虎咽', with:'dine, consume, devour'},
  'drink': {note:'辨析：drink 喝；sip 小口喝；gulp 大口喝；swallow 吞咽', with:'sip, gulp, swallow'},
  'sleep': {note:'辨析：sleep 睡觉；doze 打盹；nap 小睡；slumber 沉睡', with:'doze, nap, slumber'},
  'work': {note:'辨析：work 工作；labour 劳动；toil 苦干；operate 运转', with:'labour, toil, operate'},
  'rest': {note:'辨析：rest 休息；relax 放松；unwind 舒缓；recharge 恢复精力', with:'relax, unwind, recharge'},
  'play': {note:'辨析：play 玩；entertain 娱乐；amuse 逗乐；have fun 玩得开心', with:'entertain, amuse, have fun'},
  'visit': {note:'辨析：visit 参观；tour 游览；call on 拜访；drop by 顺访', with:'tour, call on, drop by'},
  'travel': {note:'辨析：travel 旅行；journey 旅程；voyage 远航；commute 通勤', with:'journey, voyage, commute'},
  'arrive': {note:'辨析：arrive 到达；reach 抵达；come 来；turn up 到场', with:'reach, come, turn up'},
  'leave': {note:'辨析：leave 离开；depart 出发；withdraw 撤离；exit 退场', with:'depart, withdraw, exit'},
  'enter': {note:'辨析：enter 进入；go in 进去；intrude 闯入；penetrate 渗透', with:'go in, intrude, penetrate'},
  'return': {note:'辨析：return 返回；come back 回来；revert 恢复；regain 恢复（获得）', with:'come back, revert, regain'},
  'wait': {note:'辨析：wait 等待；await 等候（正式）；anticipate 期待', with:'await, anticipate'},
  'meet': {note:'辨析：meet 遇见；encounter 遭遇；run into 偶遇；gather 聚集', with:'encounter, run into, gather'},
  'join': {note:'辨析：join 加入；participate 参与；attend 出席；enroll 注册入学', with:'participate, attend, enroll'},
  'win': {note:'辨析：win 赢；beat 击败；defeat 战胜；triumph 获胜', with:'beat, defeat, triumph'},
  'lose': {note:'辨析：lose 输；fail 失败；miss 错过；defeat 被击败', with:'fail, miss, defeat'},
  'find': {note:'辨析：find 找到；discover 发现；locate 定位；detect 探测', with:'discover, locate, detect'},
  'search': {note:'辨析：search 搜索；seek 寻找；hunt 搜寻；look for 寻找', with:'seek, hunt, look for'},
  'study': {note:'辨析：study 学习；learn 学；review 复习；research 研究', with:'learn, review, research'},
  'read': {note:'辨析：read 阅读；skim 略读；scan 浏览；browse 翻阅', with:'skim, scan, browse'},
  'write': {note:'辨析：write 写；compose 创作；draft 起草；record 记录', with:'compose, draft, record'},
  'listen': {note:'辨析：listen 听；hear 听见；pay attention 留意；tune in 收听', with:'hear, pay attention, tune in'},
  'watch': {note:'辨析：watch 观看；view 观看；observe 观察；monitor 监控', with:'view, observe, monitor'},
  'speak about': {note:'辨析：speak about 谈及；discuss 讨论；mention 提及；address 论述', with:'discuss, mention, address'},
  'worried': {note:'辨析：worried 担心；anxious 焦虑；concerned 关切；nervous 紧张', with:'anxious, concerned, nervous'},
  'excited': {note:'辨析：excited 兴奋；thrilled 激动；eager 渴望；enthusiastic 热情', with:'thrilled, eager, enthusiastic'},
  'proud': {note:'辨析：proud 自豪；satisfied 满意；honoured 荣幸；dignified 有尊严', with:'satisfied, honoured, dignified'},
  'famous': {note:'辨析：famous 著名；well-known 知名；renowned 享誉；notable 显要', with:'well-known, renowned, notable'},
  'popular': {note:'辨析：popular 受欢迎；well-liked 讨喜；trendy 时髦；widespread 盛行', with:'well-liked, trendy, widespread'},
  'common': {note:'辨析：common 常见；widespread 普遍；prevalent 盛行；typical 典型', with:'widespread, prevalent, typical'},
  'rare': {note:'辨析：rare 稀有；scarce 稀缺；uncommon 罕见；exceptional 例外', with:'scarce, uncommon, exceptional'},
  'usual': {note:'辨析：usual 通常；normal 正常；ordinary 普通；typical 典型', with:'normal, ordinary, typical'},
  'strange': {note:'辨析：strange 奇怪；odd 古怪；peculiar 奇特；bizarre 怪诞', with:'odd, peculiar, bizarre'},
  'interesting': {note:'辨析：interesting 有趣；fascinating 迷人；engaging 吸引人；intriguing 引人入胜', with:'fascinating, engaging, intriguing'},
  'boring': {note:'辨析：boring 无聊；dull 乏味；tedious 冗长乏味；monotonous 单调', with:'dull, tedious, monotonous'},
  'fun': {note:'辨析：fun 有趣；enjoyable 令人愉快；entertaining 娱乐的；amusing 逗趣', with:'enjoyable, entertaining, amusing'},
  'serious': {note:'辨析：serious 严肃；grave 严重；solemn 庄重；severe 严峻', with:'grave, solemn, severe'},
  'important thing': {note:'辨析：priority 优先事项；emphasis 重点；highlight 亮点；key point 要点', with:'priority, emphasis, highlight, key point'},
  'problem': {note:'辨析：problem 问题；issue 议题；difficulty 困难；challenge 挑战', with:'issue, difficulty, challenge'},
  'reason': {note:'辨析：reason 原因；cause 起因；motive 动机；justification 理由（正当性）', with:'cause, motive, justification'},
  'result': {note:'辨析：result 结果；outcome 成果；consequence 后果；effect 效果', with:'outcome, consequence, effect'},
  'effect': {note:'辨析：effect 影响（结果）；impact 冲击；influence 影响（潜移默化）；consequence 后果', with:'impact, influence, consequence'},
  'advantage': {note:'辨析：advantage 优势；benefit 好处；merit 优点；strength 强项', with:'benefit, merit, strength'},
  'disadvantage': {note:'辨析：disadvantage 劣势；drawback 缺点；downside 不利面；weakness 弱点', with:'drawback, downside, weakness'},
  'idea': {note:'辨析：idea 想法；notion 概念；concept 概念（学术）；thought 想法', with:'notion, concept, thought'},
  'opinion': {note:'辨析：opinion 观点；view 看法；belief 信念；perspective 视角', with:'view, belief, perspective'},
  'plan': {note:'辨析：plan 计划；scheme 方案；strategy 策略；approach 方法', with:'scheme, strategy, approach'},
  'method': {note:'辨析：method 方法；approach 途径；technique 技巧；way 方式', with:'approach, technique, way'},
  'habit': {note:'辨析：habit 习惯；routine 常规；custom 风俗；practice 惯例', with:'routine, custom, practice'},
  'job': {note:'辨析：job 工作；occupation 职业；profession 专业职业；career 事业', with:'occupation, profession, career'},
  'skill': {note:'辨析：skill 技能；ability 能力；competence 胜任力；expertise 专长', with:'ability, competence, expertise'},
  'knowledge': {note:'辨析：knowledge 知识；understanding 理解；insight 洞见；awareness 意识', with:'understanding, insight, awareness'},
  'success': {note:'辨析：success 成功；achievement 成就；accomplishment 完成；triumph 胜利', with:'achievement, accomplishment, triumph'},
  'goal': {note:'辨析：goal 目标；aim 目的；objective 目标（正式）；target 指标', with:'aim, objective, target'},
  'freedom': {note:'辨析：freedom 自由；liberty 自由（政治）；independence 独立；autonomy 自主', with:'liberty, independence, autonomy'},
  'money': {note:'辨析：money 钱；income 收入；salary 薪水；wealth 财富', with:'income, salary, wealth'},
  'food': {note:'辨析：food 食物；meal 一餐；dish 菜肴；cuisine 菜系', with:'meal, dish, cuisine'},
  'home': {note:'辨析：home 家；house 房子；residence 住所；accommodation 住处', with:'house, residence, accommodation'},
  'city': {note:'辨析：city 城市；metropolis 大都市；town 城镇；urban area 城区', with:'metropolis, town, urban area'},
  'school': {note:'辨析：school 学校；college 学院；university 大学；institute 研究所', with:'college, university, institute'},
  'teacher': {note:'辨析：teacher 老师；instructor 指导者；tutor 导师；professor 教授', with:'instructor, tutor, professor'},
  'student': {note:'辨析：student 学生；pupil 小学生；undergraduate 本科生；postgraduate 研究生', with:'pupil, undergraduate, postgraduate'},
  'friend': {note:'辨析：friend 朋友；companion 伙伴；mate 同伴；acquaintance 熟人', with:'companion, mate, acquaintance'},
  'family': {note:'辨析：family 家庭；relatives 亲戚；household 一户；kin 亲属', with:'relatives, household, kin'},
  'help': {note:'辨析：help 帮助；aid 援助；assistance 协助；support 支持', with:'aid, assistance, support'},
};
module.exports = { SYNNOTE };
