'use strict';
/* v4 新增词库：z = 'w' 书写专区 / 'l' 听力专区 */
const V4NEW = [
{t:"academic",w:"argument",s:["point","case","reasoning"],c:"论点，论据",e:"Her main point is that education should be free.",k:"point",p:"ˈɑːɡjumənt",pos:"n.",d:"a set of reasons supporting an idea",z:"w"},
{t:"academic",w:"claim",s:["assert","maintain","state"],c:"声称，主张",e:"Critics assert that the policy has failed.",k:"assert",p:"kleɪm",pos:"v.",d:"to state that something is true",z:"w"},
{t:"academic",w:"opinion",s:["view","viewpoint","perspective"],c:"观点",e:"From my perspective, the benefits outweigh the costs.",k:"perspective",p:"əˈpɪnjən",pos:"n.",d:"a belief or judgement about something",z:"w"},
{t:"academic",w:"support",s:["back up","endorse","reinforce"],c:"支持",e:"The evidence backs up this claim.",k:"backs up",p:"səˈpɔːt",pos:"v.",d:"to agree with and help something",z:"w"},
{t:"academic",w:"illustrate",s:["demonstrate","exemplify","show"],c:"说明，举例说明",e:"The chart demonstrates the sharp rise in prices.",k:"demonstrates",p:"ˈɪləstreɪt",pos:"v.",d:"to explain something with examples",z:"w"},
{t:"academic",w:"emphasise",s:["stress","highlight","underline"],c:"强调",e:"The report highlights the need for reform.",k:"highlights",p:"ˈemfəsaɪz",pos:"v.",d:"to give special importance to something",z:"w"},
{t:"academic",w:"consequence",s:["outcome","result","ramification"],c:"后果",e:"One outcome of the change is higher costs.",k:"outcome",p:"ˈkɒnsɪkwəns",pos:"n.",d:"a result of an action",z:"w"},
{t:"academic",w:"contribute",s:["play a part","lead to","add to"],c:"促成，贡献",e:"Several factors play a part in obesity.",k:"play a part",p:"kənˈtrɪbjuːt",pos:"v.",d:"to help cause something",z:"w"},
{t:"academic",w:"factor",s:["element","variable","aspect"],c:"因素",e:"Cost is a key element in the decision.",k:"element",p:"ˈfæktə",pos:"n.",d:"something that influences a result",z:"w"},
{t:"academic",w:"significant",s:["considerable","substantial","marked"],c:"显著的",e:"There was a substantial increase in sales.",k:"substantial",p:"sɪɡˈnɪfɪkənt",pos:"adj.",d:"large or important enough to notice",z:"w"},
{t:"academic",w:"marginal",s:["slight","minimal","small"],c:"微小的，边缘的",e:"The figures show only a minimal improvement.",k:"minimal",p:"ˈmɑːdʒɪnl",pos:"adj.",d:"very small in amount or degree",z:"w"},
{t:"academic",w:"gradual",s:["steady","slow","progressive"],c:"逐渐的",e:"There was a steady fall in unemployment.",k:"steady",p:"ˈɡrædʒuəl",pos:"adj.",d:"happening slowly over time",z:"w"},
{t:"academic",w:"sharp",s:["dramatic","rapid","steep"],c:"急剧的",e:"The graph shows a dramatic drop in profits.",k:"dramatic",p:"ʃɑːp",pos:"adj.",d:"sudden and large",z:"w"},
{t:"academic",w:"fluctuate",s:["vary","change repeatedly","oscillate"],c:"波动",e:"Prices varied between January and March.",k:"varied",p:"ˈflʌktʃueɪt",pos:"v.",d:"to change often from one level to another",z:"w"},
{t:"academic",w:"peak",s:["reach the highest point","culminate"],c:"达到顶峰",e:"Demand reaches its highest point in summer.",k:"reaches its highest point",p:"piːk",pos:"v.",d:"to reach the top level",z:"w"},
{t:"academic",w:"plateau",s:["level off","stabilise","flatten out"],c:"趋于平稳",e:"The number of users levelled off in 2023.",k:"levelled off",p:"ˈplætəʊ",pos:"v.",d:"to stay at a steady level",z:"w"},
{t:"academic",w:"proportion",s:["percentage","share","ratio"],c:"比例",e:"A large share of income goes on housing.",k:"share",p:"prəˈpɔːʃn",pos:"n.",d:"the amount of something compared to the whole",z:"w"},
{t:"academic",w:"figure",s:["number","statistic","data"],c:"数字",e:"The statistics show a clear upward trend.",k:"statistics",p:"ˈfɪɡə",pos:"n.",d:"a number or amount",z:"w"},
{t:"academic",w:"estimate",s:["rough calculation","approximation","assessment"],c:"估计",e:"A rough calculation puts the cost at five million.",k:"rough calculation",p:"ˈestɪmət",pos:"n.",d:"an approximate judgement of an amount",z:"w"},
{t:"academic",w:"double",s:["multiply by two","twice as much"],c:"翻倍",e:"The population multiplied by two in ten years.",k:"multiplied by two",p:"ˈdʌbl",pos:"v.",d:"to become twice as much",z:"w"},
{t:"academic",w:"whereas",s:["while","in contrast","whilst"],c:"然而，而",e:"In contrast, the rural population shrank.",k:"in contrast",p:"weərˈæz",pos:"conj.",d:"used to compare two different facts",z:"w"},
{t:"academic",w:"similarly",s:["likewise","in the same way","equally"],c:"类似地",e:"Likewise, sales in Europe increased.",k:"likewise",p:"ˈsɪmələli",pos:"adv.",d:"in a similar way",z:"w"},
{t:"academic",w:"differ",s:["vary","be different","contrast"],c:"不同",e:"The results vary between regions.",k:"vary",p:"ˈdɪfə",pos:"v.",d:"to be different from something else",z:"w"},
{t:"academic",w:"distinct",s:["separate","different","clear"],c:"明显不同的",e:"The two groups have separate needs.",k:"separate",p:"dɪˈstɪŋkt",pos:"adj.",d:"clearly different or separate",z:"w"},
{t:"academic",w:"justify",s:["give reasons for","defend","validate"],c:"证明……有理",e:"The company must give reasons for the increase.",k:"give reasons for",p:"ˈdʒʌstɪfaɪ",pos:"v.",d:"to show that something is right or reasonable",z:"w"},
{t:"academic",w:"summarise",s:["outline","give a summary of","recap"],c:"总结",e:"To outline, the policy has three main aims.",k:"outline",p:"ˈsʌməraɪz",pos:"v.",d:"to state the main points of something",z:"w"},
{t:"academic",w:"overall",s:["in general","on the whole","all in all"],c:"总的来说",e:"On the whole, the results were positive.",k:"on the whole",p:"ˌəʊvərˈɔːl",pos:"adv.",d:"considering everything together",z:"w"},
{t:"academic",w:"notably",s:["particularly","especially","in particular"],c:"尤其，显著地",e:"Particularly, spending on health rose.",k:"particularly",p:"ˈnəʊtəbli",pos:"adv.",d:"especially or in a noticeable way",z:"w"},
{t:"academic",w:"graph",s:["chart","diagram","figure"],c:"图表",e:"The chart compares two sets of data.",k:"chart",p:"ɡrɑːf",pos:"n.",d:"a diagram showing information",z:"w"},
{t:"academic",w:"comparison",s:["contrast","juxtaposition","parallel"],c:"比较",e:"The contrast between the years is clear.",k:"contrast",p:"kəmˈpærɪsn",pos:"n.",d:"the act of comparing things",z:"w"},
{t:"academic",w:"percentage",s:["proportion","share","rate"],c:"百分比",e:"A large proportion of students agree.",k:"proportion",p:"pəˈsentɪdʒ",pos:"n.",d:"an amount expressed as part of a hundred",z:"w"},
{t:"core",w:"advantage",s:["benefit","merit","strength"],c:"优势",e:"One merit of the scheme is its low cost.",k:"merit",p:"ədˈvɑːntɪdʒ",pos:"n.",d:"a good or useful feature",z:"w"},
{t:"core",w:"drawback",s:["disadvantage","downside","weakness"],c:"缺点",e:"The main downside is the time required.",k:"downside",p:"ˈdrɔːbæk",pos:"n.",d:"an unpleasant part of something",z:"w"},
{t:"core",w:"solution",s:["answer","remedy","resolution"],c:"解决办法",e:"A possible remedy is to improve public transport.",k:"remedy",p:"səˈluːʃn",pos:"n.",d:"a way of solving a problem",z:"w"},
{t:"core",w:"encourage",s:["promote","foster","stimulate"],c:"鼓励，促进",e:"The scheme fosters innovation in schools.",k:"fosters",p:"ɪnˈkʌrɪdʒ",pos:"v.",d:"to give support or confidence to something",z:"w"},
{t:"core",w:"raise",s:["increase","boost","lift"],c:"提高",e:"The firm will boost wages next year.",k:"boost",p:"reɪz",pos:"v.",d:"to make something higher or greater",z:"w"},
{t:"core",w:"lower",s:["reduce","cut","bring down"],c:"降低",e:"The plan aims to cut carbon emissions.",k:"cut",p:"ˈləʊə",pos:"v.",d:"to make something less in amount",z:"w"},
{t:"core",w:"achieve",s:["accomplish","attain","reach"],c:"实现，达到",e:"The team accomplished all its goals.",k:"accomplished",p:"əˈtʃiːv",pos:"v.",d:"to succeed in doing something",z:"w"},
{t:"core",w:"aim",s:["goal","objective","target"],c:"目标",e:"The main objective is to cut waste.",k:"objective",p:"eɪm",pos:"n.",d:"what someone hopes to achieve",z:"w"},
{t:"core",w:"policy",s:["strategy","approach","plan"],c:"政策",e:"The new strategy targets young drivers.",k:"strategy",p:"ˈpɒləsi",pos:"n.",d:"an official plan of action",z:"w"},
{t:"core",w:"regulation",s:["rule","law","requirement"],c:"规定",e:"New rules will apply to all factories.",k:"rules",p:"ˌreɡjuˈleɪʃn",pos:"n.",d:"an official rule that controls something",z:"w"},
{t:"core",w:"government",s:["authorities","state","administration"],c:"政府",e:"The authorities have banned the practice.",k:"authorities",p:"ˈɡʌvənmənt",pos:"n.",d:"the group that governs a country",z:"w"},
{t:"core",w:"individual",s:["person","citizen","someone"],c:"个人",e:"Each person must take responsibility.",k:"person",p:"ˌɪndɪˈvɪdʒuəl",pos:"n.",d:"a single person",z:"w"},
{t:"core",w:"society",s:["community","the public","population"],c:"社会",e:"The whole community benefits from the project.",k:"community",p:"səˈsaɪəti",pos:"n.",d:"people living together in a country",z:"w"},
{t:"core",w:"population",s:["inhabitants","people","residents"],c:"人口",e:"The number of residents is growing.",k:"residents",p:"ˌpɒpjuˈleɪʃn",pos:"n.",d:"all the people living in a place",z:"w"},
{t:"core",w:"wealth",s:["riches","resources","affluence"],c:"财富",e:"The region's affluence attracts workers.",k:"affluence",p:"welθ",pos:"n.",d:"a large amount of money or property",z:"w"},
{t:"core",w:"poverty",s:["hardship","destitution","need"],c:"贫困",e:"Many families face hardship in winter.",k:"hardship",p:"ˈpɒvəti",pos:"n.",d:"the state of being poor",z:"w"},
{t:"core",w:"inequality",s:["disparity","gap","imbalance"],c:"不平等",e:"The gap between rich and poor is widening.",k:"gap",p:"ˌɪnɪˈkwɒləti",pos:"n.",d:"unfair differences between groups of people",z:"w"},
{t:"core",w:"unemployment",s:["joblessness","being out of work"],c:"失业",e:"Joblessness among young people is high.",k:"joblessness",p:"ˌʌnɪmˈplɔɪmənt",pos:"n.",d:"the state of having no job",z:"w"},
{t:"core",w:"income",s:["earnings","wages","pay"],c:"收入",e:"Average earnings rose last year.",k:"earnings",p:"ˈɪnkʌm",pos:"n.",d:"money received for work",z:"w"},
{t:"core",w:"spending",s:["expenditure","outlay","costs"],c:"支出",e:"Government expenditure on health increased.",k:"expenditure",p:"ˈspendɪŋ",pos:"n.",d:"the money that is spent",z:"w"},
{t:"core",w:"tax",s:["duty","levy","charge"],c:"税收",e:"The government introduced a new levy on fuel.",k:"levy",p:"tæks",pos:"n.",d:"money paid to the government",z:"w"},
{t:"core",w:"budget",s:["funds","allocation","resources"],c:"预算",e:"Funds for the project were cut.",k:"funds",p:"ˈbʌdʒɪt",pos:"n.",d:"the money available for a purpose",z:"w"},
{t:"core",w:"funding",s:["finance","backing","money"],c:"资金",e:"The scheme needs extra finance.",k:"finance",p:"ˈfʌndɪŋ",pos:"n.",d:"money provided for something",z:"w"},
{t:"core",w:"investment",s:["capital","funding","outlay"],c:"投资",e:"More capital is flowing into renewable energy.",k:"capital",p:"ɪnˈvestmənt",pos:"n.",d:"money put into something to make a profit",z:"w"},
{t:"core",w:"profit",s:["gain","return","earnings"],c:"利润",e:"The company reported strong gains.",k:"gains",p:"ˈprɒfɪt",pos:"n.",d:"money made in business",z:"w"},
{t:"core",w:"demand",s:["need","requirement","desire"],c:"需求",e:"The need for housing is growing.",k:"need",p:"dɪˈmɑːnd",pos:"n.",d:"the amount of something people want",z:"w"},
{t:"core",w:"supply",s:["provision","source","stock"],c:"供应",e:"The provision of clean water is essential.",k:"provision",p:"səˈplaɪ",pos:"n.",d:"the amount of something available",z:"w"},
{t:"core",w:"surplus",s:["excess","oversupply","extra"],c:"过剩",e:"An excess of oil pushed prices down.",k:"excess",p:"ˈsɜːpləs",pos:"n.",d:"more of something than is needed",z:"w"},
{t:"core",w:"efficient",s:["effective","productive","well-organised"],c:"高效的",e:"The new system is highly effective.",k:"effective",p:"ɪˈfɪʃnt",pos:"adj.",d:"working well without wasting time or money",z:"w"},
{t:"core",w:"effective",s:["successful","productive","efficient"],c:"有效的",e:"The campaign was highly successful.",k:"successful",p:"ɪˈfektɪv",pos:"adj.",d:"producing the result that is wanted",z:"w"},
{t:"core",w:"sustainable",s:["environmentally friendly","viable","long-term"],c:"可持续的",e:"The scheme is environmentally friendly.",k:"environmentally friendly",p:"səˈsteɪnəbl",pos:"adj.",d:"able to continue without harming the environment",z:"w"},
{t:"core",w:"obesity",s:["being overweight","excess weight"],c:"肥胖",e:"Being overweight raises health risks.",k:"being overweight",p:"əʊˈbiːsəti",pos:"n.",d:"the condition of being very overweight",z:"w"},
{t:"core",w:"healthcare",s:["medical care","treatment","care"],c:"医疗保健",e:"Medical care has improved greatly.",k:"medical care",p:"ˈhelθkeə",pos:"n.",d:"the treatment of illness and injury",z:"w"},
{t:"core",w:"sedentary",s:["inactive","sitting down a lot"],c:"久坐的",e:"Inactive lifestyles are common in cities.",k:"inactive",p:"ˈsedntri",pos:"adj.",d:"involving little physical activity",z:"w"},
{t:"core",w:"mental",s:["psychological","emotional","cognitive"],c:"心理的",e:"Psychological health is often ignored.",k:"psychological",p:"ˈmentl",pos:"adj.",d:"relating to the mind",z:"w"},
{t:"core",w:"wellbeing",s:["health","welfare","quality of life"],c:"幸福感，健康",e:"Exercise improves overall welfare.",k:"welfare",p:"ˌwelˈbiːɪŋ",pos:"n.",d:"the state of being healthy and happy",z:"w"},
{t:"core",w:"disease",s:["illness","sickness","condition"],c:"疾病",e:"The illness spread quickly.",k:"illness",p:"dɪˈziːz",pos:"n.",d:"a serious illness affecting the body",z:"w"},
{t:"core",w:"prevention",s:["avoidance","stopping","protection"],c:"预防",e:"Avoidance is better than cure.",k:"avoidance",p:"prɪˈvenʃn",pos:"n.",d:"stopping something before it happens",z:"w"},
{t:"core",w:"technology",s:["innovation","digital tools","equipment"],c:"技术",e:"Digital tools have changed education.",k:"digital tools",p:"tekˈnɒlədʒi",pos:"n.",d:"scientific knowledge applied in practical ways",z:"w"},
{t:"core",w:"automation",s:["machine use","robotics","computerisation"],c:"自动化",e:"Machine use has replaced some jobs.",k:"machine use",p:"ˌɔːtəˈmeɪʃn",pos:"n.",d:"using machines to do work",z:"w"},
{t:"core",w:"innovation",s:["invention","new idea","advance"],c:"创新",e:"The invention transformed travel.",k:"invention",p:"ˌɪnəˈveɪʃn",pos:"n.",d:"a new idea or method",z:"w"},
{t:"core",w:"advancement",s:["progress","development","improvement"],c:"进步",e:"Progress in medicine has been rapid.",k:"progress",p:"ədˈvɑːnsmənt",pos:"n.",d:"forward movement or improvement",z:"w"},
{t:"core",w:"device",s:["gadget","machine","appliance"],c:"设备",e:"People carry several gadgets.",k:"gadgets",p:"dɪˈvaɪs",pos:"n.",d:"a piece of electronic equipment",z:"w"},
{t:"core",w:"artificial",s:["man-made","synthetic","manufactured"],c:"人造的",e:"Man-made intelligence is advancing.",k:"man-made",p:"ˌɑːtɪˈfɪʃl",pos:"adj.",d:"made by people rather than nature",z:"w"},
{t:"core",w:"online",s:["digital","virtual","on the internet"],c:"在线的",e:"Virtual lessons are now common.",k:"virtual",p:"ˌɒnˈlaɪn",pos:"adj.",d:"connected to the internet",z:"w"},
{t:"core",w:"curriculum",s:["syllabus","course of study","programme"],c:"课程体系",e:"The syllabus includes more science.",k:"syllabus",p:"kəˈrɪkjələm",pos:"n.",d:"the subjects taught in a school or course",z:"w"},
{t:"core",w:"literacy",s:["reading and writing","basic skills"],c:"读写能力",e:"Reading and writing rates have improved.",k:"reading and writing",p:"ˈlɪtərəsi",pos:"n.",d:"the ability to read and write",z:"w"},
{t:"core",w:"tuition",s:["fees","teaching","instruction"],c:"学费，教学",e:"University fees have doubled.",k:"fees",p:"tjuˈɪʃn",pos:"n.",d:"money paid for teaching",z:"w"},
{t:"core",w:"vocational",s:["practical","work-related","career-based"],c:"职业的",e:"Work-related training is valued.",k:"work-related",p:"vəʊˈkeɪʃənl",pos:"adj.",d:"relating to skills needed for a job",z:"w"},
{t:"core",w:"productivity",s:["output","efficiency","yield"],c:"生产力",e:"Output rose by ten percent.",k:"output",p:"ˌprɒdʌkˈtɪvəti",pos:"n.",d:"the amount of work produced",z:"w"},
{t:"core",w:"workforce",s:["staff","employees","labour force"],c:"劳动力",e:"The labour force is shrinking.",k:"labour force",p:"ˈwɜːkfɔːs",pos:"n.",d:"all the people who work in a place",z:"w"},
{t:"core",w:"opportunity",s:["chance","prospect","opening"],c:"机会",e:"The scheme offers new chances.",k:"chances",p:"ˌɒpəˈtjuːnəti",pos:"n.",d:"a chance to do something",z:"w"},
{t:"core",w:"career",s:["profession","occupation","working life"],c:"职业",e:"She chose a career in medicine.",k:"career",p:"kəˈrɪə",pos:"n.",d:"the job you do during your working life",z:"w"},
{t:"core",w:"flexible",s:["adaptable","adjustable","versatile"],c:"灵活的",e:"The company offers adaptable hours.",k:"adaptable",p:"ˈfleksəbl",pos:"adj.",d:"able to change easily",z:"w"},
{t:"core",w:"congestion",s:["traffic jams","gridlock","crowding"],c:"拥堵",e:"Traffic jams are worse in the morning.",k:"traffic jams",p:"kənˈdʒestʃən",pos:"n.",d:"too much traffic blocking roads",z:"w"},
{t:"core",w:"commute",s:["travel to work","daily journey","round trip"],c:"通勤",e:"Her daily journey takes an hour.",k:"daily journey",p:"kəˈmjuːt",pos:"n.",d:"the journey to and from work",z:"w"},
{t:"core",w:"infrastructure",s:["roads and systems","facilities","networks"],c:"基础设施",e:"Better roads and systems are needed.",k:"roads and systems",p:"ˈɪnfrəstrʌktʃə",pos:"n.",d:"basic systems such as roads and power",z:"w"},
{t:"core",w:"housing",s:["homes","accommodation","shelter"],c:"住房",e:"Affordable homes are scarce.",k:"homes",p:"ˈhaʊzɪŋ",pos:"n.",d:"houses available for people to live in",z:"w"},
{t:"core",w:"urban",s:["city","metropolitan","town"],c:"城市的",e:"City life is becoming costly.",k:"city",p:"ˈɜːbən",pos:"adj.",d:"relating to towns or cities",z:"w"},
{t:"core",w:"rural",s:["countryside","country","agricultural"],c:"乡村的",e:"Countryside services are limited.",k:"countryside",p:"ˈrʊərəl",pos:"adj.",d:"relating to the countryside",z:"w"},
{t:"core",w:"consumer",s:["buyer","customer","shopper"],c:"消费者",e:"Buyers want lower prices.",k:"buyers",p:"kənˈsjuːmə",pos:"n.",d:"a person who buys goods",z:"w"},
{t:"core",w:"manufacture",s:["produce","make","fabricate"],c:"制造",e:"The goods are produced locally.",k:"produced",p:"ˌmænjuˈfæktʃə",pos:"v.",d:"to make goods in large numbers",z:"w"},
{t:"core",w:"brand",s:["label","trademark","name"],c:"品牌",e:"The label is known worldwide.",k:"label",p:"brænd",pos:"n.",d:"a product name made by a company",z:"w"},
{t:"core",w:"luxury",s:["premium","high-end","expensive"],c:"奢侈品",e:"Premium goods sell well.",k:"premium",p:"ˈlʌkʃəri",pos:"n.",d:"something expensive but not necessary",z:"w"},
{t:"core",w:"concern",s:["worry","issue","anxiety"],c:"担忧，关切",e:"The main worry is safety.",k:"worry",p:"kənˈsɜːn",pos:"n.",d:"a feeling of worry about something",z:"w"},
{t:"core",w:"positive",s:["favourable","good","optimistic"],c:"积极的",e:"The response was favourable.",k:"favourable",p:"ˈpɒzətɪv",pos:"adj.",d:"good or hopeful",z:"w"},
{t:"core",w:"negative",s:["unfavourable","harmful","adverse"],c:"消极的",e:"There were adverse effects on health.",k:"adverse",p:"ˈneɡətɪv",pos:"adj.",d:"bad or harmful",z:"w"},
{t:"core",w:"balance",s:["equilibrium","stability","proportion"],c:"平衡",e:"A good balance between work and rest is key.",k:"balance",p:"ˈbæləns",pos:"n.",d:"a state where things are equal",z:"w"},
{t:"core",w:"contrast",s:["difference","distinction","comparison"],c:"对比，差异",e:"The distinction between the two is clear.",k:"distinction",p:"ˈkɒntrɑːst",pos:"n.",d:"a clear difference between things",z:"w"},
{t:"core",w:"similarity",s:["resemblance","likeness","parallel"],c:"相似之处",e:"There is a clear resemblance between the charts.",k:"resemblance",p:"ˌsɪməˈlærəti",pos:"n.",d:"the state of being similar",z:"w"},
{t:"core",w:"difference",s:["distinction","gap","variation"],c:"差异",e:"The variation is small but real.",k:"variation",p:"ˈdɪfrəns",pos:"n.",d:"the way things are not the same",z:"w"},
{t:"core",w:"transform",s:["change completely","revolutionise","alter"],c:"彻底改变",e:"The internet revolutionised communication.",k:"revolutionised",p:"trænsˈfɔːm",pos:"v.",d:"to change something completely",z:"w"},
{t:"core",w:"develop",s:["expand","grow","build up"],c:"发展",e:"The company expanded rapidly.",k:"expanded",p:"dɪˈveləp",pos:"v.",d:"to grow or improve",z:"w"},
{t:"core",w:"address",s:["tackle","deal with","solve"],c:"解决（问题）",e:"The plan tackles the housing crisis.",k:"tackles",p:"əˈdres",pos:"v.",d:"to deal with a problem",z:"w"},
{t:"core",w:"tackle",s:["deal with","address","solve"],c:"处理",e:"The council dealt with the issue quickly.",k:"dealt with",p:"ˈtækl",pos:"v.",d:"to make an effort to deal with something",z:"w"},
{t:"core",w:"implement",s:["carry out","put into practice","introduce"],c:"实施",e:"The policy will be carried out next year.",k:"carried out",p:"ˈɪmplɪment",pos:"v.",d:"to put a plan into action",z:"w"},
{t:"core",w:"evaluate",s:["assess","appraise","judge"],c:"评估",e:"The programme will be assessed annually.",k:"assessed",p:"ɪˈvæljueɪt",pos:"v.",d:"to judge the value or quality of something",z:"w"},
{t:"core",w:"recommend",s:["suggest","advise","propose"],c:"建议",e:"Experts advise against the ban.",k:"advise",p:"ˌrekəˈmend",pos:"v.",d:"to suggest something as good",z:"w"},
{t:"core",w:"propose",s:["suggest","put forward","recommend"],c:"提议",e:"The council put forward a new plan.",k:"put forward",p:"prəˈpəʊz",pos:"v.",d:"to suggest a plan or idea",z:"w"},
{t:"core",w:"debate",s:["discussion","argument","controversy"],c:"辩论，讨论",e:"The discussion focused on education.",k:"discussion",p:"dɪˈbeɪt",pos:"n.",d:"a formal discussion of a topic",z:"w"},
{t:"core",w:"influence",s:["shape","affect","determine"],c:"影响",e:"The media shape public opinion.",k:"shape",p:"ˈɪnfluəns",pos:"v.",d:"to change or affect something",z:"w"},
{t:"core",w:"shape",s:["influence","form","determine"],c:"塑造",e:"Family values determine our choices.",k:"determine",p:"ʃeɪp",pos:"v.",d:"to influence how something develops",z:"w"},
{t:"core",w:"fundamental",s:["basic","essential","core"],c:"根本的",e:"Basic rights must be protected.",k:"basic",p:"ˌfʌndəˈmentl",pos:"adj.",d:"forming the base of something",z:"w"},
{t:"core",w:"relate to",s:["connect with","be linked to","concern"],c:"与……相关",e:"The results connect with earlier findings.",k:"connect with",p:"rɪˈleɪt tuː",pos:"v.",d:"to be connected with something",z:"w"},
{t:"core",w:"connection",s:["link","relationship","tie"],c:"联系",e:"The link between diet and health is strong.",k:"link",p:"kəˈnekʃn",pos:"n.",d:"a relationship between things",z:"w"},
{t:"core",w:"dependent",s:["reliant","depending","conditional"],c:"依赖的",e:"The region is reliant on tourism.",k:"reliant",p:"dɪˈpendənt",pos:"adj.",d:"needing something or someone",z:"w"},
{t:"core",w:"equal",s:["the same","identical","even"],c:"平等的，相等的",e:"Both groups received the same pay.",k:"the same",p:"ˈiːkwəl",pos:"adj.",d:"the same in amount or level",z:"w"},
{t:"core",w:"major",s:["main","principal","chief"],c:"主要的",e:"The principal cause is overuse.",k:"principal",p:"ˈmeɪdʒə",pos:"adj.",d:"very important or large",z:"w"},
{t:"core",w:"minor",s:["small","less important","secondary"],c:"次要的",e:"A secondary issue was ignored.",k:"secondary",p:"ˈmaɪnə",pos:"adj.",d:"small or not important",z:"w"},
{t:"core",w:"rapid",s:["fast","quick","swift"],c:"快速的",e:"The city is expanding at a swift pace.",k:"swift",p:"ˈræpɪd",pos:"adj.",d:"happening very quickly",z:"w"},
{t:"core",w:"steadily",s:["gradually","consistently","evenly"],c:"稳定地",e:"Prices have risen consistently.",k:"consistently",p:"ˈstedɪli",pos:"adv.",d:"in a regular and continuous way",z:"w"},
{t:"core",w:"widespread",s:["common","prevalent","general"],c:"普遍的",e:"Smartphone use is prevalent.",k:"prevalent",p:"ˈwaɪdspred",pos:"adj.",d:"existing in many places",z:"w"},
{t:"core",w:"rare",s:["uncommon","scarce","infrequent"],c:"罕见的",e:"Such skills are uncommon.",k:"uncommon",p:"reə",pos:"adj.",d:"not common or frequent",z:"w"},
{t:"core",w:"current",s:["present","existing","now"],c:"当前的",e:"The present system is outdated.",k:"present",p:"ˈkʌrənt",pos:"adj.",d:"happening or existing now",z:"w"},
{t:"core",w:"previous",s:["earlier","past","former"],c:"之前的",e:"Earlier studies found the same.",k:"earlier",p:"ˈpriːviəs",pos:"adj.",d:"happening or existing before",z:"w"},
{t:"core",w:"likely",s:["probable","possible","expected"],c:"可能的",e:"A further rise is probable.",k:"probable",p:"ˈlaɪkli",pos:"adj.",d:"probably going to happen",z:"w"},
{t:"core",w:"unlikely",s:["improbable","doubtful","unexpected"],c:"不太可能的",e:"Change is doubtful in the short term.",k:"doubtful",p:"ʌnˈlaɪkli",pos:"adj.",d:"not likely to happen",z:"w"},
{t:"core",w:"despite",s:["in spite of","regardless of","even with"],c:"尽管",e:"In spite of the cost, the plan went ahead.",k:"in spite of",p:"dɪˈspaɪt",pos:"prep.",d:"without being affected by something",z:"w"},
{t:"core",w:"although",s:["even though","though","while"],c:"虽然",e:"Even though it rained, we continued.",k:"even though",p:"ɔːlˈðəʊ",pos:"conj.",d:"in spite of the fact that",z:"w"},
{t:"core",w:"consequently",s:["as a result","therefore","thus"],c:"因此",e:"As a result, prices fell.",k:"as a result",p:"ˈkɒnsɪkwəntli",pos:"adv.",d:"because of that",z:"w"},{t:"edu",w:"achievement",s:["accomplishment","success","attainment"],c:"成就",e:"The school celebrates every accomplishment.",k:"accomplishment",p:"əˈtʃiːvmənt",pos:"n.",d:"something good that you succeed in doing",z:"w"},
{t:"feelings",w:"attitude",s:["view","stance","approach"],c:"态度",e:"Her stance on the issue is clear.",k:"stance",p:"ˈætɪtjuːd",pos:"n.",d:"the way you think or feel about something",z:"w"},
{t:"travel",w:"junction",s:["crossing","intersection","corner"],c:"路口",e:"Turn left at the next intersection.",k:"intersection",p:"ˈdʒʌŋkʃn",pos:"n.",d:"a place where roads meet",z:"l"},
{t:"travel",w:"roundabout",s:["traffic circle","rotary"],c:"环岛",e:"Take the second exit at the traffic circle.",k:"traffic circle",p:"ˈraʊndəbaʊt",pos:"n.",d:"a circular road junction",z:"l"},
{t:"travel",w:"pedestrian",s:["walker","person on foot"],c:"行人",e:"The walker used the crossing.",k:"walker",p:"pəˈdestriən",pos:"n.",d:"a person walking rather than driving",z:"l"},
{t:"travel",w:"crossing",s:["zebra crossing","pedestrian crossing"],c:"人行横道",e:"Use the zebra crossing to reach the bank.",k:"zebra crossing",p:"ˈkrɒsɪŋ",pos:"n.",d:"a place where people cross the road",z:"l"},
{t:"travel",w:"platform",s:["track","bay","stand"],c:"站台",e:"The train leaves from track three.",k:"track",p:"ˈplætfɔːm",pos:"n.",d:"the place where you get on a train",z:"l"},
{t:"travel",w:"arrival",s:["landing","coming in","arrive"],c:"到达",e:"Landing is scheduled for noon.",k:"landing",p:"əˈraɪvl",pos:"n.",d:"the act of arriving",z:"l"},
{t:"travel",w:"cancel",s:["call off","scrap","abort"],c:"取消",e:"The flight was called off.",k:"called off",p:"ˈkænsl",pos:"v.",d:"to decide that something will not happen",z:"l"},
{t:"travel",w:"terminal",s:["station","depot","gate"],c:"航站楼，终点站",e:"Meet me at the bus station.",k:"station",p:"ˈtɜːmɪnl",pos:"n.",d:"a building where journeys begin or end",z:"l"},
{t:"travel",w:"hostel",s:["budget accommodation","youth hostel"],c:"青年旅舍",e:"The youth hostel is near the station.",k:"youth hostel",p:"ˈhɒstl",pos:"n.",d:"cheap accommodation for travellers",z:"l"},
{t:"travel",w:"cancellation",s:["calling off","withdrawal","cancelling"],c:"取消",e:"Calling off the trip costs nothing.",k:"calling off",p:"ˌkænsəˈleɪʃn",pos:"n.",d:"the act of cancelling something",z:"l"},
{t:"travel",w:"insurance",s:["cover","protection","policy"],c:"保险",e:"Travel cover is included in the price.",k:"cover",p:"ɪnˈʃʊərəns",pos:"n.",d:"protection against loss or damage",z:"l"},
{t:"travel",w:"customs",s:["border control","immigration"],c:"海关",e:"Border control took twenty minutes.",k:"border control",p:"ˈkʌstəmz",pos:"n.",d:"the place where goods are checked",z:"l"},
{t:"travel",w:"boarding",s:["getting on","embarkation"],c:"登机",e:"Getting on begins at gate twelve.",k:"getting on",p:"ˈbɔːdɪŋ",pos:"n.",d:"the act of getting on a plane or ship",z:"l"},
{t:"travel",w:"timetable",s:["schedule","programme"],c:"时刻表",e:"The schedule changed last week.",k:"schedule",p:"ˈtaɪmteɪbl",pos:"n.",d:"a list of times when things happen",z:"l"},
{t:"living",w:"tenant",s:["renter","occupant","lodger"],c:"房客",e:"The renter pays the rent monthly.",k:"renter",p:"ˈtenənt",pos:"n.",d:"a person who rents a property",z:"l"},
{t:"living",w:"furnished",s:["equipped","with furniture"],c:"带家具的",e:"The flat is equipped with furniture.",k:"equipped",p:"ˈfɜːnɪʃt",pos:"adj.",d:"containing furniture",z:"l"},
{t:"living",w:"unfurnished",s:["empty","without furniture"],c:"不带家具的",e:"The room is empty of furniture.",k:"empty",p:"ʌnˈfɜːnɪʃt",pos:"adj.",d:"without furniture",z:"l"},
{t:"edu",w:"enrol",s:["register","sign up","join"],c:"报名，注册",e:"Register online before Friday.",k:"register",p:"ɪnˈrəʊl",pos:"v.",d:"to officially join a course",z:"l"},
{t:"edu",w:"registration",s:["enrolment","sign-up","joining"],c:"注册",e:"Enrolment opens in September.",k:"enrolment",p:"ˌredʒɪˈstreɪʃn",pos:"n.",d:"the process of registering",z:"l"},
{t:"edu",w:"laboratory",s:["lab","workshop","science room"],c:"实验室",e:"The lab is on the third floor.",k:"lab",p:"ləˈbɒrətri",pos:"n.",d:"a room used for scientific work",z:"l"},
{t:"edu",w:"auditorium",s:["hall","lecture hall","theatre"],c:"礼堂",e:"The lecture hall seats two hundred.",k:"lecture hall",p:"ˌɔːdɪˈtɔːriəm",pos:"n.",d:"a large room for audiences",z:"l"},
{t:"edu",w:"reception",s:["front desk","enquiry desk","office"],c:"前台，接待处",e:"Ask at the front desk.",k:"front desk",p:"rɪˈsepʃn",pos:"n.",d:"the place where visitors report",z:"l"},
{t:"edu",w:"extension",s:["extra time","postponement","more time"],c:"延期",e:"Ask for extra time if needed.",k:"extra time",p:"ɪkˈstenʃn",pos:"n.",d:"more time allowed for something",z:"l"},
{t:"edu",w:"reference",s:["recommendation","testimonial"],c:"推荐信",e:"Provide a recommendation from a tutor.",k:"recommendation",p:"ˈrefrəns",pos:"n.",d:"a statement about someone's qualities",z:"l"},
{t:"edu",w:"draft",s:["first version","rough copy","outline"],c:"草稿",e:"Submit a first version by Monday.",k:"first version",p:"drɑːft",pos:"n.",d:"an early version of a piece of writing",z:"l"},
{t:"edu",w:"plagiarism",s:["copying","cheating","stealing work"],c:"抄袭",e:"Copying will lead to failure.",k:"copying",p:"ˈpleɪdʒərɪzəm",pos:"n.",d:"using other people's work as your own",z:"l"},
{t:"health",w:"surgery",s:["clinic","doctor's office","practice"],c:"诊所，手术",e:"The clinic opens at nine.",k:"clinic",p:"ˈsɜːdʒəri",pos:"n.",d:"a place where doctors treat patients",z:"l"},
{t:"health",w:"prescription",s:["medicine order","medical note"],c:"处方",e:"Take the medical note to the chemist.",k:"medical note",p:"prɪˈskrɪpʃn",pos:"n.",d:"a doctor's order for medicine",z:"l"},
{t:"health",w:"vaccination",s:["injection","jab","immunisation"],c:"接种疫苗",e:"The jab is free for students.",k:"jab",p:"ˌvæksɪˈneɪʃn",pos:"n.",d:"a medical injection against disease",z:"l"},
{t:"shopping",w:"special offer",s:["deal","promotion","reduction"],c:"特价优惠",e:"There is a deal on this week.",k:"deal",p:"ˈspeʃl ˈɒfə",pos:"n.",d:"a temporary price reduction",z:"l"},
{t:"shopping",w:"voucher",s:["coupon","token","credit note"],c:"代金券",e:"Use the coupon at checkout.",k:"coupon",p:"ˈvaʊtʃə",pos:"n.",d:"a ticket that gives a discount",z:"l"},
{t:"shopping",w:"outlet",s:["store","shop","branch"],c:"专卖店，折扣店",e:"The store is in the mall.",k:"store",p:"ˈaʊtlet",pos:"n.",d:"a shop that sells goods",z:"l"},
{t:"shopping",w:"counter",s:["desk","till","stand"],c:"柜台",e:"Pay at the till.",k:"till",p:"ˈkaʊntə",pos:"n.",d:"the place where you pay in a shop",z:"l"},
{t:"shopping",w:"grocery",s:["food shopping","supermarket goods","groceries"],c:"食品杂货",e:"The supermarket sells groceries.",k:"groceries",p:"ˈɡrəʊsəri",pos:"n.",d:"food and household goods",z:"l"},
{t:"work",w:"resign",s:["quit","leave","step down"],c:"辞职",e:"She decided to quit her job.",k:"quit",p:"rɪˈzaɪn",pos:"v.",d:"to leave a job officially",z:"l"},
{t:"work",w:"application",s:["form","request","submission"],c:"申请表",e:"The form is available online.",k:"form",p:"ˌæplɪˈkeɪʃn",pos:"n.",d:"a formal request for a job or course",z:"l"},
{t:"env",w:"wildlife",s:["animals","nature","fauna"],c:"野生动物",e:"Local animals are protected.",k:"animals",p:"ˈwaɪldlaɪf",pos:"n.",d:"wild animals and plants",z:"l"},
{t:"env",w:"species",s:["type","kind","variety"],c:"物种",e:"Many types of bird live here.",k:"types",p:"ˈspiːʃiːz",pos:"n.",d:"a group of animals or plants",z:"l"},
{t:"core",w:"description",s:["account","details","overview"],c:"描述",e:"Give an account of the process.",k:"account",p:"dɪˈskrɪpʃn",pos:"n.",d:"a spoken or written explanation",z:"l"},
{t:"core",w:"location",s:["position","site","place"],c:"位置",e:"The site is near the park.",k:"site",p:"ləʊˈkeɪʃn",pos:"n.",d:"a place where something is",z:"l"},
{t:"core",w:"opposite",s:["across from","facing","opposite to"],c:"在……对面",e:"The bank is across from the library.",k:"across from",p:"ˈɒpəzɪt",pos:"prep.",d:"facing something on the other side",z:"l"},
{t:"core",w:"adjacent",s:["next to","beside","nearby"],c:"相邻的",e:"The cafe is next to the bookshop.",k:"next to",p:"əˈdʒeɪsnt",pos:"adj.",d:"very close or next to something",z:"l"},
{t:"core",w:"directions",s:["instructions","guidance","way"],c:"方向指示",e:"Follow the instructions to the hall.",k:"instructions",p:"dəˈrekʃnz",pos:"n.",d:"guidance on how to get somewhere",z:"l"},
{t:"core",w:"entrance",s:["way in","door","gate"],c:"入口",e:"The way in is on the left.",k:"way in",p:"ˈentrəns",pos:"n.",d:"the place where you go in",z:"l"},
{t:"core",w:"exit",s:["way out","door","gate"],c:"出口",e:"The way out is at the back.",k:"way out",p:"ˈeksɪt",pos:"n.",d:"the place where you go out",z:"l"},
{t:"core",w:"noticeboard",s:["bulletin board","message board","board"],c:"公告栏",e:"Check the bulletin board daily.",k:"bulletin board",p:"ˈnəʊtɪsbɔːd",pos:"n.",d:"a board for public notices",z:"l"},
{t:"core",w:"newsletter",s:["bulletin","update","mailing"],c:"简报",e:"The bulletin comes monthly.",k:"bulletin",p:"ˈnjuːzletə",pos:"n.",d:"a regular update sent to members",z:"l"},
{t:"core",w:"enquiry",s:["question","inquiry","request for information"],c:"询问",e:"Send your questions to the office.",k:"questions",p:"ɪnˈkwaɪəri",pos:"n.",d:"a question about something",z:"l"},
{t:"core",w:"brochure",s:["leaflet","pamphlet","booklet"],c:"宣传册",e:"The leaflet explains the course.",k:"leaflet",p:"ˈbrəʊʃə",pos:"n.",d:"a small book with information",z:"l"},
{t:"core",w:"details",s:["information","particulars","specifics"],c:"详细信息",e:"Write your particulars below.",k:"particulars",p:"ˈdiːteɪlz",pos:"n.",d:"facts or information about something",z:"l"},
{t:"core",w:"confirmation",s:["verification","approval","receipt"],c:"确认",e:"You will receive verification by email.",k:"verification",p:"ˌkɒnfəˈmeɪʃn",pos:"n.",d:"a statement that something is true or arranged",z:"l"}
];
module.exports = { V4NEW };