'use strict';
const V5A = [
{t:"academic",w:"surge",s:["soar","rocket","shoot up"],c:"激增",e:"House prices soared in the last decade.",k:"soared",p:"sɜːdʒ",pos:"v.",d:"to increase suddenly and greatly",z:"w"},
{t:"academic",w:"plummet",s:["plunge","drop sharply","nosedive"],c:"暴跌",e:"Sales plunged after the scandal.",k:"plunged",p:"ˈplʌmɪt",pos:"v.",d:"to fall suddenly and quickly",z:"w"},
{t:"academic",w:"dip",s:["decline slightly","edge down","fall a little"],c:"小幅下降",e:"Unemployment edged down slightly last month.",k:"edged down",p:"dɪp",pos:"v.",d:"to go down by a small amount",z:"w"},
{t:"academic",w:"rebound",s:["bounce back","recover","rally"],c:"回升",e:"The economy bounced back in the second quarter.",k:"bounced back",p:"rɪˈbaʊnd",pos:"v.",d:"to increase again after a fall",z:"w"},
{t:"academic",w:"escalate",s:["intensify","worsen","grow"],c:"加剧",e:"The conflict intensified over the summer.",k:"intensified",p:"ˈeskəleɪt",pos:"v.",d:"to become much worse or more intense",z:"w"},
{t:"academic",w:"diminish",s:["decline","fade","dwindle"],c:"减少，减弱",e:"Support for the policy dwindled over time.",k:"dwindled",p:"dɪˈmɪnɪʃ",pos:"v.",d:"to become smaller or less",z:"w"},
{t:"academic",w:"halve",s:["cut in half","reduce by fifty per cent"],c:"减半",e:"The number of smokers was cut in half.",k:"cut in half",p:"hɑːv",pos:"v.",d:"to reduce something to half its size",z:"w"},
{t:"academic",w:"triple",s:["multiply by three","increase threefold"],c:"增至三倍",e:"Online sales increased threefold in five years.",k:"increased threefold",p:"ˈtrɪpl",pos:"v.",d:"to become three times as much",z:"w"},
{t:"academic",w:"outstrip",s:["exceed","surpass","overtake"],c:"超过",e:"Demand far exceeded the available supply.",k:"exceeded",p:"ˌaʊtˈstrɪp",pos:"v.",d:"to be greater than something else",z:"w"},
{t:"academic",w:"account for",s:["constitute","make up","comprise"],c:"占（比例）",e:"Young people make up a third of the workforce.",k:"make up",p:"əˈkaʊnt fɔː",pos:"phr.",d:"to form a particular part of something",z:"w"},
{t:"academic",w:"comprise",s:["consist of","be made up of","include"],c:"由…组成",e:"The panel is made up of five experts.",k:"made up of",p:"kəmˈpraɪz",pos:"v.",d:"to consist of particular parts",z:"w"},
{t:"academic",w:"approximately",s:["roughly","about","around"],c:"大约",e:"The journey takes roughly two hours.",k:"roughly",p:"əˈprɒksɪmətli",pos:"adv.",d:"close to a particular number",z:"w"},
{t:"academic",w:"fluctuation",s:["variation","swing","volatility"],c:"波动",e:"There was considerable variation between months.",k:"variation",p:"ˌflʌktʃuˈeɪʃn",pos:"n.",d:"a change in level or amount",z:"w"},
{t:"academic",w:"considerable",s:["substantial","significant","sizeable"],c:"相当大的",e:"The scheme requires substantial investment.",k:"substantial",p:"kənˈsɪdərəbl",pos:"adj.",d:"large in amount or degree",z:"w"},
{t:"academic",w:"modest",s:["moderate","small","restrained"],c:"适度的，不大的",e:"The region saw only moderate growth.",k:"moderate",p:"ˈmɒdɪst",pos:"adj.",d:"not very large in size or amount",z:"w"},
{t:"academic",w:"slight",s:["minor","small","mild"],c:"轻微的",e:"A minor adjustment was needed.",k:"minor",p:"slaɪt",pos:"adj.",d:"small in degree",z:"w"},
{t:"academic",w:"marked",s:["notable","noticeable","pronounced"],c:"显著的",e:"There was a noticeable improvement in results.",k:"noticeable",p:"mɑːkt",pos:"adj.",d:"clear and easy to notice",z:"w"},
{t:"academic",w:"conversely",s:["on the other hand","in contrast","whilst"],c:"相反地",e:"In contrast, rural areas lost population.",k:"in contrast",p:"ˈkɒnvɜːsli",pos:"adv.",d:"used to introduce an opposite idea",z:"w"},
{t:"academic",w:"give rise to",s:["lead to","cause","trigger"],c:"引起",e:"Poor planning can trigger serious delays.",k:"trigger",p:"ɡɪv raɪz tuː",pos:"phr.",d:"to cause something to happen",z:"w"},
{t:"academic",w:"stem from",s:["arise from","result from","originate from"],c:"源于",e:"Most problems arise from poor communication.",k:"arise from",p:"stem frɒm",pos:"phr.",d:"to be caused by something",z:"w"},
{t:"academic",w:"bring about",s:["cause","produce","generate"],c:"导致，带来",e:"The policy brought about major changes.",k:"brought about",p:"brɪŋ əˈbaʊt",pos:"phr.",d:"to make something happen",z:"w"},
{t:"academic",w:"hinder",s:["impede","hamper","obstruct"],c:"阻碍",e:"Lack of funds hampers research.",k:"hampers",p:"ˈhɪndə",pos:"v.",d:"to make it difficult for something to develop",z:"w"},
{t:"academic",w:"facilitate",s:["enable","make possible","assist"],c:"促进，使便利",e:"Technology enables faster communication.",k:"enables",p:"fəˈsɪlɪteɪt",pos:"v.",d:"to make a process easier",z:"w"},
{t:"academic",w:"accelerate",s:["speed up","hasten","quicken"],c:"加速",e:"Investment sped up economic growth.",k:"sped up",p:"əkˈseləreɪt",pos:"v.",d:"to happen or move faster",z:"w"},
{t:"academic",w:"crucial",s:["vital","essential","critical"],c:"关键的",e:"Timing is vital to the success of the plan.",k:"vital",p:"ˈkruːʃl",pos:"adj.",d:"extremely important",z:"w"},
{t:"academic",w:"paramount",s:["supreme","of greatest importance","primary"],c:"至为重要的",e:"Safety remains of greatest importance.",k:"of greatest importance",p:"ˈpærəmaʊnt",pos:"adj.",d:"more important than anything else",z:"w"},
{t:"academic",w:"indispensable",s:["essential","crucial","necessary"],c:"不可或缺的",e:"The internet is essential for modern study.",k:"essential",p:"ˌɪndɪˈspensəbl",pos:"adj.",d:"too important to be without",z:"w"},
{t:"academic",w:"merit",s:["advantage","strength","virtue"],c:"优点",e:"Each option has its own strengths and weaknesses.",k:"strengths",p:"ˈmerɪt",pos:"n.",d:"a good quality that makes something valuable",z:"w"},
{t:"academic",w:"downside",s:["drawback","weakness","disadvantage"],c:"缺点",e:"The main drawback is the high cost.",k:"drawback",p:"ˈdaʊnsaɪd",pos:"n.",d:"a negative part of a situation",z:"w"},
{t:"academic",w:"shortcoming",s:["flaw","defect","weakness"],c:"不足之处",e:"The plan has a serious flaw.",k:"flaw",p:"ˈʃɔːtkʌmɪŋ",pos:"n.",d:"a fault or weakness in something",z:"w"},
{t:"academic",w:"pitfall",s:["trap","danger","hazard"],c:"隐患，陷阱",e:"New businesses face many hidden dangers.",k:"dangers",p:"ˈpɪtfɔːl",pos:"n.",d:"a hidden difficulty or danger",z:"w"},
{t:"academic",w:"trade-off",s:["compromise","balance","exchange"],c:"权衡取舍",e:"There is a balance between cost and quality.",k:"balance",p:"ˈtreɪd ɒf",pos:"n.",d:"a situation where you accept less of one thing to get more of another",z:"w"},
{t:"academic",w:"majority",s:["most","the greater part","bulk"],c:"大多数",e:"The bulk of the budget goes on staff.",k:"bulk",p:"məˈdʒɒrəti",pos:"n.",d:"more than half of a group",z:"w"},
{t:"academic",w:"minority",s:["small number","few","handful"],c:"少数",e:"Only a handful of students dropped out.",k:"handful",p:"maɪˈnɒrəti",pos:"n.",d:"less than half of a group",z:"w"},
{t:"academic",w:"contend",s:["argue","maintain","assert"],c:"主张，认为",e:"Critics argue that the costs outweigh the benefits.",k:"argue",p:"kənˈtend",pos:"v.",d:"to state an opinion in an argument",z:"w"},
{t:"academic",w:"assert",s:["declare","state firmly","insist"],c:"断言，坚称",e:"The report states firmly that reform is urgent.",k:"states firmly",p:"əˈsɜːt",pos:"v.",d:"to say something in a confident way",z:"w"},
{t:"academic",w:"advocate",s:["support","back","recommend"],c:"提倡",e:"Many experts recommend stricter rules.",k:"recommend",p:"ˈædvəkeɪt",pos:"v.",d:"to publicly support an idea",z:"w"},
{t:"academic",w:"oppose",s:["be against","resist","object to"],c:"反对",e:"Residents objected to the new motorway.",k:"objected to",p:"əˈpəʊz",pos:"v.",d:"to disagree with a plan or idea",z:"w"},
{t:"academic",w:"reject",s:["refuse","turn down","dismiss"],c:"拒绝，驳回",e:"The committee dismissed the proposal.",k:"dismissed",p:"rɪˈdʒekt",pos:"v.",d:"to refuse to accept something",z:"w"},
{t:"academic",w:"refute",s:["disprove","counter","rebuke"],c:"驳斥",e:"The data disproves the earlier claim.",k:"disproves",p:"rɪˈfjuːt",pos:"v.",d:"to prove that a statement is wrong",z:"w"},
{t:"academic",w:"concede",s:["admit","acknowledge","grant"],c:"承认",e:"Officials admitted that mistakes were made.",k:"admitted",p:"kənˈsiːd",pos:"v.",d:"to admit that something is true",z:"w"},
{t:"academic",w:"acknowledge",s:["recognise","accept","admit"],c:"承认，认可",e:"Experts recognise the limits of the study.",k:"recognise",p:"əkˈnɒlɪdʒ",pos:"v.",d:"to accept that something is true",z:"w"},
{t:"academic",w:"highlight",s:["emphasise","underline","accentuate"],c:"强调",e:"The report emphasises the need for action.",k:"emphasises",p:"ˈhaɪlaɪt",pos:"v.",d:"to give special importance to something",z:"w"},
{t:"academic",w:"underscore",s:["emphasise","stress","accentuate"],c:"强调，凸显",e:"The figures accentuate the scale of the problem.",k:"accentuate",p:"ˌʌndəˈskɔː",pos:"v.",d:"to emphasise or show that something is important",z:"w"},
{t:"academic",w:"spotlight",s:["highlight","focus on","draw attention to"],c:"聚焦，突出",e:"The study focuses on young consumers.",k:"focuses on",p:"ˈspɒtlaɪt",pos:"v.",d:"to make people notice something",z:"w"},
{t:"academic",w:"furthermore",s:["moreover","in addition","besides"],c:"此外",e:"Moreover, the costs keep rising.",k:"moreover",p:"ˌfɜːðəˈmɔː",pos:"adv.",d:"used to add another point",z:"w"},
{t:"academic",w:"nevertheless",s:["however","nonetheless","still"],c:"然而",e:"Nonetheless, the benefits are clear.",k:"nonetheless",p:"ˌnevəðəˈles",pos:"adv.",d:"despite what has just been said",z:"w"},
{t:"academic",w:"hence",s:["therefore","thus","consequently"],c:"因此",e:"The data is incomplete, hence the uncertainty.",k:"hence",p:"hens",pos:"adv.",d:"for this reason",z:"w"},
{t:"academic",w:"accordingly",s:["therefore","consequently","as a result"],c:"因此",e:"Demand fell, and prices dropped accordingly.",k:"accordingly",p:"əˈkɔːdɪŋli",pos:"adv.",d:"as a result of something",z:"w"},
{t:"academic",w:"subsequently",s:["later","afterwards","then"],c:"随后",e:"The findings were later confirmed.",k:"later",p:"ˈsʌbsɪkwəntli",pos:"adv.",d:"after something else happened",z:"w"},
{t:"academic",w:"simultaneously",s:["at the same time","together","concurrently"],c:"同时",e:"The two events happened at the same time.",k:"at the same time",p:"ˌsɪmlˈteɪniəsli",pos:"adv.",d:"at exactly the same time",z:"w"},
{t:"academic",w:"alleviate",s:["reduce","ease","relieve"],c:"缓解",e:"The measures helped ease the housing shortage.",k:"ease",p:"əˈliːvieɪt",pos:"v.",d:"to make a problem less severe",z:"w"},
{t:"academic",w:"mitigate",s:["lessen","soften","reduce the impact of"],c:"减轻",e:"Good design can lessen the environmental impact.",k:"lessen",p:"ˈmɪtɪɡeɪt",pos:"v.",d:"to make something less harmful",z:"w"},
{t:"academic",w:"remedy",s:["solution","cure","fix"],c:"补救措施",e:"There is no easy solution to this problem.",k:"solution",p:"ˈremədi",pos:"n.",d:"a way of solving a problem",z:"w"},
{t:"academic",w:"eradicate",s:["eliminate","wipe out","remove"],c:"根除",e:"The goal is to wipe out the disease.",k:"wipe out",p:"ɪˈrædɪkeɪt",pos:"v.",d:"to completely destroy something",z:"w"},
{t:"academic",w:"curb",s:["restrict","control","limit"],c:"抑制",e:"New rules restrict the use of plastics.",k:"restrict",p:"kɜːb",pos:"v.",d:"to control or limit something",z:"w"},
{t:"academic",w:"resolve",s:["settle","solve","sort out"],c:"解决",e:"The dispute was finally settled.",k:"settled",p:"rɪˈzɒlv",pos:"v.",d:"to find a solution to a problem",z:"w"},
{t:"academic",w:"accessibility",s:["availability","convenience","ease of use"],c:"可获得性",e:"The availability of services varies by region.",k:"availability",p:"əkˌsesəˈbɪləti",pos:"n.",d:"how easy something is to reach or use",z:"w"},
{t:"academic",w:"affordability",s:["low cost","cheapness","value"],c:"可负担性",e:"Housing costs are the main barrier for young buyers.",k:"costs",p:"əˌfɔːdəˈbɪləti",pos:"n.",d:"the quality of being cheap enough to buy",z:"w"},
{t:"academic",w:"efficacy",s:["effectiveness","power","success"],c:"效力",e:"The effectiveness of the vaccine was proven.",k:"effectiveness",p:"ˈefɪkəsi",pos:"n.",d:"the ability to produce the desired result",z:"w"},
{t:"academic",w:"feasibility",s:["practicability","viability","possibility"],c:"可行性",e:"Engineers doubted the viability of the tunnel.",k:"viability",p:"ˌfiːzəˈbɪləti",pos:"n.",d:"whether something can be done",z:"w"},
{t:"academic",w:"longevity",s:["long life","durability","lifespan"],c:"长寿，持久",e:"The device is known for its durability.",k:"durability",p:"lɒnˈdʒevəti",pos:"n.",d:"the fact of lasting a long time",z:"w"},
{t:"academic",w:"prosperity",s:["wealth","success","affluence"],c:"繁荣",e:"Trade brought wealth to the region.",k:"wealth",p:"prɒˈsperəti",pos:"n.",d:"the state of being successful and rich",z:"w"},
{t:"academic",w:"disparity",s:["gap","difference","imbalance"],c:"差距",e:"The gap between regions is widening.",k:"gap",p:"dɪˈspærəti",pos:"n.",d:"a big difference between groups",z:"w"},
{t:"academic",w:"discrepancy",s:["inconsistency","difference","mismatch"],c:"不一致",e:"There is an inconsistency between the two reports.",k:"inconsistency",p:"dɪˈskrepənsi",pos:"n.",d:"a difference between things that should be the same",z:"w"},
{t:"academic",w:"prevalence",s:["commonness","widespread occurrence","frequency"],c:"普遍性",e:"The frequency of the disease is rising.",k:"frequency",p:"ˈprevələns",pos:"n.",d:"how common something is",z:"w"},
{t:"academic",w:"propensity",s:["tendency","inclination","likelihood"],c:"倾向",e:"He has a tendency to overstate the risks.",k:"tendency",p:"prəˈpensəti",pos:"n.",d:"a natural tendency to behave in a certain way",z:"w"},
{t:"academic",w:"reluctance",s:["unwillingness","hesitation","resistance"],c:"不情愿",e:"There was widespread unwillingness to change.",k:"unwillingness",p:"rɪˈlʌktəns",pos:"n.",d:"the feeling of not wanting to do something",z:"w"},
{t:"academic",w:"depict",s:["show","portray","illustrate"],c:"描绘",e:"The chart portrays a steady decline.",k:"portrays",p:"dɪˈpɪkt",pos:"v.",d:"to show or describe something",z:"w"},
{t:"academic",w:"demonstrate",s:["show","prove","reveal"],c:"表明，证明",e:"The results reveal a clear pattern.",k:"reveal",p:"ˈdemənstreɪt",pos:"v.",d:"to show clearly that something is true",z:"w"},
{t:"academic",w:"exhibit",s:["display","show","present"],c:"展示",e:"The data displays a downward trend.",k:"displays",p:"ɪɡˈzɪbɪt",pos:"v.",d:"to show a quality or feeling",z:"w"},
{t:"academic",w:"indicate",s:["suggest","point to","signal"],c:"表明",e:"The figures point to a recovery.",k:"point to",p:"ˈɪndɪkeɪt",pos:"v.",d:"to show that something is likely",z:"w"},
{t:"academic",w:"outline",s:["summarise","sketch","overview"],c:"概述",e:"The introduction summarises the main arguments.",k:"summarises",p:"ˈaʊtlaɪn",pos:"v.",d:"to describe the main points of something",z:"w"},
{t:"academic",w:"prevalent",s:["common","widespread","frequent"],c:"普遍的",e:"Air pollution is common in large cities.",k:"common",p:"ˈprevələnt",pos:"adj.",d:"existing in many places",z:"w"},
{t:"academic",w:"ubiquitous",s:["omnipresent","everywhere","universal"],c:"无处不在的",e:"Smartphones are everywhere these days.",k:"everywhere",p:"juːˈbɪkwɪtəs",pos:"adj.",d:"present everywhere",z:"w"},
{t:"academic",w:"pervasive",s:["widespread","prevalent","all-pervading"],c:"弥漫的，遍布的",e:"The influence of social media is all-pervading.",k:"all-pervading",p:"pəˈveɪsɪv",pos:"adj.",d:"spreading widely through everything",z:"w"},
{t:"academic",w:"acute",s:["severe","serious","intense"],c:"严重的，剧烈的",e:"The city faces a serious housing crisis.",k:"serious",p:"əˈkjuːt",pos:"adj.",d:"very serious or severe",z:"w"},
{t:"academic",w:"chronic",s:["long-lasting","persistent","continual"],c:"长期的",e:"The country suffers from persistent inflation.",k:"persistent",p:"ˈkrɒnɪk",pos:"adj.",d:"lasting for a long time",z:"w"},
{t:"academic",w:"profound",s:["deep","far-reaching","significant"],c:"深远的",e:"The internet had a deep effect on society.",k:"deep",p:"prəˈfaʊnd",pos:"adj.",d:"very great or intense",z:"w"},
{t:"academic",w:"subtle",s:["slight","delicate","fine"],c:"微妙的",e:"There is a delicate difference between the two words.",k:"delicate",p:"ˈsʌtl",pos:"adj.",d:"not obvious, hard to notice",z:"w"},
{t:"academic",w:"trivial",s:["unimportant","minor","insignificant"],c:"琐碎的",e:"The difference is unimportant in practice.",k:"unimportant",p:"ˈtrɪviəl",pos:"adj.",d:"of little value or importance",z:"w"},
{t:"academic",w:"negligible",s:["tiny","insignificant","minimal"],c:"微不足道的",e:"The change had a minimal effect.",k:"minimal",p:"ˈneɡlɪdʒəbl",pos:"adj.",d:"too small to matter",z:"w"},
{t:"academic",w:"drastic",s:["extreme","radical","severe"],c:"剧烈的",e:"The company took extreme measures to cut costs.",k:"extreme",p:"ˈdræstɪk",pos:"adj.",d:"very great and sudden",z:"w"},
{t:"academic",w:"dramatic",s:["striking","considerable","sudden"],c:"急剧的，引人注目的",e:"There was a striking rise in prices.",k:"striking",p:"drəˈmætɪk",pos:"adj.",d:"sudden and very noticeable",z:"w"},
{t:"academic",w:"exponential",s:["rapid","accelerating","explosive"],c:"指数级的，飞速的",e:"The city experienced rapid population growth.",k:"rapid",p:"ˌekspəˈnenʃl",pos:"adj.",d:"increasing very quickly",z:"w"},
{t:"academic",w:"drastically",s:["dramatically","sharply","radically"],c:"急剧地",e:"Costs rose dramatically last year.",k:"dramatically",p:"ˈdræstɪkli",pos:"adv.",d:"in a sudden and extreme way",z:"w"},
{t:"academic",w:"substantially",s:["considerably","significantly","greatly"],c:"大幅度地",e:"Sales increased considerably in 2023.",k:"considerably",p:"səbˈstænʃəli",pos:"adv.",d:"to a large degree",z:"w"},
{t:"academic",w:"marginally",s:["slightly","barely","a little"],c:"轻微地",e:"Results improved only slightly.",k:"slightly",p:"ˈmɑːdʒɪnəli",pos:"adv.",d:"to a small degree",z:"w"},
{t:"academic",w:"moderately",s:["somewhat","fairly","to a limited extent"],c:"适度地",e:"The figure rose somewhat over the decade.",k:"somewhat",p:"ˈmɒdərətli",pos:"adv.",d:"to a medium degree",z:"w"},
{t:"academic",w:"steeply",s:["sharply","rapidly","abruptly"],c:"急剧地",e:"Unemployment fell sharply in spring.",k:"sharply",p:"ˈstiːpli",pos:"adv.",d:"at a sharp angle, quickly",z:"w"},
{t:"academic",w:"gradually",s:["steadily","slowly","progressively"],c:"逐渐地",e:"The climate changed progressively over decades.",k:"progressively",p:"ˈɡrædʒuəli",pos:"adv.",d:"slowly over a period of time",z:"w"},
{t:"academic",w:"markedly",s:["noticeably","clearly","significantly"],c:"显著地",e:"Prices differ noticeably between regions.",k:"noticeably",p:"ˈmɑːkɪdli",pos:"adv.",d:"in a clear and noticeable way",z:"w"},
{t:"academic",w:"overwhelmingly",s:["predominantly","mainly","vastly"],c:"压倒性地",e:"Residents were overwhelmingly in favour.",k:"overwhelmingly",p:"ˌəʊvəˈwelmɪŋli",pos:"adv.",d:"by a very large amount",z:"w"},
{t:"academic",w:"predominantly",s:["mainly","mostly","chiefly"],c:"主要地",e:"The region is mainly agricultural.",k:"mainly",p:"prɪˈdɒmɪnəntli",pos:"adv.",d:"mostly, in the main",z:"w"},
{t:"academic",w:"exceptionally",s:["remarkably","extremely","unusually"],c:"异常地",e:"The results were remarkably consistent.",k:"remarkably",p:"ɪkˈsepʃənəli",pos:"adv.",d:"to a much greater degree than usual",z:"w"},
{t:"core",w:"whilst",s:["while","whereas","although"],c:"然而，尽管",e:"While some disagree, most support the plan.",k:"while",p:"waɪlst",pos:"conj.",d:"during the time that, or although",z:"w"},
{t:"core",w:"thereafter",s:["afterwards","from then on","later"],c:"此后",e:"The policy changed from then on.",k:"from then on",p:"ˌðeərˈɑːftə",pos:"adv.",d:"after a particular time",z:"w"},
{t:"core",w:"likewise",s:["similarly","in the same way","equally"],c:"同样地",e:"Similarly, costs rose in the north.",k:"similarly",p:"ˈlaɪkwaɪz",pos:"adv.",d:"in a similar way",z:"w"},
{t:"core",w:"notwithstanding",s:["despite","in spite of","regardless of"],c:"尽管",e:"Despite the risks, the project went ahead.",k:"despite",p:"ˌnɒtwɪθˈstændɪŋ",pos:"prep.",d:"in spite of",z:"w"},
{t:"core",w:"conducive",s:["favourable","helpful","beneficial"],c:"有助于…的",e:"Quiet surroundings are favourable to study.",k:"favourable",p:"kənˈdjuːsɪv",pos:"adj.",d:"making it easy for something to happen",z:"w"},
{t:"core",w:"detrimental",s:["harmful","damaging","adverse"],c:"有害的",e:"Smoking is harmful to health.",k:"harmful",p:"ˌdetrɪˈmentl",pos:"adj.",d:"causing harm or damage",z:"w"},
{t:"core",w:"deleterious",s:["harmful","damaging","injurious"],c:"有害的",e:"The drug has injurious side effects.",k:"injurious",p:"ˌdelɪˈtɪəriəs",pos:"adj.",d:"causing harm",z:"w"},
{t:"core",w:"beneficial",s:["advantageous","helpful","positive"],c:"有益的",e:"Exercise is helpful for mental health.",k:"helpful",p:"ˌbenɪˈfɪʃl",pos:"adj.",d:"having a good effect",z:"w"},
{t:"core",w:"detract",s:["reduce","diminish","take away from"],c:"减损",e:"Crowds take away from the experience.",k:"take away from",p:"dɪˈtrækt",pos:"v.",d:"to make something seem less good",z:"w"},
{t:"core",w:"prerequisite",s:["requirement","precondition","necessary condition"],c:"前提条件",e:"A degree is a requirement for the post.",k:"requirement",p:"ˌpriːˈrekwəzɪt",pos:"n.",d:"something that must exist before something else",z:"w"},
{t:"core",w:"constraint",s:["restriction","limitation","bound"],c:"限制",e:"Budget restrictions limited the options.",k:"restrictions",p:"kənˈstreɪnt",pos:"n.",d:"a limitation on what is possible",z:"w"},
{t:"core",w:"implication",s:["consequence","effect","significance"],c:"影响，含意",e:"The findings have serious consequences for policy.",k:"consequences",p:"ˌɪmplɪˈkeɪʃn",pos:"n.",d:"a possible effect of an action",z:"w"},
{t:"core",w:"notion",s:["idea","concept","belief"],c:"观念",e:"The idea of remote work is now common.",k:"idea",p:"ˈnəʊʃn",pos:"n.",d:"an idea or belief",z:"w"},
{t:"core",w:"assumption",s:["supposition","belief","premise"],c:"假设",e:"The plan rests on a false premise.",k:"premise",p:"əˈsʌmpʃn",pos:"n.",d:"something accepted as true without proof",z:"w"},
{t:"core",w:"compelling",s:["convincing","persuasive","powerful"],c:"有说服力的",e:"The evidence is convincing.",k:"convincing",p:"kəmˈpelɪŋ",pos:"adj.",d:"strong enough to persuade people",z:"w"},
{t:"core",w:"coherent",s:["logical","consistent","organised"],c:"连贯的",e:"The essay needs a more logical structure.",k:"logical",p:"kəʊˈhɪərənt",pos:"adj.",d:"clear and well organised",z:"w"},
{t:"core",w:"plausible",s:["credible","believable","reasonable"],c:"貌似合理的",e:"Her explanation is quite believable.",k:"believable",p:"ˈplɔːzəbl",pos:"adj.",d:"seeming reasonable or likely to be true",z:"w"},
{t:"core",w:"ambiguous",s:["unclear","vague","equivocal"],c:"模棱两可的",e:"The wording is vague and open to debate.",k:"vague",p:"æmˈbɪɡjuəs",pos:"adj.",d:"having more than one possible meaning",z:"w"},
{t:"core",w:"explicit",s:["clear","direct","specific"],c:"明确的",e:"The instructions are clear and simple.",k:"clear",p:"ɪkˈsplɪsɪt",pos:"adj.",d:"stated clearly and directly",z:"w"},
{t:"core",w:"intrinsic",s:["inherent","essential","innate"],c:"内在的",e:"Learning has an inherent value.",k:"inherent",p:"ɪnˈtrɪnsɪk",pos:"adj.",d:"belonging naturally to something",z:"w"},
{t:"core",w:"viable",s:["workable","feasible","practical"],c:"可行的",e:"The plan is technically workable.",k:"workable",p:"ˈvaɪəbl",pos:"adj.",d:"able to work successfully",z:"w"},
{t:"core",w:"stagnant",s:["static","unchanging","flat"],c:"停滞的",e:"Wages have remained static for years.",k:"static",p:"ˈstæɡnənt",pos:"adj.",d:"not growing or developing",z:"w"},
{t:"core",w:"attain",s:["achieve","reach","accomplish"],c:"达到，获得",e:"Few students achieve top grades.",k:"achieve",p:"əˈteɪn",pos:"v.",d:"to succeed in reaching a goal",z:"w"},
{t:"core",w:"deteriorate",s:["worsen","decline","degenerate"],c:"恶化",e:"Air quality worsened in summer.",k:"worsened",p:"dɪˈtɪəriəreɪt",pos:"v.",d:"to become worse",z:"w"},
{t:"core",w:"foster",s:["encourage","promote","nurture"],c:"促进，培养",e:"Schools should encourage creativity.",k:"encourage",p:"ˈfɒstə",pos:"v.",d:"to help something develop",z:"w"},
{t:"core",w:"undermine",s:["weaken","erode","damage"],c:"削弱",e:"Inflation weakens household savings.",k:"weakens",p:"ˌʌndəˈmaɪn",pos:"v.",d:"to gradually make something weaker",z:"w"},
{t:"core",w:"scrutinise",s:["examine closely","inspect","analyse"],c:"仔细审查",e:"The claims were examined closely.",k:"examined closely",p:"ˈskruːtənaɪz",pos:"v.",d:"to examine something very carefully",z:"w"},
{t:"core",w:"jeopardise",s:["endanger","threaten","risk"],c:"危及",e:"The strike threatens the whole project.",k:"threatens",p:"ˈdʒepədaɪz",pos:"v.",d:"to put something in danger",z:"w"},
{t:"core",w:"incur",s:["suffer","face","take on"],c:"招致，蒙受",e:"The company faced heavy losses.",k:"faced",p:"ɪnˈkɜː",pos:"v.",d:"to experience something unpleasant",z:"w"},
{t:"core",w:"retain",s:["keep","hold","preserve"],c:"保留",e:"The city keeps its historic character.",k:"keeps",p:"rɪˈteɪn",pos:"v.",d:"to continue to have something",z:"w"},
{t:"core",w:"obtain",s:["get","acquire","gain"],c:"获得",e:"Applicants must acquire a work permit.",k:"acquire",p:"əbˈteɪn",pos:"v.",d:"to get something",z:"w"},];
module.exports = { V5A };