'use strict';
const V5B = [
{t:"travel",w:"itinerary",s:["plan","schedule","route"],c:"行程安排",e:"The travel agency sent us a detailed plan.",k:"plan",p:"aɪˈtɪnərəri",pos:"n.",d:"a plan of a journey",z:"l"},
{t:"travel",w:"excursion",s:["day trip","outing","tour"],c:"短途旅行",e:"We booked a day trip to the lake.",k:"day trip",p:"ɪkˈskɜːʃn",pos:"n.",d:"a short journey for pleasure",z:"l"},
{t:"travel",w:"souvenir",s:["memento","keepsake","reminder"],c:"纪念品",e:"I bought a small keepsake from the market.",k:"keepsake",p:"ˌsuːvəˈnɪə",pos:"n.",d:"an object kept as a reminder of a place",z:"l"},
{t:"travel",w:"baggage",s:["luggage","bags","suitcases"],c:"行李",e:"Please collect your bags at gate three.",k:"bags",p:"ˈbæɡɪdʒ",pos:"n.",d:"suitcases and bags for travelling",z:"l"},
{t:"travel",w:"carry-on",s:["hand luggage","cabin bag","small bag"],c:"随身行李",e:"You may take one small bag on board.",k:"small bag",p:"ˈkæri ɒn",pos:"n.",d:"a small bag you take onto a plane",z:"l"},
{t:"travel",w:"immigration",s:["border control","passport control","entry checks"],c:"入境检查",e:"We waited an hour at passport control.",k:"passport control",p:"ˌɪmɪˈɡreɪʃn",pos:"n.",d:"the place where officials check people entering a country",z:"l"},
{t:"travel",w:"quarantine",s:["isolation","seclusion","detention"],c:"隔离",e:"Travellers faced fourteen days of isolation.",k:"isolation",p:"ˈkwɒrəntiːn",pos:"n.",d:"a period when a person stays away from others for health reasons",z:"l"},
{t:"travel",w:"currency exchange",s:["money exchange","bureau de change","foreign exchange"],c:"货币兑换",e:"The rate at the money exchange was poor.",k:"money exchange",p:"ˈkʌrənsi ɪksˈtʃeɪndʒ",pos:"n.",d:"a place or service for changing money",z:"l"},
{t:"travel",w:"package tour",s:["all-inclusive trip","organised holiday","tour package"],c:"跟团游",e:"We booked an organised holiday to Crete.",k:"organised holiday",p:"ˈpækɪdʒ tʊə",pos:"n.",d:"a holiday sold with travel and accommodation together",z:"l"},
{t:"travel",w:"self-catering",s:["no meals included","self-service accommodation","cook your own"],c:"自炊的",e:"The villa is no meals included, so we cook ourselves.",k:"no meals included",p:"ˌself ˈkeɪtərɪŋ",pos:"adj.",d:"a place to stay where you cook your own food",z:"l"},
{t:"travel",w:"half board",s:["breakfast and dinner","two meals a day"],c:"半食宿",e:"The price includes breakfast and dinner.",k:"breakfast and dinner",p:"hɑːf bɔːd",pos:"n.",d:"a hotel deal with breakfast and dinner",z:"l"},
{t:"travel",w:"en suite",s:["attached bathroom","private bathroom"],c:"带独立卫浴的",e:"Every room has an attached bathroom.",k:"attached bathroom",p:"ˌɒn ˈswiːt",pos:"adj.",d:"a bedroom with its own bathroom",z:"l"},
{t:"travel",w:"concierge",s:["hotel assistant","porter","front desk helper"],c:"礼宾员",e:"The hotel assistant arranged our taxi.",k:"hotel assistant",p:"kɒnˈsjeəʒ",pos:"n.",d:"a hotel worker who helps guests",z:"l"},
{t:"travel",w:"shuttle",s:["shuttle bus","transfer bus","courtesy bus"],c:"班车",e:"A courtesy bus runs every hour.",k:"courtesy bus",p:"ˈʃʌtl",pos:"n.",d:"a bus that travels regularly between two places",z:"l"},
{t:"travel",w:"coach",s:["long-distance bus","motor coach"],c:"长途客车",e:"We took a long-distance bus to the coast.",k:"long-distance bus",p:"kəʊtʃ",pos:"n.",d:"a comfortable bus for long journeys",z:"l"},
{t:"travel",w:"ferry",s:["boat","ship","crossing"],c:"渡轮",e:"The crossing takes ninety minutes.",k:"crossing",p:"ˈferi",pos:"n.",d:"a boat that carries people across water",z:"l"},
{t:"travel",w:"tram",s:["streetcar","light rail"],c:"有轨电车",e:"The streetcar stops near the museum.",k:"streetcar",p:"træm",pos:"n.",d:"a vehicle that runs on rails in a city",z:"l"},
{t:"travel",w:"metro",s:["underground","subway","tube"],c:"地铁",e:"Take the underground to the city centre.",k:"underground",p:"ˈmetrəʊ",pos:"n.",d:"an underground railway system",z:"l"},
{t:"travel",w:"rush hour",s:["peak time","busy period"],c:"高峰时段",e:"Avoid the train during the busy period.",k:"busy period",p:"ˈrʌʃ aʊə",pos:"n.",d:"the time when traffic is heaviest",z:"l"},
{t:"travel",w:"off-peak",s:["quiet time","non-rush hour"],c:"非高峰的",e:"Tickets are cheaper in the quiet time.",k:"quiet time",p:"ˌɒf ˈpiːk",pos:"adj.",d:"at a time when there is less demand",z:"l"},
{t:"travel",w:"one-way",s:["single","not return"],c:"单程的",e:"A single ticket to Oxford costs twenty pounds.",k:"single",p:"ˌwʌn ˈweɪ",pos:"adj.",d:"a ticket for travel in one direction only",z:"l"},
{t:"travel",w:"return ticket",s:["round trip","two-way ticket"],c:"往返票",e:"A round trip to the airport is cheaper.",k:"round trip",p:"rɪˈtɜːn ˈtɪkɪt",pos:"n.",d:"a ticket for going and coming back",z:"l"},
{t:"travel",w:"carriage",s:["train car","coach","compartment"],c:"车厢",e:"The train car is almost empty.",k:"train car",p:"ˈkærɪdʒ",pos:"n.",d:"one section of a train",z:"l"},
{t:"travel",w:"sleeper",s:["sleeping car","berth","overnight train"],c:"卧铺",e:"We booked a berth on the night train.",k:"berth",p:"ˈsliːpə",pos:"n.",d:"a bed on a train",z:"l"},
{t:"travel",w:"reservation",s:["booking","arrangement","prior booking"],c:"预订",e:"Your booking is confirmed for Friday.",k:"booking",p:"ˌrezəˈveɪʃn",pos:"n.",d:"an arrangement to have something kept for you",z:"l"},
{t:"travel",w:"luggage locker",s:["storage locker","baggage locker"],c:"行李寄存柜",e:"Put your case in a storage locker.",k:"storage locker",p:"ˈlʌɡɪdʒ ˈlɒkə",pos:"n.",d:"a cupboard where you can leave luggage",z:"l"},
{t:"travel",w:"departure lounge",s:["waiting area","departure hall"],c:"候机厅",e:"We waited in the departure hall.",k:"departure hall",p:"dɪˈpɑːtʃə laʊndʒ",pos:"n.",d:"the area at an airport where passengers wait",z:"l"},
{t:"travel",w:"check-in desk",s:["registration counter","front desk"],c:"值机柜台",e:"Go to the registration counter first.",k:"registration counter",p:"ˈtʃek ɪn desk",pos:"n.",d:"the place where you show your ticket",z:"l"},
{t:"travel",w:"gate",s:["boarding gate","exit","departure gate"],c:"登机口",e:"Board at departure gate twelve.",k:"departure gate",p:"ɡeɪt",pos:"n.",d:"the place where passengers board a plane",z:"l"},
{t:"travel",w:"turbulence",s:["rough air","bumpy flight"],c:"气流颠簸",e:"We hit rough air over the ocean.",k:"rough air",p:"ˈtɜːbjələns",pos:"n.",d:"sudden irregular movement of air",z:"l"},
{t:"travel",w:"connecting flight",s:["transfer flight","layover flight"],c:"转机航班",e:"Our transfer flight leaves at noon.",k:"transfer flight",p:"kəˈnektɪŋ flaɪt",pos:"n.",d:"a second flight taken to reach a destination",z:"l"},
{t:"travel",w:"duty-free",s:["tax-free","no tax"],c:"免税的",e:"Perfume is tax-free at the airport.",k:"tax-free",p:"ˌdjuːti ˈfriː",pos:"adj.",d:"sold without tax at airports",z:"l"},
{t:"travel",w:"hire car",s:["rental car","car rental","rented car"],c:"租车",e:"We picked up a rental car at the airport.",k:"rental car",p:"ˈhaɪə kɑː",pos:"n.",d:"a car you pay to use for a period",z:"l"},
{t:"travel",w:"campsite",s:["camping ground","campground"],c:"露营地",e:"The camping ground has hot showers.",k:"camping ground",p:"ˈkæmpsaɪt",pos:"n.",d:"a place where people camp",z:"l"},
{t:"travel",w:"youth hostel",s:["budget hostel","backpacker hostel"],c:"青年旅舍",e:"We stayed at a budget hostel near the station.",k:"budget hostel",p:"juːθ ˈhɒstl",pos:"n.",d:"cheap accommodation for travellers",z:"l"},
{t:"travel",w:"landmark",s:["famous site","monument","attraction"],c:"地标",e:"The tower is the city famous monument.",k:"famous monument",p:"ˈlændmɑːk",pos:"n.",d:"an easily recognised building or place",z:"l"},
{t:"travel",w:"scenic",s:["picturesque","beautiful","panoramic"],c:"风景优美的",e:"The drive along the coast is picturesque.",k:"picturesque",p:"ˈsiːnɪk",pos:"adj.",d:"having beautiful views",z:"l"},
{t:"travel",w:"guided tour",s:["organised visit","tour with a guide"],c:"有导游的游览",e:"We joined an organised visit of the castle.",k:"organised visit",p:"ˈɡaɪdɪd tʊə",pos:"n.",d:"a visit led by a guide",z:"l"},
{t:"travel",w:"travel insurance",s:["trip cover","holiday protection"],c:"旅行保险",e:"Trip cover is essential for long journeys.",k:"trip cover",p:"ˈtrævl ɪnˈʃʊərəns",pos:"n.",d:"insurance that covers problems during a trip",z:"l"},
{t:"food",w:"ingredient",s:["component","element","part"],c:"原料，配料",e:"Mix all the components in a large bowl.",k:"components",p:"ɪnˈɡriːdiənt",pos:"n.",d:"one of the foods used to make a dish",z:"l"},
{t:"food",w:"recipe",s:["cooking instructions","method","formula"],c:"食谱",e:"Follow the cooking instructions carefully.",k:"cooking instructions",p:"ˈresəpi",pos:"n.",d:"instructions for cooking a dish",z:"l"},
{t:"food",w:"flavour",s:["taste","savour","zest"],c:"味道",e:"This soup has a rich taste.",k:"taste",p:"ˈfleɪvə",pos:"n.",d:"the particular taste of food",z:"l"},
{t:"food",w:"seasoning",s:["spice","flavouring","condiment"],c:"调味料",e:"Add a little flavouring to the meat.",k:"flavouring",p:"ˈsiːznɪŋ",pos:"n.",d:"salt, pepper or herbs added to food",z:"l"},
{t:"food",w:"appetiser",s:["starter","first course","opening dish"],c:"开胃菜",e:"We ordered a starter to share.",k:"starter",p:"ˈæpɪtaɪzə",pos:"n.",d:"a small dish before the main meal",z:"l"},
{t:"food",w:"portion",s:["serving","helping","amount"],c:"一份",e:"The servings here are very generous.",k:"servings",p:"ˈpɔːʃn",pos:"n.",d:"the amount of food for one person",z:"l"},
{t:"food",w:"buffet",s:["self-service meal","cold spread"],c:"自助餐",e:"Breakfast is a self-service meal.",k:"self-service meal",p:"ˈbʊfeɪ",pos:"n.",d:"a meal where you serve yourself",z:"l"},
{t:"food",w:"brunch",s:["late breakfast","mid-morning meal"],c:"早午餐",e:"We had a mid-morning meal at the cafe.",k:"mid-morning meal",p:"brʌntʃ",pos:"n.",d:"a meal between breakfast and lunch",z:"l"},
{t:"food",w:"vegetarian",s:["meat-free","plant-based"],c:"素食的",e:"The menu has several meat-free options.",k:"meat-free",p:"ˌvedʒəˈteəriən",pos:"adj.",d:"not eating meat",z:"l"},
{t:"food",w:"vegan",s:["plant-only","no animal products"],c:"纯素的",e:"This cake contains no animal products.",k:"no animal products",p:"ˈviːɡən",pos:"adj.",d:"not using any animal products",z:"l"},
{t:"food",w:"gluten-free",s:["no wheat","without gluten"],c:"无麸质的",e:"They offer bread without gluten.",k:"without gluten",p:"ˌɡluːtən ˈfriː",pos:"adj.",d:"containing no gluten",z:"l"},
{t:"food",w:"takeaway",s:["food to go","carry-out","delivery meal"],c:"外卖",e:"We ordered food to go from the Chinese place.",k:"food to go",p:"ˈteɪkəweɪ",pos:"n.",d:"cooked food bought to eat elsewhere",z:"l"},
{t:"food",w:"expiry date",s:["use-by date","sell-by date","best before date"],c:"保质期",e:"Check the use-by date on the milk.",k:"use-by date",p:"ɪkˈspaɪəri deɪt",pos:"n.",d:"the date when food is no longer safe to eat",z:"l"},
{t:"food",w:"utensil",s:["kitchen tool","implement","tool"],c:"厨具",e:"You need a sharp kitchen tool for this.",k:"kitchen tool",p:"juːˈtensl",pos:"n.",d:"a tool used for cooking or eating",z:"l"},
{t:"food",w:"kettle",s:["boiler","hot water jug"],c:"水壶",e:"Fill the hot water jug and switch it on.",k:"hot water jug",p:"ˈketl",pos:"n.",d:"a container for boiling water",z:"l"},
{t:"food",w:"microwave",s:["microwave oven","quick cooker"],c:"微波炉",e:"Heat the soup in the microwave oven.",k:"microwave oven",p:"ˈmaɪkrəweɪv",pos:"n.",d:"an oven that cooks food very quickly",z:"l"},
{t:"food",w:"carton",s:["box","pack","container"],c:"纸盒",e:"Buy a box of orange juice.",k:"box",p:"ˈkɑːtn",pos:"n.",d:"a cardboard container for liquids",z:"l"},
{t:"food",w:"barcode",s:["code","strip code","scan code"],c:"条形码",e:"The cashier scanned the code on the label.",k:"code",p:"ˈbɑːkəʊd",pos:"n.",d:"a pattern of lines that a machine can read",z:"l"},
{t:"food",w:"garnish",s:["decoration","topping","trimming"],c:"装饰菜",e:"Add a topping of fresh herbs.",k:"topping",p:"ˈɡɑːnɪʃ",pos:"n.",d:"a small amount of food used to decorate a dish",z:"l"},
{t:"food",w:"complimentary",s:["free","on the house","no charge"],c:"免费赠送的",e:"The hotel offers free breakfast.",k:"free",p:"ˌkɒmplɪˈmentri",pos:"adj.",d:"given free of charge",z:"l"},
{t:"food",w:"service charge",s:["tip","gratuity","service fee"],c:"服务费",e:"A gratuity of ten percent was added.",k:"gratuity",p:"ˈsɜːvɪs tʃɑːdʒ",pos:"n.",d:"an amount added to a bill for service",z:"l"},
{t:"travel",w:"congestion charge",s:["traffic fee","city toll","road pricing"],c:"拥堵费",e:"Drivers must pay a city toll to enter.",k:"city toll",p:"kənˈdʒestʃən tʃɑːdʒ",pos:"n.",d:"a fee for driving in a busy city area",z:"l"},
{t:"travel",w:"layover",s:["stopover","waiting time","connection time"],c:"中转停留",e:"We had a short stopover in Dubai.",k:"stopover",p:"ˈleɪəʊvə",pos:"n.",d:"a period of waiting between flights",z:"l"},
{t:"travel",w:"punctual",s:["on time","prompt","timely"],c:"准时的",e:"The train is always on time.",k:"on time",p:"ˈpʌŋktʃuəl",pos:"adj.",d:"arriving at the expected time",z:"l"},
{t:"travel",w:"detour",s:["diversion","roundabout route","alternative route"],c:"绕行",e:"Roadworks forced us to take a diversion.",k:"diversion",p:"ˈdiːtʊə",pos:"n.",d:"a longer route taken to avoid something",z:"l"},
{t:"travel",w:"pedestrian crossing",s:["zebra crossing","crosswalk","safe crossing"],c:"人行横道",e:"Use the zebra crossing to reach the shops.",k:"zebra crossing",p:"pəˈdestriən ˈkrɒsɪŋ",pos:"n.",d:"a place where people can cross a road safely",z:"l"},
{t:"travel",w:"car park",s:["parking lot","parking area","garage"],c:"停车场",e:"The parking area is behind the station.",k:"parking area",p:"ˈkɑː pɑːk",pos:"n.",d:"a place where cars are parked",z:"l"},
{t:"travel",w:"speed limit",s:["maximum speed","legal speed"],c:"限速",e:"The maximum speed is thirty miles an hour.",k:"maximum speed",p:"ˈspiːd ˌlɪmɪt",pos:"n.",d:"the fastest speed allowed by law",z:"l"},
{t:"travel",w:"traffic jam",s:["gridlock","tailback","hold-up"],c:"交通堵塞",e:"We were stuck in gridlock for an hour.",k:"gridlock",p:"ˈtræfɪk dʒæm",pos:"n.",d:"a long line of cars moving slowly",z:"l"},
{t:"travel",w:"motorway",s:["highway","expressway","freeway"],c:"高速公路",e:"The expressway links the two cities.",k:"expressway",p:"ˈməʊtəweɪ",pos:"n.",d:"a wide fast road for long distances",z:"l"},
{t:"travel",w:"cycle lane",s:["bike lane","cycle path","bicycle lane"],c:"自行车道",e:"Use the bike lane when cycling downtown.",k:"bike lane",p:"ˈsaɪkl leɪn",pos:"n.",d:"a part of the road for bicycles",z:"l"},
];
module.exports = { V5B };