'use strict';
const V5C = [
{t:"health",w:"allergy",s:["sensitivity","reaction","intolerance"],c:"过敏",e:"She has a sensitivity to peanuts.",k:"sensitivity",p:"ˈælədʒi",pos:"n.",d:"a bad reaction of the body to certain foods or substances",z:"l"},
{t:"health",w:"allergic",s:["sensitive","intolerant"],c:"过敏的",e:"He is sensitive to dust.",k:"sensitive",p:"əˈlɜːdʒɪk",pos:"adj.",d:"having a bad reaction to something",z:"l"},
{t:"health",w:"medication",s:["medicine","drugs","treatment"],c:"药物",e:"Take the medicine after meals.",k:"medicine",p:"ˌmedɪˈkeɪʃn",pos:"n.",d:"drugs used to treat an illness",z:"l"},
{t:"health",w:"dose",s:["amount","quantity","measure"],c:"剂量",e:"Take the correct amount twice a day.",k:"amount",p:"dəʊs",pos:"n.",d:"the amount of a medicine to take",z:"l"},
{t:"health",w:"tablet",s:["pill","caplet","lozenge"],c:"药片",e:"Take one pill in the morning.",k:"pill",p:"ˈtæblət",pos:"n.",d:"a small solid medicine",z:"l"},
{t:"health",w:"capsule",s:["gel cap","pill","medicine"],c:"胶囊",e:"The gel cap dissolves quickly.",k:"gel cap",p:"ˈkæpsjuːl",pos:"n.",d:"a small container of medicine",z:"l"},
{t:"health",w:"injection",s:["jab","shot","vaccine dose"],c:"注射",e:"You will need a jab before travelling.",k:"jab",p:"ɪnˈdʒekʃn",pos:"n.",d:"medicine given through a needle",z:"l"},
{t:"health",w:"specialist",s:["expert","consultant","professional"],c:"专科医生",e:"The consultant will see you on Monday.",k:"consultant",p:"ˈspeʃəlɪst",pos:"n.",d:"a doctor who treats one type of illness",z:"l"},
{t:"health",w:"diagnosis",s:["identification","assessment","finding"],c:"诊断",e:"The doctor made a correct identification of the illness.",k:"identification",p:"ˌdaɪəɡˈnəʊsɪs",pos:"n.",d:"the process of identifying an illness",z:"l"},
{t:"health",w:"therapy",s:["treatment","care","rehabilitation"],c:"治疗",e:"She needs six weeks of rehabilitation.",k:"rehabilitation",p:"ˈθerəpi",pos:"n.",d:"treatment to help someone recover",z:"l"},
{t:"health",w:"physiotherapy",s:["physical therapy","exercise treatment"],c:"物理治疗",e:"Physical therapy helped his knee recover.",k:"physical therapy",p:"ˌfɪziəʊˈθerəpi",pos:"n.",d:"treatment using exercise and movement",z:"l"},
{t:"health",w:"counselling",s:["therapy sessions","guidance","support"],c:"心理咨询",e:"She attended therapy sessions for stress.",k:"therapy sessions",p:"ˈkaʊnsəlɪŋ",pos:"n.",d:"professional help for emotional problems",z:"l"},
{t:"health",w:"nutrition",s:["nourishment","food value","diet"],c:"营养",e:"Good nourishment is vital for children.",k:"nourishment",p:"njuˈtrɪʃn",pos:"n.",d:"the food you eat and how it affects health",z:"l"},
{t:"health",w:"intake",s:["consumption","amount taken","use"],c:"摄入量",e:"Cut down your consumption of sugar.",k:"consumption",p:"ˈɪnteɪk",pos:"n.",d:"the amount of something you take in",z:"l"},
{t:"health",w:"deficiency",s:["shortage","lack","insufficiency"],c:"缺乏",e:"A lack of vitamin D affects bones.",k:"lack",p:"dɪˈfɪʃnsi",pos:"n.",d:"not having enough of something",z:"l"},
{t:"health",w:"cholesterol",s:["blood fat","fatty substance"],c:"胆固醇",e:"High blood fat increases heart risk.",k:"blood fat",p:"kəˈlestərɒl",pos:"n.",d:"a fatty substance in the blood",z:"l"},
{t:"health",w:"screening",s:["check","test","examination"],c:"筛查",e:"Free checks are offered every year.",k:"checks",p:"ˈskriːnɪŋ",pos:"n.",d:"testing people to find disease early",z:"l"},
{t:"health",w:"immunity",s:["resistance","protection","defence"],c:"免疫力",e:"Vaccination builds resistance to the virus.",k:"resistance",p:"ɪˈmjuːnəti",pos:"n.",d:"the ability to resist infection",z:"l"},
{t:"health",w:"hygiene",s:["cleanliness","sanitation","clean habits"],c:"卫生",e:"Good cleanliness prevents infection.",k:"cleanliness",p:"ˈhaɪdʒiːn",pos:"n.",d:"keeping yourself clean to stay healthy",z:"l"},
{t:"health",w:"outbreak",s:["epidemic","flare-up","sudden spread"],c:"爆发",e:"The epidemic spread quickly in winter.",k:"epidemic",p:"ˈaʊtbreɪk",pos:"n.",d:"a sudden start of a disease",z:"l"},
{t:"health",w:"pandemic",s:["global epidemic","worldwide outbreak"],c:"大流行病",e:"The worldwide outbreak closed the borders.",k:"worldwide outbreak",p:"pænˈdemɪk",pos:"n.",d:"a disease affecting the whole world",z:"l"},
{t:"health",w:"contagious",s:["infectious","spreading","catching"],c:"传染性的",e:"The flu is highly infectious.",k:"infectious",p:"kənˈteɪdʒəs",pos:"adj.",d:"able to spread from person to person",z:"l"},
{t:"health",w:"bacteria",s:["germs","microbes","micro-organisms"],c:"细菌",e:"Wash your hands to remove germs.",k:"germs",p:"bækˈtɪəriə",pos:"n.",d:"tiny living things that can cause disease",z:"l"},
{t:"health",w:"virus",s:["germ","infection","pathogen"],c:"病毒",e:"A new germ is spreading in the city.",k:"germ",p:"ˈvaɪrəs",pos:"n.",d:"a very small thing that causes disease",z:"l"},
{t:"health",w:"dosage",s:["dose","amount","quantity"],c:"剂量",e:"The correct dose depends on your age.",k:"dose",p:"ˈdəʊsɪdʒ",pos:"n.",d:"the amount of medicine to take",z:"l"},
{t:"health",w:"X-ray",s:["scan","radiograph","image"],c:"X光检查",e:"The radiograph showed a broken bone.",k:"radiograph",p:"ˈeks reɪ",pos:"n.",d:"a picture of the inside of the body",z:"l"},
{t:"health",w:"anaesthetic",s:["painkiller","numbing drug","sedative"],c:"麻醉剂",e:"The numbing drug wore off quickly.",k:"numbing drug",p:"ˈænəsθetɪk",pos:"n.",d:"a drug that stops you feeling pain",z:"l"},
{t:"health",w:"fracture",s:["broken bone","crack","break"],c:"骨折",e:"The broken bone will heal in weeks.",k:"broken bone",p:"ˈfræktʃə",pos:"n.",d:"a break in a bone",z:"l"},
{t:"health",w:"sprain",s:["twist","strain","injury"],c:"扭伤",e:"He twisted his ankle playing football.",k:"twisted",p:"spreɪn",pos:"n.",d:"an injury to a joint",z:"l"},
{t:"health",w:"asthma",s:["breathing condition","lung disease"],c:"哮喘",e:"Her lung condition is triggered by pollen.",k:"lung condition",p:"ˈæsmə",pos:"n.",d:"a condition that makes breathing difficult",z:"l"},
{t:"health",w:"diabetes",s:["blood sugar disease","metabolic disorder"],c:"糖尿病",e:"The blood sugar disease needs daily care.",k:"blood sugar disease",p:"ˌdaɪəˈbiːtiːz",pos:"n.",d:"a disease involving too much sugar in the blood",z:"l"},
{t:"health",w:"malnutrition",s:["undernutrition","poor diet","starvation"],c:"营养不良",e:"Undernutrition affects children in poor areas.",k:"undernutrition",p:"ˌmælnjuˈtrɪʃn",pos:"n.",d:"poor health from not eating enough food",z:"l"},
{t:"health",w:"hydration",s:["water intake","fluid balance"],c:"补水",e:"Keep your water intake high in summer.",k:"water intake",p:"haɪˈdreɪʃn",pos:"n.",d:"the process of taking in enough water",z:"l"},
{t:"health",w:"supplement",s:["vitamin pill","dietary aid","additive"],c:"补充剂",e:"She takes a vitamin pill daily.",k:"vitamin pill",p:"ˈsʌplɪmənt",pos:"n.",d:"a product that adds nutrients to your diet",z:"l"},
{t:"health",w:"relapse",s:["return","recurrence","setback"],c:"复发",e:"He suffered a recurrence of the illness.",k:"recurrence",p:"rɪˈlæps",pos:"n.",d:"a return of an illness",z:"l"},
{t:"health",w:"fever",s:["high temperature","temperature"],c:"发烧",e:"She has a high temperature today.",k:"high temperature",p:"ˈfiːvə",pos:"n.",d:"a body temperature higher than normal",z:"l"},
{t:"health",w:"dizziness",s:["light-headedness","faintness"],c:"头晕",e:"The medicine caused light-headedness.",k:"light-headedness",p:"ˈdɪzinəs",pos:"n.",d:"a feeling that you might fall",z:"l"},
{t:"health",w:"nausea",s:["sickness","queasiness"],c:"恶心",e:"Some patients feel sickness after the drug.",k:"sickness",p:"ˈnɔːziə",pos:"n.",d:"the feeling that you want to vomit",z:"l"},
{t:"health",w:"appetite",s:["hunger","desire for food"],c:"食欲",e:"Exercise can increase hunger.",k:"hunger",p:"ˈæpɪtaɪt",pos:"n.",d:"the desire to eat",z:"l"},
{t:"health",w:"hereditary",s:["genetic","inherited","in the family"],c:"遗传的",e:"The condition is genetic in some families.",k:"genetic",p:"həˈredɪtri",pos:"adj.",d:"passed from parents to children",z:"l"},
{t:"health",w:"fitness",s:["physical condition","health","stamina"],c:"健康体魄",e:"Regular running improves physical condition.",k:"physical condition",p:"ˈfɪtnəs",pos:"n.",d:"the state of being physically healthy",z:"l"},
{t:"health",w:"consultation",s:["appointment","meeting","session"],c:"就诊，咨询",e:"Book a meeting with the doctor tomorrow.",k:"meeting",p:"ˌkɒnsəlˈteɪʃn",pos:"n.",d:"a meeting with a doctor or expert",z:"l"},
{t:"health",w:"casualty",s:["emergency room","accident and emergency","urgent care"],c:"急诊室",e:"She was taken to the emergency room.",k:"emergency room",p:"ˈkæʒuəlti",pos:"n.",d:"the part of a hospital for emergencies",z:"l"},
{t:"health",w:"first aid",s:["emergency care","basic treatment"],c:"急救",e:"Volunteers learned basic treatment skills.",k:"basic treatment",p:"ˌfɜːst ˈeɪd",pos:"n.",d:"simple medical help given before a doctor arrives",z:"l"},
{t:"health",w:"ambulance",s:["emergency vehicle","rescue van"],c:"救护车",e:"An emergency vehicle arrived quickly.",k:"emergency vehicle",p:"ˈæmbjələns",pos:"n.",d:"a vehicle that takes sick people to hospital",z:"l"},
{t:"health",w:"ward",s:["hospital room","unit","department"],c:"病房",e:"She stayed in the children unit overnight.",k:"children unit",p:"wɔːd",pos:"n.",d:"a room in a hospital for patients",z:"l"},
{t:"health",w:"discharge",s:["release","send home","let out"],c:"出院",e:"The hospital released him on Friday.",k:"released",p:"dɪsˈtʃɑːdʒ",pos:"v.",d:"to allow a patient to leave hospital",z:"l"},
{t:"health",w:"transplant",s:["organ replacement","graft","operation"],c:"移植",e:"He needed an organ replacement surgery.",k:"organ replacement",p:"ˈtrænsplɑːnt",pos:"n.",d:"an operation to replace an organ",z:"l"},
{t:"health",w:"donor",s:["giver","contributor","provider"],c:"捐献者",e:"The giver wished to remain anonymous.",k:"giver",p:"ˈdəʊnə",pos:"n.",d:"a person who gives blood or organs",z:"l"},
{t:"health",w:"stem cell",s:["body cell","repair cell"],c:"干细胞",e:"Repair cells may treat the disease.",k:"repair cells",p:"stem sel",pos:"n.",d:"special cells that can develop into other cells",z:"l"},
{t:"science",w:"breakthrough",s:["discovery","advance","development"],c:"突破",e:"The discovery could change medicine.",k:"discovery",p:"ˈbreɪkθruː",pos:"n.",d:"an important new discovery",z:"l"},
{t:"science",w:"invention",s:["creation","device","innovation"],c:"发明",e:"The creation of the wheel changed history.",k:"creation",p:"ɪnˈvenʃn",pos:"n.",d:"a new machine or idea that is created",z:"l"},
{t:"science",w:"researcher",s:["scientist","scholar","academic"],c:"研究人员",e:"The scientist published her findings.",k:"scientist",p:"rɪˈsɜːtʃə",pos:"n.",d:"a person who studies a subject carefully",z:"l"},
{t:"science",w:"specimen",s:["sample","example","piece"],c:"样本",e:"The laboratory analysed each sample.",k:"sample",p:"ˈspesɪmən",pos:"n.",d:"a small amount used for testing",z:"l"},
{t:"science",w:"observation",s:["monitoring","watching","recording"],c:"观察",e:"Careful monitoring showed clear changes.",k:"monitoring",p:"ˌɒbzəˈveɪʃn",pos:"n.",d:"the act of watching something carefully",z:"l"},
{t:"science",w:"methodology",s:["approach","method","procedure"],c:"方法论",e:"The approach was tested in two schools.",k:"approach",p:"ˌmeθəˈdɒlədʒi",pos:"n.",d:"the system of methods used in a study",z:"l"},
{t:"science",w:"findings",s:["results","outcomes","conclusions"],c:"研究结果",e:"The results support the original theory.",k:"results",p:"ˈfaɪndɪŋz",pos:"n.",d:"the information learned from a study",z:"l"},
{t:"science",w:"patent",s:["copyright","protection","right"],c:"专利",e:"The company holds a protection on the design.",k:"protection",p:"ˈpætnt",pos:"n.",d:"a legal right to own an invention",z:"l"},
{t:"science",w:"prototype",s:["model","sample version","test version"],c:"原型",e:"They showed a test version of the robot.",k:"test version",p:"ˈprəʊtətaɪp",pos:"n.",d:"a first model of a new product",z:"l"},
{t:"technology",w:"gadget",s:["device","gizmo","tool"],c:"小工具",e:"This device saves a lot of time.",k:"device",p:"ˈɡædʒɪt",pos:"n.",d:"a small useful machine",z:"l"},
{t:"technology",w:"software",s:["computer programs","applications","code"],c:"软件",e:"The computer programs need updating.",k:"computer programs",p:"ˈsɒftweə",pos:"n.",d:"programs used by a computer",z:"l"},
{t:"technology",w:"hardware",s:["equipment","machinery","parts"],c:"硬件",e:"The equipment is quite old now.",k:"equipment",p:"ˈhɑːdweə",pos:"n.",d:"the physical parts of a computer",z:"l"},
{t:"technology",w:"wireless",s:["cordless","radio","wi-fi"],c:"无线的",e:"The cordless speaker is easy to use.",k:"cordless",p:"ˈwaɪələs",pos:"adj.",d:"using signals instead of wires",z:"l"},
{t:"technology",w:"network",s:["system","web","grid"],c:"网络",e:"The system connects all the offices.",k:"system",p:"ˈnetwɜːk",pos:"n.",d:"a group of connected computers",z:"l"},
{t:"technology",w:"password",s:["code","passcode","key"],c:"密码",e:"Enter your passcode to continue.",k:"passcode",p:"ˈpɑːswɜːd",pos:"n.",d:"a secret word to access a system",z:"l"},
{t:"technology",w:"username",s:["user id","login name","account name"],c:"用户名",e:"Type your user id in this box.",k:"user id",p:"ˈjuːzəneɪm",pos:"n.",d:"a name that identifies a user",z:"l"},
{t:"technology",w:"browser",s:["web browser","internet tool"],c:"浏览器",e:"Open the page in a web browser.",k:"web browser",p:"ˈbraʊzə",pos:"n.",d:"a program for viewing websites",z:"l"},
{t:"technology",w:"virtual",s:["digital","online","simulated"],c:"虚拟的",e:"The tour is a digital experience.",k:"digital",p:"ˈvɜːtʃuəl",pos:"adj.",d:"existing on a computer rather than in reality",z:"l"},
{t:"technology",w:"robotic",s:["automated","machine-driven","automatic"],c:"机器人的",e:"The factory uses automated arms.",k:"automated",p:"rəʊˈbɒtɪk",pos:"adj.",d:"done by machines or robots",z:"l"},
{t:"technology",w:"algorithm",s:["formula","procedure","set of rules"],c:"算法",e:"The set of rules decides what you see.",k:"set of rules",p:"ˈælɡərɪðəm",pos:"n.",d:"a set of steps a computer follows",z:"l"},
{t:"technology",w:"database",s:["data store","archive","repository"],c:"数据库",e:"The data store holds millions of records.",k:"data store",p:"ˈdeɪtəbeɪs",pos:"n.",d:"a large collection of organised data",z:"l"},
{t:"technology",w:"backup",s:["copy","safety copy","duplicate"],c:"备份",e:"Keep a safety copy of your files.",k:"safety copy",p:"ˈbækʌp",pos:"n.",d:"a copy kept in case the original is lost",z:"l"},
{t:"technology",w:"sensor",s:["detector","monitor","probe"],c:"传感器",e:"The detector warns of smoke.",k:"detector",p:"ˈsensə",pos:"n.",d:"a device that reacts to light, heat or movement",z:"l"},
{t:"technology",w:"drone",s:["unmanned aircraft","remote-controlled plane"],c:"无人机",e:"An unmanned aircraft took the photos.",k:"unmanned aircraft",p:"drəʊn",pos:"n.",d:"a flying machine without a pilot",z:"l"},
{t:"technology",w:"artificial intelligence",s:["machine intelligence","AI","smart computing"],c:"人工智能",e:"Machine intelligence is changing many jobs.",k:"machine intelligence",p:"ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns",pos:"n.",d:"the ability of machines to think and learn",z:"l"},
{t:"technology",w:"download",s:["save","transfer","fetch"],c:"下载",e:"Save the file to your phone.",k:"save",p:"ˌdaʊnˈləʊd",pos:"v.",d:"to copy data from the internet to a device",z:"l"},
{t:"technology",w:"upload",s:["post","transfer up","send"],c:"上传",e:"Post your photos to the site.",k:"post",p:"ˌʌpˈləʊd",pos:"v.",d:"to send data from a device to the internet",z:"l"},
{t:"technology",w:"update",s:["upgrade","refresh","renew"],c:"更新",e:"Upgrade the app to the latest version.",k:"upgrade",p:"ˌʌpˈdeɪt",pos:"v.",d:"to make something more modern",z:"l"},
{t:"technology",w:"screen",s:["display","monitor","screen display"],c:"屏幕",e:"The display is very clear.",k:"display",p:"skriːn",pos:"n.",d:"the flat surface where images appear",z:"l"},
{t:"technology",w:"battery",s:["power cell","charge pack"],c:"电池",e:"The power cell lasts all day.",k:"power cell",p:"ˈbætri",pos:"n.",d:"a device that stores electricity",z:"l"},
{t:"technology",w:"charger",s:["power adapter","charging cable"],c:"充电器",e:"I forgot my charging cable.",k:"charging cable",p:"ˈtʃɑːdʒə",pos:"n.",d:"a device used to fill a battery with power",z:"l"},
{t:"technology",w:"cable",s:["wire","cord","lead"],c:"电缆",e:"Connect the wire to the computer.",k:"wire",p:"ˈkeɪbl",pos:"n.",d:"a thick wire for electricity or data",z:"l"},
];
module.exports = { V5C };