'use strict';
const V5D = [
{t:"living",w:"lease",s:["contract","agreement","tenancy"],c:"租约",e:"Sign the tenancy before moving in.",k:"tenancy",p:"liːs",pos:"n.",d:"a legal agreement to rent property",z:"l"},
{t:"living",w:"property",s:["housing","premises","real estate"],c:"房产",e:"Real estate prices keep rising.",k:"real estate",p:"ˈprɒpəti",pos:"n.",d:"a building or land owned by someone",z:"l"},
{t:"living",w:"estate agent",s:["property agent","realtor","letting agent"],c:"房产中介",e:"The property agent showed us three flats.",k:"property agent",p:"ɪˈsteɪt ˌeɪdʒənt",pos:"n.",d:"a person who helps people buy or rent property",z:"l"},
{t:"living",w:"mortgage",s:["home loan","property loan","loan"],c:"按揭贷款",e:"They took out a home loan for the flat.",k:"home loan",p:"ˈmɔːɡɪdʒ",pos:"n.",d:"a loan used to buy a house",z:"l"},
{t:"living",w:"appliance",s:["machine","device","equipment"],c:"家用电器",e:"The kitchen machine broke down.",k:"machine",p:"əˈplaɪəns",pos:"n.",d:"a machine used in the home",z:"l"},
{t:"living",w:"washing machine",s:["laundry machine","washer"],c:"洗衣机",e:"The laundry machine is on the top floor.",k:"laundry machine",p:"ˈwɒʃɪŋ məʃiːn",pos:"n.",d:"a machine that washes clothes",z:"l"},
{t:"living",w:"dishwasher",s:["dish machine","washing device"],c:"洗碗机",e:"The dish machine saves water.",k:"dish machine",p:"ˈdɪʃwɒʃə",pos:"n.",d:"a machine that washes plates",z:"l"},
{t:"living",w:"tumble dryer",s:["clothes dryer","drying machine"],c:"烘干机",e:"Use the clothes dryer on rainy days.",k:"clothes dryer",p:"ˈtʌmbl ˌdraɪə",pos:"n.",d:"a machine that dries clothes",z:"l"},
{t:"living",w:"broadband",s:["high-speed internet","fast connection"],c:"宽带",e:"High-speed internet is included in the rent.",k:"high-speed internet",p:"ˈbrɔːdbænd",pos:"n.",d:"a fast internet connection",z:"l"},
{t:"living",w:"outskirts",s:["edge","outer area","fringe"],c:"市郊",e:"They live on the edge of town.",k:"edge",p:"ˈaʊtskɜːts",pos:"n.",d:"the outer parts of a city",z:"l"},
{t:"living",w:"downtown",s:["city centre","central area","town centre"],c:"市中心",e:"The office is in the central area.",k:"central area",p:"ˌdaʊnˈtaʊn",pos:"n.",d:"the main business area of a city",z:"l"},
{t:"living",w:"maintenance",s:["repairs","upkeep","servicing"],c:"维护",e:"Upkeep costs are shared by tenants.",k:"upkeep",p:"ˈmeɪntənəns",pos:"n.",d:"work done to keep something in good condition",z:"l"},
{t:"living",w:"meter reading",s:["reading","usage check"],c:"抄表",e:"The usage check happens every month.",k:"usage check",p:"ˈmiːtə ˌriːdɪŋ",pos:"n.",d:"recording the amount of gas or electricity used",z:"l"},
{t:"living",w:"council tax",s:["local tax","municipal tax","property tax"],c:"市政税",e:"Local tax is paid in ten monthly payments.",k:"local tax",p:"ˈkaʊnsl tæks",pos:"n.",d:"a tax paid to the local government",z:"l"},
{t:"living",w:"refuse collection",s:["garbage pickup","waste collection","rubbish removal"],c:"垃圾收集",e:"Waste collection happens on Tuesdays.",k:"waste collection",p:"rɪˈfjuːz kəˌlekʃn",pos:"n.",d:"the service that removes rubbish",z:"l"},
{t:"living",w:"compost",s:["rotted waste","plant food","soil improver"],c:"堆肥",e:"Kitchen scraps become soil improver.",k:"soil improver",p:"ˈkɒmpɒst",pos:"n.",d:"decayed plants used to improve soil",z:"l"},
{t:"living",w:"recycle bin",s:["recycling container","green bin"],c:"回收桶",e:"Put bottles in the green bin.",k:"green bin",p:"ˌriːˈsaɪkl bɪn",pos:"n.",d:"a container for things to be recycled",z:"l"},
{t:"living",w:"parking permit",s:["parking pass","resident permit"],c:"停车许可证",e:"You need a parking pass for this street.",k:"parking pass",p:"ˈpɑːkɪŋ ˌpɜːmɪt",pos:"n.",d:"a document allowing you to park",z:"l"},
{t:"living",w:"neighbourhood watch",s:["community watch","local patrol"],c:"社区联防",e:"The community watch reduced crime.",k:"community watch",p:"ˈneɪbəhʊd wɒtʃ",pos:"n.",d:"a group of neighbours who watch for crime",z:"l"},
{t:"living",w:"amenities",s:["facilities","services","conveniences"],c:"配套设施",e:"The area has excellent facilities.",k:"facilities",p:"əˈmiːnətiz",pos:"n.",d:"useful services or buildings in an area",z:"l"},
{t:"living",w:"housing association",s:["social landlord","non-profit landlord"],c:"住房协会",e:"The social landlord manages the flats.",k:"social landlord",p:"ˈhaʊzɪŋ əˌsəʊsiˈeɪʃn",pos:"n.",d:"an organisation that provides low-cost housing",z:"l"},
{t:"living",w:"surveyor",s:["inspector","examiner","property checker"],c:"房屋检查员",e:"The inspector checked the roof.",k:"inspector",p:"səˈveɪə",pos:"n.",d:"a person who examines buildings",z:"l"},
{t:"living",w:"double glazing",s:["two-layer windows","insulated windows"],c:"双层玻璃",e:"Insulated windows reduce noise.",k:"insulated windows",p:"ˌdʌbl ˈɡleɪzɪŋ",pos:"n.",d:"windows with two layers of glass",z:"l"},
{t:"living",w:"utility bill",s:["energy bill","service bill"],c:"水电账单",e:"The energy bill arrives by email.",k:"energy bill",p:"juːˈtɪləti bɪl",pos:"n.",d:"a bill for gas, water or electricity",z:"l"},
{t:"living",w:"move-in date",s:["starting date","entry date"],c:"入住日期",e:"The starting date is the first of May.",k:"starting date",p:"ˌmuːv ˈɪn deɪt",pos:"n.",d:"the day you start living in a place",z:"l"},
{t:"shopping",w:"warranty",s:["guarantee","cover","assurance"],c:"保修",e:"The laptop comes with a two-year guarantee.",k:"guarantee",p:"ˈwɒrənti",pos:"n.",d:"a promise to repair a product for a period",z:"l"},
{t:"shopping",w:"catalogue",s:["list","brochure","product list"],c:"商品目录",e:"Check the product list for prices.",k:"product list",p:"ˈkætəlɒɡ",pos:"n.",d:"a book or list of products",z:"l"},
{t:"shopping",w:"complaint",s:["grievance","protest","objection"],c:"投诉",e:"Customers filed a grievance about the service.",k:"grievance",p:"kəmˈpleɪnt",pos:"n.",d:"a statement that something is wrong",z:"l"},
{t:"shopping",w:"stock",s:["goods","supply","inventory"],c:"库存",e:"The shoes are out of inventory.",k:"inventory",p:"stɒk",pos:"n.",d:"the goods a shop has to sell",z:"l"},
{t:"shopping",w:"price tag",s:["label","tag","sticker"],c:"价格标签",e:"The label shows the original price.",k:"label",p:"ˈpraɪs tæɡ",pos:"n.",d:"a small label showing a price",z:"l"},
{t:"shopping",w:"express delivery",s:["fast shipping","quick delivery"],c:"快递",e:"Fast shipping costs extra.",k:"fast shipping",p:"ɪkˈspres dɪˈlɪvəri",pos:"n.",d:"delivery that is very quick",z:"l"},
{t:"shopping",w:"click and collect",s:["buy online pick up","online order collection"],c:"线上下单门店取货",e:"We ordered online and used online order collection.",k:"online order collection",p:"klɪk ənd kəˈlekt",pos:"n.",d:"ordering online and collecting in a shop",z:"l"},
{t:"shopping",w:"out of stock",s:["sold out","unavailable","no stock"],c:"缺货",e:"The item is sold out this week.",k:"sold out",p:"ˌaʊt əv ˈstɒk",pos:"adj.",d:"not available because it has all been sold",z:"l"},
{t:"shopping",w:"counterfeit",s:["fake","forged","imitation"],c:"假冒的",e:"The bag turned out to be fake.",k:"fake",p:"ˈkaʊntəfɪt",pos:"adj.",d:"made to look like a real product illegally",z:"l"},
{t:"shopping",w:"customer service",s:["after-sales support","help desk","support"],c:"客户服务",e:"The after-sales support is very helpful.",k:"after-sales support",p:"ˈkʌstəmə ˈsɜːvɪs",pos:"n.",d:"help given to people who buy products",z:"l"},
{t:"shopping",w:"second-hand",s:["used","pre-owned","gently used"],c:"二手的",e:"She bought a used bicycle.",k:"used",p:"ˌsekənd ˈhænd",pos:"adj.",d:"previously owned by someone else",z:"l"},
{t:"shopping",w:"refund policy",s:["returns policy","money-back policy"],c:"退款政策",e:"Read the returns policy before buying.",k:"returns policy",p:"ˈriːfʌnd ˌpɒləsi",pos:"n.",d:"rules about returning goods and getting money back",z:"l"},
{t:"shopping",w:"till",s:["cash register","checkout","counter"],c:"收银台",e:"Pay at the cash register.",k:"cash register",p:"tɪl",pos:"n.",d:"a machine that holds money in a shop",z:"l"},
{t:"shopping",w:"online shopping",s:["e-commerce","internet shopping","online buying"],c:"网上购物",e:"E-commerce has grown quickly.",k:"e-commerce",p:"ˌɒnlaɪn ˈʃɒpɪŋ",pos:"n.",d:"buying things over the internet",z:"l"},
{t:"shopping",w:"sales assistant",s:["shop worker","retail assistant","clerk"],c:"售货员",e:"The retail assistant helped me choose.",k:"retail assistant",p:"ˈseɪlz əˌsɪstənt",pos:"n.",d:"a person who helps customers in a shop",z:"l"},
{t:"shopping",w:"window shopping",s:["browsing","looking at displays"],c:"逛橱窗",e:"We spent the afternoon browsing in town.",k:"browsing",p:"ˈwɪndəʊ ˌʃɒpɪŋ",pos:"n.",d:"looking at shops without buying",z:"l"},
{t:"shopping",w:"bulk buying",s:["buying in large quantities","wholesale buying"],c:"批量购买",e:"Buying in large quantities saves money.",k:"buying in large quantities",p:"ˌbʌlk ˈbaɪɪŋ",pos:"n.",d:"buying large amounts at a cheaper price",z:"l"},
{t:"shopping",w:"display",s:["showcase","exhibit","window display"],c:"陈列",e:"The window display attracted customers.",k:"window display",p:"dɪˈspleɪ",pos:"n.",d:"an arrangement of goods for people to see",z:"l"},
{t:"shopping",w:"impulse buy",s:["spontaneous purchase","sudden purchase"],c:"冲动消费",e:"A spontaneous purchase emptied my wallet.",k:"spontaneous purchase",p:"ˈɪmpʌls baɪ",pos:"n.",d:"something bought without planning",z:"l"},
{t:"feelings",w:"anxious",s:["worried","nervous","uneasy"],c:"焦虑的",e:"She felt uneasy about the exam.",k:"uneasy",p:"ˈæŋkʃəs",pos:"adj.",d:"feeling worried or nervous",z:"l"},
{t:"feelings",w:"delighted",s:["thrilled","pleased","overjoyed"],c:"高兴的",e:"We were thrilled with the news.",k:"thrilled",p:"dɪˈlaɪtɪd",pos:"adj.",d:"very happy",z:"l"},
{t:"feelings",w:"frustrated",s:["annoyed","exasperated","discouraged"],c:"沮丧的",e:"He felt discouraged after failing twice.",k:"discouraged",p:"frʌˈstreɪtɪd",pos:"adj.",d:"annoyed because you cannot do something",z:"l"},
{t:"feelings",w:"guilty",s:["ashamed","remorseful","regretful"],c:"内疚的",e:"She felt ashamed about the mistake.",k:"ashamed",p:"ˈɡɪlti",pos:"adj.",d:"feeling bad about something you did",z:"l"},
{t:"feelings",w:"ashamed",s:["embarrassed","humiliated","mortified"],c:"羞愧的",e:"He felt humiliated in front of everyone.",k:"humiliated",p:"əˈʃeɪmd",pos:"adj.",d:"feeling shame or embarrassment",z:"l"},
{t:"feelings",w:"furious",s:["angry","fuming","enraged"],c:"狂怒的",e:"She was fuming about the delay.",k:"fuming",p:"ˈfjʊəriəs",pos:"adj.",d:"extremely angry",z:"l"},
{t:"feelings",w:"overwhelmed",s:["swamped","stressed","flooded"],c:"不知所措的",e:"New students often feel swamped.",k:"swamped",p:"ˌəʊvəˈwelmd",pos:"adj.",d:"feeling too much to handle",z:"l"},
{t:"feelings",w:"homesick",s:["missing home","longing for home"],c:"想家的",e:"She was missing home after a month away.",k:"missing home",p:"ˈhəʊmsɪk",pos:"adj.",d:"sad because you are away from home",z:"l"},
{t:"feelings",w:"terrified",s:["frightened","scared","horrified"],c:"恐惧的",e:"He is scared of flying.",k:"scared",p:"ˈterɪfaɪd",pos:"adj.",d:"very afraid",z:"l"},
{t:"feelings",w:"miserable",s:["unhappy","wretched","gloomy"],c:"痛苦的",e:"He felt wretched all week.",k:"wretched",p:"ˈmɪzərəbl",pos:"adj.",d:"very unhappy",z:"l"},
{t:"feelings",w:"cheerful",s:["happy","lively","bright"],c:"愉快的",e:"She is always lively in the morning.",k:"lively",p:"ˈtʃɪəfl",pos:"adj.",d:"noticeably happy",z:"l"},
{t:"feelings",w:"content",s:["satisfied","pleased","happy"],c:"满足的",e:"He is satisfied with his progress.",k:"satisfied",p:"kənˈtent",pos:"adj.",d:"happy and satisfied",z:"l"},
{t:"feelings",w:"hopeful",s:["optimistic","positive","expectant"],c:"抱有希望的",e:"Doctors are optimistic about her recovery.",k:"optimistic",p:"ˈhəʊpfl",pos:"adj.",d:"feeling that good things will happen",z:"l"},
{t:"feelings",w:"upset",s:["distressed","hurt","sad"],c:"难过的",e:"She was distressed by the news.",k:"distressed",p:"ʌpˈset",pos:"adj.",d:"unhappy or worried",z:"l"},
{t:"feelings",w:"emotional",s:["feeling-based","sentimental","affective"],c:"情绪的",e:"The film had a sentimental ending.",k:"sentimental",p:"ɪˈməʊʃənl",pos:"adj.",d:"related to strong feelings",z:"l"},
{t:"feelings",w:"sympathetic",s:["understanding","caring","compassionate"],c:"同情的",e:"The nurse was very compassionate.",k:"compassionate",p:"ˌsɪmpəˈθetɪk",pos:"adj.",d:"showing that you understand others problems",z:"l"},
{t:"edu",w:"assignment",s:["task","homework","project"],c:"作业",e:"Hand in the task by Friday.",k:"task",p:"əˈsaɪnmənt",pos:"n.",d:"a piece of work given to students",z:"l"},
{t:"edu",w:"coursework",s:["assignments","studies","academic work"],c:"课程作业",e:"Your assignments count for half the grade.",k:"assignments",p:"ˈkɔːswɜːk",pos:"n.",d:"work done during a course",z:"l"},
{t:"edu",w:"certificate",s:["diploma","qualification","document"],c:"证书",e:"The diploma is recognised worldwide.",k:"diploma",p:"səˈtɪfɪkət",pos:"n.",d:"an official document showing you completed a course",z:"l"},
{t:"edu",w:"transcript",s:["record of results","grade report","academic record"],c:"成绩单",e:"Send your grade report with the application.",k:"grade report",p:"ˈtrænskrɪpt",pos:"n.",d:"an official list of a student grades",z:"l"},
{t:"edu",w:"undergraduate",s:["degree student","bachelor student"],c:"本科生",e:"Degree students live on campus in year one.",k:"degree students",p:"ˌʌndəˈɡrædʒuət",pos:"n.",d:"a student studying for a first degree",z:"l"},
{t:"edu",w:"postgraduate",s:["graduate student","master student"],c:"研究生",e:"Graduate students share an office.",k:"graduate students",p:"ˌpəʊstˈɡrædʒuət",pos:"n.",d:"a student studying after a first degree",z:"l"},
{t:"edu",w:"campus",s:["university grounds","college site"],c:"校园",e:"The college site has three libraries.",k:"college site",p:"ˈkæmpəs",pos:"n.",d:"the land and buildings of a university",z:"l"},
{t:"edu",w:"faculty",s:["teaching staff","academic staff","department"],c:"教职工",e:"The teaching staff voted on the change.",k:"teaching staff",p:"ˈfæklti",pos:"n.",d:"the teachers of a university",z:"l"},
{t:"edu",w:"tutor",s:["teacher","instructor","mentor"],c:"导师",e:"My mentor helped me plan the essay.",k:"mentor",p:"ˈtjuːtə",pos:"n.",d:"a teacher who guides a small group",z:"l"},
{t:"edu",w:"graduation",s:["completion","finishing","ceremony"],c:"毕业",e:"The completion ceremony is in June.",k:"completion ceremony",p:"ˌɡrædʒuˈeɪʃn",pos:"n.",d:"the ceremony when students finish their studies",z:"l"},
{t:"edu",w:"dropout",s:["quitter","leaver","withdrawal"],c:"辍学者",e:"The leaver rate fell after the reforms.",k:"leaver rate",p:"ˈdrɒpaʊt",pos:"n.",d:"a student who leaves before finishing",z:"l"},
{t:"edu",w:"enrolment",s:["registration","sign-up","admission"],c:"注册入学",e:"Registration opens in September.",k:"registration",p:"ɪnˈrəʊlmənt",pos:"n.",d:"the act of joining a course",z:"l"},
{t:"edu",w:"foundation course",s:["preparatory course","pre-degree course"],c:"预科课程",e:"The preparatory course lasts one year.",k:"preparatory course",p:"faʊnˈdeɪʃn kɔːs",pos:"n.",d:"a course preparing students for a degree",z:"l"},
{t:"edu",w:"distance learning",s:["online study","remote education","home study"],c:"远程学习",e:"Remote education suits working adults.",k:"remote education",p:"ˈdɪstəns ˌlɜːnɪŋ",pos:"n.",d:"studying from home using the internet",z:"l"},
{t:"edu",w:"study abroad",s:["overseas study","international exchange"],c:"出国留学",e:"Overseas study broadens the mind.",k:"overseas study",p:"ˈstʌdi əˈbrɔːd",pos:"n.",d:"studying in a foreign country",z:"l"},
{t:"edu",w:"seminar",s:["discussion class","workshop","group session"],c:"研讨课",e:"The discussion class meets weekly.",k:"discussion class",p:"ˈsemɪnɑː",pos:"n.",d:"a small class for discussion",z:"l"},
{t:"edu",w:"lecturer",s:["professor","teacher","academic"],c:"讲师",e:"The professor gave an excellent talk.",k:"professor",p:"ˈlektʃərə",pos:"n.",d:"a person who teaches at a university",z:"l"},
{t:"edu",w:"dissertation",s:["thesis","long essay","research paper"],c:"学位论文",e:"Her research paper took a year to write.",k:"research paper",p:"ˌdɪsəˈteɪʃn",pos:"n.",d:"a long piece of writing for a degree",z:"l"},
{t:"edu",w:"field trip",s:["study visit","excursion","outdoor lesson"],c:"实地考察",e:"The study visit is on Thursday.",k:"study visit",p:"ˈfiːld trɪp",pos:"n.",d:"a visit made by students to learn outside class",z:"l"},
{t:"edu",w:"exemption",s:["waiver","release","exception"],c:"豁免",e:"You can apply for a waiver of the course.",k:"waiver",p:"ɪɡˈzempʃn",pos:"n.",d:"official permission not to do something",z:"l"},
{t:"edu",w:"cramming",s:["last-minute revision","swotting"],c:"临时抱佛脚",e:"Last-minute revision rarely works.",k:"last-minute revision",p:"ˈkræmɪŋ",pos:"n.",d:"studying hard just before an exam",z:"l"},
{t:"edu",w:"referencing",s:["citing sources","citations","source listing"],c:"引用格式",e:"Correct citing sources avoids penalties.",k:"citing sources",p:"ˈrefərənsɪŋ",pos:"n.",d:"the practice of listing sources in academic work",z:"l"},
{t:"edu",w:"module",s:["unit","course component","subject block"],c:"课程模块",e:"This unit covers statistics.",k:"unit",p:"ˈmɒdjuːl",pos:"n.",d:"one part of a course",z:"l"},
{t:"edu",w:"benchmark",s:["standard","reference point","measure"],c:"基准",e:"The test sets a national standard.",k:"national standard",p:"ˈbentʃmɑːk",pos:"n.",d:"a standard used for comparison",z:"l"},
{t:"work",w:"wage",s:["pay","earnings","salary"],c:"工资",e:"Pay is higher in the capital.",k:"pay",p:"weɪdʒ",pos:"n.",d:"money paid for work by the hour or week",z:"l"},
{t:"work",w:"employer",s:["company","boss","firm"],c:"雇主",e:"The firm offers good training.",k:"firm",p:"ɪmˈplɔɪə",pos:"n.",d:"a person or company that employs people",z:"l"},
{t:"work",w:"probation",s:["trial period","test period","trainee period"],c:"试用期",e:"New staff have a three-month trial period.",k:"trial period",p:"prəˈbeɪʃn",pos:"n.",d:"a period when a new worker is tested",z:"l"},
{t:"work",w:"appraisal",s:["review","assessment","evaluation"],c:"绩效评估",e:"Your annual review is next week.",k:"annual review",p:"əˈpreɪzl",pos:"n.",d:"a meeting to assess a worker performance",z:"l"},
{t:"work",w:"bonus",s:["extra pay","reward","incentive"],c:"奖金",e:"Staff receive extra pay in December.",k:"extra pay",p:"ˈbəʊnəs",pos:"n.",d:"extra money given for good work",z:"l"},
{t:"work",w:"redundancy",s:["job loss","layoff","dismissal"],c:"裁员",e:"The factory announced job losses.",k:"job losses",p:"rɪˈdʌndənsi",pos:"n.",d:"the situation of losing your job",z:"l"},
{t:"work",w:"internship",s:["work placement","traineeship","work experience"],c:"实习",e:"Her work placement lasts six months.",k:"work placement",p:"ˈɪntɜːnʃɪp",pos:"n.",d:"a period of work for training",z:"l"},
{t:"work",w:"apprentice",s:["trainee","learner","novice"],c:"学徒",e:"The trainee learns on the job.",k:"trainee",p:"əˈprentɪs",pos:"n.",d:"a person learning a skilled job",z:"l"},
{t:"work",w:"freelance",s:["self-employed","independent","contract worker"],c:"自由职业的",e:"She works as a self-employed designer.",k:"self-employed",p:"ˈfriːlɑːns",pos:"adj.",d:"working for different companies, not one employer",z:"l"},
{t:"work",w:"remote work",s:["working from home","teleworking","home working"],c:"远程办公",e:"Working from home saves commuting time.",k:"working from home",p:"rɪˈməʊt wɜːk",pos:"n.",d:"work done away from an office",z:"l"},
{t:"work",w:"networking",s:["making contacts","socialising","meeting people"],c:"人脉拓展",e:"Making contacts is key to career growth.",k:"making contacts",p:"ˈnetwɜːkɪŋ",pos:"n.",d:"meeting people to build professional relationships",z:"l"},
{t:"work",w:"burnout",s:["exhaustion","overwork","fatigue"],c:"职业倦怠",e:"Overwork leads to exhaustion.",k:"overwork",p:"ˈbɜːnaʊt",pos:"n.",d:"mental tiredness caused by too much work",z:"l"},
{t:"work",w:"annual leave",s:["holiday time","paid vacation","time off"],c:"年假",e:"Staff get twenty-five days of paid vacation.",k:"paid vacation",p:"ˈænjuəl liːv",pos:"n.",d:"paid days off work each year",z:"l"},
{t:"work",w:"pay rise",s:["salary increase","pay increase","raise"],c:"加薪",e:"She asked for a salary increase.",k:"salary increase",p:"ˈpeɪ raɪz",pos:"n.",d:"more money for the same job",z:"l"},
{t:"work",w:"notice",s:["warning","notification","heads-up"],c:"离职通知期",e:"You must give two weeks warning.",k:"warning",p:"ˈnəʊtɪs",pos:"n.",d:"a formal statement that you are leaving a job",z:"l"},
{t:"work",w:"rota",s:["work schedule","timetable","rotation"],c:"排班表",e:"The work schedule changes weekly.",k:"work schedule",p:"ˈrəʊtə",pos:"n.",d:"a list of people and times for work",z:"l"},
{t:"work",w:"team spirit",s:["teamwork","cooperation","unity"],c:"团队精神",e:"Good teamwork improves results.",k:"teamwork",p:"ˌtiːm ˈspɪrɪt",pos:"n.",d:"the feeling of working well together",z:"l"},
{t:"work",w:"sabbatical",s:["career break","study leave","extended leave"],c:"公休假",e:"He took a career break to travel.",k:"career break",p:"səˈbætɪkl",pos:"n.",d:"a long period of leave from work",z:"l"},
];
module.exports = { V5D };