'use strict';
const V5E = [
{t:"env",w:"ecosystem",s:["habitat system","natural community","biotope"],c:"生态系统",e:"The natural community is fragile.",k:"natural community",p:"ˈiːkəʊsɪstəm",pos:"n.",d:"plants and animals living together with their environment",z:"l"},
{t:"env",w:"sewage",s:["wastewater","dirty water","effluent"],c:"污水",e:"Wastewater flows into the river.",k:"wastewater",p:"ˈsuːɪdʒ",pos:"n.",d:"used water and waste from homes",z:"l"},
{t:"env",w:"erosion",s:["wearing away","soil loss","wearing down"],c:"侵蚀",e:"Soil loss follows heavy rain.",k:"soil loss",p:"ɪˈrəʊʒn",pos:"n.",d:"the gradual wearing away of soil or rock",z:"l"},
{t:"env",w:"greenhouse gas",s:["warming gas","heat-trapping gas"],c:"温室气体",e:"Heat-trapping gas warms the planet.",k:"heat-trapping gas",p:"ˈɡriːnhaʊs ɡæs",pos:"n.",d:"a gas that traps heat in the atmosphere",z:"l"},
{t:"env",w:"carbon footprint",s:["carbon impact","emissions total"],c:"碳足迹",e:"Flying raises your carbon impact.",k:"carbon impact",p:"ˈkɑːbən ˈfʊtprɪnt",pos:"n.",d:"the amount of carbon you cause to be released",z:"l"},
{t:"env",w:"global warming",s:["climate heating","planet warming"],c:"全球变暖",e:"Climate heating raises sea levels.",k:"climate heating",p:"ˌɡləʊbl ˈwɔːmɪŋ",pos:"n.",d:"the rise in the earth temperature",z:"l"},
{t:"env",w:"ozone layer",s:["protective gas layer","atmospheric shield"],c:"臭氧层",e:"The atmospheric shield blocks UV rays.",k:"atmospheric shield",p:"ˈəʊzəʊn ˌleɪə",pos:"n.",d:"a layer of gas that protects the earth from the sun",z:"l"},
{t:"env",w:"acid rain",s:["polluted rain","harmful rain"],c:"酸雨",e:"Polluted rain damages forests.",k:"polluted rain",p:"ˌæsɪd ˈreɪn",pos:"n.",d:"rain made harmful by pollution",z:"l"},
{t:"env",w:"endangered",s:["at risk","threatened","rare"],c:"濒危的",e:"The species is at risk of extinction.",k:"at risk",p:"ɪnˈdeɪndʒəd",pos:"adj.",d:"in danger of disappearing",z:"l"},
{t:"env",w:"extinct",s:["gone","disappeared","no longer existing"],c:"灭绝的",e:"The bird is no longer existing in the wild.",k:"no longer existing",p:"ɪkˈstɪŋkt",pos:"adj.",d:"no longer existing",z:"l"},
{t:"env",w:"extinction",s:["disappearance","dying out","eradication"],c:"灭绝",e:"The dying out of the species is a tragedy.",k:"dying out",p:"ɪkˈstɪŋkʃn",pos:"n.",d:"the end of a species",z:"l"},
{t:"env",w:"solar power",s:["sun energy","solar energy"],c:"太阳能",e:"Sun energy powers the village.",k:"sun energy",p:"ˈsəʊlə ˈpaʊə",pos:"n.",d:"energy from the sun",z:"l"},
{t:"env",w:"wind farm",s:["turbine site","wind energy site"],c:"风电场",e:"The turbine site is offshore.",k:"turbine site",p:"ˈwɪnd fɑːm",pos:"n.",d:"an area with many wind turbines",z:"l"},
{t:"env",w:"hydroelectric",s:["water-powered","dam-powered"],c:"水力发电的",e:"Water-powered stations supply the grid.",k:"water-powered",p:"ˌhaɪdrəʊɪˈlektrɪk",pos:"adj.",d:"using water to make electricity",z:"l"},
{t:"env",w:"pesticide",s:["chemical spray","crop chemical","insecticide"],c:"杀虫剂",e:"Crop chemicals can harm bees.",k:"crop chemicals",p:"ˈpestɪsaɪd",pos:"n.",d:"a chemical used to kill pests",z:"l"},
{t:"env",w:"fertiliser",s:["plant food","soil nutrient","manure"],c:"化肥",e:"Soil nutrients boost the harvest.",k:"soil nutrients",p:"ˈfɜːtəlaɪzə",pos:"n.",d:"a substance added to soil to help plants grow",z:"l"},
{t:"env",w:"exhaust fumes",s:["vehicle emissions","smoke","polluted gases"],c:"尾气",e:"Vehicle emissions hang over the city.",k:"vehicle emissions",p:"ɪɡˈzɔːst fjuːmz",pos:"n.",d:"gases from car engines",z:"l"},
{t:"env",w:"smog",s:["air pollution","haze","dirty air"],c:"雾霾",e:"Dirty air covered the capital.",k:"dirty air",p:"smɒɡ",pos:"n.",d:"thick polluted air in cities",z:"l"},
{t:"env",w:"water scarcity",s:["water shortage","lack of water"],c:"水资源短缺",e:"Water shortage affects millions.",k:"water shortage",p:"ˈwɔːtə ˈskeəsəti",pos:"n.",d:"not enough clean water",z:"l"},
{t:"env",w:"organic farming",s:["natural farming","chemical-free agriculture"],c:"有机农业",e:"Chemical-free agriculture protects soil.",k:"chemical-free agriculture",p:"ɔːˈɡænɪk ˈfɑːmɪŋ",pos:"n.",d:"farming without artificial chemicals",z:"l"},
{t:"env",w:"litter",s:["rubbish","trash","dropped waste"],c:"乱扔的垃圾",e:"Trash on the beach harms wildlife.",k:"trash",p:"ˈlɪtə",pos:"n.",d:"waste dropped in public places",z:"l"},
{t:"env",w:"air quality",s:["air purity","clean air level"],c:"空气质量",e:"Air purity improves after the rain.",k:"air purity",p:"ˈeə ˌkwɒləti",pos:"n.",d:"how clean the air is",z:"l"},
{t:"env",w:"recycling plant",s:["reprocessing factory","waste plant"],c:"回收厂",e:"The reprocessing factory handles glass.",k:"reprocessing factory",p:"ˌriːˈsaɪklɪŋ plɑːnt",pos:"n.",d:"a factory where waste is recycled",z:"l"},
{t:"env",w:"conservationist",s:["environmentalist","wildlife protector"],c:"环保人士",e:"The environmentalist campaigns for forests.",k:"environmentalist",p:"ˌkɒnsəˈveɪʃənɪst",pos:"n.",d:"a person who protects nature",z:"l"},
{t:"env",w:"compost heap",s:["waste pile","rotting pile"],c:"堆肥堆",e:"Vegetable scraps go on the rotting pile.",k:"rotting pile",p:"ˈkɒmpɒst hiːp",pos:"n.",d:"a pile of decaying plant waste",z:"l"},
{t:"media",w:"broadcast",s:["transmission","airing","show"],c:"广播，播出",e:"The transmission starts at nine.",k:"transmission",p:"ˈbrɔːdkɑːst",pos:"n.",d:"a programme sent by radio or TV",z:"l"},
{t:"media",w:"advertisement",s:["ad","commercial","promotion"],c:"广告",e:"The commercial aired during the match.",k:"commercial",p:"ədˈvɜːtɪsmənt",pos:"n.",d:"a notice or film that tries to sell something",z:"l"},
{t:"media",w:"headline",s:["title","main story","front page"],c:"头条",e:"The main story dominated the papers.",k:"main story",p:"ˈhedlaɪn",pos:"n.",d:"the title of a news story",z:"l"},
{t:"media",w:"subscription",s:["membership","payment plan","sign-up"],c:"订阅",e:"The membership gives full access.",k:"membership",p:"səbˈskrɪpʃn",pos:"n.",d:"paying regularly to receive a service",z:"l"},
{t:"media",w:"documentary",s:["factual film","non-fiction film","feature"],c:"纪录片",e:"The factual film explored ocean life.",k:"factual film",p:"ˌdɒkjuˈmentri",pos:"n.",d:"a film showing real facts and events",z:"l"},
{t:"media",w:"social media",s:["online platforms","social networks"],c:"社交媒体",e:"Online platforms shape public opinion.",k:"online platforms",p:"ˌsəʊʃl ˈmiːdiə",pos:"n.",d:"websites where people share content",z:"l"},
{t:"media",w:"influencer",s:["content creator","online personality"],c:"网红，影响者",e:"The content creator promoted the brand.",k:"content creator",p:"ˈɪnfluənsə",pos:"n.",d:"a person who affects others buying choices online",z:"l"},
{t:"media",w:"podcast",s:["audio show","digital broadcast"],c:"播客",e:"The audio show is free to download.",k:"audio show",p:"ˈpɒdkɑːst",pos:"n.",d:"a radio-style programme you download",z:"l"},
{t:"media",w:"streaming",s:["online watching","live streaming","digital viewing"],c:"流媒体播放",e:"Online watching replaced downloads.",k:"online watching",p:"ˈstriːmɪŋ",pos:"n.",d:"watching video over the internet",z:"l"},
{t:"media",w:"censorship",s:["control","banning","restriction"],c:"审查",e:"Control of the press increased.",k:"control",p:"ˈsensəʃɪp",pos:"n.",d:"removing or restricting content",z:"l"},
{t:"media",w:"journalist",s:["reporter","correspondent","writer"],c:"记者",e:"The reporter filed a story from the scene.",k:"reporter",p:"ˈdʒɜːnəlɪst",pos:"n.",d:"a person who writes news",z:"l"},
{t:"media",w:"audience",s:["viewers","listeners","crowd"],c:"观众",e:"Viewers can vote online.",k:"viewers",p:"ˈɔːdiəns",pos:"n.",d:"the people watching or listening",z:"l"},
{t:"media",w:"tabloid",s:["popular paper","sensational paper","red-top"],c:"小报",e:"The popular paper printed the story.",k:"popular paper",p:"ˈtæblɔɪd",pos:"n.",d:"a small newspaper with simple news",z:"l"},
{t:"media",w:"editor",s:["chief","person in charge","head"],c:"编辑",e:"The head of the section approved it.",k:"head of the section",p:"ˈedɪtə",pos:"n.",d:"a person who prepares content for publication",z:"l"},
{t:"media",w:"celebrity",s:["star","famous person","public figure"],c:"名人",e:"The star launched a new brand.",k:"star",p:"səˈlebrəti",pos:"n.",d:"a very famous person",z:"l"},
{t:"media",w:"exhibition",s:["show","display","fair"],c:"展览",e:"The show runs until Sunday.",k:"show",p:"ˌeksɪˈbɪʃn",pos:"n.",d:"a public display of art or objects",z:"l"},
{t:"media",w:"gallery",s:["art space","museum hall","exhibition room"],c:"美术馆",e:"The art space opens at ten.",k:"art space",p:"ˈɡæləri",pos:"n.",d:"a building where art is shown",z:"l"},
{t:"media",w:"heritage",s:["legacy","tradition","cultural inheritance"],c:"遗产",e:"The old town is part of our cultural inheritance.",k:"cultural inheritance",p:"ˈherɪtɪdʒ",pos:"n.",d:"things passed down from the past",z:"l"},
{t:"media",w:"folklore",s:["traditional stories","legends","folk tales"],c:"民间传说",e:"Folk tales are told at festivals.",k:"folk tales",p:"ˈfəʊklɔː",pos:"n.",d:"traditional stories of a community",z:"l"},
{t:"media",w:"masterpiece",s:["great work","masterwork","classic"],c:"杰作",e:"The painting is a true masterwork.",k:"masterwork",p:"ˈmɑːstəpiːs",pos:"n.",d:"an excellent work of art",z:"l"},
{t:"media",w:"sculpture",s:["statue","carving","figure"],c:"雕塑",e:"A bronze statue stands in the square.",k:"statue",p:"ˈskʌlptʃə",pos:"n.",d:"a work of art made from stone or metal",z:"l"},
{t:"media",w:"orchestra",s:["band","ensemble","symphony group"],c:"管弦乐团",e:"The symphony group plays tonight.",k:"symphony group",p:"ˈɔːkɪstrə",pos:"n.",d:"a large group of musicians",z:"l"},
{t:"media",w:"conductor",s:["director","leader","maestro"],c:"指挥",e:"The maestro led the final movement.",k:"maestro",p:"kənˈdʌktə",pos:"n.",d:"the person who directs an orchestra",z:"l"},
{t:"media",w:"contemporary",s:["modern","current","present-day"],c:"当代的",e:"The museum shows modern art.",k:"modern",p:"kənˈtemprəri",pos:"adj.",d:"belonging to the present time",z:"l"},
{t:"media",w:"archaeology",s:["study of the past","excavation science"],c:"考古学",e:"Excavation science uncovered a city.",k:"excavation science",p:"ˌɑːkiˈɒlədʒi",pos:"n.",d:"the study of ancient remains",z:"l"},
{t:"money",w:"loan",s:["borrowed money","credit","advance"],c:"贷款",e:"They repaid the borrowed money in five years.",k:"borrowed money",p:"ləʊn",pos:"n.",d:"money that you borrow and repay",z:"l"},
{t:"money",w:"debt",s:["money owed","arrears","obligation"],c:"债务",e:"The money owed kept growing.",k:"money owed",p:"det",pos:"n.",d:"money that you owe",z:"l"},
{t:"money",w:"savings",s:["nest egg","reserves","money put aside"],c:"储蓄",e:"Their reserves funded the trip.",k:"reserves",p:"ˈseɪvɪŋz",pos:"n.",d:"money kept for the future",z:"l"},
{t:"money",w:"interest rate",s:["borrowing cost","rate","percentage"],c:"利率",e:"The rate rose to five percent.",k:"rate",p:"ˈɪntrəst reɪt",pos:"n.",d:"the percentage charged for borrowing money",z:"l"},
{t:"money",w:"exchange rate",s:["currency rate","conversion rate"],c:"汇率",e:"The currency rate changed overnight.",k:"currency rate",p:"ɪksˈtʃeɪndʒ reɪt",pos:"n.",d:"the value of one currency against another",z:"l"},
{t:"money",w:"withdraw",s:["take out","draw out","remove"],c:"取款",e:"Take out cash at the bank.",k:"take out",p:"wɪðˈdrɔː",pos:"v.",d:"to take money out of an account",z:"l"},
{t:"money",w:"transaction",s:["payment","deal","transfer"],c:"交易",e:"Each payment is recorded online.",k:"payment",p:"trænˈzækʃn",pos:"n.",d:"an act of buying or selling",z:"l"},
{t:"money",w:"instalment",s:["part payment","monthly payment","payment plan"],c:"分期付款",e:"We paid in monthly payments.",k:"monthly payments",p:"ɪnˈstɔːlmənt",pos:"n.",d:"one part of a series of payments",z:"l"},
{t:"money",w:"penalty",s:["fine","charge","punishment"],c:"罚款",e:"Late returns carry a fine.",k:"fine",p:"ˈpenəlti",pos:"n.",d:"money paid as a punishment",z:"l"},
{t:"money",w:"credit card",s:["payment card","plastic money"],c:"信用卡",e:"She paid with a payment card.",k:"payment card",p:"ˈkredɪt kɑːd",pos:"n.",d:"a card that lets you buy now and pay later",z:"l"},
{t:"money",w:"cashless",s:["card-only","no cash","digital payment"],c:"无现金的",e:"The cafe is card-only now.",k:"card-only",p:"ˈkæʃləs",pos:"adj.",d:"not using cash",z:"l"},
{t:"money",w:"fee",s:["charge","cost","payment"],c:"费用",e:"The charge covers the whole year.",k:"charge",p:"fiː",pos:"n.",d:"money paid for a service",z:"l"},
{t:"money",w:"fine",s:["penalty","charge","payment"],c:"罚款",e:"The penalty for speeding is high.",k:"penalty",p:"faɪn",pos:"n.",d:"money paid for breaking a rule",z:"l"},
{t:"money",w:"wallet",s:["purse","money holder","billfold"],c:"钱包",e:"He left his purse on the bus.",k:"purse",p:"ˈwɒlɪt",pos:"n.",d:"a small case for money and cards",z:"l"},
{t:"money",w:"pension",s:["retirement pay","old-age income","superannuation"],c:"养老金",e:"Retirement pay rises each year.",k:"retirement pay",p:"ˈpenʃn",pos:"n.",d:"money paid to people after retirement",z:"l"},
{t:"money",w:"bank statement",s:["account record","monthly record"],c:"银行对账单",e:"Check the account record each month.",k:"account record",p:"ˈbæŋk ˌsteɪtmənt",pos:"n.",d:"a record of money in and out of an account",z:"l"},
{t:"money",w:"overdraft",s:["overdrawn amount","negative balance"],c:"透支",e:"The negative balance must be repaid.",k:"negative balance",p:"ˈəʊvədrɑːft",pos:"n.",d:"money you spend that is not in your account",z:"l"},
{t:"money",w:"currency",s:["money","legal tender","cash"],c:"货币",e:"The local money is the dollar.",k:"local money",p:"ˈkʌrənsi",pos:"n.",d:"the money used in a country",z:"l"},
{t:"money",w:"expense",s:["cost","spending","outlay"],c:"开支",e:"Travel costs were high.",k:"travel costs",p:"ɪkˈspens",pos:"n.",d:"money spent on something",z:"l"},
{t:"money",w:"grant",s:["award","funding","allowance"],c:"补助金",e:"The award covers tuition fees.",k:"award",p:"ɡrɑːnt",pos:"n.",d:"money given for study or research",z:"l"},
{t:"living",w:"wardrobe",s:["closet","cupboard","clothes storage"],c:"衣柜",e:"The closet is built into the wall.",k:"closet",p:"ˈwɔːdrəʊb",pos:"n.",d:"a cupboard for clothes",z:"l"},
{t:"living",w:"socket",s:["power point","outlet","wall plug"],c:"插座",e:"The power point is near the desk.",k:"power point",p:"ˈsɒkɪt",pos:"n.",d:"a place to plug in electrical devices",z:"l"},
{t:"living",w:"thermostat",s:["temperature control","heating dial"],c:"恒温器",e:"Set the temperature control to twenty.",k:"temperature control",p:"ˈθɜːməstæt",pos:"n.",d:"a device that controls temperature",z:"l"},
{t:"living",w:"fire drill",s:["practice evacuation","safety exercise"],c:"消防演习",e:"The practice evacuation took four minutes.",k:"practice evacuation",p:"ˈfaɪə drɪl",pos:"n.",d:"a practice of leaving a building in an emergency",z:"l"},
{t:"living",w:"receptionist",s:["front desk worker","greeter","reception staff"],c:"前台接待员",e:"The front desk worker gave us keys.",k:"front desk worker",p:"rɪˈsepʃənɪst",pos:"n.",d:"a person who welcomes visitors",z:"l"},
{t:"edu",w:"orientation",s:["induction","introduction","welcome session"],c:"迎新介绍",e:"The induction covers the campus tour.",k:"induction",p:"ˌɔːriənˈteɪʃn",pos:"n.",d:"a session that introduces new people to a place",z:"l"},
{t:"travel",w:"venue",s:["location","site","place"],c:"场地",e:"The site holds two thousand people.",k:"site",p:"ˈvenjuː",pos:"n.",d:"the place where an event happens",z:"l"},
{t:"travel",w:"attendant",s:["helper","staff member","assistant"],c:"服务员，工作人员",e:"A staff member showed us our seats.",k:"staff member",p:"əˈtendənt",pos:"n.",d:"a person whose job is to help customers",z:"l"},
];
module.exports = { V5E };