'use strict';
const V5F = [
{t:"academic",w:"imminent",s:["approaching","coming soon","near"],c:"即将发生的",e:"The deadline is approaching fast.",k:"approaching",p:"ˈɪmɪnənt",pos:"adj.",d:"likely to happen very soon",z:"w"},
{t:"academic",w:"inevitable",s:["unavoidable","certain","bound to happen"],c:"不可避免的",e:"Change is bound to happen.",k:"bound to happen",p:"ɪnˈevɪtəbl",pos:"adj.",d:"certain to happen",z:"w"},
{t:"academic",w:"phenomenon",s:["occurrence","event","development"],c:"现象",e:"Urban sprawl is a global occurrence.",k:"occurrence",p:"fəˈnɒmɪnən",pos:"n.",d:"a fact or event that can be observed",z:"w"},
{t:"academic",w:"paradigm",s:["model","framework","pattern"],c:"范式",e:"The industry needs a new model.",k:"model",p:"ˈpærədaɪm",pos:"n.",d:"a typical example or model",z:"w"},
{t:"academic",w:"enhance",s:["improve","boost","strengthen"],c:"增强",e:"Training improves worker skills.",k:"improves",p:"ɪnˈhɑːns",pos:"v.",d:"to improve the quality of something",z:"w"},
{t:"academic",w:"hamper",s:["impede","obstruct","slow down"],c:"妨碍",e:"Snow obstructed the roads.",k:"obstructed",p:"ˈhæmpə",pos:"v.",d:"to prevent something from working well",z:"w"},
{t:"academic",w:"impede",s:["block","obstruct","hinder"],c:"阻碍",e:"Bad weather blocked the rescue.",k:"blocked",p:"ɪmˈpiːd",pos:"v.",d:"to make progress difficult",z:"w"},
{t:"academic",w:"exacerbate",s:["worsen","aggravate","intensify"],c:"使恶化",e:"The cuts aggravated the crisis.",k:"aggravated",p:"ɪɡˈzæsəbeɪt",pos:"v.",d:"to make a problem worse",z:"w"},
{t:"academic",w:"reinforce",s:["strengthen","bolster","support"],c:"加强",e:"The data strengthens the argument.",k:"strengthens",p:"ˌriːɪnˈfɔːs",pos:"v.",d:"to make something stronger",z:"w"},
{t:"academic",w:"substantiate",s:["prove","support","verify"],c:"证实",e:"No evidence supports the claim.",k:"supports",p:"səbˈstænʃieɪt",pos:"v.",d:"to provide evidence for something",z:"w"},
{t:"academic",w:"corroborate",s:["confirm","verify","back up"],c:"证实",e:"Two witnesses confirm the story.",k:"confirm",p:"kəˈrɒbəreɪt",pos:"v.",d:"to support with more evidence",z:"w"},
{t:"academic",w:"juxtapose",s:["compare side by side","place together"],c:"并置对比",e:"The essay places the two policies side by side.",k:"side by side",p:"ˌdʒʌkstəˈpəʊz",pos:"v.",d:"to put things together to show contrast",z:"w"},
{t:"academic",w:"nuanced",s:["subtle","detailed","fine-grained"],c:"有细微差别的",e:"The report offers a subtle analysis.",k:"subtle",p:"ˈnjuːɑːnst",pos:"adj.",d:"showing small but important differences",z:"w"},
{t:"academic",w:"overarching",s:["overall","dominant","umbrella"],c:"总体的",e:"The overall goal is equality.",k:"overall",p:"ˌəʊvərˈɑːtʃɪŋ",pos:"adj.",d:"including or affecting everything",z:"w"},
{t:"academic",w:"dichotomy",s:["division","split","polarity"],c:"二分法",e:"The split between rich and poor grows.",k:"split",p:"daɪˈkɒtəmi",pos:"n.",d:"a division into two opposite parts",z:"w"},
{t:"academic",w:"arbitrary",s:["random","unpredictable","unreasonable"],c:"任意的",e:"The decision seemed random.",k:"random",p:"ˈɑːbɪtrəri",pos:"adj.",d:"based on chance, not reason",z:"w"},
{t:"academic",w:"pragmatic",s:["practical","realistic","sensible"],c:"务实的",e:"A practical approach works best.",k:"practical",p:"præɡˈmætɪk",pos:"adj.",d:"dealing with things sensibly",z:"w"},
{t:"academic",w:"tangible",s:["concrete","real","measurable"],c:"切实的",e:"We need concrete results.",k:"concrete",p:"ˈtændʒəbl",pos:"adj.",d:"clear and real",z:"w"},
{t:"academic",w:"myriad",s:["countless","numerous","many"],c:"无数的",e:"There are countless reasons for this.",k:"countless",p:"ˈmɪriəd",pos:"adj.",d:"very many",z:"w"},
{t:"academic",w:"burgeoning",s:["growing","expanding","flourishing"],c:"迅速增长的",e:"The growing economy needs workers.",k:"growing",p:"ˈbɜːdʒənɪŋ",pos:"adj.",d:"increasing quickly",z:"w"},
{t:"academic",w:"scarcity",s:["shortage","lack","dearth"],c:"稀缺",e:"The shortage of housing is acute.",k:"shortage",p:"ˈskeəsəti",pos:"n.",d:"a lack of something",z:"w"},
{t:"academic",w:"abundance",s:["plenty","wealth","profusion"],c:"丰富",e:"The region has plenty of water.",k:"plenty",p:"əˈbʌndəns",pos:"n.",d:"a large amount of something",z:"w"},
{t:"academic",w:"deficit",s:["shortfall","gap","lack"],c:"赤字",e:"The trade shortfall widened.",k:"shortfall",p:"ˈdefɪsɪt",pos:"n.",d:"the amount by which something is too small",z:"w"},
{t:"academic",w:"incentivise",s:["motivate","encourage","prompt"],c:"激励",e:"Bonuses motivate the staff.",k:"motivate",p:"ɪnˈsentɪvaɪz",pos:"v.",d:"to give someone a reason to act",z:"w"},
{t:"academic",w:"penalise",s:["punish","disadvantage","fine"],c:"处罚",e:"The new tax punishes polluters.",k:"punishes",p:"ˈpiːnəlaɪz",pos:"v.",d:"to treat someone unfairly as a punishment",z:"w"},
{t:"academic",w:"outweigh",s:["exceed","be greater than","prevail over"],c:"超过，比…重要",e:"The benefits exceed the costs.",k:"exceed",p:"ˌaʊtˈweɪ",pos:"v.",d:"to be more important than something",z:"w"},
{t:"academic",w:"underpin",s:["support","strengthen","sustain"],c:"支撑，巩固",e:"Trust supports the whole system.",k:"supports",p:"ˌʌndəˈpɪn",pos:"v.",d:"to form the basis of something",z:"w"},
{t:"academic",w:"relinquish",s:["give up","surrender","abandon"],c:"放弃",e:"He gave up control of the firm.",k:"gave up",p:"rɪˈlɪŋkwɪʃ",pos:"v.",d:"to give up something",z:"w"},
{t:"academic",w:"ascertain",s:["determine","find out","establish"],c:"查明",e:"We need to determine the cause.",k:"determine",p:"ˌæsəˈteɪn",pos:"v.",d:"to find out something for certain",z:"w"},
{t:"academic",w:"deem",s:["consider","regard","judge"],c:"认为",e:"The plan is considered risky.",k:"considered",p:"diːm",pos:"v.",d:"to consider or judge something",z:"w"},
{t:"travel",w:"postponement",s:["delay","putting off","deferral"],c:"推迟",e:"The delay annoyed the fans.",k:"delay",p:"pəˈspəʊnmənt",pos:"n.",d:"the act of moving something to a later time",z:"l"},
{t:"travel",w:"availability",s:["open slots","free time","capacity"],c:"可预约时间",e:"Check the open slots for Tuesday.",k:"open slots",p:"əˌveɪləˈbɪləti",pos:"n.",d:"whether something is free to use",z:"l"},
{t:"travel",w:"form",s:["application","document","questionnaire"],c:"表格",e:"Fill in the application carefully.",k:"application",p:"fɔːm",pos:"n.",d:"a paper with spaces to write information",z:"l"},
{t:"travel",w:"identification",s:["ID","proof of identity","documents"],c:"身份证明",e:"Bring proof of identity to the desk.",k:"proof of identity",p:"aɪˌdentɪfɪˈkeɪʃn",pos:"n.",d:"a document that proves who you are",z:"l"},
{t:"travel",w:"inventory",s:["stock list","catalogue","supply list"],c:"库存清单",e:"The stock list is updated daily.",k:"stock list",p:"ˈɪnvəntri",pos:"n.",d:"a list of all the goods in a place",z:"l"},
{t:"travel",w:"duplicate",s:["copy","extra copy","replica"],c:"副本",e:"Keep a copy of the form.",k:"copy",p:"ˈdjuːplɪkət",pos:"n.",d:"an exact copy of something",z:"l"},
{t:"travel",w:"confirm",s:["verify","double-check","validate"],c:"确认",e:"Please verify your booking online.",k:"verify",p:"kənˈfɜːm",pos:"v.",d:"to state that something is true or arranged",z:"l"},
{t:"travel",w:"swipe",s:["scan","slide","pass"],c:"刷卡",e:"Scan your card at the gate.",k:"scan",p:"swaɪp",pos:"v.",d:"to pass a card through a machine",z:"l"},
{t:"travel",w:"verify",s:["check","confirm","validate"],c:"核实",e:"Check your details before sending.",k:"check",p:"ˈverɪfaɪ",pos:"v.",d:"to make sure something is correct",z:"l"},
{t:"travel",w:"prior",s:["earlier","previous","beforehand"],c:"先前的",e:"No earlier booking was made.",k:"earlier",p:"ˈpraɪə",pos:"adj.",d:"happening before something else",z:"l"},
{t:"travel",w:"refreshment",s:["snack","light food","drink"],c:"茶点",e:"Light food is served at the break.",k:"light food",p:"rɪˈfreʃmənt",pos:"n.",d:"food and drink served at an event",z:"l"},
{t:"travel",w:"belongings",s:["possessions","things","personal items"],c:"随身物品",e:"Take your personal items with you.",k:"personal items",p:"bɪˈlɒŋɪŋz",pos:"n.",d:"the things that belong to you",z:"l"},
{t:"travel",w:"valuables",s:["treasures","precious items","jewellery"],c:"贵重物品",e:"Keep your precious items in the safe.",k:"precious items",p:"ˈvæljuəblz",pos:"n.",d:"things worth a lot of money",z:"l"},
{t:"travel",w:"announcement",s:["notice","statement","message"],c:"通知",e:"Listen for the notice about Gate 5.",k:"notice",p:"əˈnaʊnsmənt",pos:"n.",d:"a public statement",z:"l"},
{t:"travel",w:"switchboard",s:["phone exchange","call centre"],c:"总机",e:"The phone exchange put me through.",k:"phone exchange",p:"ˈswɪtʃbɔːd",pos:"n.",d:"a system that connects phone calls",z:"l"},
{t:"academic",w:"twofold",s:["double","twice","two times"],c:"两倍的",e:"Costs rose double last year.",k:"double",p:"ˈtuːfəʊld",pos:"adj.",d:"twice as much",z:"w"},
{t:"academic",w:"annual",s:["yearly","per year","each year"],c:"每年的",e:"Yearly sales reached a record.",k:"yearly",p:"ˈænjuəl",pos:"adj.",d:"happening every year",z:"w"},
{t:"academic",w:"quarterly",s:["every three months","per quarter"],c:"每季度的",e:"Reports are issued every three months.",k:"every three months",p:"ˈkwɔːtəli",pos:"adj.",d:"happening every three months",z:"w"},
{t:"academic",w:"aggregate",s:["total","combined","overall"],c:"总计的",e:"The combined figure is misleading.",k:"combined",p:"ˈæɡrɪɡət",pos:"adj.",d:"formed by adding several amounts",z:"w"},
{t:"academic",w:"interim",s:["temporary","provisional","trial"],c:"临时的",e:"The provisional results look good.",k:"provisional",p:"ˈɪntərɪm",pos:"adj.",d:"happening between two points in time",z:"w"},
{t:"academic",w:"subsequent",s:["following","later","ensuing"],c:"随后的",e:"The following years saw growth.",k:"following",p:"ˈsʌbsɪkwənt",pos:"adj.",d:"happening after something else",z:"w"},
{t:"academic",w:"magnitude",s:["size","scale","extent"],c:"规模，程度",e:"The scale of the problem is clear.",k:"scale",p:"ˈmæɡnɪtjuːd",pos:"n.",d:"the great size or importance of something",z:"w"},
{t:"academic",w:"capacity",s:["ability","potential","volume"],c:"能力，容量",e:"The plant has the ability to double output.",k:"ability",p:"kəˈpæsəti",pos:"n.",d:"the ability to do or contain something",z:"w"},
{t:"academic",w:"resilience",s:["toughness","recovery power","strength"],c:"韧性",e:"The economy showed strong toughness.",k:"toughness",p:"rɪˈzɪliəns",pos:"n.",d:"the ability to recover from difficulties",z:"w"},
{t:"academic",w:"volatility",s:["instability","unpredictability","fluctuation"],c:"波动性",e:"Instability in prices worried investors.",k:"instability",p:"ˌvɒləˈtɪləti",pos:"n.",d:"the tendency to change suddenly",z:"w"},
{t:"academic",w:"credibility",s:["trustworthiness","reliability","believability"],c:"可信度",e:"The scandal damaged the report trustworthiness.",k:"trustworthiness",p:"ˌkredəˈbɪləti",pos:"n.",d:"the quality of being trusted",z:"w"},
{t:"academic",w:"accountability",s:["responsibility","answerability","liability"],c:"问责制",e:"Managers must take responsibility.",k:"responsibility",p:"əˌkaʊntəˈbɪləti",pos:"n.",d:"being responsible for your actions",z:"w"},
{t:"academic",w:"transparency",s:["openness","clarity","honesty"],c:"透明度",e:"Openness builds public trust.",k:"openness",p:"trænsˈpærənsi",pos:"n.",d:"the quality of being open and clear",z:"w"},
{t:"academic",w:"equilibrium",s:["balance","stability","steady state"],c:"平衡",e:"The market reached a balance.",k:"balance",p:"ˌiːkwɪˈlɪbriəm",pos:"n.",d:"a state of balance",z:"w"},
{t:"academic",w:"trajectory",s:["path","course","direction"],c:"轨迹，趋势",e:"The path of growth continues.",k:"path",p:"trəˈdʒektəri",pos:"n.",d:"the path followed by something over time",z:"w"},
{t:"academic",w:"parameter",s:["factor","variable","limit"],c:"参数",e:"Set the key factors before the test.",k:"factors",p:"pəˈræmɪtə",pos:"n.",d:"a limit or factor that affects something",z:"w"},
{t:"academic",w:"criterion",s:["standard","benchmark","measure"],c:"标准",e:"Quality is the main standard.",k:"standard",p:"kraɪˈtɪəriən",pos:"n.",d:"a standard used to judge something",z:"w"},
{t:"academic",w:"anomaly",s:["irregularity","oddity","exception"],c:"异常",e:"The irregularity was hard to explain.",k:"irregularity",p:"əˈnɒməli",pos:"n.",d:"something that is different from normal",z:"w"},
{t:"academic",w:"nuance",s:["subtlety","shade","distinction"],c:"细微差别",e:"The subtlety of the argument is lost in translation.",k:"subtlety",p:"ˈnjuːɑːns",pos:"n.",d:"a very small difference in meaning",z:"w"},
{t:"academic",w:"succinct",s:["brief","concise","short"],c:"简洁的",e:"Keep the answer brief and clear.",k:"brief",p:"səkˈsɪŋkt",pos:"adj.",d:"expressed clearly in few words",z:"w"},
{t:"academic",w:"verbose",s:["wordy","long-winded","lengthy"],c:"冗长的",e:"The report is too wordy.",k:"wordy",p:"vɜːˈbəʊs",pos:"adj.",d:"using more words than needed",z:"w"},
{t:"academic",w:"deviate",s:["differ","diverge","stray"],c:"偏离",e:"Results diverged from the forecast.",k:"diverged",p:"ˈdiːvieɪt",pos:"v.",d:"to be different from what is expected",z:"w"},
{t:"academic",w:"conform",s:["comply","follow","obey"],c:"遵从",e:"All products must comply with the rules.",k:"comply",p:"kənˈfɔːm",pos:"v.",d:"to follow rules or standards",z:"w"},
{t:"academic",w:"augment",s:["increase","supplement","boost"],c:"增加",e:"Online sales supplement store income.",k:"supplement",p:"ɔːɡˈment",pos:"v.",d:"to make something larger",z:"w"},
{t:"academic",w:"delineate",s:["describe","outline","define"],c:"描述，界定",e:"The report outlines the main risks.",k:"outlines",p:"dɪˈlɪnieɪt",pos:"v.",d:"to describe or show something clearly",z:"w"},
];
module.exports = { V5F };