'use strict';
/* v6 ?????z = 'l' ???? / 'w' ???????????? */
const V6L = [
{t:"education",w:"suitable",s:["appropriate","fitting","right"],c:"合适的",e:"This course is appropriate for beginners.",k:"appropriate",p:"ˈsuːtəbl",pos:"adj.",d:"right for a particular purpose",z:"l"},
{t:"shopping",w:"various",s:["diverse","assorted","a range of"],c:"各种各样的",e:"The shop stocks a range of fresh bread.",k:"a range of",p:"ˈveəriəs",pos:"adj.",d:"of several different kinds",z:"l"},
{t:"living",w:"entire",s:["whole","complete","full"],c:"整个的",e:"The whole building was closed for repairs.",k:"whole",p:"ɪnˈtaɪə",pos:"adj.",d:"including every part of something",z:"l"},
{t:"media",w:"recent",s:["latest","new","up-to-date"],c:"最近的",e:"The latest figures show a steady rise.",k:"latest",p:"ˈriːsnt",pos:"adj.",d:"happening a short time ago",z:"l"},
{t:"education",w:"additional",s:["extra","further","supplementary"],c:"额外的",e:"You may need extra time for the exam.",k:"extra",p:"əˈdɪʃənl",pos:"adj.",d:"more than what already exists",z:"l"},
{t:"environment",w:"essential",s:["vital","crucial","necessary"],c:"必不可少的",e:"Clean water is vital for all living things.",k:"vital",p:"ɪˈsenʃl",pos:"adj.",d:"completely necessary",z:"l"},
{t:"media",w:"announce",s:["declare","state","make known"],c:"宣布",e:"The college declared a holiday tomorrow.",k:"declared",p:"əˈnaʊns",pos:"v.",d:"to say something publicly",z:"l"},
{t:"feelings",w:"apologise",s:["say sorry","express regret"],c:"道歉",e:"She said sorry for arriving late.",k:"said sorry",p:"əˈpɒlədʒaɪz",pos:"v.",d:"to say that you are sorry",z:"l"},
{t:"work",w:"arrange",s:["organise","set up","plan"],c:"安排",e:"The office set up a meeting for Friday.",k:"set up",p:"əˈreɪndʒ",pos:"v.",d:"to make plans for something to happen",z:"l"},
{t:"work",w:"assist",s:["help","aid","support"],c:"协助",e:"Staff will help you fill in the form.",k:"help",p:"əˈsɪst",pos:"v.",d:"to help someone do something",z:"l"},
{t:"education",w:"attend",s:["go to","be present at","join"],c:"参加",e:"All students must go to the lecture.",k:"go to",p:"əˈtend",pos:"v.",d:"to be present at an event",z:"l"},
{t:"education",w:"borrow",s:["take on loan","use temporarily"],c:"借入",e:"You can take books on loan for three weeks.",k:"take books on loan",p:"ˈbɒrəʊ",pos:"v.",d:"to take and use something that you must return",z:"l"},
{t:"living",w:"complain",s:["make a complaint","object","grumble"],c:"投诉",e:"A guest made a complaint about the noise.",k:"made a complaint",p:"kəmˈpleɪn",pos:"v.",d:"to say that you are not satisfied",z:"l"},
{t:"shopping",w:"deliver",s:["send","dispatch","hand over"],c:"递送",e:"The parcel was sent this morning.",k:"sent",p:"dɪˈlɪvə",pos:"v.",d:"to take goods to a place",z:"l"},
{t:"living",w:"disturb",s:["bother","interrupt","upset"],c:"打扰",e:"Please do not bother the neighbours after ten.",k:"bother",p:"dɪˈstɜːb",pos:"v.",d:"to interrupt someone when they are busy",z:"l"},
{t:"education",w:"enquire",s:["ask about","look into","find out"],c:"询问",e:"Call the office to ask about fees.",k:"ask about",p:"ɪnˈkwaɪə",pos:"v.",d:"to ask for information",z:"l"},
{t:"work",w:"inform",s:["tell","notify","let know"],c:"告知",e:"We will notify you by email.",k:"notify",p:"ɪnˈfɔːm",pos:"v.",d:"to give someone information",z:"l"},
{t:"shopping",w:"insist",s:["demand","maintain","stress"],c:"坚持",e:"She demanded a written receipt.",k:"demanded",p:"ɪnˈsɪst",pos:"v.",d:"to say firmly that something must happen",z:"l"},
{t:"feelings",w:"interrupt",s:["break in","cut in","disturb"],c:"打断",e:"He cut in while she was speaking.",k:"cut in",p:"ˌɪntəˈrʌpt",pos:"v.",d:"to stop someone while they are speaking",z:"l"},
{t:"travel",w:"invite",s:["ask","request the presence of"],c:"邀请",e:"They asked us to the opening ceremony.",k:"asked",p:"ɪnˈvaɪt",pos:"v.",d:"to ask someone to come to an event",z:"l"},
{t:"shopping",w:"order",s:["request","book","purchase"],c:"订购",e:"We requested two extra chairs.",k:"requested",p:"ˈɔːdə",pos:"v.",d:"to ask for something to be made or delivered",z:"l"},
{t:"health",w:"remind",s:["prompt","tell again","jog the memory"],c:"提醒",e:"The app prompts you to drink water.",k:"prompts",p:"rɪˈmaɪnd",pos:"v.",d:"to help someone remember something",z:"l"},
{t:"travel",w:"require",s:["need","demand","call for"],c:"需要",e:"The visa needs a valid passport.",k:"needs",p:"rɪˈkwaɪə",pos:"v.",d:"to need something",z:"l"},
{t:"food",w:"reserve",s:["book","secure","hold"],c:"预订",e:"We booked a table for eight.",k:"booked",p:"rɪˈzɜːv",pos:"v.",d:"to arrange for a seat or room to be kept",z:"l"},
{t:"shopping",w:"satisfy",s:["meet","fulfil","please"],c:"满足",e:"The service meets all our needs.",k:"meets",p:"ˈsætɪsfaɪ",pos:"v.",d:"to be enough for someone's needs",z:"l"},
{t:"travel",w:"appear",s:["show up","turn up","emerge"],c:"出现",e:"The bus failed to show up on time.",k:"show up",p:"əˈpɪə",pos:"v.",d:"to start to be seen",z:"l"},
{t:"feelings",w:"appreciate",s:["be grateful for","value","thank"],c:"感激",e:"We are grateful for your support.",k:"grateful for",p:"əˈpriːʃieɪt",pos:"v.",d:"to be thankful for something",z:"l"},
{t:"education",w:"assess",s:["evaluate","judge","appraise"],c:"评估",e:"Tutors evaluate your progress each term.",k:"evaluate",p:"əˈses",pos:"v.",d:"to judge how good or important something is",z:"l"},
{t:"travel",w:"avoid",s:["keep away from","steer clear of","dodge"],c:"避免",e:"Keep away from the city at rush hour.",k:"keep away from",p:"əˈvɔɪd",pos:"v.",d:"to stay away from something",z:"l"},
{t:"education",w:"collect",s:["gather","pick up","accumulate"],c:"收集",e:"Please gather your results at reception.",k:"gather",p:"kəˈlekt",pos:"v.",d:"to bring things together",z:"l"},
{t:"travel",w:"combine",s:["merge","mix","blend"],c:"结合",e:"The tour blends history with art.",k:"blends",p:"kəmˈbaɪn",pos:"v.",d:"to join two or more things together",z:"l"},
{t:"work",w:"complete",s:["finish","fill in","finalise"],c:"完成",e:"Fill in the form and send it back.",k:"fill in",p:"kəmˈpliːt",pos:"v.",d:"to finish doing something",z:"l"},
{t:"living",w:"connect",s:["link","join","hook up"],c:"连接",e:"The lounge links the two halls.",k:"links",p:"kəˈnekt",pos:"v.",d:"to join two things together",z:"l"},
{t:"living",w:"convert",s:["change","transform","turn into"],c:"转换",e:"They changed the garage into a studio.",k:"changed",p:"kənˈvɜːt",pos:"v.",d:"to change something into a different form",z:"l"},
{t:"feelings",w:"convince",s:["persuade","win over","talk into"],c:"说服",e:"She persuaded me to join the club.",k:"persuaded",p:"kənˈvɪns",pos:"v.",d:"to make someone believe something",z:"l"},
{t:"feelings",w:"cope",s:["manage","deal with","handle"],c:"应对",e:"He finds it hard to deal with pressure.",k:"deal with",p:"kəʊp",pos:"v.",d:"to deal successfully with a problem",z:"l"},
{t:"money",w:"cost",s:["price","charge","expense"],c:"费用，成本",e:"The charge includes breakfast.",k:"charge",p:"kɒst",pos:"n.",d:"the amount of money needed to buy something",z:"l"},
{t:"living",w:"cover",s:["include","take in","span"],c:"涵盖",e:"The fee includes all materials.",k:"includes",p:"ˈkʌvə",pos:"v.",d:"to include or deal with something",z:"l"},
{t:"travel",w:"declare",s:["state","announce","reveal"],c:"申报，宣布",e:"You must state the value of the goods.",k:"state",p:"dɪˈkleə",pos:"v.",d:"to say something officially",z:"l"},
{t:"money",w:"decline",s:["fall","drop","go down"],c:"下降",e:"Sales fell by ten per cent last year.",k:"fell",p:"dɪˈklaɪn",pos:"v.",d:"to become smaller or less",z:"l"},
{t:"education",w:"define",s:["explain","describe","clarify"],c:"定义",e:"Please explain the term in your own words.",k:"explain",p:"dɪˈfaɪn",pos:"v.",d:"to say what a word means",z:"l"},
{t:"feelings",w:"depend",s:["rely on","count on","be based on"],c:"依赖，取决于",e:"You can rely on the bus timetable.",k:"rely on",p:"dɪˈpend",pos:"v.",d:"to need someone or something for support",z:"l"},
{t:"work",w:"describe",s:["outline","depict","explain"],c:"描述",e:"Outline your duties in the report.",k:"outline",p:"dɪˈskraɪb",pos:"v.",d:"to say what something is like",z:"l"},
{t:"work",w:"design",s:["plan","devise","draft"],c:"设计",e:"They planned a new layout for the office.",k:"planned",p:"dɪˈzaɪn",pos:"v.",d:"to plan how something will look or work",z:"l"},
{t:"environment",w:"destroy",s:["ruin","demolish","wreck"],c:"破坏",e:"The flood ruined many homes.",k:"ruined",p:"dɪˈstrɔɪ",pos:"v.",d:"to damage something so badly that it cannot be used",z:"l"},
{t:"feelings",w:"devote",s:["dedicate","commit","give"],c:"投入",e:"She dedicated her time to charity work.",k:"dedicated",p:"dɪˈvəʊt",pos:"v.",d:"to give a lot of time or effort to something",z:"l"},
{t:"travel",w:"disappear",s:["vanish","fade away","go"],c:"消失",e:"The mist vanished by noon.",k:"vanished",p:"ˌdɪsəˈpɪə",pos:"v.",d:"to no longer be seen",z:"l"},
{t:"education",w:"discover",s:["find out","uncover","detect"],c:"发现",e:"Find out the opening times online.",k:"find out",p:"dɪˈskʌvə",pos:"v.",d:"to find something for the first time",z:"l"},
{t:"education",w:"distinguish",s:["tell apart","differentiate","separate"],c:"区分",e:"It is hard to tell apart the two designs.",k:"tell apart",p:"dɪˈstɪŋɡwɪʃ",pos:"v.",d:"to see the difference between things",z:"l"},
{t:"work",w:"divide",s:["split","separate","share out"],c:"划分",e:"The class was split into four groups.",k:"split",p:"dɪˈvaɪd",pos:"v.",d:"to separate into parts",z:"l"},
{t:"money",w:"donate",s:["give","contribute","pledge"],c:"捐赠",e:"Please give generously to the appeal.",k:"give",p:"dəʊˈneɪt",pos:"v.",d:"to give money or goods to help others",z:"l"},
{t:"travel",w:"drop",s:["fall","decrease","decline"],c:"下降，掉落",e:"The temperature fell sharply at night.",k:"fell",p:"drɒp",pos:"v.",d:"to fall to a lower level",z:"l"},
{t:"work",w:"earn",s:["make","gain","receive"],c:"赚取",e:"She makes a good salary in the city.",k:"makes",p:"ɜːn",pos:"v.",d:"to get money for work you do",z:"l"},
{t:"technology",w:"edit",s:["revise","amend","correct"],c:"编辑",e:"Revise the text before sending it.",k:"revise",p:"ˈedɪt",pos:"v.",d:"to change written material",z:"l"},
{t:"education",w:"educate",s:["teach","instruct","train"],c:"教育",e:"The museum teaches children about science.",k:"teaches",p:"ˈedʒukeɪt",pos:"v.",d:"to teach someone over a period of time",z:"l"},
{t:"feelings",w:"engage",s:["take part","participate","get involved"],c:"参与",e:"Take part in the group discussion.",k:"take part",p:"ɪnˈɡeɪdʒ",pos:"v.",d:"to become involved in an activity",z:"l"},
{t:"education",w:"enter",s:["join","go into","sign up for"],c:"进入，报名",e:"She signed up for the writing course.",k:"signed up for",p:"ˈentə",pos:"v.",d:"to join an event or place",z:"l"},
{t:"work",w:"equip",s:["provide","supply","fit out"],c:"配备",e:"The lab is fitted out with new computers.",k:"fitted out",p:"ɪˈkwɪp",pos:"v.",d:"to provide with the necessary items",z:"l"},
{t:"travel",w:"escape",s:["get away","flee","break free"],c:"逃脱",e:"We want to get away for the weekend.",k:"get away",p:"ɪˈskeɪp",pos:"v.",d:"to get free from a place or situation",z:"l"},
{t:"work",w:"establish",s:["set up","found","create"],c:"建立",e:"The company set up a new branch.",k:"set up",p:"ɪˈstæblɪʃ",pos:"v.",d:"to start an organisation",z:"l"},
{t:"work",w:"expand",s:["grow","extend","spread"],c:"扩大",e:"The firm plans to extend its offices.",k:"extend",p:"ɪkˈspænd",pos:"v.",d:"to become larger",z:"l"},
{t:"feelings",w:"expect",s:["anticipate","await","predict"],c:"期待，预期",e:"We anticipate a large crowd tonight.",k:"anticipate",p:"ɪkˈspekt",pos:"v.",d:"to think something will happen",z:"l"},
{t:"environment",w:"exist",s:["be present","occur","survive"],c:"存在",e:"These plants are present in dry areas.",k:"present",p:"ɪɡˈzɪst",pos:"v.",d:"to be real or found in a place",z:"l"},
{t:"travel",w:"explore",s:["tour","discover","look around"],c:"探索",e:"We toured the old town on foot.",k:"toured",p:"ɪkˈsplɔː",pos:"v.",d:"to travel around a place to learn about it",z:"l"},
{t:"work",w:"express",s:["convey","state","voice"],c:"表达",e:"Convey your ideas clearly in the essay.",k:"convey",p:"ɪkˈspres",pos:"v.",d:"to show or say what you think",z:"l"},
{t:"work",w:"extend",s:["lengthen","prolong","stretch"],c:"延长",e:"The library prolonged its opening hours.",k:"prolonged",p:"ɪkˈstend",pos:"v.",d:"to make something longer",z:"l"},
{t:"feelings",w:"face",s:["confront","deal with","encounter"],c:"面对",e:"Workers now confront a new challenge.",k:"confront",p:"feɪs",pos:"v.",d:"to deal with a difficult situation",z:"l"},
{t:"media",w:"feature",s:["include","present","highlight"],c:"以…为特色",e:"The programme highlights local artists.",k:"highlights",p:"ˈfiːtʃə",pos:"v.",d:"to include something as an important part",z:"l"},
{t:"living",w:"fill",s:["complete","occupy","stuff"],c:"填写，装满",e:"Complete the form in black ink.",k:"complete",p:"fɪl",pos:"v.",d:"to put something into a space or form",z:"l"},
{t:"living",w:"fix",s:["repair","mend","sort out"],c:"修理，固定",e:"A plumber will mend the tap tomorrow.",k:"mend",p:"fɪks",pos:"v.",d:"to repair something",z:"l"},
{t:"education",w:"focus",s:["concentrate","centre on","direct"],c:"集中",e:"Concentrate on the main question.",k:"concentrate",p:"ˈfəʊkəs",pos:"v.",d:"to give attention to one thing",z:"l"},
{t:"work",w:"follow",s:["obey","stick to","go along with"],c:"遵循",e:"Stick to the safety rules at all times.",k:"stick to",p:"ˈfɒləʊ",pos:"v.",d:"to do what someone tells you to do",z:"l"},
{t:"health",w:"forgive",s:["pardon","excuse","overlook"],c:"原谅",e:"Please pardon my late reply.",k:"pardon",p:"fəˈɡɪv",pos:"v.",d:"to stop being angry with someone",z:"l"},
{t:"work",w:"found",s:["establish","set up","create"],c:"创立",e:"The school was established in 1960.",k:"established",p:"faʊnd",pos:"v.",d:"to start an organisation or city",z:"l"},
{t:"food",w:"freeze",s:["chill","ice over","solidify"],c:"冷冻",e:"Chill the soup before serving.",k:"chill",p:"friːz",pos:"v.",d:"to make something very cold",z:"l"},
{t:"work",w:"function",s:["work","operate","run"],c:"运转",e:"The lift is working again.",k:"working",p:"ˈfʌŋkʃn",pos:"v.",d:"to work in the correct way",z:"l"},
{t:"education",w:"gather",s:["collect","assemble","bring together"],c:"聚集，收集",e:"The group assembled in the hall.",k:"assembled",p:"ˈɡæðə",pos:"v.",d:"to come together in a group",z:"l"},
{t:"science",w:"generate",s:["produce","create","make"],c:"产生",e:"The panels produce clean electricity.",k:"produce",p:"ˈdʒenəreɪt",pos:"v.",d:"to create energy or heat",z:"l"},
{t:"feelings",w:"glance",s:["look quickly","peek","scan"],c:"瞥一眼",e:"She peeked at her phone during class.",k:"peeked",p:"ɡlɑːns",pos:"v.",d:"to look at something quickly",z:"l"},
{t:"education",w:"graduate",s:["finish","complete a degree","qualify"],c:"毕业",e:"He completed his degree in 2020.",k:"completed his degree",p:"ˈɡrædʒueɪt",pos:"v.",d:"to finish a course at university",z:"l"},
{t:"work",w:"handle",s:["deal with","manage","cope with"],c:"处理",e:"The team deals with customer questions.",k:"deals with",p:"ˈhændl",pos:"v.",d:"to deal with a situation or person",z:"l"},
{t:"living",w:"hang",s:["suspend","attach","put up"],c:"悬挂",e:"Put up the picture near the window.",k:"put up",p:"hæŋ",pos:"v.",d:"to fix something at the top so it swings",z:"l"},
{t:"health",w:"harm",s:["damage","hurt","injure"],c:"伤害",e:"Smoking damages your lungs.",k:"damages",p:"hɑːm",pos:"v.",d:"to hurt or damage something",z:"l"},
{t:"science",w:"harvest",s:["gather","collect","reap"],c:"收割",e:"Farmers reap the wheat in August.",k:"reap",p:"ˈhɑːvɪst",pos:"v.",d:"to collect crops from the fields",z:"l"},
{t:"living",w:"heat",s:["warm up","warm","cook"],c:"加热",e:"Warm up the soup in a pan.",k:"warm up",p:"hiːt",pos:"v.",d:"to make something hot",z:"l"},
{t:"living",w:"hide",s:["conceal","cover","disguise"],c:"隐藏",e:"The camera was concealed behind a mirror.",k:"concealed",p:"haɪd",pos:"v.",d:"to put something where it cannot be seen",z:"l"},
{t:"work",w:"hold",s:["organise","host","run"],c:"举办，持有",e:"The city hosted the sports event.",k:"hosted",p:"həʊld",pos:"v.",d:"to organise an event",z:"l"},
{t:"travel",w:"host",s:["receive","welcome","entertain"],c:"主办，招待",e:"The hotel welcomed the visiting team.",k:"welcomed",p:"həʊst",pos:"v.",d:"to entertain guests at an event",z:"l"},
{t:"environment",w:"hunt",s:["chase","pursue","search for"],c:"打猎，寻找",e:"The cat chased the bird across the yard.",k:"chased",p:"hʌnt",pos:"v.",d:"to chase animals or search for something",z:"l"},
{t:"feelings",w:"ignore",s:["pay no attention to","overlook","neglect"],c:"忽视",e:"Do not overlook the small print.",k:"overlook",p:"ɪɡˈnɔː",pos:"v.",d:"to pay no attention to something",z:"l"},
{t:"education",w:"imagine",s:["picture","envisage","visualise"],c:"想象",e:"Picture yourself at the interview.",k:"picture",p:"ɪˈmædʒɪn",pos:"v.",d:"to form a picture in your mind",z:"l"},
{t:"shopping",w:"import",s:["bring in","buy from abroad"],c:"进口",e:"The country brings in coffee from Brazil.",k:"brings in",p:"ɪmˈpɔːt",pos:"v.",d:"to bring goods into a country to sell",z:"l"},
{t:"feelings",w:"impress",s:["strike","amaze","wow"],c:"给…留下印象",e:"The view amazed every visitor.",k:"amazed",p:"ɪmˈpres",pos:"v.",d:"to make someone admire you",z:"l"},
{t:"family",w:"inherit",s:["receive","come into","take over"],c:"继承",e:"She came into a large fortune.",k:"came into",p:"ɪnˈherɪt",pos:"v.",d:"to receive money or property from someone who has died",z:"l"},
{t:"work",w:"inspect",s:["check","examine","review"],c:"检查",e:"Officials checked every package.",k:"checked",p:"ɪnˈspekt",pos:"v.",d:"to look at something carefully to check it",z:"l"},
{t:"feelings",w:"inspire",s:["motivate","encourage","stimulate"],c:"激励",e:"Her story motivated the whole team.",k:"motivated",p:"ɪnˈspaɪə",pos:"v.",d:"to make someone want to do something",z:"l"},
{t:"living",w:"install",s:["fit","set up","put in"],c:"安装",e:"They fitted a new shower yesterday.",k:"fitted",p:"ɪnˈstɔːl",pos:"v.",d:"to put equipment in place and make it work",z:"l"},
{t:"feelings",w:"intend",s:["plan","aim","mean"],c:"打算",e:"We plan to arrive before noon.",k:"plan",p:"ɪnˈtend",pos:"v.",d:"to have something in mind to do",z:"l"},
{t:"education",w:"interact",s:["communicate","mix","socialise"],c:"互动",e:"Students communicate well in groups.",k:"communicate",p:"ˌɪntərˈækt",pos:"v.",d:"to talk and work with other people",z:"l"},
{t:"travel",w:"interpret",s:["translate","explain","decode"],c:"口译，解释",e:"She translated the talk for visitors.",k:"translated",p:"ɪnˈtɜːprɪt",pos:"v.",d:"to change spoken words into another language",z:"l"},
{t:"feelings",w:"introduce",s:["present","bring in","launch"],c:"介绍，引进",e:"The firm launched a new product.",k:"launched",p:"ˌɪntrəˈdjuːs",pos:"v.",d:"to make someone known to others",z:"l"},
{t:"science",w:"invent",s:["create","devise","design"],c:"发明",e:"They devised a new type of battery.",k:"devised",p:"ɪnˈvent",pos:"v.",d:"to design something that did not exist before",z:"l"},
{t:"money",w:"invest",s:["put money into","fund","finance"],c:"投资",e:"The firm put money into new equipment.",k:"put money into",p:"ɪnˈvest",pos:"v.",d:"to spend money to make a profit",z:"l"},
{t:"work",w:"join",s:["become a member of","enrol in","sign up"],c:"加入",e:"She enrolled in the evening class.",k:"enrolled in",p:"dʒɔɪn",pos:"v.",d:"to become part of a group or club",z:"l"},
{t:"feelings",w:"judge",s:["assess","evaluate","rate"],c:"评判",e:"The panel rated each speech.",k:"rated",p:"dʒʌdʒ",pos:"v.",d:"to form an opinion about something",z:"l"},
{t:"work",w:"launch",s:["start","introduce","begin"],c:"发起，推出",e:"They began a new advertising campaign.",k:"began",p:"lɔːntʃ",pos:"v.",d:"to start something new, such as a product",z:"l"},
{t:"living",w:"lay",s:["place","put","set"],c:"放置，铺设",e:"Place the plates on the table.",k:"place",p:"leɪ",pos:"v.",d:"to put something down carefully",z:"l"},
{t:"money",w:"lend",s:["loan","advance","give credit"],c:"借出",e:"The bank loaned her the money.",k:"loaned",p:"lend",pos:"v.",d:"to give something to someone who must return it",z:"l"},
{t:"health",w:"lie",s:["recline","rest","stretch out"],c:"躺",e:"Rest on the bed for a while.",k:"rest",p:"laɪ",pos:"v.",d:"to be in a flat position",z:"l"},
{t:"travel",w:"locate",s:["find","pinpoint","situate"],c:"定位，位于",e:"Find the museum on the map.",k:"find",p:"ləʊˈkeɪt",pos:"v.",d:"to find the exact position of something",z:"l"},
{t:"living",w:"lock",s:["secure","fasten","bolt"],c:"锁",e:"Secure the door before leaving.",k:"secure",p:"lɒk",pos:"v.",d:"to close something with a key",z:"l"},
{t:"work",w:"maintain",s:["keep up","preserve","sustain"],c:"维持，保养",e:"Keep up a regular study routine.",k:"keep up",p:"meɪnˈteɪn",pos:"v.",d:"to make something continue at the same level",z:"l"},
{t:"work",w:"manage",s:["run","operate","head"],c:"管理",e:"She runs the local branch.",k:"runs",p:"ˈmænɪdʒ",pos:"v.",d:"to be in charge of a business or team",z:"l"},
{t:"education",w:"match",s:["correspond","fit","equal"],c:"匹配",e:"The password must fit the records.",k:"fit",p:"mætʃ",pos:"v.",d:"to be the same as or suitable for something",z:"l"},
{t:"science",w:"monitor",s:["track","observe","watch"],c:"监控",e:"Nurses track the patient's heart rate.",k:"track",p:"ˈmɒnɪtə",pos:"v.",d:"to watch something over a period of time",z:"l"},
{t:"work",w:"applicant",s:["candidate","job seeker","contender"],c:"申请人",e:"Each candidate gave a short talk.",k:"candidate",p:"ˈæplɪkənt",pos:"n.",d:"a person who applies for a job or place",z:"l"},
{t:"work",w:"branch",s:["office","outlet","division"],c:"分部，分行",e:"The bank opened a new outlet in town.",k:"outlet",p:"brɑːntʃ",pos:"n.",d:"a local office of a large organisation",z:"l"},
{t:"work",w:"candidate",s:["applicant","contender","nominee"],c:"候选人",e:"The successful applicant starts on Monday.",k:"applicant",p:"ˈkændɪdət",pos:"n.",d:"a person competing for a job or position",z:"l"},
{t:"education",w:"choice",s:["option","selection","pick"],c:"选择",e:"There is a wide option of courses.",k:"option",p:"tʃɔɪs",pos:"n.",d:"the act of choosing between things",z:"l"},
{t:"living",w:"condition",s:["state","situation","circumstance"],c:"状况，条件",e:"The flat is in good state.",k:"state",p:"kənˈdɪʃn",pos:"n.",d:"the physical state of something",z:"l"},
{t:"work",w:"consultant",s:["advisor","specialist","expert"],c:"顾问",e:"An advisor will review your plan.",k:"advisor",p:"kənˈsʌltənt",pos:"n.",d:"an expert who gives advice",z:"l"},
{t:"work",w:"contact",s:["details","information","number"],c:"联系方式",e:"Leave your details at reception.",k:"details",p:"ˈkɒntækt",pos:"n.",d:"the details used to communicate with someone",z:"l"},
{t:"work",w:"contract",s:["agreement","deal","terms"],c:"合同",e:"Read the agreement before signing.",k:"agreement",p:"ˈkɒntrækt",pos:"n.",d:"a legal written agreement",z:"l"},
{t:"shopping",w:"coupon",s:["voucher","discount code","token"],c:"优惠券",e:"Use this voucher for ten per cent off.",k:"voucher",p:"ˈkuːpɒn",pos:"n.",d:"a ticket that gives a discount",z:"l"},
{t:"travel",w:"distance",s:["length","gap","space"],c:"距离",e:"The length of the walk is five miles.",k:"length",p:"ˈdɪstəns",pos:"n.",d:"the amount of space between two places",z:"l"},
{t:"work",w:"duration",s:["length","period","time"],c:"持续时间",e:"The length of the tour is two hours.",k:"length",p:"djuˈreɪʃn",pos:"n.",d:"the time that something lasts",z:"l"},
{t:"travel",w:"fare",s:["price","charge","ticket cost"],c:"车费",e:"The ticket cost has risen again.",k:"ticket cost",p:"feə",pos:"n.",d:"the money paid for a journey",z:"l"},
{t:"science",w:"fuel",s:["energy source","petrol","power"],c:"燃料",e:"The van uses very little petrol.",k:"petrol",p:"ˈfjuːəl",pos:"n.",d:"a substance burned to produce energy",z:"l"},
{t:"living",w:"garage",s:["workshop","car park","shed"],c:"车库，修车厂",e:"The car is in the workshop.",k:"workshop",p:"ˈɡærɑːʒ",pos:"n.",d:"a building where cars are kept or repaired",z:"l"},
{t:"education",w:"guidance",s:["advice","direction","support"],c:"指导",e:"Ask your tutor for advice.",k:"advice",p:"ˈɡaɪdns",pos:"n.",d:"help and advice about what to do",z:"l"},
{t:"health",w:"gym",s:["fitness centre","sports hall","training room"],c:"健身房",e:"The fitness centre opens at six.",k:"fitness centre",p:"dʒɪm",pos:"n.",d:"a place with equipment for exercise",z:"l"},
{t:"feelings",w:"intention",s:["plan","aim","purpose"],c:"意图",e:"Her aim is to study abroad.",k:"aim",p:"ɪnˈtenʃn",pos:"n.",d:"something you plan to do",z:"l"},
{t:"travel",w:"intersection",s:["crossroads","junction","crossing"],c:"交叉路口",e:"Turn left at the crossroads.",k:"crossroads",p:"ˌɪntəˈsekʃn",pos:"n.",d:"a place where roads meet",z:"l"},
{t:"money",w:"invoice",s:["bill","statement","receipt"],c:"发票",e:"Send the bill to our office.",k:"bill",p:"ˈɪnvɔɪs",pos:"n.",d:"a list of goods with the price to pay",z:"l"},
{t:"travel",w:"lane",s:["strip","track","carriageway"],c:"车道",e:"Stay in the middle carriageway.",k:"carriageway",p:"leɪn",pos:"n.",d:"a part of a road for one line of traffic",z:"l"},
{t:"living",w:"lawn",s:["grass","green","garden"],c:"草坪",e:"The children played on the grass.",k:"grass",p:"lɔːn",pos:"n.",d:"an area of short grass in a garden",z:"l"},
{t:"work",w:"licence",s:["permit","certificate","authorisation"],c:"执照，许可证",e:"You need a permit to fish here.",k:"permit",p:"ˈlaɪsns",pos:"n.",d:"an official document allowing something",z:"l"},
{t:"living",w:"lift",s:["elevator","hoist","upward journey"],c:"电梯",e:"Take the elevator to the tenth floor.",k:"elevator",p:"lɪft",pos:"n.",d:"a machine that carries people between floors",z:"l"},
{t:"work",w:"manual",s:["handbook","guide","instructions"],c:"手册",e:"Read the handbook before use.",k:"handbook",p:"ˈmænjuəl",pos:"n.",d:"a book of instructions",z:"l"},
{t:"shopping",w:"membership",s:["subscription","enrolment","joining"],c:"会员资格",e:"The subscription costs forty pounds a year.",k:"subscription",p:"ˈmembəʃɪp",pos:"n.",d:"the state of being a member",z:"l"},
{t:"food",w:"menu",s:["list of dishes","bill of fare"],c:"菜单",e:"Check the list of dishes online.",k:"list of dishes",p:"ˈmenjuː",pos:"n.",d:"a list of food available in a restaurant",z:"l"},
{t:"health",w:"operation",s:["surgery","procedure","treatment"],c:"手术，运作",e:"The surgery took two hours.",k:"surgery",p:"ˌɒpəˈreɪʃn",pos:"n.",d:"a medical procedure on the body",z:"l"},
{t:"education",w:"option",s:["choice","alternative","possibility"],c:"选项",e:"There is a cheaper alternative.",k:"alternative",p:"ˈɒpʃn",pos:"n.",d:"one thing you can choose",z:"l"},
{t:"shopping",w:"package",s:["bundle","deal","set"],c:"套餐，包裹",e:"The bundle includes two nights.",k:"bundle",p:"ˈpækɪdʒ",pos:"n.",d:"a set of things offered together",z:"l"},
{t:"travel",w:"parking",s:["car park","parking space","lot"],c:"停车",e:"There is a car park behind the store.",k:"car park",p:"ˈpɑːkɪŋ",pos:"n.",d:"a place where cars can be left",z:"l"},
{t:"money",w:"payment",s:["charge","settlement","instalment"],c:"付款",e:"The first settlement is due today.",k:"settlement",p:"ˈpeɪmənt",pos:"n.",d:"an amount of money paid",z:"l"},
{t:"work",w:"permission",s:["consent","approval","authorisation"],c:"许可",e:"You need consent from the manager.",k:"consent",p:"pəˈmɪʃn",pos:"n.",d:"the right to do something given by someone in charge",z:"l"},
{t:"education",w:"possibility",s:["chance","likelihood","prospect"],c:"可能性",e:"There is a chance of rain today.",k:"chance",p:"ˌpɒsəˈbɪləti",pos:"n.",d:"something that may happen",z:"l"},
{t:"health",w:"precaution",s:["safety measure","safeguard","protection"],c:"预防措施",e:"Wear gloves as a safety measure.",k:"safety measure",p:"prɪˈkɔːʃn",pos:"n.",d:"something done to prevent harm",z:"l"},
{t:"work",w:"priority",s:["first concern","preference","main focus"],c:"优先事项",e:"Safety is our first concern.",k:"first concern",p:"praɪˈɒrəti",pos:"n.",d:"the thing that is most important",z:"l"},
{t:"work",w:"process",s:["procedure","method","system"],c:"流程",e:"The application procedure takes a week.",k:"procedure",p:"ˈprəʊses",pos:"n.",d:"a series of steps to achieve something",z:"l"},
{t:"media",w:"programme",s:["show","broadcast","series"],c:"节目，项目",e:"The show starts at eight.",k:"show",p:"ˈprəʊɡræm",pos:"n.",d:"a television or radio show",z:"l"},
{t:"work",w:"progress",s:["development","advance","improvement"],c:"进展",e:"The team made good development this month.",k:"development",p:"ˈprəʊɡres",pos:"n.",d:"the process of improving",z:"l"},
{t:"work",w:"proposal",s:["plan","suggestion","scheme"],c:"提议",e:"The plan was approved yesterday.",k:"plan",p:"prəˈpəʊzl",pos:"n.",d:"a formal suggestion",z:"l"},
{t:"environment",w:"protection",s:["safeguard","defence","security"],c:"保护",e:"The law offers safeguard for wildlife.",k:"safeguard",p:"prəˈtekʃn",pos:"n.",d:"the act of keeping something safe",z:"l"},
{t:"shopping",w:"quantity",s:["amount","volume","number"],c:"数量",e:"Order a large amount of paper.",k:"amount",p:"ˈkwɒntəti",pos:"n.",d:"how much of something there is",z:"l"},
{t:"education",w:"quiz",s:["test","game","questionnaire"],c:"小测验",e:"We have a short test on Friday.",k:"test",p:"kwɪz",pos:"n.",d:"a short test of knowledge",z:"l"},
{t:"work",w:"recommendation",s:["advice","suggestion","reference"],c:"推荐",e:"Follow the tutor's advice.",k:"advice",p:"ˌrekəmenˈdeɪʃn",pos:"n.",d:"a suggestion about the best course of action",z:"l"},
{t:"work",w:"record",s:["register","log","file"],c:"记录",e:"Keep a register of all visitors.",k:"register",p:"ˈrekɔːd",pos:"n.",d:"a written account of something",z:"l"},
{t:"feelings",w:"relationship",s:["connection","bond","link"],c:"关系",e:"There is a strong bond between them.",k:"bond",p:"rɪˈleɪʃnʃɪp",pos:"n.",d:"the way people feel about each other",z:"l"},
{t:"living",w:"removal",s:["moving","transfer","relocation"],c:"搬迁",e:"The moving company arrives at nine.",k:"moving",p:"rɪˈmuːvl",pos:"n.",d:"the act of taking something away",z:"l"},
{t:"work",w:"reward",s:["prize","bonus","benefit"],c:"奖励",e:"There is a prize for the best essay.",k:"prize",p:"rɪˈwɔːd",pos:"n.",d:"something given for good work",z:"l"},
{t:"environment",w:"rubbish",s:["waste","garbage","litter"],c:"垃圾",e:"Put the waste in the green bin.",k:"waste",p:"ˈrʌbɪʃ",pos:"n.",d:"things that are thrown away",z:"l"},
{t:"work",w:"safety",s:["security","protection","welfare"],c:"安全",e:"Security is checked at the entrance.",k:"security",p:"ˈseɪfti",pos:"n.",d:"the state of being free from danger",z:"l"},
{t:"work",w:"schedule",s:["timetable","plan","programme"],c:"时间表",e:"The timetable changed last week.",k:"timetable",p:"ˈʃedjuːl",pos:"n.",d:"a plan of times for events",z:"l"},
{t:"environment",w:"shelter",s:["protection","refuge","cover"],c:"庇护所",e:"The birds found refuge in the trees.",k:"refuge",p:"ˈʃeltə",pos:"n.",d:"a place that protects you from danger",z:"l"},
{t:"living",w:"situation",s:["circumstances","state","position"],c:"情况",e:"The circumstances have changed completely.",k:"circumstances",p:"ˌsɪtʃuˈeɪʃn",pos:"n.",d:"the conditions at a particular time",z:"l"},
{t:"education",w:"source",s:["origin","starting point","basis"],c:"来源",e:"Check the origin of the information.",k:"origin",p:"sɔːs",pos:"n.",d:"the place where something comes from",z:"l"},
{t:"living",w:"standard",s:["level","quality","norm"],c:"标准",e:"The hotel has a high quality of service.",k:"quality",p:"ˈstændəd",pos:"n.",d:"a level of quality",z:"l"},
{t:"work",w:"stationery",s:["office supplies","paper goods","materials"],c:"文具",e:"Buy office supplies from the shop.",k:"office supplies",p:"ˈsteɪʃənəri",pos:"n.",d:"materials for writing, such as paper and pens",z:"l"},
{t:"work",w:"strategy",s:["plan","approach","method"],c:"策略",e:"We need a better approach to revision.",k:"approach",p:"ˈstrætədʒi",pos:"n.",d:"a plan for achieving something",z:"l"},
{t:"work",w:"target",s:["goal","aim","objective"],c:"目标",e:"Our goal is to finish by June.",k:"goal",p:"ˈtɑːɡɪt",pos:"n.",d:"something you aim to achieve",z:"l"},
{t:"education",w:"technique",s:["method","skill","approach"],c:"技巧",e:"Learn a new method for taking notes.",k:"method",p:"tekˈniːk",pos:"n.",d:"a particular way of doing something",z:"l"}
];
const V6W = [
{t:"academic",w:"albeit",s:["although","even though","though"],c:"尽管",e:"The plan worked, although slowly.",k:"although",p:"ˌɔːlˈbiːɪt",pos:"conj.",d:"although; even though",z:"w"},
{t:"academic",w:"nonetheless",s:["nevertheless","still","even so"],c:"尽管如此",e:"The task was hard; even so, we finished.",k:"even so",p:"ˌnʌnðəˈles",pos:"adv.",d:"in spite of what has just been said",z:"w"},
{t:"academic",w:"dramatically",s:["sharply","steeply","suddenly"],c:"急剧地",e:"Output fell sharply in the final quarter.",k:"sharply",p:"drəˈmætɪkli",pos:"adv.",d:"in a sudden and striking way",z:"w"},
{t:"academic",w:"exclusively",s:["only","solely","entirely"],c:"仅仅",e:"The room is used solely for meetings.",k:"solely",p:"ɪkˈskluːsɪvli",pos:"adv.",d:"only; not including anything else",z:"w"},
{t:"academic",w:"virtually",s:["almost","nearly","practically"],c:"几乎",e:"The scheme covers nearly all schools.",k:"nearly",p:"ˈvɜːtʃuəli",pos:"adv.",d:"almost completely",z:"w"},
{t:"academic",w:"essentially",s:["fundamentally","basically","in essence"],c:"本质上",e:"The two plans are basically the same.",k:"basically",p:"ɪˈsenʃəli",pos:"adv.",d:"in the most important ways",z:"w"},
{t:"academic",w:"inherently",s:["intrinsically","by nature","naturally"],c:"天生地，内在地",e:"The system is by nature unstable.",k:"by nature",p:"ɪnˈhɪərəntli",pos:"adv.",d:"in a way that is a basic part of something",z:"w"},
{t:"academic",w:"increasingly",s:["more and more","progressively","ever more"],c:"日益",e:"People are more and more aware of health.",k:"more and more",p:"ɪnˈkriːsɪŋli",pos:"adv.",d:"more and more over time",z:"w"},
{t:"academic",w:"ultimately",s:["eventually","in the end","finally"],c:"最终",e:"Eventually, the reforms took effect.",k:"eventually",p:"ˈʌltɪmətli",pos:"adv.",d:"finally; after a long time",z:"w"},
{t:"academic",w:"thereby",s:["in this way","as a result","thus"],c:"从而",e:"In this way, costs were reduced.",k:"in this way",p:"ˌðeəˈbaɪ",pos:"adv.",d:"as a result of this action",z:"w"},
{t:"academic",w:"acquisition",s:["purchase","obtaining","gaining"],c:"获得，收购",e:"The purchase of the firm was approved.",k:"purchase",p:"ˌækwɪˈzɪʃn",pos:"n.",d:"the act of getting or buying something",z:"w"},
{t:"academic",w:"allocation",s:["distribution","assignment","apportionment"],c:"分配",e:"The distribution of funds was unfair.",k:"distribution",p:"ˌæləˈkeɪʃn",pos:"n.",d:"the act of giving resources to people",z:"w"},
{t:"academic",w:"alteration",s:["change","modification","adjustment"],c:"更改",e:"A small modification improved the design.",k:"modification",p:"ˌɔːltəˈreɪʃn",pos:"n.",d:"a change to something",z:"w"},
{t:"academic",w:"bias",s:["prejudice","partiality","favouritism"],c:"偏见",e:"The survey may contain prejudice.",k:"prejudice",p:"ˈbaɪəs",pos:"n.",d:"an unfair preference for one side",z:"w"},
{t:"academic",w:"cohesion",s:["unity","togetherness","coherence"],c:"凝聚力",e:"The essay lacks overall unity.",k:"unity",p:"kəʊˈhiːʒn",pos:"n.",d:"the state of sticking together as one",z:"w"},
{t:"academic",w:"commodity",s:["goods","product","resource"],c:"商品",e:"Coffee is a major traded product.",k:"product",p:"kəˈmɒdəti",pos:"n.",d:"a product that can be bought and sold",z:"w"},
{t:"academic",w:"compensation",s:["payment","reparation","repayment"],c:"补偿",e:"Workers received payment for overtime.",k:"payment",p:"ˌkɒmpenˈseɪʃn",pos:"n.",d:"money paid to make up for loss",z:"w"},
{t:"academic",w:"competence",s:["ability","skill","proficiency"],c:"能力",e:"Her ability in the field is clear.",k:"ability",p:"ˈkɒmpɪtəns",pos:"n.",d:"the ability to do something well",z:"w"},
{t:"academic",w:"consensus",s:["agreement","general opinion","accord"],c:"共识",e:"There is broad agreement on the issue.",k:"agreement",p:"kənˈsensəs",pos:"n.",d:"a general agreement among people",z:"w"},
{t:"academic",w:"contradiction",s:["conflict","inconsistency","opposition"],c:"矛盾",e:"There is a conflict between the two reports.",k:"conflict",p:"ˌkɒntrəˈdɪkʃn",pos:"n.",d:"a situation where two things disagree",z:"w"},
{t:"academic",w:"controversy",s:["dispute","debate","disagreement"],c:"争议",e:"The decision caused a public dispute.",k:"dispute",p:"ˈkɒntrəvɜːsi",pos:"n.",d:"strong public disagreement",z:"w"},
{t:"academic",w:"correlation",s:["connection","link","relationship"],c:"相关性",e:"There is a clear link between diet and health.",k:"link",p:"ˌkɒrəˈleɪʃn",pos:"n.",d:"a connection between two things",z:"w"},
{t:"academic",w:"deterioration",s:["decline","worsening","degeneration"],c:"恶化",e:"The worsening of the roads is worrying.",k:"worsening",p:"dɪˌtɪəriəˈreɪʃn",pos:"n.",d:"the process of becoming worse",z:"w"},
{t:"academic",w:"deviation",s:["departure","divergence","difference"],c:"偏离",e:"Any departure from the rules is noted.",k:"departure",p:"ˌdiːviˈeɪʃn",pos:"n.",d:"a difference from what is normal",z:"w"},
{t:"academic",w:"disruption",s:["disturbance","interruption","breakdown"],c:"扰乱",e:"The strike caused major disturbance.",k:"disturbance",p:"dɪsˈrʌpʃn",pos:"n.",d:"the act of interrupting normal activity",z:"w"},
{t:"academic",w:"dominance",s:["control","supremacy","influence"],c:"支配，优势",e:"One firm holds total control of the market.",k:"control",p:"ˈdɒmɪnəns",pos:"n.",d:"the state of being more powerful than others",z:"w"},
{t:"academic",w:"efficiency",s:["productivity","effectiveness","performance"],c:"效率",e:"New tools raised workplace productivity.",k:"productivity",p:"ɪˈfɪʃnsi",pos:"n.",d:"the ability to work well without waste",z:"w"},
{t:"academic",w:"emergence",s:["appearance","rise","development"],c:"出现",e:"The rise of online retail changed shopping.",k:"rise",p:"ɪˈmɜːdʒəns",pos:"n.",d:"the process of becoming known or visible",z:"w"},
{t:"academic",w:"endorsement",s:["approval","support","backing"],c:"支持，背书",e:"The plan gained official approval.",k:"approval",p:"ɪnˈdɔːsmənt",pos:"n.",d:"public support for something",z:"w"},
{t:"academic",w:"enforcement",s:["implementation","application","imposition"],c:"执行",e:"Implementation of the law begins in May.",k:"implementation",p:"ɪnˈfɔːsmənt",pos:"n.",d:"the act of making people obey a rule",z:"w"},
{t:"academic",w:"enhancement",s:["improvement","upgrade","boost"],c:"提升",e:"The upgrade improved the sound quality.",k:"upgrade",p:"ɪnˈhɑːnsmənt",pos:"n.",d:"an improvement in quality or value",z:"w"},
{t:"academic",w:"expenditure",s:["spending","outlay","costs"],c:"支出",e:"Government spending rose last year.",k:"spending",p:"ɪkˈspendɪtʃə",pos:"n.",d:"the total amount of money spent",z:"w"},
{t:"academic",w:"formulation",s:["devising","drafting","creation"],c:"制定",e:"The drafting of the policy took months.",k:"drafting",p:"ˌfɔːmjuˈleɪʃn",pos:"n.",d:"the process of creating a plan or idea",z:"w"},
{t:"academic",w:"hierarchy",s:["ranking","order","grading"],c:"等级制度",e:"A clear ranking exists within the firm.",k:"ranking",p:"ˈhaɪərɑːki",pos:"n.",d:"a system of levels from high to low",z:"w"},
{t:"academic",w:"ideology",s:["belief system","doctrine","philosophy"],c:"意识形态",e:"Their belief system shapes policy.",k:"belief system",p:"ˌaɪdiˈɒlədʒi",pos:"n.",d:"a set of beliefs behind a system",z:"w"},
{t:"academic",w:"illusion",s:["false impression","misconception","delusion"],c:"错觉",e:"The idea creates a false impression.",k:"false impression",p:"ɪˈluːʒn",pos:"n.",d:"something that seems true but is not",z:"w"},
{t:"academic",w:"implementation",s:["execution","application","carrying out"],c:"实施",e:"Execution of the plan starts in March.",k:"execution",p:"ˌɪmplɪmenˈteɪʃn",pos:"n.",d:"the act of putting a plan into action",z:"w"},
{t:"academic",w:"incidence",s:["occurrence","rate","frequency"],c:"发生率",e:"The rate of the disease is falling.",k:"rate",p:"ˈɪnsɪdəns",pos:"n.",d:"how often something happens",z:"w"},
{t:"academic",w:"inconsistency",s:["contradiction","variation","discrepancy"],c:"不一致",e:"A variation appears in the data.",k:"variation",p:"ˌɪnkənˈsɪstənsi",pos:"n.",d:"a lack of agreement between things",z:"w"},
{t:"academic",w:"indicator",s:["sign","signal","measure"],c:"指标",e:"Unemployment is a key measure of health.",k:"measure",p:"ˈɪndɪkeɪtə",pos:"n.",d:"a sign that shows the state of something",z:"w"},
{t:"academic",w:"inference",s:["conclusion","deduction","reasoning"],c:"推断",e:"The conclusion follows from the evidence.",k:"conclusion",p:"ˈɪnfərəns",pos:"n.",d:"a conclusion reached from evidence",z:"w"},
{t:"academic",w:"insight",s:["understanding","perception","awareness"],c:"洞察力",e:"The report gives deep understanding of the issue.",k:"understanding",p:"ˈɪnsaɪt",pos:"n.",d:"a clear understanding of something",z:"w"},
{t:"academic",w:"integration",s:["combination","merging","incorporation"],c:"整合",e:"The merging of the teams was smooth.",k:"merging",p:"ˌɪntɪˈɡreɪʃn",pos:"n.",d:"the act of combining into one whole",z:"w"},
{t:"academic",w:"integrity",s:["honesty","uprightness","principle"],c:"正直",e:"Her honesty is beyond doubt.",k:"honesty",p:"ɪnˈteɡrəti",pos:"n.",d:"the quality of being honest",z:"w"},
{t:"academic",w:"intensity",s:["strength","force","severity"],c:"强度",e:"The strength of the storm increased.",k:"strength",p:"ɪnˈtensəti",pos:"n.",d:"the degree of strength or force",z:"w"},
{t:"academic",w:"intervention",s:["involvement","action","interference"],c:"干预",e:"Early involvement prevents failure.",k:"involvement",p:"ˌɪntəˈvenʃn",pos:"n.",d:"the act of becoming involved to change something",z:"w"},
{t:"academic",w:"justification",s:["reason","grounds","defence"],c:"正当理由",e:"There is no reason for the delay.",k:"reason",p:"ˌdʒʌstɪfɪˈkeɪʃn",pos:"n.",d:"a good reason for doing something",z:"w"},
{t:"academic",w:"legitimacy",s:["validity","lawfulness","rightfulness"],c:"合法性",e:"The validity of the contract was questioned.",k:"validity",p:"lɪˈdʒɪtɪməsi",pos:"n.",d:"the quality of being legal or acceptable",z:"w"},
{t:"academic",w:"manifestation",s:["expression","display","sign"],c:"表现",e:"The strike is an expression of anger.",k:"expression",p:"ˌmænɪfeˈsteɪʃn",pos:"n.",d:"a clear sign of something",z:"w"},
{t:"academic",w:"manipulation",s:["control","influence","handling"],c:"操纵",e:"The control of the data caused doubt.",k:"control",p:"məˌnɪpjuˈleɪʃn",pos:"n.",d:"the act of controlling something unfairly",z:"w"},
{t:"academic",w:"mechanism",s:["system","process","structure"],c:"机制",e:"A new system for feedback was set up.",k:"system",p:"ˈmekənɪzəm",pos:"n.",d:"a process that produces a result",z:"w"},
{t:"academic",w:"misconception",s:["false belief","misunderstanding","error"],c:"误解",e:"A false belief about diets is common.",k:"false belief",p:"ˌmɪskənˈsepʃn",pos:"n.",d:"a wrong idea about something",z:"w"},
{t:"academic",w:"modification",s:["change","adjustment","alteration"],c:"修改",e:"A small adjustment solved the problem.",k:"adjustment",p:"ˌmɒdɪfɪˈkeɪʃn",pos:"n.",d:"a small change to something",z:"w"},
{t:"academic",w:"obligation",s:["duty","commitment","responsibility"],c:"义务",e:"Every citizen has a duty to vote.",k:"duty",p:"ˌɒblɪˈɡeɪʃn",pos:"n.",d:"something you must do",z:"w"},
{t:"academic",w:"obstacle",s:["barrier","hindrance","block"],c:"障碍",e:"Cost remains the main barrier.",k:"barrier",p:"ˈɒbstəkl",pos:"n.",d:"something that blocks progress",z:"w"},
{t:"academic",w:"optimisation",s:["improvement","refinement","fine-tuning"],c:"优化",e:"Refinement of the process saved time.",k:"refinement",p:"ˌɒptɪmaɪˈzeɪʃn",pos:"n.",d:"the act of making something as good as possible",z:"w"},
{t:"academic",w:"participation",s:["involvement","engagement","attendance"],c:"参与",e:"Involvement in sports is encouraged.",k:"involvement",p:"pɑːˌtɪsɪˈpeɪʃn",pos:"n.",d:"the act of taking part in something",z:"w"},
{t:"academic",w:"perception",s:["view","impression","awareness"],c:"看法，感知",e:"Public view of the issue has changed.",k:"view",p:"pəˈsepʃn",pos:"n.",d:"the way people see or understand something",z:"w"},
{t:"academic",w:"persistence",s:["determination","perseverance","staying power"],c:"坚持",e:"Determination led to her success.",k:"determination",p:"pəˈsɪstəns",pos:"n.",d:"the quality of continuing despite difficulty",z:"w"},
{t:"academic",w:"probability",s:["likelihood","chance","odds"],c:"可能性",e:"The likelihood of success is high.",k:"likelihood",p:"ˌprɒbəˈbɪləti",pos:"n.",d:"how likely something is to happen",z:"w"},
{t:"academic",w:"proficiency",s:["skill","competence","mastery"],c:"熟练",e:"Her skill in English is advanced.",k:"skill",p:"prəˈfɪʃnsi",pos:"n.",d:"a high level of skill",z:"w"},
{t:"academic",w:"progression",s:["development","advance","sequence"],c:"进展，序列",e:"The development of skills takes time.",k:"development",p:"prəˈɡreʃn",pos:"n.",d:"the process of developing step by step",z:"w"},
{t:"academic",w:"proliferation",s:["rapid growth","spread","expansion"],c:"激增，扩散",e:"The rapid growth of apps is clear.",k:"rapid growth",p:"prəˌlɪfəˈreɪʃn",pos:"n.",d:"a sudden increase in number",z:"w"},
{t:"academic",w:"prominence",s:["importance","visibility","fame"],c:"突出，重要",e:"The issue gained new importance.",k:"importance",p:"ˈprɒmɪnəns",pos:"n.",d:"the state of being well known or important",z:"w"},
{t:"academic",w:"rationale",s:["reasoning","logic","justification"],c:"理由，逻辑",e:"The reasoning behind the rule is sound.",k:"reasoning",p:"ˌræʃəˈnɑːl",pos:"n.",d:"the reasons behind a decision",z:"w"},
{t:"academic",w:"recession",s:["downturn","slump","economic decline"],c:"经济衰退",e:"The downturn lasted two years.",k:"downturn",p:"rɪˈseʃn",pos:"n.",d:"a period when the economy declines",z:"w"},
{t:"academic",w:"recognition",s:["acknowledgement","awareness","acceptance"],c:"认可",e:"Her work gained wide acknowledgement.",k:"acknowledgement",p:"ˌrekəɡˈnɪʃn",pos:"n.",d:"public praise or acceptance",z:"w"},
{t:"academic",w:"reconciliation",s:["settlement","harmonising","agreement"],c:"调和",e:"The agreement ended the conflict.",k:"agreement",p:"ˌrekənsɪliˈeɪʃn",pos:"n.",d:"the process of making things agree",z:"w"},
{t:"academic",w:"relevance",s:["importance","significance","applicability"],c:"相关性",e:"The significance of the finding is clear.",k:"significance",p:"ˈreləvəns",pos:"n.",d:"how important or connected something is",z:"w"},
{t:"academic",w:"reliability",s:["dependability","trustworthiness","consistency"],c:"可靠性",e:"The dependability of the data matters.",k:"dependability",p:"rɪˌlaɪəˈbɪləti",pos:"n.",d:"the quality of being dependable",z:"w"},
{t:"academic",w:"reputation",s:["standing","image","renown"],c:"声誉",e:"The firm has an excellent standing.",k:"standing",p:"ˌrepjuˈteɪʃn",pos:"n.",d:"the opinion people have of something",z:"w"},
{t:"academic",w:"resistance",s:["opposition","defiance","hostility"],c:"抵制",e:"Opposition to the tax grew quickly.",k:"opposition",p:"rɪˈzɪstəns",pos:"n.",d:"refusal to accept something",z:"w"},
{t:"academic",w:"resolution",s:["solution","settlement","decision"],c:"解决，决议",e:"A solution to the dispute was found.",k:"solution",p:"ˌrezəˈluːʃn",pos:"n.",d:"a firm decision or solution",z:"w"},
{t:"academic",w:"retention",s:["keeping","preservation","maintenance"],c:"保留",e:"Keeping staff reduces training costs.",k:"keeping",p:"rɪˈtenʃn",pos:"n.",d:"the act of keeping something",z:"w"},
{t:"academic",w:"revenue",s:["income","earnings","takings"],c:"收入",e:"The firm's income grew by ten per cent.",k:"income",p:"ˈrevənjuː",pos:"n.",d:"money received by a business",z:"w"},
{t:"academic",w:"scrutiny",s:["examination","inspection","review"],c:"仔细审查",e:"The plan is under close examination.",k:"examination",p:"ˈskruːtəni",pos:"n.",d:"careful and thorough examination",z:"w"},
{t:"academic",w:"sensitivity",s:["awareness","responsiveness","delicacy"],c:"敏感性",e:"Awareness of cost is vital.",k:"awareness",p:"ˌsensəˈtɪvəti",pos:"n.",d:"the quality of being easily affected",z:"w"},
{t:"academic",w:"significance",s:["importance","meaning","consequence"],c:"重要性",e:"The importance of the finding is clear.",k:"importance",p:"sɪɡˈnɪfɪkəns",pos:"n.",d:"the importance or meaning of something",z:"w"},
{t:"academic",w:"simulation",s:["model","replication","reproduction"],c:"模拟",e:"The model predicts real traffic flow.",k:"model",p:"ˌsɪmjuˈleɪʃn",pos:"n.",d:"an imitation of a real situation",z:"w"},
{t:"academic",w:"stability",s:["steadiness","balance","security"],c:"稳定",e:"Economic steadiness attracts investors.",k:"steadiness",p:"stəˈbɪləti",pos:"n.",d:"the state of being steady and secure",z:"w"},
{t:"academic",w:"stagnation",s:["standstill","inactivity","lack of growth"],c:"停滞",e:"The standstill in trade lasted a year.",k:"standstill",p:"stæɡˈneɪʃn",pos:"n.",d:"a period without growth or change",z:"w"},
{t:"academic",w:"stimulus",s:["incentive","boost","spur"],c:"刺激",e:"A tax cut provided an incentive to invest.",k:"incentive",p:"ˈstɪmjələs",pos:"n.",d:"something that encourages action",z:"w"},
{t:"academic",w:"sustainability",s:["long-term viability","durability","greenness"],c:"可持续性",e:"Long-term viability of the model is doubted.",k:"long-term viability",p:"səˌsteɪnəˈbɪləti",pos:"n.",d:"the ability to continue over time",z:"w"},
{t:"academic",w:"synthesis",s:["combination","merger","fusion"],c:"综合",e:"The essay needs a combination of ideas.",k:"combination",p:"ˈsɪnθəsɪs",pos:"n.",d:"the combining of parts into a whole",z:"w"},
{t:"academic",w:"tendency",s:["trend","inclination","habit"],c:"趋势",e:"There is a clear trend towards online work.",k:"trend",p:"ˈtendənsi",pos:"n.",d:"a natural way something tends to happen",z:"w"},
{t:"academic",w:"threshold",s:["limit","boundary","level"],c:"门槛，阈值",e:"The level for approval is strict.",k:"level",p:"ˈθreʃhəʊld",pos:"n.",d:"the level at which something starts to happen",z:"w"},
{t:"academic",w:"tolerance",s:["acceptance","patience","openness"],c:"容忍",e:"Acceptance of difference is important.",k:"acceptance",p:"ˈtɒlərəns",pos:"n.",d:"the willingness to accept differences",z:"w"},
{t:"academic",w:"transition",s:["change","shift","switch"],c:"过渡",e:"The shift to new software was smooth.",k:"shift",p:"trænˈzɪʃn",pos:"n.",d:"the process of changing from one state to another",z:"w"},
{t:"academic",w:"validity",s:["soundness","legitimacy","credibility"],c:"有效性",e:"The soundness of the test was checked.",k:"soundness",p:"vəˈlɪdəti",pos:"n.",d:"the quality of being logical or acceptable",z:"w"},
{t:"academic",w:"viability",s:["practicability","feasibility","workability"],c:"可行性",e:"The practicability of the plan is in doubt.",k:"practicability",p:"ˌvaɪəˈbɪləti",pos:"n.",d:"the ability to work successfully",z:"w"},
{t:"academic",w:"vulnerability",s:["weakness","exposure","susceptibility"],c:"脆弱性",e:"The weakness of the system was exposed.",k:"weakness",p:"ˌvʌlnərəˈbɪləti",pos:"n.",d:"the state of being easy to harm",z:"w"},
{t:"academic",w:"allocate",s:["assign","distribute","apportion"],c:"分配",e:"Funds are assigned to each department.",k:"assigned",p:"ˈæləkeɪt",pos:"v.",d:"to give resources to someone for a purpose",z:"w"},
{t:"academic",w:"anticipate",s:["expect","foresee","predict"],c:"预期",e:"Experts foresee a sharp rise in demand.",k:"foresee",p:"ænˈtɪsɪpeɪt",pos:"v.",d:"to expect that something will happen",z:"w"},
{t:"academic",w:"articulate",s:["express clearly","voice","state"],c:"清晰表达",e:"She voiced her views with confidence.",k:"voiced",p:"ɑːˈtɪkjuleɪt",pos:"v.",d:"to express ideas clearly",z:"w"},
{t:"academic",w:"categorise",s:["classify","group","sort"],c:"分类",e:"The data is classified by age.",k:"classified",p:"ˈkætəɡəraɪz",pos:"v.",d:"to put things into groups",z:"w"},
{t:"academic",w:"collaborate",s:["cooperate","work together","team up"],c:"合作",e:"The teams cooperated on the study.",k:"cooperated",p:"kəˈlæbəreɪt",pos:"v.",d:"to work together on something",z:"w"},
{t:"academic",w:"commence",s:["begin","start","launch"],c:"开始",e:"The trial begins next month.",k:"begins",p:"kəˈmens",pos:"v.",d:"to begin",z:"w"},
{t:"academic",w:"compensate",s:["make up for","offset","repay"],c:"补偿",e:"Extra pay makes up for the long hours.",k:"makes up for",p:"ˈkɒmpenseɪt",pos:"v.",d:"to reduce the bad effect of something",z:"w"},
{t:"academic",w:"compile",s:["assemble","gather","collect"],c:"汇编",e:"The team assembled the data into one file.",k:"assembled",p:"kəmˈpaɪl",pos:"v.",d:"to collect information into a list",z:"w"},
{t:"academic",w:"comprehend",s:["understand","grasp","fathom"],c:"理解",e:"Few readers grasp the full argument.",k:"grasp",p:"ˌkɒmprɪˈhend",pos:"v.",d:"to understand something fully",z:"w"},
{t:"academic",w:"compromise",s:["reach agreement","settle","meet halfway"],c:"妥协",e:"The two sides settled on a middle course.",k:"settled",p:"ˈkɒmprəmaɪz",pos:"v.",d:"to accept less than you wanted to agree",z:"w"},
{t:"academic",w:"confront",s:["face","tackle","address"],c:"面对",e:"The report faces the issue directly.",k:"faces",p:"kənˈfrʌnt",pos:"v.",d:"to deal with a difficult problem directly",z:"w"},
{t:"academic",w:"consolidate",s:["strengthen","reinforce","unite"],c:"巩固",e:"The firm strengthened its market position.",k:"strengthened",p:"kənˈsɒlɪdeɪt",pos:"v.",d:"to make something stronger or more solid",z:"w"},
{t:"academic",w:"constrain",s:["limit","restrict","bound"],c:"限制",e:"Budget cuts restrict the options.",k:"restrict",p:"kənˈstreɪn",pos:"v.",d:"to limit what is possible",z:"w"},
{t:"academic",w:"contradict",s:["dispute","deny","challenge"],c:"反驳，与…矛盾",e:"The results dispute earlier findings.",k:"dispute",p:"ˌkɒntrəˈdɪkt",pos:"v.",d:"to say the opposite of something",z:"w"},
{t:"academic",w:"correlate",s:["connect","link","associate"],c:"相关",e:"Income links closely with education.",k:"links",p:"ˈkɒrəleɪt",pos:"v.",d:"to have a close connection with something",z:"w"},
{t:"academic",w:"cultivate",s:["develop","foster","nurture"],c:"培养",e:"The course fosters critical thinking.",k:"fosters",p:"ˈkʌltɪveɪt",pos:"v.",d:"to develop a skill or attitude",z:"w"},
{t:"academic",w:"curtail",s:["cut back","reduce","limit"],c:"削减",e:"The firm cut back on travel costs.",k:"cut back",p:"kɜːˈteɪl",pos:"v.",d:"to reduce or limit something",z:"w"},
{t:"academic",w:"deduce",s:["infer","conclude","work out"],c:"推断",e:"We infer the cause from the data.",k:"infer",p:"dɪˈdjuːs",pos:"v.",d:"to reach a conclusion from evidence",z:"w"},
{t:"academic",w:"denote",s:["indicate","represent","signify"],c:"表示",e:"The symbol represents energy.",k:"represents",p:"dɪˈnəʊt",pos:"v.",d:"to be a sign of something",z:"w"},
{t:"academic",w:"derive",s:["obtain","gain","draw"],c:"获得，源自",e:"The word draws from Latin.",k:"draws",p:"dɪˈraɪv",pos:"v.",d:"to come from a source",z:"w"},
{t:"academic",w:"designate",s:["appoint","name","assign"],c:"指定",e:"She was appointed as team leader.",k:"appointed",p:"ˈdezɪɡneɪt",pos:"v.",d:"to officially choose someone for a role",z:"w"},
{t:"academic",w:"detect",s:["notice","spot","discover"],c:"察觉",e:"The test spots the disease early.",k:"spots",p:"dɪˈtekt",pos:"v.",d:"to notice or discover something",z:"w"},
{t:"academic",w:"deter",s:["discourage","prevent","hinder"],c:"阻止，威慑",e:"High fees discourage applicants.",k:"discourage",p:"dɪˈtɜː",pos:"v.",d:"to make someone less likely to do something",z:"w"},
{t:"academic",w:"devise",s:["design","invent","formulate"],c:"设计，想出",e:"The team designed a new test.",k:"designed",p:"dɪˈvaɪz",pos:"v.",d:"to invent or plan something new",z:"w"},
{t:"academic",w:"differentiate",s:["distinguish","tell apart","separate"],c:"区分",e:"The test distinguishes skilled readers.",k:"distinguishes",p:"ˌdɪfəˈrenʃieɪt",pos:"v.",d:"to show the difference between things",z:"w"},
{t:"academic",w:"discern",s:["perceive","detect","make out"],c:"辨别",e:"We perceive a clear pattern in the data.",k:"perceive",p:"dɪˈsɜːn",pos:"v.",d:"to see or notice something with difficulty",z:"w"},
{t:"academic",w:"disclose",s:["reveal","divulge","make public"],c:"披露",e:"The firm revealed its profits.",k:"revealed",p:"dɪsˈkləʊz",pos:"v.",d:"to make information known",z:"w"},
{t:"academic",w:"discriminate",s:["treat unfairly","single out","distinguish"],c:"歧视，区分",e:"The law bans treating people unfairly.",k:"treating people unfairly",p:"dɪˈskrɪmɪneɪt",pos:"v.",d:"to treat one group worse than another",z:"w"},
{t:"academic",w:"dismantle",s:["take apart","break down","remove"],c:"拆除",e:"The old system was taken apart.",k:"taken apart",p:"dɪsˈmæntl",pos:"v.",d:"to take something to pieces",z:"w"},
{t:"academic",w:"distort",s:["twist","misrepresent","bend"],c:"歪曲",e:"The media twisted his words.",k:"twisted",p:"dɪˈstɔːt",pos:"v.",d:"to change the true meaning of something",z:"w"},
{t:"academic",w:"diverge",s:["differ","deviate","part ways"],c:"分歧，偏离",e:"The two accounts differ sharply.",k:"differ",p:"daɪˈvɜːdʒ",pos:"v.",d:"to become different or separate",z:"w"},
{t:"academic",w:"diversify",s:["broaden","vary","widen"],c:"多样化",e:"The firm broadened its product range.",k:"broadened",p:"daɪˈvɜːsɪfaɪ",pos:"v.",d:"to make something more varied",z:"w"},
{t:"academic",w:"dominate",s:["control","lead","prevail over"],c:"主导",e:"One brand controls the market.",k:"controls",p:"ˈdɒmɪneɪt",pos:"v.",d:"to be the most powerful or important",z:"w"},
{t:"academic",w:"elaborate",s:["expand on","explain in detail","develop"],c:"详细说明",e:"Expand on your answer in the essay.",k:"expand on",p:"ɪˈlæbəreɪt",pos:"v.",d:"to give more details about something",z:"w"},
{t:"academic",w:"elicit",s:["draw out","obtain","extract"],c:"引出",e:"The survey drew out honest answers.",k:"drew out",p:"ɪˈlɪsɪt",pos:"v.",d:"to get information or a reaction from someone",z:"w"},
{t:"academic",w:"eliminate",s:["remove","get rid of","eradicate"],c:"消除",e:"The policy removed most barriers.",k:"removed",p:"ɪˈlɪmɪneɪt",pos:"v.",d:"to completely remove something",z:"w"},
{t:"academic",w:"embody",s:["represent","personify","reflect"],c:"体现",e:"The design reflects the brand values.",k:"reflects",p:"ɪmˈbɒdi",pos:"v.",d:"to be a clear example of an idea",z:"w"},
{t:"academic",w:"emerge",s:["appear","arise","come to light"],c:"出现",e:"New patterns appear in the data.",k:"appear",p:"ɪˈmɜːdʒ",pos:"v.",d:"to become known or visible",z:"w"},
{t:"academic",w:"enact",s:["pass","introduce","implement"],c:"颁布",e:"The law was passed last year.",k:"passed",p:"ɪˈnækt",pos:"v.",d:"to make a law official",z:"w"},
{t:"academic",w:"encounter",s:["meet","face","come across"],c:"遇到",e:"Workers face new challenges daily.",k:"face",p:"ɪnˈkaʊntə",pos:"v.",d:"to experience something unexpected",z:"w"},
{t:"academic",w:"enforce",s:["impose","apply","implement"],c:"执行，强制",e:"The rules are applied strictly.",k:"applied",p:"ɪnˈfɔːs",pos:"v.",d:"to make people obey a rule",z:"w"},
{t:"academic",w:"engender",s:["create","produce","generate"],c:"产生",e:"The policy created public trust.",k:"created",p:"ɪnˈdʒendə",pos:"v.",d:"to cause a feeling or situation to exist",z:"w"},
{t:"academic",w:"entail",s:["involve","require","necessitate"],c:"需要，牵涉",e:"The job involves frequent travel.",k:"involves",p:"ɪnˈteɪl",pos:"v.",d:"to make something necessary",z:"w"},
{t:"academic",w:"evoke",s:["bring to mind","arouse","elicit"],c:"唤起",e:"The song brings to mind old memories.",k:"brings to mind",p:"ɪˈvəʊk",pos:"v.",d:"to cause a memory or feeling",z:"w"},
{t:"academic",w:"evolve",s:["develop","progress","change gradually"],c:"演变",e:"The system developed over decades.",k:"developed",p:"ɪˈvɒlv",pos:"v.",d:"to change gradually over time",z:"w"},
{t:"academic",w:"exert",s:["apply","use","wield"],c:"施加",e:"Parents apply pressure on schools.",k:"apply",p:"ɪɡˈzɜːt",pos:"v.",d:"to use power or influence",z:"w"},
{t:"academic",w:"expedite",s:["speed up","accelerate","hasten"],c:"加快",e:"The team sped up the review process.",k:"sped up",p:"ˈekspədaɪt",pos:"v.",d:"to make something happen faster",z:"w"},
{t:"academic",w:"exploit",s:["take advantage of","utilise","use"],c:"利用，开发",e:"Firms utilise the data for profit.",k:"utilise",p:"ɪkˈsplɔɪt",pos:"v.",d:"to use something to your advantage",z:"w"},
{t:"academic",w:"expose",s:["reveal","uncover","disclose"],c:"揭露",e:"The report uncovered the fraud.",k:"uncovered",p:"ɪkˈspəʊz",pos:"v.",d:"to make something hidden become known",z:"w"},
{t:"academic",w:"extract",s:["remove","take out","pull out"],c:"提取",e:"Scientists remove oil from the rock.",k:"remove",p:"ɪkˈstrækt",pos:"v.",d:"to take something out",z:"w"},
{t:"academic",w:"fulfil",s:["achieve","meet","satisfy"],c:"实现，履行",e:"The course meets all requirements.",k:"meets",p:"fʊlˈfɪl",pos:"v.",d:"to achieve or do what is required",z:"w"},
{t:"academic",w:"generalise",s:["oversimplify","broaden","make general"],c:"概括",e:"Do not oversimplify the findings.",k:"oversimplify",p:"ˈdʒenrəlaɪz",pos:"v.",d:"to make a broad statement from limited evidence",z:"w"},
{t:"academic",w:"gauge",s:["measure","assess","estimate"],c:"衡量",e:"Surveys measure public opinion.",k:"measure",p:"ɡeɪdʒ",pos:"v.",d:"to judge or measure something",z:"w"},
{t:"academic",w:"hypothesise",s:["theorise","speculate","assume"],c:"假设",e:"Scientists theorise about the cause.",k:"theorise",p:"haɪˈpɒθəsaɪz",pos:"v.",d:"to suggest an idea that can be tested",z:"w"},
{t:"academic",w:"illuminate",s:["clarify","explain","shed light on"],c:"阐明",e:"The data sheds light on the issue.",k:"sheds light on",p:"ɪˈluːmɪneɪt",pos:"v.",d:"to make something clear or easier to understand",z:"w"},
{t:"academic",w:"impose",s:["force","apply","introduce"],c:"强加，征收",e:"The tax was applied to all imports.",k:"applied",p:"ɪmˈpəʊz",pos:"v.",d:"to force a rule or tax on people",z:"w"},
{t:"academic",w:"incorporate",s:["include","integrate","combine"],c:"纳入",e:"The plan includes feedback from staff.",k:"includes",p:"ɪnˈkɔːpəreɪt",pos:"v.",d:"to include something as part of a whole",z:"w"},
{t:"academic",w:"induce",s:["cause","trigger","prompt"],c:"引起",e:"Stress can trigger illness.",k:"trigger",p:"ɪnˈdjuːs",pos:"v.",d:"to cause something to happen",z:"w"},
{t:"academic",w:"inhibit",s:["hinder","restrain","suppress"],c:"抑制",e:"Fear can hinder learning.",k:"hinder",p:"ɪnˈhɪbɪt",pos:"v.",d:"to prevent or slow something",z:"w"},
{t:"academic",w:"initiate",s:["start","begin","launch"],c:"发起",e:"The council started a new scheme.",k:"started",p:"ɪˈnɪʃieɪt",pos:"v.",d:"to make something begin",z:"w"},
{t:"academic",w:"integrate",s:["combine","merge","unify"],c:"整合",e:"The course combines theory and practice.",k:"combines",p:"ˈɪntɪɡreɪt",pos:"v.",d:"to combine things into one whole",z:"w"},
{t:"academic",w:"intervene",s:["step in","interfere","mediate"],c:"干预",e:"The bank stepped in to help.",k:"stepped in",p:"ˌɪntəˈviːn",pos:"v.",d:"to become involved to change a situation",z:"w"},
{t:"academic",w:"isolate",s:["separate","cut off","set apart"],c:"隔离",e:"The lab separates the samples.",k:"separates",p:"ˈaɪsəleɪt",pos:"v.",d:"to keep something separate from others",z:"w"},
{t:"academic",w:"minimise",s:["reduce","lessen","keep to a minimum"],c:"最小化",e:"Good planning reduces waste.",k:"reduces",p:"ˈmɪnɪmaɪz",pos:"v.",d:"to make something as small as possible",z:"w"},
{t:"academic",w:"modify",s:["change","adjust","alter"],c:"修改",e:"The rules were adjusted last year.",k:"adjusted",p:"ˈmɒdɪfaɪ",pos:"v.",d:"to change something slightly",z:"w"},
{t:"academic",w:"motivate",s:["inspire","encourage","drive"],c:"激励",e:"Praise encourages students to work.",k:"encourages",p:"ˈməʊtɪveɪt",pos:"v.",d:"to make someone want to do something",z:"w"},
{t:"academic",w:"nurture",s:["develop","foster","cultivate"],c:"培养",e:"The school develops young talent.",k:"develops",p:"ˈnɜːtʃə",pos:"v.",d:"to help something grow and develop",z:"w"},
{t:"academic",w:"offset",s:["balance","compensate for","counteract"],c:"抵消",e:"Savings balance the extra cost.",k:"balance",p:"ˈɒfset",pos:"v.",d:"to balance or cancel out something",z:"w"},
{t:"academic",w:"omit",s:["leave out","skip","exclude"],c:"省略",e:"Leave out the final paragraph.",k:"leave out",p:"əˈmɪt",pos:"v.",d:"to not include something",z:"w"},
{t:"academic",w:"perceive",s:["see","view","regard"],c:"感知，认为",e:"The public views the change positively.",k:"views",p:"pəˈsiːv",pos:"v.",d:"to see or understand something in a particular way",z:"w"},
{t:"academic",w:"persist",s:["continue","carry on","endure"],c:"坚持，持续",e:"The problem continues despite efforts.",k:"continues",p:"pəˈsɪst",pos:"v.",d:"to continue doing something or continue to exist",z:"w"},
{t:"academic",w:"pinpoint",s:["identify","locate","determine"],c:"准确定位",e:"The study identified the main cause.",k:"identified",p:"ˈpɪnpɔɪnt",pos:"v.",d:"to find the exact position or cause",z:"w"},
{t:"academic",w:"precede",s:["come before","lead to","go before"],c:"先于",e:"A short talk comes before the tour.",k:"comes before",p:"prɪˈsiːd",pos:"v.",d:"to happen before something else",z:"w"}
];
const V6NEW = [].concat(V6L, V6W);
module.exports = { V6NEW };
