'use strict';
/* v7 新增词库：z = 'l' 听力专区 / 'w' 书写专区（雅思核心词汇，扩充批次）*/
const V7L = [
{t:"living",w:"apartment",s:["flat","lodgings","unit"],c:"公寓",e:"She rents a flat near the campus.",k:"flat",p:"əˈpɑːtmənt",pos:"n.",d:"a set of rooms for living in",z:"l"},
{t:"living",w:"basement",s:["cellar","underground floor"],c:"地下室",e:"The wine is kept in the cellar.",k:"cellar",p:"ˈbeɪsmənt",pos:"n.",d:"a room below ground level",z:"l"},
{t:"food",w:"beverage",s:["drink","refreshment"],c:"饮料",e:"A free drink comes with the meal.",k:"drink",p:"ˈbevərɪdʒ",pos:"n.",d:"a drink other than water",z:"l"},
{t:"living",w:"blanket",s:["cover","rug","throw"],c:"毯子",e:"Ask for an extra cover at reception.",k:"cover",p:"ˈblæŋkɪt",pos:"n.",d:"a thick cover for a bed",z:"l"},
{t:"living",w:"ceiling",s:["roof surface","top"],c:"天花板",e:"A lamp hangs from the roof surface.",k:"roof surface",p:"ˈsiːlɪŋ",pos:"n.",d:"the top surface of a room",z:"l"},
{t:"health",w:"chemist",s:["pharmacy","drugstore"],c:"药店",e:"The pharmacy opens at nine.",k:"pharmacy",p:"ˈkemɪst",pos:"n.",d:"a shop that sells medicines",z:"l"},
{t:"media",w:"cinema",s:["movie theatre","picture house"],c:"电影院",e:"The movie theatre is next to the station.",k:"movie theatre",p:"ˈsɪnəmə",pos:"n.",d:"a place where films are shown",z:"l"},
{t:"living",w:"community",s:["neighbourhood","district","society"],c:"社区",e:"The neighbourhood built a new park.",k:"neighbourhood",p:"kəˈmjuːnəti",pos:"n.",d:"the people living in one area",z:"l"},
{t:"work",w:"conference",s:["meeting","convention","seminar"],c:"会议，研讨会",e:"The convention is held in May.",k:"convention",p:"ˈkɒnfərəns",pos:"n.",d:"a large formal meeting",z:"l"},
{t:"travel",w:"cottage",s:["cabin","lodge","hut"],c:"小屋",e:"They stayed in a cabin by the lake.",k:"cabin",p:"ˈkɒtɪdʒ",pos:"n.",d:"a small house in the countryside",z:"l"},
{t:"travel",w:"countryside",s:["rural area","country","landscape"],c:"乡村",e:"We walked through the rural area.",k:"rural area",p:"ˈkʌntrisaɪd",pos:"n.",d:"land outside towns and cities",z:"l"},
{t:"living",w:"courtyard",s:["yard","quad","forecourt"],c:"庭院",e:"Students meet in the central yard.",k:"yard",p:"ˈkɔːtjɑːd",pos:"n.",d:"an open area surrounded by buildings",z:"l"},
{t:"work",w:"crew",s:["team","staff","workforce"],c:"工作人员",e:"The staff checked every seat.",k:"staff",p:"kruː",pos:"n.",d:"the group of people working together",z:"l"},
{t:"living",w:"crowd",s:["throng","mob","mass"],c:"人群",e:"A throng waited at the gate.",k:"throng",p:"kraʊd",pos:"n.",d:"a large number of people together",z:"l"},
{t:"food",w:"dairy",s:["milk products","dairy produce"],c:"乳制品",e:"Milk products are in the cold section.",k:"milk products",p:"ˈdeəri",pos:"n.",d:"foods made from milk",z:"l"},
{t:"work",w:"department",s:["division","section","unit"],c:"部门",e:"She works in the sales division.",k:"division",p:"dɪˈpɑːtmənt",pos:"n.",d:"a part of an organisation",z:"l"},
{t:"travel",w:"desert",s:["wasteland","arid land"],c:"沙漠",e:"Few plants survive in the arid land.",k:"arid land",p:"ˈdezət",pos:"n.",d:"a dry area with little rain",z:"l"},
{t:"work",w:"designer",s:["creator","stylist","planner"],c:"设计师",e:"The creator showed us the plans.",k:"creator",p:"dɪˈzaɪnə",pos:"n.",d:"a person who designs things",z:"l"},
{t:"living",w:"diary",s:["journal","log","record"],c:"日记，日程本",e:"Note the date in your journal.",k:"journal",p:"ˈdaɪəri",pos:"n.",d:"a book for daily notes",z:"l"},
{t:"work",w:"director",s:["head","manager","chief"],c:"主管，导演",e:"The head approved the budget.",k:"head",p:"dəˈrektə",pos:"n.",d:"the person in charge",z:"l"},
{t:"environment",w:"disaster",s:["catastrophe","calamity","tragedy"],c:"灾难",e:"The flood was a real catastrophe.",k:"catastrophe",p:"dɪˈzɑːstə",pos:"n.",d:"a sudden terrible event",z:"l"},
{t:"living",w:"district",s:["area","region","neighbourhood"],c:"地区",e:"The area is famous for markets.",k:"area",p:"ˈdɪstrɪkt",pos:"n.",d:"a part of a town or country",z:"l"},
{t:"travel",w:"dock",s:["wharf","pier","quay"],c:"码头",e:"The ship left the wharf at noon.",k:"wharf",p:"dɒk",pos:"n.",d:"a place where ships load and unload",z:"l"},
{t:"money",w:"donation",s:["gift","contribution","grant"],c:"捐赠",e:"A generous contribution arrived today.",k:"contribution",p:"dəʊˈneɪʃn",pos:"n.",d:"money or goods given to help",z:"l"},
{t:"living",w:"drain",s:["pipe","outlet","sewer"],c:"排水管",e:"The pipe is blocked again.",k:"pipe",p:"dreɪn",pos:"n.",d:"a pipe that carries away water",z:"l"},
{t:"living",w:"drawer",s:["compartment","box","tray"],c:"抽屉",e:"The keys are in the top compartment.",k:"compartment",p:"drɔː",pos:"n.",d:"a sliding box in a piece of furniture",z:"l"},
{t:"work",w:"drill",s:["boring tool","exercise","rehearsal"],c:"钻，演练",e:"We ran a fire exercise this morning.",k:"exercise",p:"drɪl",pos:"n.",d:"a practice exercise",z:"l"},
{t:"work",w:"duty",s:["responsibility","obligation","task"],c:"职责",e:"Cleaning is part of your responsibility.",k:"responsibility",p:"ˈdjuːti",pos:"n.",d:"something you must do as part of a job",z:"l"},
{t:"living",w:"elevator",s:["lift","hoist"],c:"电梯",e:"Take the lift to the fifth floor.",k:"lift",p:"ˈelɪveɪtə",pos:"n.",d:"a machine that carries people between floors",z:"l"},
{t:"travel",w:"embassy",s:["consulate","diplomatic mission"],c:"大使馆",e:"Apply for the visa at the consulate.",k:"consulate",p:"ˈembəsi",pos:"n.",d:"the office of a country's officials abroad",z:"l"},
{t:"health",w:"emergency",s:["crisis","accident","urgent situation"],c:"紧急情况",e:"In a crisis, call this number.",k:"crisis",p:"ɪˈmɜːdʒənsi",pos:"n.",d:"a sudden serious situation",z:"l"},
{t:"technology",w:"engine",s:["motor","power unit"],c:"发动机",e:"The motor needs servicing.",k:"motor",p:"ˈendʒɪn",pos:"n.",d:"the machine that makes a vehicle move",z:"l"},
{t:"work",w:"engineer",s:["technician","designer","planner"],c:"工程师",e:"A technician checked the wiring.",k:"technician",p:"ˌendʒɪˈnɪə",pos:"n.",d:"a person who designs or repairs machines",z:"l"},
{t:"work",w:"expert",s:["specialist","authority","professional"],c:"专家",e:"A specialist examined the report.",k:"specialist",p:"ˈekspɜːt",pos:"n.",d:"a person with special knowledge",z:"l"},
{t:"work",w:"factory",s:["plant","works","mill"],c:"工厂",e:"The plant employs two hundred people.",k:"plant",p:"ˈfæktri",pos:"n.",d:"a building where goods are made",z:"l"},
{t:"shopping",w:"fashion",s:["style","trend","craze"],c:"时尚",e:"This style is popular this year.",k:"style",p:"ˈfæʃn",pos:"n.",d:"a popular way of dressing or behaving",z:"l"},
{t:"living",w:"fence",s:["barrier","railing","boundary"],c:"围栏",e:"A barrier surrounds the garden.",k:"barrier",p:"fens",pos:"n.",d:"a wooden or metal barrier around land",z:"l"},
{t:"environment",w:"forecast",s:["prediction","outlook","prognosis"],c:"预报",e:"The outlook is sunny tomorrow.",k:"outlook",p:"ˈfɔːkɑːst",pos:"n.",d:"a statement about future weather",z:"l"},
{t:"environment",w:"forest",s:["woodland","woods","timberland"],c:"森林",e:"The woodland is home to deer.",k:"woodland",p:"ˈfɒrɪst",pos:"n.",d:"a large area of trees",z:"l"},
{t:"education",w:"grade",s:["mark","score","level"],c:"分数，年级",e:"Her mark was higher this term.",k:"mark",p:"ɡreɪd",pos:"n.",d:"a level or mark for work",z:"l"},
{t:"health",w:"gymnasium",s:["sports hall","fitness centre"],c:"体育馆",e:"The sports hall has new equipment.",k:"sports hall",p:"dʒɪmˈneɪziəm",pos:"n.",d:"a large room for exercise",z:"l"},
{t:"living",w:"hall",s:["entrance area","corridor","room"],c:"大厅，走廊",e:"Wait in the entrance area.",k:"entrance area",p:"hɔːl",pos:"n.",d:"a large room or passage",z:"l"},
{t:"living",w:"handbook",s:["manual","guide","instructions"],c:"手册",e:"Read the manual before you start.",k:"manual",p:"ˈhændbʊk",pos:"n.",d:"a small book of information",z:"l"},
{t:"environment",w:"hazard",s:["danger","risk","threat"],c:"危险",e:"The wet floor is a danger.",k:"danger",p:"ˈhæzəd",pos:"n.",d:"something that may cause harm",z:"l"},
{t:"health",w:"heart",s:["centre","core","organ"],c:"心脏，中心",e:"The hotel is in the centre of town.",k:"centre",p:"hɑːt",pos:"n.",d:"the organ that pumps blood; the middle",z:"l"},
{t:"living",w:"heating",s:["warming system","central heating","warmth"],c:"暖气",e:"The warming system is electric.",k:"warming system",p:"ˈhiːtɪŋ",pos:"n.",d:"a system that makes a building warm",z:"l"},
{t:"living",w:"hedge",s:["fence","boundary","bushes"],c:"树篱",e:"The bushes line the path.",k:"bushes",p:"hedʒ",pos:"n.",d:"a row of bushes as a boundary",z:"l"},
{t:"travel",w:"highway",s:["motorway","main road","freeway"],c:"公路",e:"The motorway is closed tonight.",k:"motorway",p:"ˈhaɪweɪ",pos:"n.",d:"a main road between cities",z:"l"},
{t:"travel",w:"hobby",s:["pastime","interest","leisure activity"],c:"爱好",e:"Gardening is her main pastime.",k:"pastime",p:"ˈhɒbi",pos:"n.",d:"an activity done for enjoyment",z:"l"},
{t:"living",w:"household",s:["family","home","domestic unit"],c:"家庭，家户",e:"The family shares the costs.",k:"family",p:"ˈhaʊshəʊld",pos:"n.",d:"all the people living in one house",z:"l"},
{t:"travel",w:"inn",s:["pub with rooms","guesthouse","lodge"],c:"小旅馆",e:"We stayed at a guesthouse in the hills.",k:"guesthouse",p:"ɪn",pos:"n.",d:"a small hotel or pub with rooms",z:"l"},
{t:"education",w:"institute",s:["college","academy","organisation"],c:"学院，机构",e:"The academy offers evening courses.",k:"academy",p:"ˈɪnstɪtjuːt",pos:"n.",d:"an organisation for education or research",z:"l"},
{t:"work",w:"instruction",s:["directions","guidance","orders"],c:"说明，指示",e:"Follow the directions on the box.",k:"directions",p:"ɪnˈstrʌkʃn",pos:"n.",d:"information on how to do something",z:"l"},
{t:"media",w:"journal",s:["magazine","diary","periodical"],c:"期刊，日志",e:"The magazine comes out monthly.",k:"magazine",p:"ˈdʒɜːnl",pos:"n.",d:"a serious magazine or daily record",z:"l"},
{t:"living",w:"kitchen",s:["cooking area","galley","scullery"],c:"厨房",e:"The cooking area is well equipped.",k:"cooking area",p:"ˈkɪtʃɪn",pos:"n.",d:"the room where food is cooked",z:"l"},
{t:"living",w:"ladder",s:["steps","rungs","stairs"],c:"梯子",e:"Use the steps to reach the shelf.",k:"steps",p:"ˈlædə",pos:"n.",d:"a tool with steps for climbing",z:"l"},
{t:"travel",w:"landscape",s:["scenery","view","countryside"],c:"风景",e:"The scenery here is stunning.",k:"scenery",p:"ˈlændskeɪp",pos:"n.",d:"the natural view of an area",z:"l"},
{t:"travel",w:"lodge",s:["cabin","hut","shelter"],c:"小木屋",e:"The cabin sleeps four people.",k:"cabin",p:"lɒdʒ",pos:"n.",d:"a small house used for holidays",z:"l"},
{t:"travel",w:"lounge",s:["waiting room","sitting room","hall"],c:"休息室",e:"Wait in the sitting room.",k:"sitting room",p:"laʊndʒ",pos:"n.",d:"a comfortable room for relaxing",z:"l"},
{t:"shopping",w:"mall",s:["shopping centre","arcade","plaza"],c:"购物中心",e:"The shopping centre opens at ten.",k:"shopping centre",p:"mɔːl",pos:"n.",d:"a large covered shopping area",z:"l"},
{t:"living",w:"mattress",s:["bed base","cushion","padding"],c:"床垫",e:"The bed base is very firm.",k:"bed base",p:"ˈmætrəs",pos:"n.",d:"the soft part of a bed",z:"l"},
{t:"education",w:"memory",s:["recollection","remembrance","mind"],c:"记忆",e:"His recollection of the event is clear.",k:"recollection",p:"ˈmeməri",pos:"n.",d:"the ability to remember",z:"l"},
{t:"science",w:"molecule",s:["particle","unit","atom group"],c:"分子",e:"A water particle is very small.",k:"particle",p:"ˈmɒlɪkjuːl",pos:"n.",d:"the smallest unit of a substance",z:"l"},
{t:"travel",w:"mountain",s:["peak","summit","hill"],c:"山",e:"The peak is covered in snow.",k:"peak",p:"ˈmaʊntən",pos:"n.",d:"a very high hill",z:"l"},
{t:"media",w:"museum",s:["gallery","exhibition hall","collection"],c:"博物馆",e:"The gallery is free on Mondays.",k:"gallery",p:"mjuˈziːəm",pos:"n.",d:"a building where objects are displayed",z:"l"},
{t:"living",w:"napkin",s:["serviette","cloth","tissue"],c:"餐巾",e:"A serviette is on each plate.",k:"serviette",p:"ˈnæpkɪn",pos:"n.",d:"a cloth used while eating",z:"l"},
{t:"media",w:"newspaper",s:["paper","daily","press"],c:"报纸",e:"The daily costs two pounds.",k:"daily",p:"ˈnjuːzpeɪpə",pos:"n.",d:"a paper printed daily with news",z:"l"},
{t:"health",w:"nurse",s:["carer","attendant","medic"],c:"护士",e:"The carer checked his temperature.",k:"carer",p:"nɜːs",pos:"n.",d:"a person who looks after the sick",z:"l"},
{t:"food",w:"oven",s:["cooker","range","stove"],c:"烤箱",e:"The cooker is gas powered.",k:"cooker",p:"ˈʌvn",pos:"n.",d:"a device for baking food",z:"l"},
{t:"living",w:"owner",s:["proprietor","holder","landlord"],c:"主人，业主",e:"The proprietor welcomed the guests.",k:"proprietor",p:"ˈəʊnə",pos:"n.",d:"a person who owns something",z:"l"},
{t:"travel",w:"passenger",s:["traveller","rider","commuter"],c:"乘客",e:"Each traveller needs a valid ticket.",k:"traveller",p:"ˈpæsɪndʒə",pos:"n.",d:"a person travelling in a vehicle",z:"l"},
{t:"travel",w:"pavement",s:["sidewalk","footpath","walkway"],c:"人行道",e:"Walk on the sidewalk at night.",k:"sidewalk",p:"ˈpeɪvmənt",pos:"n.",d:"the path beside a road",z:"l"},
{t:"living",w:"purse",s:["wallet","handbag","money bag"],c:"钱包",e:"Her wallet was left on the bus.",k:"wallet",p:"pɜːs",pos:"n.",d:"a small bag for money",z:"l"},
{t:"travel",w:"railway",s:["rail line","track","train route"],c:"铁路",e:"The rail line runs along the coast.",k:"rail line",p:"ˈreɪlweɪ",pos:"n.",d:"a track for trains",z:"l"},
{t:"travel",w:"resort",s:["holiday spot","retreat","seaside town"],c:"度假胜地",e:"The holiday spot is crowded in July.",k:"holiday spot",p:"rɪˈzɔːt",pos:"n.",d:"a place people visit for holidays",z:"l"},
{t:"food",w:"restaurant",s:["eating place","diner","café"],c:"餐厅",e:"The eating place is near the river.",k:"eating place",p:"ˈrestrɒnt",pos:"n.",d:"a place where meals are served",z:"l"},
{t:"living",w:"attic",s:["loft","roof space"],c:"阁楼",e:"The old boxes are stored in the loft.",k:"loft",p:"ˈætɪk",pos:"n.",d:"a room directly under the roof",z:"l"},
{t:"living",w:"balcony",s:["veranda","terrace"],c:"阳台",e:"They had breakfast on the veranda.",k:"veranda",p:"ˈbælkəni",pos:"n.",d:"a platform on the outside of a building",z:"l"},
{t:"living",w:"patio",s:["terrace","courtyard"],c:"露台",e:"The terrace has a table and chairs.",k:"terrace",p:"ˈpætiəʊ",pos:"n.",d:"an outdoor area next to a house",z:"l"},
{t:"living",w:"porch",s:["veranda","entrance way"],c:"门廊",e:"Wait under the entrance way until the rain stops.",k:"entrance way",p:"pɔːtʃ",pos:"n.",d:"a covered entrance to a building",z:"l"},
{t:"living",w:"boiler",s:["water heater","heating unit"],c:"锅炉",e:"The water heater needs to be serviced.",k:"water heater",p:"ˈbɔɪlə",pos:"n.",d:"a device that heats water for a building",z:"l"},
{t:"living",w:"radiator",s:["heater","heat panel"],c:"暖气片",e:"Turn up the heater before bed.",k:"heater",p:"ˈreɪdieɪtə",pos:"n.",d:"a metal device that heats a room",z:"l"},
{t:"living",w:"insulation",s:["lagging","heatproof layer"],c:"隔热层",e:"The heatproof layer keeps the house warm.",k:"heatproof layer",p:"ˌɪnsjuˈleɪʃn",pos:"n.",d:"material that keeps heat or sound inside",z:"l"},
{t:"living",w:"plug",s:["connector","fitting"],c:"插头",e:"The connector fits into the wall socket.",k:"connector",p:"plʌɡ",pos:"n.",d:"a device pushed into a socket for electricity",z:"l"},
{t:"living",w:"tap",s:["faucet","valve"],c:"水龙头",e:"Turn off the faucet after washing.",k:"faucet",p:"tæp",pos:"n.",d:"a device that controls water flow",z:"l"},
{t:"living",w:"pillow",s:["cushion","headrest"],c:"枕头",e:"There is a spare cushion on the bed.",k:"cushion",p:"ˈpɪləʊ",pos:"n.",d:"a soft support for the head in bed",z:"l"},
{t:"living",w:"duvet",s:["quilt","comforter"],c:"羽绒被",e:"A quilt is provided in every room.",k:"quilt",p:"ˈduːveɪ",pos:"n.",d:"a soft thick cover for a bed",z:"l"},
{t:"living",w:"detergent",s:["washing powder","cleaner"],c:"洗涤剂",e:"This cleaner removes stubborn stains.",k:"cleaner",p:"dɪˈtɜːdʒənt",pos:"n.",d:"a liquid or powder for cleaning",z:"l"},
{t:"living",w:"bleach",s:["whitener","disinfectant"],c:"漂白剂",e:"Use the disinfectant for white clothes.",k:"disinfectant",p:"bliːtʃ",pos:"n.",d:"a chemical that whitens or cleans",z:"l"},
{t:"living",w:"mop",s:["floor cloth","squeegee"],c:"拖把",e:"Use the floor cloth to wipe the kitchen.",k:"floor cloth",p:"mɒp",pos:"n.",d:"a tool for cleaning floors with water",z:"l"},
{t:"living",w:"broom",s:["brush","sweeper"],c:"扫帚",e:"Grab the sweeper and clean the porch.",k:"sweeper",p:"bruːm",pos:"n.",d:"a brush with a long handle for sweeping",z:"l"},
{t:"living",w:"bucket",s:["pail","container"],c:"水桶",e:"Fill the pail with warm water.",k:"pail",p:"ˈbʌkɪt",pos:"n.",d:"a round open container with a handle",z:"l"},
{t:"living",w:"curtain",s:["drape","blind"],c:"窗帘",e:"Draw the drape to block the sun.",k:"drape",p:"ˈkɜːtn",pos:"n.",d:"a piece of cloth hanging over a window",z:"l"},
{t:"living",w:"cushion",s:["pad","sofa pillow"],c:"靠垫",e:"Put an extra pad on the sofa.",k:"pad",p:"ˈkʊʃn",pos:"n.",d:"a soft bag used to sit on",z:"l"},
{t:"living",w:"corridor",s:["hallway","passage"],c:"走廊",e:"The hallway leads to the main office.",k:"hallway",p:"ˈkɒrɪdɔː",pos:"n.",d:"a long narrow passage inside a building",z:"l"},
{t:"living",w:"lobby",s:["foyer","entrance hall"],c:"大堂",e:"Wait in the foyer for the tour guide.",k:"foyer",p:"ˈlɒbi",pos:"n.",d:"the entrance area of a building",z:"l"},
{t:"living",w:"tenancy",s:["lease period","rental term"],c:"租期",e:"The rental term lasts for one year.",k:"rental term",p:"ˈtenənsi",pos:"n.",d:"the period for which a property is rented",z:"l"},
{t:"living",w:"sublet",s:["sublease","rent out"],c:"转租",e:"They decided to sublease the flat.",k:"sublease",p:"ˌsʌbˈlet",pos:"v.",d:"to rent a property from a tenant",z:"l"},
{t:"living",w:"flatmate",s:["housemate","roommate"],c:"室友",e:"My housemate pays half the rent.",k:"housemate",p:"ˈflætmeɪt",pos:"n.",d:"a person sharing a flat",z:"l"},
{t:"living",w:"mould",s:["fungus","mildew"],c:"霉菌",e:"Mildew grows in damp corners.",k:"Mildew",p:"məʊld",pos:"n.",d:"a soft green or black growth on damp surfaces",z:"l"},
{t:"living",w:"leak",s:["drip","seepage"],c:"漏水",e:"A drip from the pipe stained the ceiling.",k:"drip",p:"liːk",pos:"n.",d:"a hole or crack where liquid escapes",z:"l"},
{t:"living",w:"plumber",s:["pipe fitter","repairman"],c:"水管工",e:"The pipe fitter will come this afternoon.",k:"pipe fitter",p:"ˈplʌmə",pos:"n.",d:"a person who repairs water pipes",z:"l"},
{t:"living",w:"electrician",s:["wiring expert","repairer"],c:"电工",e:"Call the wiring expert to fix the fuse.",k:"wiring expert",p:"ɪˌlekˈtrɪʃn",pos:"n.",d:"a person who repairs electrical systems",z:"l"},
{t:"living",w:"carpenter",s:["joiner","woodworker"],c:"木匠",e:"The joiner built the new shelves.",k:"joiner",p:"ˈkɑːpəntə",pos:"n.",d:"a person who makes things from wood",z:"l"},
{t:"living",w:"handyman",s:["odd-job man","maintenance man"],c:"杂务工",e:"The maintenance man fixed the door.",k:"maintenance man",p:"ˈhændimæn",pos:"n.",d:"a person who does small repairs",z:"l"},
{t:"travel",w:"freight",s:["cargo","goods transport"],c:"货运",e:"Cargo is loaded at the dock.",k:"Cargo",p:"freɪt",pos:"n.",d:"goods carried by ship, train or lorry",z:"l"},
{t:"travel",w:"cargo",s:["load","goods","shipment"],c:"货物",e:"The shipment left the port this morning.",k:"shipment",p:"ˈkɑːɡəʊ",pos:"n.",d:"goods carried on a ship or plane",z:"l"},
{t:"travel",w:"depot",s:["storage yard","bus terminal"],c:"车场，仓库",e:"The buses return to the storage yard at night.",k:"storage yard",p:"ˈdepəʊ",pos:"n.",d:"a place where vehicles or goods are kept",z:"l"},
{t:"travel",w:"consignment",s:["shipment","delivery"],c:"托运的货物",e:"Sign for the delivery at the front desk.",k:"delivery",p:"kənˈsaɪnmənt",pos:"n.",d:"a batch of goods sent to someone",z:"l"},
{t:"travel",w:"parcel",s:["package","packet"],c:"包裹",e:"The package arrived by courier.",k:"package",p:"ˈpɑːsl",pos:"n.",d:"an object wrapped for posting",z:"l"},
{t:"travel",w:"envelope",s:["wrapper","mailer"],c:"信封",e:"Put the form in the mailer provided.",k:"mailer",p:"ˈenvələʊp",pos:"n.",d:"a paper cover for a letter",z:"l"},
{t:"travel",w:"registered mail",s:["recorded delivery","certified mail"],c:"挂号信",e:"Send it by recorded delivery to be safe.",k:"recorded delivery",p:"ˈredʒɪstəd meɪl",pos:"n.",d:"a mail service that records delivery",z:"l"},
{t:"travel",w:"airmail",s:["air post","express post"],c:"航空邮件",e:"Use air post for overseas letters.",k:"air post",p:"ˈeəmeɪl",pos:"n.",d:"mail sent by aircraft",z:"l"},
{t:"travel",w:"ramp",s:["slope","incline"],c:"坡道",e:"The slope makes the entrance easier to reach.",k:"slope",p:"ræmp",pos:"n.",d:"a sloping surface joining two levels",z:"l"},
{t:"travel",w:"tube",s:["underground","metro"],c:"地铁",e:"Take the metro to the city centre.",k:"metro",p:"tjuːb",pos:"n.",d:"an underground railway",z:"l"},
{t:"travel",w:"interchange",s:["junction","transfer point"],c:"换乘站",e:"Change trains at the transfer point.",k:"transfer point",p:"ˈɪntətʃeɪndʒ",pos:"n.",d:"a station where passengers change trains",z:"l"},
{t:"travel",w:"terminus",s:["end station","terminal"],c:"终点站",e:"The end station is two stops away.",k:"end station",p:"ˈtɜːmɪnəs",pos:"n.",d:"the final stop of a transport route",z:"l"},
{t:"travel",w:"flyover",s:["overpass","bridge"],c:"立交桥",e:"The overpass crosses the main road.",k:"overpass",p:"ˈflaɪəʊvə",pos:"n.",d:"a road built over another road",z:"l"},
{t:"travel",w:"underpass",s:["tunnel","subway"],c:"地下通道",e:"Use the tunnel to cross the road safely.",k:"tunnel",p:"ˈʌndəpɑːs",pos:"n.",d:"a passage under a road for pedestrians",z:"l"},
{t:"travel",w:"kerb",s:["edge","road edge"],c:"路缘石",e:"Park close to the edge of the road.",k:"edge",p:"kɜːb",pos:"n.",d:"the raised edge of a pavement",z:"l"},
{t:"travel",w:"pothole",s:["hole","dip"],c:"坑洼",e:"The bus hit a dip in the road.",k:"dip",p:"ˈpɒthəʊl",pos:"n.",d:"a hole in the road surface",z:"l"},
{t:"travel",w:"toll",s:["charge","road fee"],c:"过路费",e:"Drivers pay a charge to cross the bridge.",k:"charge",p:"təʊl",pos:"n.",d:"money paid to use a road or bridge",z:"l"},
{t:"travel",w:"commuter",s:["daily traveller","regular passenger"],c:"通勤者",e:"The daily traveller buys a season ticket.",k:"daily traveller",p:"kəˈmjuːtə",pos:"n.",d:"a person who travels to work each day",z:"l"},
{t:"travel",w:"runway",s:["landing strip","airstrip"],c:"跑道",e:"The plane waited on the landing strip.",k:"landing strip",p:"ˈrʌnweɪ",pos:"n.",d:"the strip of ground where planes land",z:"l"},
{t:"travel",w:"hangar",s:["aircraft shed","garage"],c:"机库",e:"The aircraft shed is near the control tower.",k:"aircraft shed",p:"ˈhæŋə",pos:"n.",d:"a large building for aircraft",z:"l"},
{t:"travel",w:"checkpoint",s:["control point","barrier"],c:"检查站",e:"Show your pass at the control point.",k:"control point",p:"ˈtʃekpɔɪnt",pos:"n.",d:"a place where documents are checked",z:"l"},
{t:"travel",w:"baggage claim",s:["luggage collection","baggage area"],c:"行李提取处",e:"Wait near luggage collection for your suitcase.",k:"luggage collection",p:"ˈbæɡɪdʒ kleɪm",pos:"n.",d:"the place where passengers collect bags",z:"l"},
{t:"health",w:"wheelchair",s:["mobility chair","chair"],c:"轮椅",e:"The mobility chair can use the ramp.",k:"mobility chair",p:"ˈwiːltʃeə",pos:"n.",d:"a chair with wheels for disabled people",z:"l"},
{t:"health",w:"outpatient",s:["clinic patient","day patient"],c:"门诊病人",e:"The clinic patient returns next week.",k:"clinic patient",p:"ˈaʊtpeɪʃnt",pos:"n.",d:"a patient treated without staying overnight",z:"l"},
{t:"health",w:"inpatient",s:["hospital patient","ward patient"],c:"住院病人",e:"The ward patient needs a blood test.",k:"ward patient",p:"ˈɪnpeɪʃnt",pos:"n.",d:"a patient staying in hospital overnight",z:"l"},
{t:"health",w:"epidemic",s:["outbreak","plague"],c:"流行病",e:"The outbreak spread across the city.",k:"outbreak",p:"ˌepɪˈdemɪk",pos:"n.",d:"a rapid spread of disease in an area",z:"l"},
{t:"edu",w:"workshop",s:["training session","seminar"],c:"工作坊，研讨会",e:"The training session starts at ten.",k:"training session",p:"ˈwɜːkʃɒp",pos:"n.",d:"a meeting for practical learning",z:"l"},
{t:"edu",w:"practicum",s:["placement","field training"],c:"实习课程",e:"Students complete a placement in term three.",k:"placement",p:"ˈpræktɪkəm",pos:"n.",d:"a practical part of a course",z:"l"},
{t:"edu",w:"matriculation",s:["enrolment","admission"],c:"入学注册",e:"Admission week begins on Monday.",k:"Admission",p:"məˌtrɪkjuˈleɪʃn",pos:"n.",d:"the process of entering a university",z:"l"},
{t:"edu",w:"lecture theatre",s:["auditorium","lecture hall"],c:"阶梯教室",e:"The lecture hall seats three hundred.",k:"lecture hall",p:"ˈlektʃə ˈθɪətə",pos:"n.",d:"a large room for lectures",z:"l"},
{t:"shopping",w:"basket",s:["carrier","bin"],c:"购物篮",e:"Grab a carrier for the vegetables.",k:"carrier",p:"ˈbɑːskɪt",pos:"n.",d:"a container for carrying shopping",z:"l"},
{t:"shopping",w:"leaflet",s:["flyer","handout"],c:"传单",e:"The flyer lists this week's offers.",k:"flyer",p:"ˈliːflət",pos:"n.",d:"a printed sheet with information",z:"l"},
{t:"shopping",w:"poster",s:["placard","notice"],c:"海报",e:"The notice announces the sale.",k:"notice",p:"ˈpəʊstə",pos:"n.",d:"a large printed picture or announcement",z:"l"},
{t:"food",w:"cuisine",s:["cooking","dishes"],c:"菜系，烹饪",e:"The restaurant serves French cooking.",k:"cooking",p:"kwɪˈziːn",pos:"n.",d:"a style of cooking",z:"l"},
{t:"food",w:"dessert",s:["pudding","sweet course"],c:"甜点",e:"The pudding is included in the price.",k:"pudding",p:"dɪˈzɜːt",pos:"n.",d:"sweet food eaten after a meal",z:"l"},
{t:"food",w:"pastry",s:["baked goods","cake"],c:"糕点",e:"Fresh baked goods are sold downstairs.",k:"baked goods",p:"ˈpeɪstri",pos:"n.",d:"food made with flour and fat",z:"l"},
{t:"food",w:"dough",s:["batter","mixture"],c:"面团",e:"Knead the batter until smooth.",k:"batter",p:"dəʊ",pos:"n.",d:"a thick mixture of flour and water",z:"l"},
{t:"food",w:"grill",s:["barbecue","broil"],c:"烧烤",e:"Barbecue the fish for five minutes.",k:"Barbecue",p:"ɡrɪl",pos:"v.",d:"to cook food over direct heat",z:"l"},
{t:"food",w:"roast",s:["bake","cook"],c:"烤",e:"Bake the chicken for an hour.",k:"Bake",p:"rəʊst",pos:"v.",d:"to cook food in an oven",z:"l"},
{t:"food",w:"stew",s:["casserole","hotpot"],c:"炖菜",e:"The casserole simmered all morning.",k:"casserole",p:"stjuː",pos:"n.",d:"a dish of meat and vegetables cooked slowly",z:"l"},
{t:"food",w:"fridge",s:["refrigerator","cooler"],c:"冰箱",e:"Keep the milk in the refrigerator.",k:"refrigerator",p:"frɪdʒ",pos:"n.",d:"an appliance that keeps food cold",z:"l"}
];
const V7W = [
{t:"academic",w:"accumulate",s:["build up","gather","amass"],c:"积累",e:"Dust tends to build up on the shelves.",k:"build up",p:"əˈkjuːmjəleɪt",pos:"v.",d:"to gradually increase in amount",z:"w"},
{t:"core",w:"adapt",s:["adjust","acclimatise"],c:"适应",e:"New students quickly adjust to the routine.",k:"adjust",p:"əˈdæpt",pos:"v.",d:"to change to suit a new situation",z:"w"},
{t:"academic",w:"alienate",s:["estrange","isolate"],c:"疏远",e:"The policy may estrange local residents.",k:"estrange",p:"ˈeɪliəneɪt",pos:"v.",d:"to make someone feel unwelcome",z:"w"},
{t:"work",w:"aspire",s:["aim","strive for"],c:"渴望，立志",e:"She aims to become a researcher.",k:"aims",p:"əˈspaɪə",pos:"v.",d:"to have a strong desire to achieve",z:"w"},
{t:"academic",w:"assimilate",s:["absorb","take in"],c:"吸收，同化",e:"It takes time to absorb new information.",k:"absorb",p:"əˈsɪməleɪt",pos:"v.",d:"to fully understand and accept ideas",z:"w"},
{t:"academic",w:"attribute",s:["ascribe","credit"],c:"归因于",e:"Experts ascribe the rise to better diet.",k:"ascribe",p:"əˈtrɪbjuːt",pos:"v.",d:"to say something is caused by something",z:"w"},
{t:"academic",w:"avert",s:["prevent","avoid"],c:"避免",e:"Good planning can prevent such disasters.",k:"prevent",p:"əˈvɜːt",pos:"v.",d:"to stop something bad from happening",z:"w"},
{t:"academic",w:"bolster",s:["reinforce","strengthen"],c:"支持，加强",e:"Extra funding will strengthen the programme.",k:"strengthen",p:"ˈbəʊlstə",pos:"v.",d:"to support or improve something",z:"w"},
{t:"shopping",w:"boycott",s:["protest against","refuse to buy"],c:"抵制",e:"Consumers refused to buy the product.",k:"refused to buy",p:"ˈbɔɪkɒt",pos:"v.",d:"to refuse to buy goods as a protest",z:"w"},
{t:"academic",w:"calibrate",s:["adjust","tune"],c:"校准",e:"The team adjusted the equipment daily.",k:"adjusted",p:"ˈkælɪbreɪt",pos:"v.",d:"to check and correct a measuring device",z:"w"},
{t:"academic",w:"circulate",s:["spread","go around"],c:"传播，流通",e:"The news spread quickly online.",k:"spread",p:"ˈsɜːkjəleɪt",pos:"v.",d:"to move around or pass from person to person",z:"w"},
{t:"academic",w:"clarify",s:["explain","make clear"],c:"澄清",e:"The report explains the main causes.",k:"explains",p:"ˈklærəfaɪ",pos:"v.",d:"to make something easier to understand",z:"w"},
{t:"academic",w:"classify",s:["categorise","sort"],c:"分类",e:"Researchers categorise the data by age.",k:"categorise",p:"ˈklæsɪfaɪ",pos:"v.",d:"to arrange things into groups",z:"w"},
{t:"academic",w:"collapse",s:["fall down","break down"],c:"崩溃，倒塌",e:"The old bridge fell down last year.",k:"fell down",p:"kəˈlæps",pos:"v.",d:"to fall down suddenly",z:"w"},
{t:"travel",w:"collide",s:["crash","bump into"],c:"碰撞",e:"Two cars crashed at the junction.",k:"crashed",p:"kəˈlaɪd",pos:"v.",d:"to hit each other with force",z:"w"},
{t:"academic",w:"complement",s:["supplement","complete"],c:"补充",e:"The course supplements classroom learning.",k:"supplements",p:"ˈkɒmplɪment",pos:"v.",d:"to add to something to make it complete",z:"w"},
{t:"work",w:"comply",s:["obey","follow"],c:"遵守",e:"All staff must obey safety rules.",k:"obey",p:"kəmˈplaɪ",pos:"v.",d:"to act according to a rule or request",z:"w"},
{t:"academic",w:"conceal",s:["hide","cover up"],c:"隐藏",e:"She tried to hide her nervousness.",k:"hide",p:"kənˈsiːl",pos:"v.",d:"to keep something from being seen",z:"w"},
{t:"academic",w:"condense",s:["compress","shorten"],c:"浓缩，压缩",e:"The article was shortened for the journal.",k:"shortened",p:"kənˈdens",pos:"v.",d:"to make something shorter or thicker",z:"w"},
{t:"academic",w:"confine",s:["restrict","limit"],c:"限制",e:"The study was limited to one city.",k:"limited",p:"kənˈfaɪn",pos:"v.",d:"to keep something within limits",z:"w"},
{t:"academic",w:"contemplate",s:["consider","ponder"],c:"沉思，考虑",e:"The committee considered several options.",k:"considered",p:"ˈkɒntəmpleɪt",pos:"v.",d:"to think about something carefully",z:"w"},
{t:"academic",w:"converge",s:["meet","come together"],c:"汇聚",e:"The two rivers come together here.",k:"come together",p:"kənˈvɜːdʒ",pos:"v.",d:"to move towards one point",z:"w"},
{t:"academic",w:"convey",s:["communicate","express"],c:"传达",e:"The diagram communicates the trend clearly.",k:"communicates",p:"kənˈveɪ",pos:"v.",d:"to pass information or feelings to others",z:"w"},
{t:"work",w:"cooperate",s:["work together","collaborate"],c:"合作",e:"Teams work together on the project.",k:"work together",p:"kəʊˈɒpəreɪt",pos:"v.",d:"to work with others towards a goal",z:"w"},
{t:"work",w:"coordinate",s:["organise","arrange"],c:"协调",e:"She organises the training schedule.",k:"organises",p:"kəʊˈɔːdɪneɪt",pos:"v.",d:"to arrange activities to work well together",z:"w"},
{t:"academic",w:"correspond",s:["match","agree with"],c:"相符，对应",e:"The results match the prediction.",k:"match",p:"ˌkɒrəˈspɒnd",pos:"v.",d:"to be the same or similar to something",z:"w"},
{t:"academic",w:"culminate",s:["peak","end in"],c:"达到顶点",e:"The course ends in a final exam.",k:"ends in",p:"ˈkʌlmɪneɪt",pos:"v.",d:"to reach a final high point",z:"w"},
{t:"academic",w:"dedicate",s:["devote","commit"],c:"奉献",e:"She devotes hours to revision.",k:"devotes",p:"ˈdedɪkeɪt",pos:"v.",d:"to give time and effort to something",z:"w"},
{t:"academic",w:"deduct",s:["subtract","take off"],c:"扣除",e:"The fee is subtracted from your pay.",k:"subtracted",p:"dɪˈdʌkt",pos:"v.",d:"to take an amount away from a total",z:"w"},
{t:"env",w:"degrade",s:["worsen","deteriorate"],c:"退化，恶化",e:"Pollution worsens the soil quality.",k:"worsens",p:"dɪˈɡreɪd",pos:"v.",d:"to make something worse or less good",z:"w"},
{t:"living",w:"demolish",s:["tear down","knock down"],c:"拆除",e:"They tore down the old warehouse.",k:"tore down",p:"dɪˈmɒlɪʃ",pos:"v.",d:"to destroy a building completely",z:"w"},
{t:"work",w:"deploy",s:["utilise","position"],c:"部署，调用",e:"The firm utilises new software.",k:"utilises",p:"dɪˈplɔɪ",pos:"v.",d:"to use or arrange resources effectively",z:"w"},
{t:"academic",w:"deprive",s:["deny","strip of"],c:"剥夺",e:"Poor sleep denies students energy.",k:"denies",p:"dɪˈpraɪv",pos:"v.",d:"to take something away from someone",z:"w"},
{t:"academic",w:"descend",s:["go down","drop"],c:"下降",e:"Prices go down in winter.",k:"go down",p:"dɪˈsend",pos:"v.",d:"to move downwards",z:"w"},
{t:"work",w:"dismiss",s:["fire","lay off"],c:"解雇",e:"The company laid off fifty workers.",k:"laid off",p:"dɪsˈmɪs",pos:"v.",d:"to remove someone from a job",z:"w"},
{t:"academic",w:"displace",s:["replace","dislodge"],c:"取代",e:"Machines replaced many manual jobs.",k:"replaced",p:"dɪsˈpleɪs",pos:"v.",d:"to take the place of something",z:"w"},
{t:"work",w:"dispute",s:["challenge","question"],c:"质疑，争议",e:"Scientists challenge the finding.",k:"challenge",p:"dɪˈspjuːt",pos:"v.",d:"to argue that something is not true",z:"w"},
{t:"academic",w:"dissolve",s:["melt","break down"],c:"溶解",e:"The powder melts in water.",k:"melts",p:"dɪˈzɒlv",pos:"v.",d:"to mix completely into a liquid",z:"w"},
{t:"academic",w:"distract",s:["divert","take attention away"],c:"分散注意力",e:"Noise takes attention away from study.",k:"takes attention away",p:"dɪˈstrækt",pos:"v.",d:"to stop someone focusing on something",z:"w"},
{t:"academic",w:"distribute",s:["hand out","spread"],c:"分配，分发",e:"The charity handed out food parcels.",k:"handed out",p:"dɪˈstrɪbjuːt",pos:"v.",d:"to give things to a group of people",z:"w"},
{t:"travel",w:"divert",s:["reroute","redirect"],c:"改道",e:"Traffic was rerouted during repairs.",k:"rerouted",p:"daɪˈvɜːt",pos:"v.",d:"to send something a different way",z:"w"},
{t:"living",w:"dwell",s:["reside","live"],c:"居住",e:"Many families live in the suburbs.",k:"live",p:"dwel",pos:"v.",d:"to live in a place",z:"w"},
{t:"academic",w:"elevate",s:["raise","boost"],c:"提升",e:"The course raises skill levels.",k:"raises",p:"ˈelɪveɪt",pos:"v.",d:"to raise to a higher level",z:"w"},
{t:"travel",w:"embark",s:["set off","begin"],c:"启程，开始",e:"They set off on the expedition.",k:"set off",p:"ɪmˈbɑːk",pos:"v.",d:"to begin a journey or new venture",z:"w"},
{t:"academic",w:"embed",s:["implant","set in"],c:"嵌入",e:"The values are set in the training.",k:"set in",p:"ɪmˈbed",pos:"v.",d:"to fix something firmly within something else",z:"w"},
{t:"feelings",w:"embrace",s:["accept","adopt"],c:"接受，拥抱",e:"The city adopted the new policy.",k:"adopted",p:"ɪmˈbreɪs",pos:"v.",d:"to accept an idea willingly",z:"w"},
{t:"env",w:"emit",s:["release","discharge"],c:"排放",e:"Factories release harmful gases.",k:"release",p:"iˈmɪt",pos:"v.",d:"to send out gas, light or heat",z:"w"},
{t:"academic",w:"emphasize",s:["stress","highlight"],c:"强调",e:"The article stresses the risks.",k:"stresses",p:"ˈemfəsaɪz",pos:"v.",d:"to give special importance to something",z:"w"},
{t:"work",w:"empower",s:["enable","authorise"],c:"赋权",e:"Training enables staff to decide.",k:"enables",p:"ɪmˈpaʊə",pos:"v.",d:"to give someone the power to act",z:"w"},
{t:"academic",w:"encompass",s:["include","cover"],c:"包含",e:"The course covers all key topics.",k:"covers",p:"ɪnˈkʌmpəs",pos:"v.",d:"to include a wide range of things",z:"w"},
{t:"edu",w:"enlighten",s:["inform","educate"],c:"启发",e:"The talk educated the audience.",k:"educated",p:"ɪnˈlaɪtn",pos:"v.",d:"to give someone knowledge or understanding",z:"w"},
{t:"academic",w:"enrich",s:["enhance","improve"],c:"丰富",e:"Travel improves cultural understanding.",k:"improves",p:"ɪnˈrɪtʃ",pos:"v.",d:"to improve the quality of something",z:"w"},
{t:"academic",w:"envisage",s:["imagine","foresee"],c:"设想",e:"They imagine a cleaner city.",k:"imagine",p:"ɪnˈvɪzɪdʒ",pos:"v.",d:"to picture something happening in the future",z:"w"},
{t:"living",w:"erect",s:["build","construct"],c:"建造",e:"They built a new library.",k:"built",p:"ɪˈrekt",pos:"v.",d:"to build or put up a structure",z:"w"},
{t:"env",w:"erupt",s:["explode","burst out"],c:"喷发",e:"The volcano burst out at dawn.",k:"burst out",p:"ɪˈrʌpt",pos:"v.",d:"to explode with force",z:"w"},
{t:"academic",w:"evade",s:["avoid","dodge"],c:"逃避",e:"Drivers tried to avoid the toll.",k:"avoid",p:"ɪˈveɪd",pos:"v.",d:"to escape from or avoid something",z:"w"},
{t:"academic",w:"exaggerate",s:["overstate","overemphasise"],c:"夸大",e:"The media overstated the figures.",k:"overstated",p:"ɪɡˈzædʒəreɪt",pos:"v.",d:"to describe something as larger than it is",z:"w"},
{t:"work",w:"excel",s:["shine","do well"],c:"擅长",e:"She does well in exams.",k:"does well",p:"ɪkˈsel",pos:"v.",d:"to be very good at something",z:"w"},
{t:"work",w:"expire",s:["run out","lapse"],c:"到期",e:"Your card runs out next month.",k:"runs out",p:"ɪkˈspaɪə",pos:"v.",d:"to come to the end of validity",z:"w"},
{t:"academic",w:"fabricate",s:["invent","make up"],c:"捏造",e:"The report was made up entirely.",k:"made up",p:"ˈfæbrɪkeɪt",pos:"v.",d:"to invent false information",z:"w"},
{t:"academic",w:"fade",s:["diminish","die away"],c:"消退",e:"Interest in the topic died away.",k:"died away",p:"feɪd",pos:"v.",d:"to gradually become less strong",z:"w"},
{t:"work",w:"forbid",s:["ban","prohibit"],c:"禁止",e:"The law bans smoking indoors.",k:"bans",p:"fəˈbɪd",pos:"v.",d:"to say that something must not be done",z:"w"},
{t:"academic",w:"foresee",s:["predict","anticipate"],c:"预见",e:"Experts predicted the shortage.",k:"predicted",p:"fɔːˈsiː",pos:"v.",d:"to know about something before it happens",z:"w"},
{t:"work",w:"forge",s:["create","build"],c:"打造，建立",e:"The plan creates new links.",k:"creates",p:"fɔːdʒ",pos:"v.",d:"to build or develop something strong",z:"w"},
{t:"edu",w:"grasp",s:["understand","master"],c:"掌握",e:"Students must master key concepts.",k:"master",p:"ɡrɑːsp",pos:"v.",d:"to understand something fully",z:"w"},
{t:"work",w:"halt",s:["stop","cease"],c:"停止",e:"Work on the site stopped abruptly.",k:"stopped",p:"hɔːlt",pos:"v.",d:"to bring something to a stop",z:"w"},
{t:"academic",w:"hasten",s:["speed up","quicken"],c:"加速",e:"The crisis sped up the reform.",k:"sped up",p:"ˈheɪsn",pos:"v.",d:"to make something happen sooner",z:"w"},
{t:"health",w:"heal",s:["recover","cure"],c:"治愈",e:"The wound recovered within weeks.",k:"recovered",p:"hiːl",pos:"v.",d:"to become healthy again",z:"w"},
{t:"academic",w:"imitate",s:["copy","mimic"],c:"模仿",e:"Children copy adult behaviour.",k:"copy",p:"ˈɪmɪteɪt",pos:"v.",d:"to copy the way someone behaves",z:"w"},
{t:"health",w:"impair",s:["damage","weaken"],c:"损害",e:"Noise damages hearing over time.",k:"damages",p:"ɪmˈpeə",pos:"v.",d:"to make something less effective",z:"w"},
{t:"academic",w:"imply",s:["suggest","indicate"],c:"暗示",e:"The data suggests a decline.",k:"suggests",p:"ɪmˈplaɪ",pos:"v.",d:"to suggest something without saying it",z:"w"},
{t:"health",w:"infect",s:["contaminate","spread to"],c:"感染",e:"The virus spread to many patients.",k:"spread to",p:"ɪnˈfekt",pos:"v.",d:"to pass a disease to someone",z:"w"},
{t:"academic",w:"inflate",s:["swell","blow up"],c:"膨胀，抬高",e:"Prices swelled during the boom.",k:"swelled",p:"ɪnˈfleɪt",pos:"v.",d:"to increase in size or price",z:"w"},
{t:"living",w:"inhabit",s:["occupy","live in"],c:"居住于",e:"Few species live in the desert.",k:"live in",p:"ɪnˈhæbɪt",pos:"v.",d:"to live in a place",z:"w"},
{t:"work",w:"innovate",s:["invent","modernise"],c:"创新",e:"The firm modernised its services.",k:"modernised",p:"ˈɪnəveɪt",pos:"v.",d:"to introduce new ideas or methods",z:"w"},
{t:"academic",w:"interfere",s:["meddle","intrude"],c:"干涉",e:"The state should not meddle in markets.",k:"meddle",p:"ˌɪntəˈfɪə",pos:"v.",d:"to become involved where not wanted",z:"w"},
{t:"work",w:"intimidate",s:["frighten","threaten"],c:"恐吓",e:"Bosses should not threaten workers.",k:"threaten",p:"ɪnˈtɪmɪdeɪt",pos:"v.",d:"to frighten someone into doing something",z:"w"},
{t:"academic",w:"investigate",s:["examine","probe"],c:"调查",e:"The police examined the records.",k:"examined",p:"ɪnˈvestɪɡeɪt",pos:"v.",d:"to examine something carefully",z:"w"},
{t:"academic",w:"invoke",s:["cite","call upon"],c:"援引",e:"The report cites several studies.",k:"cites",p:"ɪnˈvəʊk",pos:"v.",d:"to mention something as support",z:"w"},
{t:"academic",w:"lessen",s:["reduce","ease"],c:"减轻",e:"Exercise reduces stress levels.",k:"reduces",p:"ˈlesn",pos:"v.",d:"to make something smaller or weaker",z:"w"},
{t:"work",w:"maximize",s:["optimise","increase"],c:"最大化",e:"The plan optimises limited resources.",k:"optimises",p:"ˈmæksɪmaɪz",pos:"v.",d:"to make something as large as possible",z:"w"},
{t:"work",w:"mediate",s:["negotiate","intervene"],c:"调解",e:"A manager intervened in the dispute.",k:"intervened",p:"ˈmiːdieɪt",pos:"v.",d:"to help two sides reach an agreement",z:"w"},
{t:"work",w:"merge",s:["combine","unite"],c:"合并",e:"The two firms combined last year.",k:"combined",p:"mɜːdʒ",pos:"v.",d:"to join together into one",z:"w"},
{t:"env",w:"migrate",s:["move","relocate"],c:"迁徙",e:"Birds move south in autumn.",k:"move",p:"maɪˈɡreɪt",pos:"v.",d:"to move from one region to another",z:"w"},
{t:"academic",w:"mimic",s:["copy","imitate"],c:"模仿",e:"The app copies human speech.",k:"copies",p:"ˈmɪmɪk",pos:"v.",d:"to copy the appearance or sound of something",z:"w"},
{t:"travel",w:"navigate",s:["steer","find the way"],c:"导航，航行",e:"The app helps drivers find the way.",k:"find the way",p:"ˈnævɪɡeɪt",pos:"v.",d:"to find the correct direction to travel",z:"w"},
{t:"health",w:"nourish",s:["feed","sustain"],c:"滋养",e:"A balanced diet feeds the brain.",k:"feeds",p:"ˈnʌrɪʃ",pos:"v.",d:"to give food needed for health",z:"w"},
{t:"work",w:"oblige",s:["force","compel"],c:"迫使",e:"The law forces firms to comply.",k:"forces",p:"əˈblaɪdʒ",pos:"v.",d:"to make someone do something",z:"w"},
{t:"living",w:"occupy",s:["take up","fill"],c:"占据",e:"The boxes take up half the room.",k:"take up",p:"ˈɒkjupaɪ",pos:"v.",d:"to fill or use a space or time",z:"w"},
{t:"feelings",w:"offend",s:["insult","upset"],c:"冒犯",e:"The remark upset several members.",k:"upset",p:"əˈfend",pos:"v.",d:"to make someone feel hurt or angry",z:"w"},
{t:"academic",w:"originate",s:["start","derive"],c:"起源",e:"The idea started in the 1990s.",k:"started",p:"əˈrɪdʒɪneɪt",pos:"v.",d:"to begin or come from somewhere",z:"w"},
{t:"work",w:"overlook",s:["miss","neglect"],c:"忽视",e:"Managers must not neglect feedback.",k:"neglect",p:"ˌəʊvəˈlʊk",pos:"v.",d:"to fail to notice something",z:"w"},
{t:"work",w:"oversee",s:["supervise","manage"],c:"监督",e:"A senior officer supervises the team.",k:"supervises",p:"ˌəʊvəˈsiː",pos:"v.",d:"to watch and check that work is done",z:"w"},
{t:"academic",w:"penetrate",s:["pierce","enter"],c:"穿透",e:"Light pierces the shallow water.",k:"pierces",p:"ˈpenətreɪt",pos:"v.",d:"to pass through or into something",z:"w"},
{t:"work",w:"perform",s:["carry out","execute"],c:"执行，表现",e:"The team carried out the tests.",k:"carried out",p:"pəˈfɔːm",pos:"v.",d:"to do a task or action",z:"w"},
{t:"academic",w:"persevere",s:["persist","keep going"],c:"坚持",e:"She kept going despite setbacks.",k:"kept going",p:"ˌpɜːsɪˈvɪə",pos:"v.",d:"to continue despite difficulty",z:"w"},
{t:"core",w:"persuade",s:["convince","win over"],c:"说服",e:"The data convinced the committee.",k:"convinced",p:"pəˈsweɪd",pos:"v.",d:"to make someone believe or do something",z:"w"},
{t:"academic",w:"plunge",s:["drop sharply","nosedive"],c:"暴跌",e:"Sales dropped sharply in May.",k:"dropped sharply",p:"plʌndʒ",pos:"v.",d:"to fall suddenly and quickly",z:"w"},
{t:"academic",w:"portray",s:["depict","describe"],c:"描绘",e:"The film describes rural life.",k:"describes",p:"pɔːˈtreɪ",pos:"v.",d:"to show or describe someone or something",z:"w"},
{t:"academic",w:"pose",s:["present","create"],c:"造成",e:"The plan creates new risks.",k:"creates",p:"pəʊz",pos:"v.",d:"to cause a problem or threat",z:"w"},
{t:"academic",w:"predict",s:["forecast","anticipate"],c:"预测",e:"Analysts forecast steady growth.",k:"forecast",p:"prɪˈdɪkt",pos:"v.",d:"to say what will happen in the future",z:"w"},
{t:"health",w:"prescribe",s:["order","recommend"],c:"开处方",e:"The doctor ordered a new medicine.",k:"ordered",p:"prɪˈskraɪb",pos:"v.",d:"to write an instruction for medicine",z:"w"},
{t:"env",w:"preserve",s:["protect","conserve"],c:"保护",e:"The park protects rare species.",k:"protects",p:"prɪˈzɜːv",pos:"v.",d:"to keep something in its original state",z:"w"},
{t:"academic",w:"presume",s:["assume","suppose"],c:"假定",e:"We assume the data is correct.",k:"assume",p:"prɪˈzjuːm",pos:"v.",d:"to believe something without proof",z:"w"},
{t:"academic",w:"proclaim",s:["declare","announce"],c:"宣告",e:"The city announced a new policy.",k:"announced",p:"prəˈkleɪm",pos:"v.",d:"to announce something publicly",z:"w"},
{t:"work",w:"procrastinate",s:["delay","put off"],c:"拖延",e:"Students put off difficult tasks.",k:"put off",p:"prəʊˈkræstɪneɪt",pos:"v.",d:"to delay doing something",z:"w"},
{t:"work",w:"procure",s:["obtain","acquire"],c:"采购",e:"The firm obtained better materials.",k:"obtained",p:"prəˈkjʊə",pos:"v.",d:"to obtain supplies for an organisation",z:"w"},
{t:"work",w:"prohibit",s:["ban","forbid"],c:"禁止",e:"The rules ban mobile phones.",k:"ban",p:"prəˈhɪbɪt",pos:"v.",d:"to officially forbid something",z:"w"},
{t:"academic",w:"proliferate",s:["multiply","spread rapidly"],c:"激增",e:"Online courses multiplied during lockdown.",k:"multiplied",p:"prəˈlɪfəreɪt",pos:"v.",d:"to increase rapidly in number",z:"w"},
{t:"health",w:"prolong",s:["extend","lengthen"],c:"延长",e:"The drug extends patients' lives.",k:"extends",p:"prəˈlɒŋ",pos:"v.",d:"to make something last longer",z:"w"},
{t:"work",w:"prompt",s:["trigger","spur"],c:"促使",e:"The results spurred further research.",k:"spurred",p:"prɒmpt",pos:"v.",d:"to cause something to happen",z:"w"},
{t:"academic",w:"propel",s:["drive","push forward"],c:"推动",e:"Innovation drives economic growth.",k:"drives",p:"prəˈpel",pos:"v.",d:"to push something forward",z:"w"},
{t:"academic",w:"prosper",s:["thrive","flourish"],c:"繁荣",e:"Small firms flourish in this market.",k:"flourish",p:"ˈprɒspə",pos:"v.",d:"to be successful financially",z:"w"},
{t:"env",w:"purify",s:["clean","filter"],c:"净化",e:"The plants clean the polluted water.",k:"clean",p:"ˈpjʊərɪfaɪ",pos:"v.",d:"to remove harmful substances from something",z:"w"},
{t:"work",w:"pursue",s:["chase","strive for"],c:"追求",e:"She strives for excellence.",k:"strives for",p:"pəˈsjuː",pos:"v.",d:"to work towards a goal",z:"w"},
{t:"work",w:"ratify",s:["approve","confirm"],c:"批准",e:"The board approved the deal.",k:"approved",p:"ˈrætɪfaɪ",pos:"v.",d:"to formally approve an agreement",z:"w"},
{t:"feelings",w:"reassure",s:["comfort","calm"],c:"使安心",e:"The nurse calmed the worried parents.",k:"calmed",p:"ˌriːəˈʃʊə",pos:"v.",d:"to make someone feel less worried",z:"w"},
{t:"academic",w:"recall",s:["remember","recollect"],c:"回忆",e:"Participants had to remember the words.",k:"remember",p:"rɪˈkɔːl",pos:"v.",d:"to bring a memory back to mind",z:"w"},
{t:"env",w:"reclaim",s:["recover","recycle"],c:"回收利用",e:"The firm recycles most of its waste.",k:"recycles",p:"rɪˈkleɪm",pos:"v.",d:"to recover material for reuse",z:"w"},
{t:"work",w:"rectify",s:["correct","fix"],c:"纠正",e:"The team corrected the error quickly.",k:"corrected",p:"ˈrektɪfaɪ",pos:"v.",d:"to put a mistake right",z:"w"},
{t:"academic",w:"recur",s:["repeat","happen again"],c:"复发，重现",e:"The same problem happens again yearly.",k:"happens again",p:"rɪˈkɜː",pos:"v.",d:"to happen again",z:"w"},
{t:"academic",w:"redeem",s:["exchange","cash in"],c:"兑换",e:"Coupons can be exchanged in store.",k:"exchanged",p:"rɪˈdiːm",pos:"v.",d:"to exchange a voucher for goods",z:"w"},
{t:"academic",w:"refine",s:["improve","perfect"],c:"改进",e:"The design was improved after feedback.",k:"improved",p:"rɪˈfaɪn",pos:"v.",d:"to make something better or purer",z:"w"},
{t:"work",w:"reform",s:["improve","change"],c:"改革",e:"The system was changed to cut waste.",k:"changed",p:"rɪˈfɔːm",pos:"v.",d:"to change a system to make it better",z:"w"},
{t:"academic",w:"refrain",s:["hold back","abstain"],c:"克制",e:"Please hold back from interrupting.",k:"hold back",p:"rɪˈfreɪn",pos:"v.",d:"to stop yourself from doing something",z:"w"},
{t:"work",w:"regulate",s:["control","govern"],c:"监管",e:"New rules control air pollution.",k:"control",p:"ˈreɡjuleɪt",pos:"v.",d:"to control by rules",z:"w"},
{t:"academic",w:"reiterate",s:["repeat","restate"],c:"重申",e:"The minister repeated the warning.",k:"repeated",p:"riˈɪtəreɪt",pos:"v.",d:"to say something again",z:"w"},
{t:"academic",w:"replicate",s:["duplicate","copy"],c:"复制",e:"Other labs must duplicate the results.",k:"duplicate",p:"ˈreplɪkeɪt",pos:"v.",d:"to copy or repeat a result",z:"w"},
{t:"living",w:"reside",s:["live","dwell"],c:"居住",e:"She lives close to campus.",k:"lives",p:"rɪˈzaɪd",pos:"v.",d:"to live in a place",z:"w"},
{t:"academic",w:"restore",s:["bring back","repair"],c:"恢复",e:"The old hall was repaired last year.",k:"repaired",p:"rɪˈstɔː",pos:"v.",d:"to return something to an earlier state",z:"w"},
{t:"work",w:"restrict",s:["limit","control"],c:"限制",e:"The law limits working hours.",k:"limits",p:"rɪˈstrɪkt",pos:"v.",d:"to keep something within limits",z:"w"},
{t:"academic",w:"retrieve",s:["recover","get back"],c:"检索，取回",e:"The system recovers deleted files.",k:"recovers",p:"rɪˈtriːv",pos:"v.",d:"to get something back",z:"w"},
{t:"media",w:"reveal",s:["disclose","show"],c:"揭示",e:"The report disclosed the true costs.",k:"disclosed",p:"rɪˈviːl",pos:"v.",d:"to make something known",z:"w"},
{t:"academic",w:"reverse",s:["overturn","undo"],c:"逆转",e:"The court overturned the decision.",k:"overturned",p:"rɪˈvɜːs",pos:"v.",d:"to change something to the opposite",z:"w"},
{t:"health",w:"revive",s:["recover","restore"],c:"复苏",e:"The economy recovered within a year.",k:"recovered",p:"rɪˈvaɪv",pos:"v.",d:"to become strong or active again",z:"w"},
{t:"academic",w:"scatter",s:["spread","disperse"],c:"散落",e:"Papers were spread across the desk.",k:"spread",p:"ˈskætə",pos:"v.",d:"to throw or place things in different directions",z:"w"},
{t:"academic",w:"signify",s:["indicate","mean"],c:"表示",e:"A green light indicates it is safe.",k:"indicates",p:"ˈsɪɡnɪfaɪ",pos:"v.",d:"to be a sign of something",z:"w"},
{t:"academic",w:"soar",s:["rise sharply","rocket"],c:"飙升",e:"House prices rose sharply last year.",k:"rose sharply",p:"sɔː",pos:"v.",d:"to increase quickly to a high level",z:"w"},
{t:"academic",w:"spark",s:["trigger","cause"],c:"引发",e:"The news caused a public debate.",k:"caused",p:"spɑːk",pos:"v.",d:"to cause something to start",z:"w"},
{t:"work",w:"specialize",s:["focus on","major in"],c:"专攻",e:"She focuses on environmental law.",k:"focuses on",p:"ˈspeʃəlaɪz",pos:"v.",d:"to give most attention to one area",z:"w"},
{t:"academic",w:"speculate",s:["guess","conjecture"],c:"推测",e:"Analysts guess at the reasons.",k:"guess",p:"ˈspekjuleɪt",pos:"v.",d:"to form opinions without firm evidence",z:"w"},
{t:"work",w:"strive",s:["struggle","work hard"],c:"努力",e:"Graduates work hard for good jobs.",k:"work hard",p:"straɪv",pos:"v.",d:"to try very hard to achieve something",z:"w"},
{t:"academic",w:"subsidize",s:["fund","support"],c:"资助",e:"The state funds public transport.",k:"funds",p:"ˈsʌbsɪdaɪz",pos:"v.",d:"to help pay for something",z:"w"},
{t:"work",w:"supervise",s:["oversee","monitor"],c:"监督",e:"Staff monitor the machines daily.",k:"monitor",p:"ˈsuːpəvaɪz",pos:"v.",d:"to watch people at work",z:"w"},
{t:"work",w:"terminate",s:["end","stop"],c:"终止",e:"The contract ends in March.",k:"ends",p:"ˈtɜːmɪneɪt",pos:"v.",d:"to bring something to an end",z:"w"},
{t:"academic",w:"thrive",s:["flourish","prosper"],c:"兴旺",e:"Small firms flourish in the city.",k:"flourish",p:"θraɪv",pos:"v.",d:"to grow and be successful",z:"w"},
{t:"academic",w:"undergo",s:["experience","go through"],c:"经历",e:"The city went through major changes.",k:"went through",p:"ˌʌndəˈɡəʊ",pos:"v.",d:"to experience a process or change",z:"w"},
{t:"work",w:"undertake",s:["take on","carry out"],c:"承担",e:"The team took on the research.",k:"took on",p:"ˌʌndəˈteɪk",pos:"v.",d:"to agree to do a task",z:"w"},
{t:"work",w:"uphold",s:["support","maintain"],c:"维护",e:"The court supported the ruling.",k:"supported",p:"ʌpˈhəʊld",pos:"v.",d:"to defend a decision or law",z:"w"},
{t:"work",w:"urge",s:["push","press"],c:"敦促",e:"Doctors press for safer rules.",k:"press",p:"ɜːdʒ",pos:"v.",d:"to strongly advise someone to act",z:"w"},
{t:"work",w:"violate",s:["break","breach"],c:"违反",e:"The firm broke safety rules.",k:"broke",p:"ˈvaɪəleɪt",pos:"v.",d:"to fail to obey a rule or law",z:"w"},
{t:"academic",w:"yield",s:["produce","give"],c:"产生",e:"The study produced useful data.",k:"produced",p:"jiːld",pos:"v.",d:"to produce a result",z:"w"},
{t:"academic",w:"affluent",s:["wealthy","well-off"],c:"富裕的",e:"Wealthy families choose private schools.",k:"Wealthy",p:"ˈæfluənt",pos:"adj.",d:"having a lot of money",z:"w"},
{t:"academic",w:"ample",s:["plenty of","abundant"],c:"充足的",e:"There is plenty of evidence for the claim.",k:"plenty of",p:"ˈæmpl",pos:"adj.",d:"enough or more than enough",z:"w"},
{t:"academic",w:"anonymous",s:["unnamed","nameless"],c:"匿名的",e:"The survey was completed by unnamed respondents.",k:"unnamed",p:"əˈnɒnɪməs",pos:"adj.",d:"with no name given",z:"w"},
{t:"academic",w:"applicable",s:["relevant","valid"],c:"适用的",e:"The rule is relevant to all cases.",k:"relevant",p:"əˈplɪkəbl",pos:"adj.",d:"that can be applied to a situation",z:"w"},
{t:"academic",w:"autonomous",s:["self-governing","independent"],c:"自主的",e:"The region became independent in 1990.",k:"independent",p:"ɔːˈtɒnəməs",pos:"adj.",d:"able to govern itself",z:"w"},
{t:"academic",w:"barrier",s:["obstacle","hurdle"],c:"障碍",e:"Language is a major obstacle for newcomers.",k:"obstacle",p:"ˈbæriə",pos:"n.",d:"something that prevents progress",z:"w"},
{t:"work",w:"bureaucracy",s:["red tape","administration"],c:"官僚机构",e:"Red tape delays most projects.",k:"Red tape",p:"bjʊəˈrɒkrəsi",pos:"n.",d:"a system of complex official rules",z:"w"},
{t:"academic",w:"capability",s:["capacity","ability"],c:"能力",e:"The system has the ability to expand.",k:"ability",p:"ˌkeɪpəˈbɪləti",pos:"n.",d:"the power to do something",z:"w"},
{t:"env",w:"catastrophe",s:["disaster","calamity"],c:"灾难",e:"The flood was a major disaster.",k:"disaster",p:"kəˈtæstrəfi",pos:"n.",d:"a sudden terrible event",z:"w"},
{t:"academic",w:"chaos",s:["disorder","confusion"],c:"混乱",e:"The strike caused total disorder.",k:"disorder",p:"ˈkeɪɒs",pos:"n.",d:"a state of complete confusion",z:"w"},
{t:"academic",w:"circumstance",s:["situation","condition"],c:"情况",e:"The situation changed overnight.",k:"situation",p:"ˈsɜːkəmstəns",pos:"n.",d:"the conditions around an event",z:"w"},
{t:"academic",w:"cognitive",s:["mental","intellectual"],c:"认知的",e:"Puzzles improve mental skills.",k:"mental",p:"ˈkɒɡnətɪv",pos:"adj.",d:"related to thinking and knowing",z:"w"},
{t:"academic",w:"comprehensive",s:["complete","thorough"],c:"全面的",e:"The guide offers thorough coverage.",k:"thorough",p:"ˌkɒmprɪˈhensɪv",pos:"adj.",d:"including everything needed",z:"w"},
{t:"academic",w:"concise",s:["brief","short"],c:"简洁的",e:"Keep the summary brief and clear.",k:"brief",p:"kənˈsaɪs",pos:"adj.",d:"short but giving all needed information",z:"w"},
{t:"academic",w:"consent",s:["permission","approval"],c:"同意",e:"The study needs parental permission.",k:"permission",p:"kənˈsent",pos:"n.",d:"agreement to allow something",z:"w"},
{t:"academic",w:"consequent",s:["resulting","following"],c:"随之发生的",e:"The resulting rise in prices hurt families.",k:"resulting",p:"ˈkɒnsɪkwənt",pos:"adj.",d:"happening as a result",z:"w"},
{t:"academic",w:"conservative",s:["traditional","cautious"],c:"保守的",e:"The estimate is cautious and realistic.",k:"cautious",p:"kənˈsɜːvətɪv",pos:"adj.",d:"not willing to accept change",z:"w"},
{t:"academic",w:"consistency",s:["uniformity","steadiness"],c:"一致性",e:"Uniformity across tests is essential.",k:"Uniformity",p:"kənˈsɪstənsi",pos:"n.",d:"the quality of being the same throughout",z:"w"},
{t:"academic",w:"context",s:["background","setting"],c:"背景，语境",e:"The policy must be seen in its wider background.",k:"background",p:"ˈkɒntekst",pos:"n.",d:"the situation in which something exists",z:"w"},
{t:"academic",w:"conventional",s:["traditional","standard"],c:"传统的",e:"Traditional methods still work well.",k:"Traditional",p:"kənˈvenʃənl",pos:"adj.",d:"following usual customs",z:"w"},
{t:"academic",w:"conviction",s:["belief","certainty"],c:"信念",e:"She holds a strong belief in fairness.",k:"belief",p:"kənˈvɪkʃn",pos:"n.",d:"a firm opinion or belief",z:"w"},
{t:"work",w:"counterpart",s:["equivalent","opposite number"],c:"对应的人",e:"The minister met her equivalent from China.",k:"equivalent",p:"ˈkaʊntəpɑːt",pos:"n.",d:"a person with the same role elsewhere",z:"w"},
{t:"academic",w:"credible",s:["believable","reliable"],c:"可信的",e:"The witness gave a believable account.",k:"believable",p:"ˈkredəbl",pos:"adj.",d:"able to be believed",z:"w"},
{t:"academic",w:"cumulative",s:["growing","accumulated"],c:"累积的",e:"The accumulated effects are damaging.",k:"accumulated",p:"ˈkjuːmjələtɪv",pos:"adj.",d:"increasing by adding amounts",z:"w"},
{t:"academic",w:"daunting",s:["intimidating","discouraging"],c:"令人生畏的",e:"The task looks intimidating at first.",k:"intimidating",p:"ˈdɔːntɪŋ",pos:"adj.",d:"seeming difficult to deal with",z:"w"},
{t:"core",w:"decade",s:["ten years","ten-year period"],c:"十年",e:"Prices rose steadily over ten years.",k:"ten years",p:"ˈdekeɪd",pos:"n.",d:"a period of ten years",z:"w"},
{t:"work",w:"decisive",s:["determined","firm"],c:"果断的",e:"A firm decision ended the debate.",k:"firm",p:"dɪˈsaɪsɪv",pos:"adj.",d:"able to decide quickly and clearly",z:"w"},
{t:"academic",w:"deliberate",s:["intentional","planned"],c:"故意的",e:"The change was intentional, not random.",k:"intentional",p:"dɪˈlɪbərət",pos:"adj.",d:"done on purpose",z:"w"},
{t:"academic",w:"democracy",s:["representative government","majority rule"],c:"民主",e:"Representative government spread across the region.",k:"Representative government",p:"dɪˈmɒkrəsi",pos:"n.",d:"government elected by the people",z:"w"},
{t:"academic",w:"dilemma",s:["predicament","difficulty"],c:"困境",e:"Workers face a difficulty between pay and time.",k:"difficulty",p:"dɪˈlemə",pos:"n.",d:"a difficult choice between options",z:"w"},
{t:"work",w:"diligent",s:["hardworking","industrious"],c:"勤奋的",e:"Hardworking students achieve more.",k:"Hardworking",p:"ˈdɪlɪdʒənt",pos:"adj.",d:"working carefully and steadily",z:"w"},
{t:"work",w:"diplomacy",s:["negotiation","tact"],c:"外交",e:"The crisis was solved by negotiation.",k:"negotiation",p:"dɪˈpləʊməsi",pos:"n.",d:"the management of relations between countries",z:"w"},
{t:"health",w:"disability",s:["impairment","handicap"],c:"残疾",e:"The building is accessible despite the impairment.",k:"impairment",p:"ˌdɪsəˈbɪləti",pos:"n.",d:"a physical or mental condition limiting activity",z:"w"},
{t:"edu",w:"discipline",s:["self-control","order"],c:"纪律",e:"Good self-control supports study habits.",k:"self-control",p:"ˈdɪsəplɪn",pos:"n.",d:"the ability to control your behaviour",z:"w"},
{t:"living",w:"domestic",s:["household","internal"],c:"国内的，家庭的",e:"Household waste is collected weekly.",k:"Household",p:"dəˈmestɪk",pos:"adj.",d:"relating to the home or a country",z:"w"},
{t:"academic",w:"dubious",s:["doubtful","questionable"],c:"可疑的",e:"The claim seems doubtful without proof.",k:"doubtful",p:"ˈdjuːbiəs",pos:"adj.",d:"not to be trusted",z:"w"},
{t:"living",w:"dwelling",s:["residence","home"],c:"住宅",e:"The new residence block opens in autumn.",k:"residence",p:"ˈdwelɪŋ",pos:"n.",d:"a place where people live",z:"w"},
{t:"work",w:"dynamic",s:["active","energetic"],c:"动态的",e:"The market is active and fast-moving.",k:"active",p:"daɪˈnæmɪk",pos:"adj.",d:"constantly changing and active",z:"w"},
{t:"academic",w:"economical",s:["cost-effective","efficient"],c:"经济的",e:"Solar power is cost-effective long term.",k:"cost-effective",p:"ˌiːkəˈnɒmɪkl",pos:"adj.",d:"cheap and efficient",z:"w"},
{t:"academic",w:"elegant",s:["graceful","refined"],c:"优雅的",e:"The design is simple and graceful.",k:"graceful",p:"ˈelɪɡənt",pos:"adj.",d:"graceful and stylish",z:"w"},
{t:"work",w:"eligible",s:["qualified","entitled"],c:"有资格的",e:"Only qualified applicants will be considered.",k:"qualified",p:"ˈelɪdʒəbl",pos:"adj.",d:"having the right to do something",z:"w"},
{t:"work",w:"eminent",s:["distinguished","prominent"],c:"杰出的",e:"A distinguished scientist led the team.",k:"distinguished",p:"ˈemɪnənt",pos:"adj.",d:"famous and respected",z:"w"},
{t:"feelings",w:"empathy",s:["understanding","compassion"],c:"同理心",e:"Nurses need compassion for patients.",k:"compassion",p:"ˈempəθi",pos:"n.",d:"the ability to share another's feelings",z:"w"},
{t:"core",w:"enormous",s:["huge","massive"],c:"巨大的",e:"The project involves huge costs.",k:"huge",p:"ɪˈnɔːməs",pos:"adj.",d:"very large in size or amount",z:"w"},
{t:"work",w:"enterprise",s:["business","venture"],c:"企业",e:"Small businesses drive job growth.",k:"businesses",p:"ˈentəpraɪz",pos:"n.",d:"a company or business",z:"w"},
{t:"feelings",w:"enthusiasm",s:["passion","eagerness"],c:"热情",e:"Students showed great eagerness to learn.",k:"eagerness",p:"ɪnˈθjuːziæzəm",pos:"n.",d:"strong excitement about something",z:"w"},
{t:"academic",w:"entity",s:["organisation","body"],c:"实体",e:"Each body operates independently.",k:"body",p:"ˈentəti",pos:"n.",d:"something that exists as a single unit",z:"w"},
{t:"work",w:"entrepreneur",s:["business founder","start-up owner"],c:"企业家",e:"The business founder raised new capital.",k:"business founder",p:"ˌɒntrəprəˈnɜː",pos:"n.",d:"a person who starts a business",z:"w"},
{t:"academic",w:"equivalent",s:["equal","comparable"],c:"等同的",e:"The two courses are comparable in content.",k:"comparable",p:"ɪˈkwɪvələnt",pos:"adj.",d:"equal in value or meaning",z:"w"},
{t:"academic",w:"essence",s:["core","nature"],c:"本质",e:"The core of the argument is simple.",k:"core",p:"ˈesns",pos:"n.",d:"the most important quality of something",z:"w"},
{t:"academic",w:"ethical",s:["moral","principled"],c:"道德的",e:"The trial raised moral questions.",k:"moral",p:"ˈeθɪkl",pos:"adj.",d:"relating to right and wrong",z:"w"},
{t:"academic",w:"evident",s:["obvious","clear"],c:"明显的",e:"The benefits are obvious to everyone.",k:"obvious",p:"ˈevɪdənt",pos:"adj.",d:"easy to see or understand",z:"w"},
{t:"work",w:"expertise",s:["specialist knowledge","skill"],c:"专业知识",e:"The team brings specialist knowledge.",k:"specialist knowledge",p:"ˌekspɜːˈtiːz",pos:"n.",d:"special skill or knowledge",z:"w"},
{t:"academic",w:"extensive",s:["broad","wide-ranging"],c:"广泛的",e:"The library has a broad collection.",k:"broad",p:"ɪkˈstensɪv",pos:"adj.",d:"covering a large area or range",z:"w"},
{t:"core",w:"extraordinary",s:["remarkable","exceptional"],c:"非凡的",e:"Her progress was remarkable.",k:"remarkable",p:"ɪkˈstrɔːdnri",pos:"adj.",d:"very unusual and impressive",z:"w"},
{t:"academic",w:"extravagant",s:["lavish","wasteful"],c:"奢侈的",e:"Lavish spending caused the debt.",k:"Lavish",p:"ɪkˈstrævəɡənt",pos:"adj.",d:"spending too much money",z:"w"},
{t:"health",w:"fatal",s:["deadly","lethal"],c:"致命的",e:"The disease can be deadly.",k:"deadly",p:"ˈfeɪtl",pos:"adj.",d:"causing death",z:"w"},
{t:"env",w:"fertile",s:["productive","rich"],c:"肥沃的",e:"The valley has rich farmland.",k:"rich",p:"ˈfɜːtaɪl",pos:"adj.",d:"able to produce good crops",z:"w"},
{t:"academic",w:"fierce",s:["intense","strong"],c:"激烈的",e:"Competition is intense in this field.",k:"intense",p:"fɪəs",pos:"adj.",d:"very strong or aggressive",z:"w"},
{t:"academic",w:"finite",s:["limited","bounded"],c:"有限的",e:"Fossil fuels are a limited resource.",k:"limited",p:"ˈfaɪnaɪt",pos:"adj.",d:"having a fixed limit",z:"w"},
{t:"academic",w:"fiscal",s:["financial","budgetary"],c:"财政的",e:"The government faces budgetary pressure.",k:"budgetary",p:"ˈfɪskl",pos:"adj.",d:"related to government money",z:"w"},
{t:"edu",w:"fluent",s:["smooth","articulate"],c:"流利的",e:"She is smooth and confident in interviews.",k:"smooth",p:"ˈfluːənt",pos:"adj.",d:"able to speak a language easily",z:"w"},
{t:"academic",w:"foremost",s:["leading","chief"],c:"首要的",e:"She is the leading expert in the field.",k:"leading",p:"ˈfɔːməʊst",pos:"adj.",d:"most important or famous",z:"w"},
{t:"academic",w:"fragile",s:["delicate","weak"],c:"脆弱的",e:"The ecosystem is delicate and easily damaged.",k:"delicate",p:"ˈfrædʒaɪl",pos:"adj.",d:"easily broken or damaged",z:"w"},
{t:"academic",w:"framework",s:["structure","system"],c:"框架",e:"The report provides a clear structure.",k:"structure",p:"ˈfreɪmwɜːk",pos:"n.",d:"a basic structure supporting an idea",z:"w"},
{t:"academic",w:"fraud",s:["scam","deception"],c:"欺诈",e:"The scam cost investors millions.",k:"scam",p:"frɔːd",pos:"n.",d:"dishonest behaviour to gain money",z:"w"},
{t:"work",w:"friction",s:["tension","conflict"],c:"摩擦",e:"Tension grew between the two teams.",k:"Tension",p:"ˈfrɪkʃn",pos:"n.",d:"disagreement between people",z:"w"},
{t:"academic",w:"futile",s:["pointless","useless"],c:"徒劳的",e:"Further debate proved pointless.",k:"pointless",p:"ˈfjuːtaɪl",pos:"adj.",d:"having no useful result",z:"w"},
{t:"academic",w:"genuine",s:["real","authentic"],c:"真正的",e:"The painting is authentic.",k:"authentic",p:"ˈdʒenjuɪn",pos:"adj.",d:"really what it appears to be",z:"w"},
{t:"academic",w:"grim",s:["severe","bleak"],c:"严峻的",e:"The outlook for jobs is bleak.",k:"bleak",p:"ɡrɪm",pos:"adj.",d:"unpleasant and hopeless",z:"w"},
{t:"academic",w:"hardship",s:["difficulty","suffering"],c:"艰辛",e:"The war caused widespread suffering.",k:"suffering",p:"ˈhɑːdʃɪp",pos:"n.",d:"difficult living conditions",z:"w"},
{t:"env",w:"hazardous",s:["dangerous","risky"],c:"危险的",e:"The waste is dangerous to handle.",k:"dangerous",p:"ˈhæzədəs",pos:"adj.",d:"likely to cause harm",z:"w"},
{t:"work",w:"hostile",s:["unfriendly","antagonistic"],c:"敌对的",e:"The talks began in an unfriendly mood.",k:"unfriendly",p:"ˈhɒstaɪl",pos:"adj.",d:"showing strong dislike",z:"w"},
{t:"academic",w:"humane",s:["compassionate","kind"],c:"人道的",e:"The prison reforms were compassionate.",k:"compassionate",p:"hjuːˈmeɪn",pos:"adj.",d:"showing kindness to people",z:"w"},
{t:"academic",w:"hurdle",s:["obstacle","barrier"],c:"障碍",e:"Cost is the biggest obstacle.",k:"obstacle",p:"ˈhɜːdl",pos:"n.",d:"a difficulty to be overcome",z:"w"},
{t:"academic",w:"identical",s:["same","indistinguishable"],c:"相同的",e:"The two samples are almost the same.",k:"same",p:"aɪˈdentɪkl",pos:"adj.",d:"exactly the same",z:"w"},
{t:"edu",w:"ignorance",s:["lack of knowledge","unawareness"],c:"无知",e:"Lack of knowledge causes fear.",k:"Lack of knowledge",p:"ˈɪɡnərəns",pos:"n.",d:"not knowing something",z:"w"},
{t:"work",w:"illegal",s:["unlawful","against the law"],c:"非法的",e:"The sale is against the law.",k:"against the law",p:"ɪˈliːɡl",pos:"adj.",d:"not allowed by law",z:"w"},
{t:"academic",w:"immense",s:["huge","vast"],c:"巨大的",e:"The task requires huge effort.",k:"huge",p:"ɪˈmens",pos:"adj.",d:"extremely large",z:"w"},
{t:"academic",w:"imperative",s:["essential","vital"],c:"必要的",e:"Quick action is essential.",k:"essential",p:"ɪmˈperətɪv",pos:"adj.",d:"extremely important",z:"w"},
{t:"academic",w:"implicit",s:["implied","unspoken"],c:"含蓄的",e:"The message was unspoken but clear.",k:"unspoken",p:"ɪmˈplɪsɪt",pos:"adj.",d:"suggested without being stated",z:"w"},
{t:"work",w:"incentive",s:["motivation","reward"],c:"激励",e:"Bonuses are a strong motivation.",k:"motivation",p:"ɪnˈsentɪv",pos:"n.",d:"something that encourages effort",z:"w"},
{t:"academic",w:"incredible",s:["unbelievable","amazing"],c:"难以置信的",e:"The results were unbelievable.",k:"unbelievable",p:"ɪnˈkredəbl",pos:"adj.",d:"difficult to believe",z:"w"},
{t:"academic",w:"indigenous",s:["native","original"],c:"本土的",e:"Native plants survive drought better.",k:"Native",p:"ɪnˈdɪdʒənəs",pos:"adj.",d:"originally living in a place",z:"w"},
{t:"academic",w:"inferior",s:["lower","worse"],c:"较差的",e:"The copy is of lower quality.",k:"lower",p:"ɪnˈfɪəriə",pos:"adj.",d:"worse in quality",z:"w"},
{t:"academic",w:"infinite",s:["endless","limitless"],c:"无限的",e:"The possibilities seem endless.",k:"endless",p:"ˈɪnfɪnət",pos:"adj.",d:"without any limit",z:"w"},
{t:"academic",w:"influx",s:["flood","arrival"],c:"涌入",e:"The sudden arrival of visitors strained services.",k:"arrival",p:"ˈɪnflʌks",pos:"n.",d:"a large flow of people or things",z:"w"},
{t:"academic",w:"ingenious",s:["clever","inventive"],c:"巧妙的",e:"The device uses an inventive design.",k:"inventive",p:"ɪnˈdʒiːniəs",pos:"adj.",d:"very clever and original",z:"w"},
{t:"work",w:"initiative",s:["scheme","programme"],c:"倡议",e:"The new scheme encourages recycling.",k:"scheme",p:"ɪˈnɪʃətɪv",pos:"n.",d:"a new plan or action",z:"w"},
{t:"academic",w:"innate",s:["inborn","natural"],c:"天生的",e:"Language learning is a natural ability.",k:"natural",p:"ɪˈneɪt",pos:"adj.",d:"existing from birth",z:"w"},
{t:"academic",w:"instinct",s:["natural tendency","urge"],c:"本能",e:"Birds follow a natural tendency to migrate.",k:"natural tendency",p:"ˈɪnstɪŋkt",pos:"n.",d:"a natural way of behaving",z:"w"},
{t:"academic",w:"insufficient",s:["inadequate","not enough"],c:"不足的",e:"The funding is not enough for research.",k:"not enough",p:"ˌɪnsəˈfɪʃnt",pos:"adj.",d:"not enough",z:"w"},
{t:"academic",w:"intellect",s:["intelligence","mind"],c:"智力",e:"The test measures general intelligence.",k:"intelligence",p:"ˈɪntəlekt",pos:"n.",d:"the ability to think and understand",z:"w"},
{t:"academic",w:"intermittent",s:["sporadic","irregular"],c:"间歇的",e:"The signal was irregular all day.",k:"irregular",p:"ˌɪntəˈmɪtənt",pos:"adj.",d:"stopping and starting again",z:"w"},
{t:"academic",w:"intricate",s:["complex","elaborate"],c:"复杂的",e:"The design is complex but functional.",k:"complex",p:"ˈɪntrɪkət",pos:"adj.",d:"very complicated",z:"w"},
{t:"academic",w:"intuitive",s:["instinctive","natural"],c:"直觉的",e:"The interface is instinctive to use.",k:"instinctive",p:"ɪnˈtjuːɪtɪv",pos:"adj.",d:"based on feeling rather than thought",z:"w"},
{t:"academic",w:"invaluable",s:["priceless","extremely useful"],c:"无价的",e:"Her advice was extremely useful.",k:"extremely useful",p:"ɪnˈvæljuəbl",pos:"adj.",d:"extremely valuable",z:"w"},
{t:"academic",w:"ironic",s:["sarcastic","paradoxical"],c:"讽刺的",e:"It is paradoxical that the cure causes harm.",k:"paradoxical",p:"aɪˈrɒnɪk",pos:"adj.",d:"showing the opposite of what is expected",z:"w"},
{t:"academic",w:"jargon",s:["specialist terms","slang"],c:"行话",e:"Avoid specialist terms in the summary.",k:"specialist terms",p:"ˈdʒɑːɡən",pos:"n.",d:"special words used by a group",z:"w"},
{t:"work",w:"judicial",s:["legal","court-related"],c:"司法的",e:"The system faces legal challenges.",k:"legal",p:"dʒuˈdɪʃl",pos:"adj.",d:"related to courts and law",z:"w"},
{t:"work",w:"laborious",s:["hard","arduous"],c:"费力的",e:"Data entry is hard and repetitive.",k:"hard",p:"ləˈbɔːriəs",pos:"adj.",d:"needing much effort",z:"w"},
{t:"work",w:"lawful",s:["legal","permitted"],c:"合法的",e:"The strike was legal under new rules.",k:"legal",p:"ˈlɔːfl",pos:"adj.",d:"allowed by law",z:"w"},
{t:"living",w:"leisure",s:["free time","spare time"],c:"休闲",e:"Students use spare time for sports.",k:"spare time",p:"ˈleʒə",pos:"n.",d:"time free from work",z:"w"},
{t:"health",w:"lethal",s:["deadly","fatal"],c:"致命的",e:"The chemical is deadly in small doses.",k:"deadly",p:"ˈliːθl",pos:"adj.",d:"able to cause death",z:"w"},
{t:"academic",w:"liberal",s:["open-minded","tolerant"],c:"自由的",e:"The college has an open-minded culture.",k:"open-minded",p:"ˈlɪbərəl",pos:"adj.",d:"willing to accept different views",z:"w"},
{t:"health",w:"lifespan",s:["lifetime","life span"],c:"寿命",e:"The average lifetime has increased.",k:"lifetime",p:"ˈlaɪfspæn",pos:"n.",d:"the length of time something lives",z:"w"},
{t:"academic",w:"likelihood",s:["probability","chance"],c:"可能性",e:"The probability of failure is low.",k:"probability",p:"ˈlaɪklihʊd",pos:"n.",d:"the chance that something will happen",z:"w"},
{t:"academic",w:"literal",s:["exact","word-for-word"],c:"字面的",e:"Give an exact translation, not a free one.",k:"exact",p:"ˈlɪtərəl",pos:"adj.",d:"following the exact words",z:"w"},
{t:"env",w:"livestock",s:["farm animals","cattle"],c:"牲畜",e:"Farm animals need clean water.",k:"Farm animals",p:"ˈlaɪvstɒk",pos:"n.",d:"animals kept on a farm",z:"w"},
{t:"feelings",w:"loyal",s:["faithful","devoted"],c:"忠诚的",e:"Faithful customers return yearly.",k:"Faithful",p:"ˈlɔɪəl",pos:"adj.",d:"staying faithful to someone",z:"w"},
{t:"academic",w:"mainstream",s:["common","conventional"],c:"主流的",e:"The idea became common in the media.",k:"common",p:"ˈmeɪnstriːm",pos:"adj.",d:"accepted by most people",z:"w"},
{t:"work",w:"mandate",s:["authority","order"],c:"授权",e:"The council has authority to decide.",k:"authority",p:"ˈmændeɪt",pos:"n.",d:"official permission to act",z:"w"},
{t:"core",w:"massive",s:["huge","enormous"],c:"大规模的",e:"The storm caused huge damage.",k:"huge",p:"ˈmæsɪv",pos:"adj.",d:"very large and heavy",z:"w"},
{t:"edu",w:"mature",s:["grown","developed"],c:"成熟的",e:"Her writing style is fully developed.",k:"developed",p:"məˈtʃʊə",pos:"adj.",d:"fully grown or developed",z:"w"},
{t:"academic",w:"measurable",s:["quantifiable","observable"],c:"可衡量的",e:"Set quantifiable targets for the team.",k:"quantifiable",p:"ˈmeʒərəbl",pos:"adj.",d:"able to be measured",z:"w"},
{t:"work",w:"mentor",s:["adviser","coach"],c:"导师",e:"Each trainee gets a personal adviser.",k:"adviser",p:"ˈmentɔː",pos:"n.",d:"an experienced person who guides others",z:"w"},
{t:"work",w:"meticulous",s:["careful","precise"],c:"一丝不苟的",e:"The records are careful and detailed.",k:"careful",p:"məˈtɪkjələs",pos:"adj.",d:"very careful about details",z:"w"},
{t:"work",w:"milestone",s:["landmark","turning point"],c:"里程碑",e:"The agreement was a landmark event.",k:"landmark",p:"ˈmaɪlstəʊn",pos:"n.",d:"an important stage in progress",z:"w"},
{t:"media",w:"misleading",s:["deceptive","confusing"],c:"误导的",e:"The headline is deceptive.",k:"deceptive",p:"ˌmɪsˈliːdɪŋ",pos:"adj.",d:"giving a wrong impression",z:"w"},
{t:"academic",w:"momentum",s:["impetus","drive"],c:"势头",e:"The campaign gained drive quickly.",k:"drive",p:"məˈmentəm",pos:"n.",d:"the force that keeps progress moving",z:"w"},
{t:"academic",w:"monopoly",s:["exclusive control","corner"],c:"垄断",e:"One firm holds exclusive control of the market.",k:"exclusive control",p:"məˈnɒpəli",pos:"n.",d:"control of a market by one seller",z:"w"},
{t:"academic",w:"monotonous",s:["boring","repetitive"],c:"单调的",e:"The task is repetitive and tiring.",k:"repetitive",p:"məˈnɒtənəs",pos:"adj.",d:"boring because it never changes",z:"w"},
{t:"academic",w:"moral",s:["ethical","right"],c:"道德的",e:"The decision raises ethical questions.",k:"ethical",p:"ˈmɒrəl",pos:"adj.",d:"relating to what is right",z:"w"},
{t:"academic",w:"motive",s:["reason","cause"],c:"动机",e:"The main reason for the move was cost.",k:"reason",p:"ˈməʊtɪv",pos:"n.",d:"a reason for doing something",z:"w"},
{t:"work",w:"mutual",s:["shared","reciprocal"],c:"相互的",e:"The deal offers shared benefits for both sides.",k:"shared",p:"ˈmjuːtʃuəl",pos:"adj.",d:"felt or done by both sides",z:"w"},
{t:"academic",w:"naive",s:["innocent","simple"],c:"天真的",e:"The plan seems simple about costs.",k:"simple",p:"naɪˈiːv",pos:"adj.",d:"lacking experience or judgement",z:"w"},
{t:"media",w:"narrative",s:["story","account"],c:"叙述",e:"The film follows a simple story.",k:"story",p:"ˈnærətɪv",pos:"n.",d:"a spoken or written story",z:"w"},
{t:"academic",w:"norm",s:["standard","convention"],c:"规范",e:"Remote work is now the standard.",k:"standard",p:"nɔːm",pos:"n.",d:"the usual or expected way of doing things",z:"w"},
{t:"academic",w:"notable",s:["remarkable","noticeable"],c:"显著的",e:"There was a noticeable rise in sales.",k:"noticeable",p:"ˈnəʊtəbl",pos:"adj.",d:"worth noticing",z:"w"},
{t:"media",w:"notorious",s:["infamous","ill-famed"],c:"臭名昭著的",e:"The area is infamous for traffic jams.",k:"infamous",p:"nəʊˈtɔːriəs",pos:"adj.",d:"famous for something bad",z:"w"},
{t:"core",w:"numerous",s:["many","countless"],c:"众多的",e:"Many factors affect the result.",k:"Many",p:"ˈnjuːmərəs",pos:"adj.",d:"existing in large numbers",z:"w"},
{t:"academic",w:"obscure",s:["unclear","vague"],c:"晦涩的",e:"The passage is unclear without notes.",k:"unclear",p:"əbˈskjʊə",pos:"adj.",d:"difficult to understand",z:"w"},
{t:"core",w:"obvious",s:["clear","evident"],c:"明显的",e:"The solution seems evident.",k:"evident",p:"ˈɒbviəs",pos:"adj.",d:"easy to see or understand",z:"w"},
{t:"work",w:"ongoing",s:["continuing","current"],c:"持续的",e:"The continuing debate delays reform.",k:"continuing",p:"ˈɒnɡəʊɪŋ",pos:"adj.",d:"still happening",z:"w"},
{t:"health",w:"onset",s:["beginning","start"],c:"开始",e:"The beginning of treatment was delayed.",k:"beginning",p:"ˈɒnset",pos:"n.",d:"the start of something",z:"w"},
{t:"work",w:"opponent",s:["rival","adversary"],c:"对手",e:"The rival team withdrew.",k:"rival",p:"əˈpəʊnənt",pos:"n.",d:"a person you compete against",z:"w"},
{t:"academic",w:"outcome",s:["result","consequence"],c:"结果",e:"The result surprised everyone.",k:"result",p:"ˈaʊtkʌm",pos:"n.",d:"the final result of an action",z:"w"},
{t:"academic",w:"outdated",s:["old-fashioned","obsolete"],c:"过时的",e:"The equipment is obsolete now.",k:"obsolete",p:"ˌaʊtˈdeɪtɪd",pos:"adj.",d:"no longer useful or modern",z:"w"},
{t:"academic",w:"outlay",s:["expenditure","spending"],c:"支出",e:"The initial spending was high.",k:"spending",p:"ˈaʊtleɪ",pos:"n.",d:"money spent to start something",z:"w"},
{t:"work",w:"outstanding",s:["excellent","exceptional"],c:"杰出的",e:"She gave an excellent presentation.",k:"excellent",p:"aʊtˈstændɪŋ",pos:"adj.",d:"extremely good",z:"w"},
{t:"academic",w:"overlap",s:["coincide","share"],c:"重叠",e:"The two roles share many duties.",k:"share",p:"ˌəʊvəˈlæp",pos:"v.",d:"to cover part of the same area or time",z:"w"},
{t:"academic",w:"overt",s:["open","public"],c:"公开的",e:"The criticism became public.",k:"public",p:"əʊˈvɜːt",pos:"adj.",d:"done openly",z:"w"},
{t:"academic",w:"paradox",s:["contradiction","puzzle"],c:"悖论",e:"It is a contradiction that saving more earns less.",k:"contradiction",p:"ˈpærədɒks",pos:"n.",d:"a statement that seems to contradict itself",z:"w"},
{t:"feelings",w:"passionate",s:["enthusiastic","intense"],c:"热情的",e:"She is enthusiastic about teaching.",k:"enthusiastic",p:"ˈpæʃənət",pos:"adj.",d:"showing strong feelings",z:"w"},
{t:"academic",w:"peculiar",s:["strange","unusual"],c:"奇特的",e:"The pattern looks unusual at first.",k:"unusual",p:"pɪˈkjuːliə",pos:"adj.",d:"strange or unusual",z:"w"},
{t:"work",w:"permanent",s:["lasting","long-term"],c:"永久的",e:"The contract offers a long-term position.",k:"long-term",p:"ˈpɜːmənənt",pos:"adj.",d:"lasting forever or for a long time",z:"w"},
{t:"work",w:"personnel",s:["staff","employees"],c:"人员",e:"All staff must attend training.",k:"staff",p:"ˌpɜːsəˈnel",pos:"n.",d:"the people working in an organisation",z:"w"},
{t:"academic",w:"perspective",s:["viewpoint","outlook"],c:"视角",e:"The report offers a fresh viewpoint.",k:"viewpoint",p:"pəˈspektɪv",pos:"n.",d:"a particular way of seeing things",z:"w"},
{t:"academic",w:"phase",s:["stage","period"],c:"阶段",e:"The first stage ends in June.",k:"stage",p:"feɪz",pos:"n.",d:"a stage in a process",z:"w"},
{t:"health",w:"physician",s:["doctor","medic"],c:"内科医生",e:"See a doctor if symptoms continue.",k:"doctor",p:"fɪˈzɪʃn",pos:"n.",d:"a medical doctor",z:"w"},
{t:"work",w:"pioneer",s:["trailblazer","innovator"],c:"先驱",e:"She was a trailblazer in medicine.",k:"trailblazer",p:"ˌpaɪəˈnɪə",pos:"n.",d:"a person who develops something new",z:"w"},
{t:"academic",w:"plight",s:["difficult situation","predicament"],c:"困境",e:"The refugees' difficult situation needs attention.",k:"difficult situation",p:"plaɪt",pos:"n.",d:"a serious and difficult situation",z:"w"},
{t:"env",w:"pollutant",s:["contaminant","waste"],c:"污染物",e:"The contaminant entered the river.",k:"contaminant",p:"pəˈluːtənt",pos:"n.",d:"a substance that pollutes",z:"w"},
{t:"academic",w:"precise",s:["exact","accurate"],c:"精确的",e:"We need exact measurements.",k:"exact",p:"prɪˈsaɪs",pos:"adj.",d:"exact and accurate",z:"w"},
{t:"academic",w:"predominant",s:["dominant","main"],c:"主要的",e:"The dominant factor is cost.",k:"dominant",p:"prɪˈdɒmɪnənt",pos:"adj.",d:"strongest or most common",z:"w"},
{t:"academic",w:"preferable",s:["better","more desirable"],c:"更可取的",e:"Walking is better for health.",k:"better",p:"ˈprefrəbl",pos:"adj.",d:"better or more suitable",z:"w"},
{t:"work",w:"prejudice",s:["bias","discrimination"],c:"偏见",e:"Bias affects hiring decisions.",k:"Bias",p:"ˈpredʒudɪs",pos:"n.",d:"an unfair opinion formed without facts",z:"w"},
{t:"academic",w:"preliminary",s:["initial","first"],c:"初步的",e:"Initial results look promising.",k:"Initial",p:"prɪˈlɪmɪnəri",pos:"adj.",d:"coming before the main part",z:"w"},
{t:"work",w:"prestige",s:["status","reputation"],c:"声望",e:"The university has great status.",k:"status",p:"preˈstiːʒ",pos:"n.",d:"respect gained by success",z:"w"},
{t:"academic",w:"principal",s:["main","primary"],c:"主要的",e:"The main cause is pollution.",k:"main",p:"ˈprɪnsəpl",pos:"adj.",d:"most important",z:"w"},
{t:"academic",w:"principle",s:["rule","belief"],c:"原则",e:"Fairness is a basic rule here.",k:"rule",p:"ˈprɪnsəpl",pos:"n.",d:"a basic idea or rule",z:"w"},
{t:"work",w:"privilege",s:["advantage","right"],c:"特权",e:"Education is a right, not a favour.",k:"right",p:"ˈprɪvəlɪdʒ",pos:"n.",d:"a special advantage",z:"w"},
{t:"academic",w:"prominent",s:["famous","leading"],c:"突出的",e:"She is a leading figure in research.",k:"leading",p:"ˈprɒmɪnənt",pos:"adj.",d:"important and well known",z:"w"},
{t:"work",w:"promising",s:["hopeful","talented"],c:"有前途的",e:"The startup looks hopeful.",k:"hopeful",p:"ˈprɒmɪsɪŋ",pos:"adj.",d:"likely to succeed",z:"w"},
{t:"health",w:"prone",s:["susceptible","liable"],c:"易于…的",e:"Young children are susceptible to colds.",k:"susceptible",p:"prəʊn",pos:"adj.",d:"likely to suffer from something",z:"w"},
{t:"work",w:"prospect",s:["outlook","chance"],c:"前景",e:"The outlook for graduates is good.",k:"outlook",p:"ˈprɒspekt",pos:"n.",d:"the chance of future success",z:"w"},
{t:"academic",w:"prudent",s:["careful","sensible"],c:"谨慎的",e:"Careful saving protects the budget.",k:"Careful",p:"ˈpruːdnt",pos:"adj.",d:"acting with care about risks",z:"w"},
{t:"academic",w:"random",s:["arbitrary","chance"],c:"随机的",e:"The sample was chosen by chance.",k:"by chance",p:"ˈrændəm",pos:"adj.",d:"happening without a pattern",z:"w"},
{t:"academic",w:"rational",s:["logical","reasonable"],c:"理性的",e:"The decision was logical.",k:"logical",p:"ˈræʃnəl",pos:"adj.",d:"based on reason",z:"w"},
{t:"core",w:"realistic",s:["practical","sensible"],c:"现实的",e:"Set practical targets for the term.",k:"practical",p:"ˌriːəˈlɪstɪk",pos:"adj.",d:"sensible and achievable",z:"w"},
{t:"work",w:"reckless",s:["careless","rash"],c:"鲁莽的",e:"Careless driving causes accidents.",k:"Careless",p:"ˈrekləs",pos:"adj.",d:"not caring about danger",z:"w"},
{t:"media",w:"renowned",s:["famous","celebrated"],c:"著名的",e:"The school is famous for music.",k:"famous",p:"rɪˈnaʊnd",pos:"adj.",d:"widely known and respected",z:"w"},
{t:"academic",w:"resilient",s:["tough","adaptable"],c:"有韧性的",e:"The economy proved tough during the crisis.",k:"tough",p:"rɪˈzɪliənt",pos:"adj.",d:"able to recover quickly",z:"w"},
{t:"academic",w:"rigorous",s:["strict","thorough"],c:"严格的",e:"The research follows strict methods.",k:"strict",p:"ˈrɪɡərəs",pos:"adj.",d:"careful and thorough",z:"w"},
{t:"academic",w:"robust",s:["strong","solid"],c:"稳健的",e:"The economy showed solid growth.",k:"solid",p:"rəʊˈbʌst",pos:"adj.",d:"strong and healthy",z:"w"},
{t:"work",w:"ruthless",s:["merciless","hard"],c:"无情的",e:"Competitors can be merciless.",k:"merciless",p:"ˈruːθləs",pos:"adj.",d:"without pity",z:"w"},
{t:"feelings",w:"sacrifice",s:["give up","forgo"],c:"牺牲",e:"Parents give up comforts for children.",k:"give up",p:"ˈsækrɪfaɪs",pos:"v.",d:"to give something up for a purpose",z:"w"},
{t:"academic",w:"scenario",s:["situation","case"],c:"情景",e:"Consider the worst situation.",k:"situation",p:"səˈnɑːriəʊ",pos:"n.",d:"a possible situation",z:"w"},
{t:"academic",w:"sceptical",s:["doubtful","unconvinced"],c:"怀疑的",e:"Experts remain doubtful about the plan.",k:"doubtful",p:"ˈskeptɪkl",pos:"adj.",d:"not easily convinced",z:"w"},
{t:"work",w:"scheme",s:["programme","plan"],c:"计划",e:"The plan covers ten cities.",k:"plan",p:"skiːm",pos:"n.",d:"a formal plan or programme",z:"w"},
{t:"edu",w:"scholar",s:["academic","researcher"],c:"学者",e:"The researcher published widely.",k:"researcher",p:"ˈskɒlə",pos:"n.",d:"a person who studies a subject deeply",z:"w"},
{t:"academic",w:"scope",s:["extent","range"],c:"范围",e:"The full range of the problem is unclear.",k:"range",p:"skəʊp",pos:"n.",d:"the range of an activity",z:"w"},
{t:"academic",w:"segment",s:["part","section"],c:"部分",e:"Young adults form the largest part.",k:"part",p:"ˈseɡmənt",pos:"n.",d:"one part of something",z:"w"},
{t:"core",w:"sensible",s:["wise","reasonable"],c:"明智的",e:"A wise choice saves money.",k:"wise",p:"ˈsensəbl",pos:"adj.",d:"showing good judgement",z:"w"},
{t:"feelings",w:"sentiment",s:["feeling","attitude"],c:"情绪",e:"Public feeling turned against the plan.",k:"feeling",p:"ˈsentɪmənt",pos:"n.",d:"an attitude or opinion",z:"w"},
{t:"academic",w:"sequence",s:["order","series"],c:"顺序",e:"Present the steps in order.",k:"order",p:"ˈsiːkwəns",pos:"n.",d:"the order in which things happen",z:"w"},
{t:"health",w:"severe",s:["serious","extreme"],c:"严重的",e:"The storm caused serious damage.",k:"serious",p:"sɪˈvɪə",pos:"adj.",d:"very bad or serious",z:"w"},
{t:"academic",w:"sheer",s:["pure","absolute"],c:"纯粹的",e:"The success was due to pure effort.",k:"pure",p:"ʃɪə",pos:"adj.",d:"complete and total",z:"w"},
{t:"feelings",w:"sincere",s:["honest","genuine"],c:"真诚的",e:"Her apology seemed genuine.",k:"genuine",p:"sɪnˈsɪə",pos:"adj.",d:"honest and real",z:"w"},
{t:"travel",w:"spectacular",s:["impressive","breathtaking"],c:"壮观的",e:"The view is breathtaking from the top.",k:"breathtaking",p:"spekˈtækjələ",pos:"adj.",d:"very impressive to see",z:"w"},
{t:"travel",w:"splendid",s:["magnificent","excellent"],c:"壮丽的",e:"The palace is magnificent.",k:"magnificent",p:"ˈsplendɪd",pos:"adj.",d:"very beautiful and impressive",z:"w"},
{t:"academic",w:"spontaneous",s:["unplanned","impulsive"],c:"自发的",e:"The applause was unplanned.",k:"unplanned",p:"spɒnˈteɪniəs",pos:"adj.",d:"done naturally without planning",z:"w"},
{t:"health",w:"stamina",s:["endurance","staying power"],c:"耐力",e:"Running builds endurance.",k:"endurance",p:"ˈstæmɪnə",pos:"n.",d:"the ability to keep going",z:"w"},
{t:"academic",w:"stark",s:["striking","clear"],c:"明显的",e:"The contrast is striking.",k:"striking",p:"stɑːk",pos:"adj.",d:"clearly noticeable",z:"w"},
{t:"work",w:"steadfast",s:["firm","unwavering"],c:"坚定的",e:"The team stayed firm under pressure.",k:"firm",p:"ˈstedfɑːst",pos:"adj.",d:"loyal and determined",z:"w"},
{t:"work",w:"strategic",s:["planned","tactical"],c:"战略的",e:"The move was planned for years.",k:"planned",p:"strəˈtiːdʒɪk",pos:"adj.",d:"carefully planned for a purpose",z:"w"},
{t:"work",w:"stringent",s:["strict","tight"],c:"严格的",e:"Strict rules protect the environment.",k:"Strict",p:"ˈstrɪndʒənt",pos:"adj.",d:"very strict",z:"w"},
{t:"feelings",w:"stubborn",s:["obstinate","inflexible"],c:"固执的",e:"He was inflexible about the deadline.",k:"inflexible",p:"ˈstʌbən",pos:"adj.",d:"refusing to change your mind",z:"w"},
{t:"academic",w:"sturdy",s:["strong","solid"],c:"坚固的",e:"The bridge is solid and safe.",k:"solid",p:"ˈstɜːdi",pos:"adj.",d:"strong and well made",z:"w"},
{t:"academic",w:"substantial",s:["significant","considerable"],c:"大量的",e:"The plan needs significant funding.",k:"significant",p:"səbˈstænʃl",pos:"adj.",d:"large in amount or importance",z:"w"},
{t:"feelings",w:"superb",s:["excellent","first-rate"],c:"极好的",e:"The performance was excellent.",k:"excellent",p:"suːˈpɜːb",pos:"adj.",d:"of the highest quality",z:"w"},
{t:"work",w:"suspicious",s:["doubtful","distrustful"],c:"可疑的",e:"The officer grew distrustful of the story.",k:"distrustful",p:"səˈspɪʃəs",pos:"adj.",d:"feeling that something is wrong",z:"w"},
{t:"core",w:"swift",s:["fast","quick"],c:"迅速的",e:"The response was quick.",k:"quick",p:"swɪft",pos:"adj.",d:"moving or happening quickly",z:"w"},
{t:"work",w:"tactic",s:["strategy","method"],c:"策略",e:"The method worked well.",k:"method",p:"ˈtæktɪk",pos:"n.",d:"a method used to achieve a goal",z:"w"},
{t:"work",w:"tedious",s:["boring","tiring"],c:"乏味的",e:"The work is boring but necessary.",k:"boring",p:"ˈtiːdiəs",pos:"adj.",d:"long and boring",z:"w"},
{t:"work",w:"temporary",s:["short-term","provisional"],c:"临时的",e:"The post is short-term.",k:"short-term",p:"ˈtemprəri",pos:"adj.",d:"lasting only a short time",z:"w"},
{t:"work",w:"thorough",s:["careful","complete"],c:"彻底的",e:"A complete review is due.",k:"complete",p:"ˈθʌrə",pos:"adj.",d:"done very carefully and completely",z:"w"},
{t:"env",w:"toxic",s:["poisonous","harmful"],c:"有毒的",e:"The waste is poisonous.",k:"poisonous",p:"ˈtɒksɪk",pos:"adj.",d:"containing poison",z:"w"},
{t:"env",w:"tragedy",s:["disaster","catastrophe"],c:"悲剧",e:"The event was a real disaster.",k:"disaster",p:"ˈtrædʒədi",pos:"n.",d:"a very sad event",z:"w"},
{t:"travel",w:"transit",s:["transport","movement"],c:"运输",e:"Public transport is expanding.",k:"transport",p:"ˈtrænzɪt",pos:"n.",d:"the movement of goods or people",z:"w"},
{t:"health",w:"trauma",s:["injury","shock"],c:"创伤",e:"The accident left deep shock.",k:"shock",p:"ˈtrɔːmə",pos:"n.",d:"a serious emotional or physical injury",z:"w"},
{t:"academic",w:"tremendous",s:["huge","enormous"],c:"巨大的",e:"The change required huge effort.",k:"huge",p:"trəˈmendəs",pos:"adj.",d:"very great in amount",z:"w"},
{t:"academic",w:"ultimate",s:["final","eventual"],c:"最终的",e:"The final goal is full recovery.",k:"final",p:"ˈʌltɪmət",pos:"adj.",d:"last or most important",z:"w"},
{t:"work",w:"unanimous",s:["agreed","united"],c:"一致的",e:"The board was united on the vote.",k:"united",p:"juˈnænɪməs",pos:"adj.",d:"agreed by everyone",z:"w"},
{t:"academic",w:"universal",s:["general","widespread"],c:"普遍的",e:"The rule has general application.",k:"general",p:"ˌjuːnɪˈvɜːsl",pos:"adj.",d:"relating to everyone or everything",z:"w"},
{t:"academic",w:"unprecedented",s:["unheard-of","record"],c:"前所未有的",e:"The growth was unheard-of.",k:"unheard-of",p:"ʌnˈpresɪdentɪd",pos:"adj.",d:"never done or known before",z:"w"},
{t:"work",w:"upheaval",s:["turmoil","disruption"],c:"动荡",e:"The reforms caused turmoil.",k:"turmoil",p:"ʌpˈhiːvl",pos:"n.",d:"great social change or confusion",z:"w"},
{t:"academic",w:"vague",s:["unclear","indefinite"],c:"模糊的",e:"The instructions were unclear.",k:"unclear",p:"veɪɡ",pos:"adj.",d:"not clear or exact",z:"w"},
{t:"core",w:"vast",s:["huge","enormous"],c:"广阔的",e:"The desert covers a huge area.",k:"huge",p:"vɑːst",pos:"adj.",d:"extremely large",z:"w"},
{t:"work",w:"venture",s:["undertaking","enterprise"],c:"冒险，创业",e:"The enterprise needed new capital.",k:"enterprise",p:"ˈventʃə",pos:"n.",d:"a new business project",z:"w"},
{t:"work",w:"versatile",s:["adaptable","flexible"],c:"多才多艺的",e:"The tool is flexible in use.",k:"flexible",p:"ˈvɜːsətaɪl",pos:"adj.",d:"able to do many different things",z:"w"},
{t:"living",w:"vibrant",s:["lively","energetic"],c:"充满活力的",e:"The district is lively at night.",k:"lively",p:"ˈvaɪbrənt",pos:"adj.",d:"full of energy and life",z:"w"},
{t:"work",w:"victim",s:["sufferer","casualty"],c:"受害者",e:"The sufferer received support.",k:"sufferer",p:"ˈvɪktɪm",pos:"n.",d:"a person harmed by an event",z:"w"},
{t:"health",w:"vigorous",s:["energetic","strong"],c:"有力的",e:"Daily exercise keeps you energetic.",k:"energetic",p:"ˈvɪɡərəs",pos:"adj.",d:"strong and full of energy",z:"w"},
{t:"academic",w:"virtue",s:["good quality","merit"],c:"美德",e:"Honesty is a good quality.",k:"good quality",p:"ˈvɜːtʃuː",pos:"n.",d:"a good moral quality",z:"w"},
{t:"academic",w:"visible",s:["noticeable","apparent"],c:"可见的",e:"The damage is apparent.",k:"apparent",p:"ˈvɪzəbl",pos:"adj.",d:"able to be seen",z:"w"},
{t:"media",w:"vivid",s:["lively","graphic"],c:"生动的",e:"The report gives a graphic account.",k:"graphic",p:"ˈvɪvɪd",pos:"adj.",d:"producing clear mental images",z:"w"},
{t:"work",w:"vocal",s:["outspoken","forthright"],c:"直言不讳的",e:"Residents were outspoken about noise.",k:"outspoken",p:"ˈvəʊkl",pos:"adj.",d:"expressing opinions freely",z:"w"},
{t:"academic",w:"volatile",s:["unstable","changeable"],c:"不稳定的",e:"Prices are unstable this year.",k:"unstable",p:"ˈvɒlətaɪl",pos:"adj.",d:"likely to change suddenly",z:"w"},
{t:"feelings",w:"wary",s:["cautious","vigilant"],c:"警惕的",e:"Investors are cautious about risk.",k:"cautious",p:"ˈweəri",pos:"adj.",d:"careful because of possible danger",z:"w"},
{t:"feelings",w:"weary",s:["tired","exhausted"],c:"疲惫的",e:"Staff felt tired after the rush.",k:"tired",p:"ˈwɪəri",pos:"adj.",d:"very tired",z:"w"},
{t:"work",w:"welfare",s:["well-being","social support"],c:"福利",e:"The scheme improves workers' well-being.",k:"well-being",p:"ˈwelfeə",pos:"n.",d:"the health and happiness of people",z:"w"},
{t:"edu",w:"wisdom",s:["insight","good judgement"],c:"智慧",e:"Experience brings good judgement.",k:"good judgement",p:"ˈwɪzdəm",pos:"n.",d:"the ability to make good decisions",z:"w"},
{t:"core",w:"worthwhile",s:["valuable","rewarding"],c:"值得的",e:"The training was valuable.",k:"valuable",p:"ˌwɜːθˈwaɪl",pos:"adj.",d:"worth the time or effort",z:"w"}
];
const V7NEW = [].concat(V7L, V7W);
module.exports = { V7NEW };
